import type { AlertCategory, NotificationPreferences } from "./alerts";

export const NOTIFICATION_CATEGORIES: readonly AlertCategory[] = ["SIMULATION_PNL_GAIN", "SIMULATION_PNL_LOSS", "HIGH_INTEREST_CANDIDATE", "ELIGIBILITY_CHANGED", "ADMISSION_CHANGED", "ALLOCATION_PLAN_RESULT", "RISK_BLOCKED", "SIMULATION_FILL", "SYSTEM_CRITICAL"];
export const UNSAVED_NOTIFICATION_DEFAULTS = { enabledCategories: [...NOTIFICATION_CATEGORIES], pnlMilestoneThresholdMajor: "1000.00", currency: "NOK", quietHoursEnabled: true, quietHoursStart: "22:00", quietHoursEnd: "07:00", timezone: "Europe/Oslo", maxNonCriticalPerHour: "10" } as const;
export type NotificationFormState = { enabledCategories: AlertCategory[]; pnlMilestoneThresholdMajor: string; currency: string; quietHoursEnabled: boolean; quietHoursStart: string; quietHoursEnd: string; timezone: string; maxNonCriticalPerHour: string };
export type NotificationPreferencesResponse = Omit<NotificationPreferences, "pnlMilestoneThresholdMinor"> & { pnlMilestoneThresholdMinor: string };

export function minorUnitsFromMajorInput(value: string): string { if (!/^\d+(?:\.\d{1,2})?$/.test(value)) throw new Error("INVALID_PNL_THRESHOLD_INPUT"); const [whole, fraction = ""] = value.split("."); const minor = `${whole}${fraction.padEnd(2, "0")}`.replace(/^0+(?=\d)/, ""); if (minor === "0") throw new Error("INVALID_PNL_THRESHOLD_INPUT"); return minor; }
export function majorInputFromMinorUnits(value: string): string { if (!/^\d+$/.test(value) || BigInt(value) <= 0n) throw new Error("INVALID_PNL_THRESHOLD"); const padded = value.padStart(3, "0"); return `${padded.slice(0, -2)}.${padded.slice(-2)}`; }
export function formFromPreferences(preferences: NotificationPreferencesResponse): NotificationFormState { return { enabledCategories: [...preferences.enabledCategories], pnlMilestoneThresholdMajor: majorInputFromMinorUnits(preferences.pnlMilestoneThresholdMinor), currency: preferences.currency, quietHoursEnabled: preferences.quietHoursEnabled, quietHoursStart: preferences.quietHoursStart, quietHoursEnd: preferences.quietHoursEnd, timezone: preferences.timezone, maxNonCriticalPerHour: String(preferences.maxNonCriticalPerHour) }; }
export function preferencesBodyFromForm(form: NotificationFormState): NotificationPreferencesResponse { return { enabledCategories: form.enabledCategories, pnlMilestoneThresholdMinor: minorUnitsFromMajorInput(form.pnlMilestoneThresholdMajor), currency: form.currency.trim().toUpperCase(), quietHoursEnabled: form.quietHoursEnabled, quietHoursStart: form.quietHoursStart, quietHoursEnd: form.quietHoursEnd, timezone: form.timezone, maxNonCriticalPerHour: Number(form.maxNonCriticalPerHour) }; }
export function unsavedNotificationForm(): NotificationFormState { return { ...UNSAVED_NOTIFICATION_DEFAULTS, enabledCategories: [...UNSAVED_NOTIFICATION_DEFAULTS.enabledCategories] }; }
