import {
  createIngestionAttempt, createIngestionRequest, createRetrievalAvailabilityClaim, createSourceArtifact, createSourceEnvelope, createSourceObservation,
  normalizeIngestionTimestamp, type JsonObject, type SafePaginationMetadata,
} from "@/domain/intelligence/ingestion-provenance";

export const M5_NORMALIZED_SOURCE_PACKAGE_VERSION = "m5-normalized-source-package/v1" as const;
export type ManualNormalizedRecord = Readonly<{ providerExternalRecordId: string; providerRevision?: string; payloadFingerprint: string; pageOrdinal: number; itemOrdinal: number; retrievedAt: string; recordedAt: string; providerPublishedAt?: string; observedAt: string; normalizedEnvelope: JsonObject; selectedAuditableFields: JsonObject; metadata: SafePaginationMetadata }>;
export type ManualNormalizedSourcePackage = Readonly<{ contractVersion: typeof M5_NORMALIZED_SOURCE_PACKAGE_VERSION; idempotencyKey: string; providerId: string; datasetId: string; datasetVersion: string; providerSourceNamespace: string; adapterContractVersion: string; adapterVersion: string; parserContractVersion: string; parserVersion: string; envelopeSchemaVersion: string; attemptNumber: number; requestedAt: string; startedAt: string; recordedAt: string; requestScope: JsonObject; provenance: JsonObject; executionInput: JsonObject; records: readonly ManualNormalizedRecord[] }>;

const secret = /authorization|cookie|password|secret|token|api[_-]?key|signed[_-]?url/i;
const sha = /^[a-f0-9]{64}$/;
type Obj = Record<string, unknown>;
const freeze = <T>(value: T): T => { if (value && typeof value === "object" && !Object.isFrozen(value)) { Object.freeze(value); for (const child of Object.values(value as Obj)) freeze(child); } return value; };
const object = (value: unknown, code: string): Obj => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(code); return value as Obj; };
const exact = (value: Obj, keys: readonly string[], code: string) => { const allowed = new Set(keys); for (const key of Object.keys(value)) if (!allowed.has(key)) throw new Error(secret.test(key) ? "M5_MANUAL_SECRET_LIKE_FIELD_REJECTED" : code); };
const string = (value: unknown, code: string, max = 512): string => { if (typeof value !== "string" || !value.trim() || value.length > max) throw new Error(code); return value.trim(); };
const timestamp = (value: unknown, code: string) => normalizeIngestionTimestamp(value, code);
const integer = (value: unknown, code: string, min = 0): number => { if (!Number.isInteger(value) || (value as number) < min) throw new Error(code); return value as number; };
function safeJson(value: unknown, code: string, depth = 0): JsonObject {
  if (depth > 4) throw new Error(code); const item = object(value, code);
  for (const [key, child] of Object.entries(item)) { if (secret.test(key)) throw new Error("M5_MANUAL_SECRET_LIKE_FIELD_REJECTED"); if (typeof child === "string" && (/^https?:\/\//i.test(child) && (child.includes("?") || child.includes("#")))) throw new Error("M5_MANUAL_SECRET_LIKE_FIELD_REJECTED"); if (child && typeof child === "object") { if (Array.isArray(child)) throw new Error(code); safeJson(child, code, depth + 1); } else if (child !== null && typeof child !== "string" && typeof child !== "number" && typeof child !== "boolean") throw new Error(code); }
  return freeze(item) as JsonObject;
}
function metadata(value: unknown, ordinal: number): SafePaginationMetadata {
  const item = object(value, "M5_MANUAL_METADATA_INVALID"); exact(item, ["pageOrdinal", "cursorSafety", "cursor", "cursorHash", "responseHostPath", "correlationId"], "M5_MANUAL_METADATA_UNKNOWN_FIELD");
  if (item.pageOrdinal !== undefined && item.pageOrdinal !== ordinal) throw new Error("M5_MANUAL_METADATA_INVALID");
  const cursorSafety = item.cursorSafety;
  if (cursorSafety !== "NONE" && cursorSafety !== "HASHED") throw new Error("M5_MANUAL_CURSOR_UNSAFE");
  if (item.cursor !== undefined) throw new Error("M5_MANUAL_CURSOR_UNSAFE");
  if (item.responseHostPath !== undefined) { const url = string(item.responseHostPath, "M5_MANUAL_RESPONSE_URL_INVALID", 2048); if (!/^https:\/\/[^/?#]+(?:\/[^?#]*)?$/.test(url)) throw new Error("M5_MANUAL_RESPONSE_URL_INVALID"); }
  if (cursorSafety === "HASHED" && (!sha.test(string(item.cursorHash, "M5_MANUAL_CURSOR_HASH_INVALID")))) throw new Error("M5_MANUAL_CURSOR_HASH_INVALID");
  if (cursorSafety === "NONE" && item.cursorHash !== undefined) throw new Error("M5_MANUAL_CURSOR_UNSAFE");
  return freeze({ pageOrdinal: ordinal, cursorSafety, ...(item.cursorHash === undefined ? {} : { cursorHash: string(item.cursorHash, "M5_MANUAL_CURSOR_HASH_INVALID") }), ...(item.responseHostPath === undefined ? {} : { responseHostPath: string(item.responseHostPath, "M5_MANUAL_RESPONSE_URL_INVALID") }), ...(item.correlationId === undefined ? {} : { correlationId: string(item.correlationId, "M5_MANUAL_CORRELATION_INVALID", 128) }) });
}

export function parseM5NormalizedSourcePackage(input: unknown): ManualNormalizedSourcePackage {
  const root = object(input, "M5_MANUAL_CONTRACT_INVALID"); exact(root, ["contractVersion", "idempotencyKey", "providerId", "datasetId", "datasetVersion", "providerSourceNamespace", "adapterContractVersion", "adapterVersion", "parserContractVersion", "parserVersion", "envelopeSchemaVersion", "attemptNumber", "requestedAt", "startedAt", "recordedAt", "requestScope", "provenance", "executionInput", "records"], "M5_MANUAL_CONTRACT_UNKNOWN_FIELD");
  if (root.contractVersion !== M5_NORMALIZED_SOURCE_PACKAGE_VERSION) throw new Error("M5_MANUAL_CONTRACT_VERSION_INVALID");
  const common = { contractVersion: M5_NORMALIZED_SOURCE_PACKAGE_VERSION, idempotencyKey: string(root.idempotencyKey, "M5_MANUAL_IDEMPOTENCY_KEY_INVALID"), providerId: string(root.providerId, "M5_MANUAL_PROVIDER_INVALID"), datasetId: string(root.datasetId, "M5_MANUAL_DATASET_INVALID"), datasetVersion: string(root.datasetVersion, "M5_MANUAL_DATASET_VERSION_INVALID"), providerSourceNamespace: string(root.providerSourceNamespace, "M5_MANUAL_NAMESPACE_INVALID"), adapterContractVersion: string(root.adapterContractVersion, "M5_MANUAL_ADAPTER_INVALID"), adapterVersion: string(root.adapterVersion, "M5_MANUAL_ADAPTER_INVALID"), parserContractVersion: string(root.parserContractVersion, "M5_MANUAL_PARSER_INVALID"), parserVersion: string(root.parserVersion, "M5_MANUAL_PARSER_INVALID"), envelopeSchemaVersion: string(root.envelopeSchemaVersion, "M5_MANUAL_ENVELOPE_SCHEMA_INVALID"), attemptNumber: integer(root.attemptNumber, "M5_MANUAL_ATTEMPT_INVALID", 1), requestedAt: timestamp(root.requestedAt, "M5_MANUAL_REQUESTED_AT_INVALID"), startedAt: timestamp(root.startedAt, "M5_MANUAL_STARTED_AT_INVALID"), recordedAt: timestamp(root.recordedAt, "M5_MANUAL_RECORDED_AT_INVALID"), requestScope: safeJson(root.requestScope, "M5_MANUAL_REQUEST_SCOPE_INVALID"), provenance: safeJson(root.provenance, "M5_MANUAL_PROVENANCE_INVALID"), executionInput: safeJson(root.executionInput, "M5_MANUAL_EXECUTION_INPUT_INVALID") } as const;
  if (common.adapterContractVersion !== common.adapterVersion || common.parserContractVersion !== common.parserVersion) throw new Error("M5_MANUAL_VERSION_MISMATCH");
  if (!Array.isArray(root.records) || root.records.length === 0) throw new Error("M5_MANUAL_EMPTY_PACKAGE");
  const ordinals = new Set<string>(), logical = new Map<string, string>();
  const records = root.records.map(value => { const item = object(value, "M5_MANUAL_RECORD_INVALID"); exact(item, ["providerExternalRecordId", "providerRevision", "payloadFingerprint", "pageOrdinal", "itemOrdinal", "retrievedAt", "recordedAt", "providerPublishedAt", "observedAt", "normalizedEnvelope", "selectedAuditableFields", "metadata"], "M5_MANUAL_RECORD_UNKNOWN_FIELD"); const pageOrdinal = integer(item.pageOrdinal, "M5_MANUAL_PAGE_ORDINAL_INVALID"); const itemOrdinal = integer(item.itemOrdinal, "M5_MANUAL_ITEM_ORDINAL_INVALID"); const retrievedAt = timestamp(item.retrievedAt, "M5_MANUAL_RETRIEVED_AT_INVALID"), recordedAt = timestamp(item.recordedAt, "M5_MANUAL_RECORD_RECORDED_AT_INVALID"), observedAt = timestamp(item.observedAt, "M5_MANUAL_OBSERVED_AT_INVALID"); if (retrievedAt > recordedAt || observedAt > retrievedAt) throw new Error("M5_MANUAL_TEMPORAL_INVALID"); const providerPublishedAt = item.providerPublishedAt === undefined ? undefined : timestamp(item.providerPublishedAt, "M5_MANUAL_PUBLISHED_AT_INVALID"); if (providerPublishedAt !== undefined && providerPublishedAt > retrievedAt) throw new Error("M5_MANUAL_TEMPORAL_QUARANTINED"); const payloadFingerprint = string(item.payloadFingerprint, "M5_MANUAL_PAYLOAD_FINGERPRINT_INVALID"); if (!sha.test(payloadFingerprint)) throw new Error("M5_MANUAL_PAYLOAD_FINGERPRINT_INVALID"); const providerExternalRecordId = string(item.providerExternalRecordId, "M5_MANUAL_EXTERNAL_ID_INVALID"); const providerRevision = item.providerRevision === undefined ? undefined : string(item.providerRevision, "M5_MANUAL_REVISION_INVALID"); const key = `${pageOrdinal}:${itemOrdinal}`; if (ordinals.has(key)) throw new Error("M5_MANUAL_DUPLICATE_ORDINAL"); ordinals.add(key); const material = JSON.stringify([providerRevision, payloadFingerprint, item.normalizedEnvelope, item.selectedAuditableFields]); const logicalId = `${providerExternalRecordId}:${providerRevision ?? ""}`; const old = logical.get(logicalId); if (old !== undefined) throw new Error(old === material ? "M5_MANUAL_DUPLICATE_RECORD" : "M5_MANUAL_CONFLICTING_RECORD"); logical.set(logicalId, material); return freeze({ providerExternalRecordId, ...(providerRevision === undefined ? {} : { providerRevision }), payloadFingerprint, pageOrdinal, itemOrdinal, retrievedAt, recordedAt, ...(providerPublishedAt === undefined ? {} : { providerPublishedAt }), observedAt, normalizedEnvelope: safeJson(item.normalizedEnvelope, "M5_MANUAL_ENVELOPE_INVALID"), selectedAuditableFields: safeJson(item.selectedAuditableFields, "M5_MANUAL_AUDIT_FIELDS_INVALID"), metadata: metadata(item.metadata, pageOrdinal) }); }).sort((a,b) => a.pageOrdinal - b.pageOrdinal || a.itemOrdinal - b.itemOrdinal || a.providerExternalRecordId.localeCompare(b.providerExternalRecordId));
  return freeze({ ...common, records: freeze(records) });
}

export function buildManualIngestionRecords(value: ManualNormalizedSourcePackage) {
  const request = createIngestionRequest({ idempotencyKey: value.idempotencyKey, providerId: value.providerId, datasetId: value.datasetId, datasetVersion: value.datasetVersion, providerSourceNamespace: value.providerSourceNamespace, envelopeSchemaVersion: value.envelopeSchemaVersion, requestScope: value.requestScope, adapterContractVersion: value.adapterContractVersion, parserContractVersion: value.parserContractVersion, requestedAt: value.requestedAt, provenance: value.provenance as never });
  const attempt = createIngestionAttempt({ ingestionRequestId: request.ingestionRequestId, attemptNumber: value.attemptNumber, adapterVersion: value.adapterVersion, parserVersion: value.parserVersion, executionInput: value.executionInput, startedAt: value.startedAt });
  const records = value.records.map(record => { const artifact = createSourceArtifact({ providerId: value.providerId, datasetId: value.datasetId, datasetVersion: value.datasetVersion, providerSourceNamespace: value.providerSourceNamespace, providerExternalRecordId: record.providerExternalRecordId, ...(record.providerRevision === undefined ? {} : { providerRevision: record.providerRevision }), payloadFingerprint: record.payloadFingerprint, recordedAt: record.recordedAt }); const envelope = createSourceEnvelope({ sourceArtifactId: artifact.sourceArtifactId, parserContractVersion: value.parserContractVersion, envelopeSchemaVersion: value.envelopeSchemaVersion, normalizedEnvelope: record.normalizedEnvelope, selectedAuditableFields: record.selectedAuditableFields, payloadFingerprint: record.payloadFingerprint, ...(record.providerPublishedAt === undefined ? {} : { providerPublishedAt: record.providerPublishedAt }), observedAt: record.observedAt, temporalQualityStatus: "RESOLVED", temporalDiagnosticCodes: [], recordedAt: record.recordedAt }); const observation = createSourceObservation({ ingestionAttemptId: attempt.ingestionAttemptId, sourceArtifactId: artifact.sourceArtifactId, responsePageOrdinal: record.pageOrdinal, itemOrdinal: record.itemOrdinal, retrievedAt: record.retrievedAt, metadata: record.metadata, recordedAt: record.recordedAt }); const claim = createRetrievalAvailabilityClaim({ envelope, observation, recordedAt: record.recordedAt }); return freeze({ artifact, envelope, observation, claim }); });
  return freeze({ request, attempt, records });
}
