import { createProviderAssetIdentityAssertion, type ProviderAssetIdentityType } from "@/domain/intelligence/provider-asset-identity-assertion";

export const PROVIDER_ASSET_IDENTITY_PROJECTION_VERSION = "m5-provider-asset-identity-projection/v1" as const;
export type ProviderAssetIdentityProjection = Readonly<{ projectionVersion: typeof PROVIDER_ASSET_IDENTITY_PROJECTION_VERSION; sourceArtifactId: string; sourceEnvelopeId: string; parserVersion: string; envelopeSchemaVersion: string; identity: Readonly<{ type: ProviderAssetIdentityType; namespace: string; value: string }>; diagnostics: readonly string[] }>;
const SECRET = /authorization|cookie|password|secret|token|api[_-]?key|header|credential|url/i;
const record = (value: unknown, code: string): Record<string, unknown> => { if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(code); return value as Record<string, unknown>; };
const exact = (value: Record<string, unknown>, keys: readonly string[], code: string) => { if (Object.keys(value).some(key => !keys.includes(key))) throw new Error(code); };
const required = (value: unknown, code: string) => { if (typeof value !== "string" || value !== value.trim() || !value) throw new Error(code); return value; };
const diagnostic = (error: unknown) => error instanceof Error && /^M5_PROVIDER_ASSET_IDENTITY_/.test(error.message) ? error.message : "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_INVALID";
export function parseProviderAssetIdentityProjection(input: unknown): ProviderAssetIdentityProjection {
  try {
    const root = record(input, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_INVALID"); exact(root, ["projectionVersion", "sourceArtifactId", "sourceEnvelopeId", "parserVersion", "envelopeSchemaVersion", "identity"], "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_UNKNOWN_FIELD"); if (Object.keys(root).some(key => SECRET.test(key))) throw new Error("M5_PROVIDER_ASSET_IDENTITY_PROJECTION_SECRET_FIELD");
    if (root.projectionVersion !== PROVIDER_ASSET_IDENTITY_PROJECTION_VERSION) throw new Error("M5_PROVIDER_ASSET_IDENTITY_PROJECTION_VERSION_INVALID");
    const identity = record(root.identity, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_IDENTITY_INVALID"); exact(identity, ["type", "namespace", "value"], "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_IDENTITY_UNKNOWN_FIELD"); if (Object.keys(identity).some(key => SECRET.test(key))) throw new Error("M5_PROVIDER_ASSET_IDENTITY_PROJECTION_SECRET_FIELD");
    const canonical = createProviderAssetIdentityAssertion({ providerId: "projection", datasetId: "projection", datasetVersion: "projection", providerSourceNamespace: "projection", providerAssetId: "projection", sourceArtifactId: required(root.sourceArtifactId, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_ARTIFACT_INVALID"), sourceEnvelopeId: required(root.sourceEnvelopeId, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_ENVELOPE_INVALID"), parserVersion: required(root.parserVersion, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_PARSER_INVALID"), envelopeSchemaVersion: required(root.envelopeSchemaVersion, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_SCHEMA_INVALID"), identityType: required(identity.type, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_TYPE_INVALID") as ProviderAssetIdentityType, identityNamespace: required(identity.namespace, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_NAMESPACE_INVALID"), identityValue: required(identity.value, "M5_PROVIDER_ASSET_IDENTITY_PROJECTION_VALUE_INVALID"), sourcePayloadFingerprint: "0".repeat(64), recordedAt: "2026-01-01T00:00:00.000Z" });
    return Object.freeze({ projectionVersion: PROVIDER_ASSET_IDENTITY_PROJECTION_VERSION, sourceArtifactId: canonical.sourceArtifactId, sourceEnvelopeId: canonical.sourceEnvelopeId, parserVersion: canonical.parserVersion, envelopeSchemaVersion: canonical.envelopeSchemaVersion, identity: Object.freeze({ type: canonical.identityType, namespace: canonical.identityNamespace, value: canonical.identityValue }), diagnostics: Object.freeze([]) });
  } catch (error) { throw new Error(diagnostic(error)); }
}
