import { createHash } from "node:crypto";
import type { IntegrityStatus, IntelligenceSnapshot, TrendResult } from "./engine";

export const CANONICAL_M4_RECORD_VERSION = "canonical-m4-analysis/v1";
export const CANONICAL_M5_RECORD_VERSION = "canonical-m5-eligibility/v1";
export const CANONICAL_CONTEXT_VERSION = "canonical-context/v1";
export type SuspiciousEvidenceStatus = "CLEAN" | "SUSPICIOUS" | "INCOMPLETE";
type TrendEvidence = Pick<TrendResult, "status" | "direction" | "signedChangeBps" | "accelerationStatus" | "accelerationBps" | "observationIds" | "previousWindowObservationIds" | "currentWindowObservationIds">;

export interface CanonicalM4AnalysisRecord { readonly analysisId:string; readonly candidateId:string; readonly canonicalIdentifier:string; readonly assetClass:string; readonly canonicalContextId:string; readonly asOf:Date; readonly availableAt:Date; readonly engineVersion:string; readonly featureSetVersion:string; readonly trendPolicyVersion:string; readonly accelerationVersion:string; readonly datasetPins:readonly string[]; readonly inputEvidenceIds:readonly string[]; readonly trend:TrendEvidence; readonly corroborationProviderIds:readonly string[]; readonly corroborationEvidenceIds:readonly string[]; readonly distinctProviderCount:number; readonly suspiciousFlags:readonly string[]; readonly integrityStatus:IntegrityStatus; readonly configHash:string; readonly fingerprint:string; }
export interface CanonicalM5EligibilityRecord { readonly evaluationId:string; readonly candidateId:string; readonly canonicalIdentifier:string; readonly assetClass:string; readonly canonicalContextId:string; readonly asOf:Date; readonly availableAt:Date; readonly policyVersion:string; readonly profileVersion:string; readonly status:"ELIGIBLE"|"INELIGIBLE"|"INCOMPLETE"; readonly checks:readonly unknown[]; readonly reasonCodes:readonly string[]; readonly evidenceIds:readonly string[]; readonly suspiciousFlags:readonly string[]; readonly suspiciousEvidenceStatus:SuspiciousEvidenceStatus; readonly suspiciousAssessmentId:string; readonly suspiciousAssessmentFingerprint:string; readonly suspiciousAssessmentResult:"NO_FINDINGS"|"FINDINGS_PRESENT"; readonly datasetPins:readonly string[]; readonly assemblyFingerprint:string; readonly fingerprint:string; }
export interface CanonicalContextIdentityInput { readonly candidateId:string; readonly canonicalIdentifier:string; readonly assetClass:string; readonly asOf:Date|string; readonly assetId?:string; readonly contextVersion?:string; }

const normalize = (value:unknown):unknown => { if (value instanceof Date) return value.toISOString(); if (typeof value === "bigint") return value.toString(); if (Array.isArray(value)) return value.map(normalize); if (value && typeof value === "object") return Object.fromEntries(Object.entries(value).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,normalize(item)])); return value; };
const sortValues = (values:readonly unknown[]) => [...values].map(normalize).sort((a,b)=>JSON.stringify(a).localeCompare(JSON.stringify(b)));
const hash = (value:unknown) => createHash("sha256").update(JSON.stringify(normalize(value))).digest("hex");
const validDate = (value:Date) => Number.isFinite(value.getTime());
const nonEmpty = (value:string, code:string) => { if (!value.trim()) throw new Error(code); return value; };
const pins = (values:readonly string[]) => { const result=[...new Set(values.map(value=>nonEmpty(value,"CANONICAL_DATASET_PIN_INVALID")))].sort(); if (!result.length) throw new Error("CANONICAL_DATASET_PINS_MISSING"); return result; };
const normalizedDate = (value:Date|string, code:string) => { const result=new Date(value); if(!validDate(result)) throw new Error(code); return result.toISOString(); };

/** Identifies one asset evaluation cycle, not either record's material evidence. */
export function deriveCanonicalContextId(input:CanonicalContextIdentityInput):string { return hash({version:nonEmpty(input.contextVersion??CANONICAL_CONTEXT_VERSION,"CANONICAL_CONTEXT_VERSION_INVALID"),candidateId:nonEmpty(input.candidateId,"CANONICAL_CANDIDATE_ID_INVALID"),canonicalIdentifier:nonEmpty(input.canonicalIdentifier,"CANONICAL_ASSET_ID_INVALID"),assetClass:nonEmpty(input.assetClass,"CANONICAL_ASSET_CLASS_INVALID"),assetId:input.assetId===undefined?null:nonEmpty(input.assetId,"CANONICAL_ASSET_ID_INVALID"),asOf:normalizedDate(input.asOf,"CANONICAL_CONTEXT_AS_OF_INVALID")}); }

export function canonicalM4Fingerprint(record:Omit<CanonicalM4AnalysisRecord,"fingerprint">):string { return hash({version:CANONICAL_M4_RECORD_VERSION,...record,datasetPins:sortValues(record.datasetPins),inputEvidenceIds:sortValues(record.inputEvidenceIds),corroborationProviderIds:sortValues(record.corroborationProviderIds),corroborationEvidenceIds:sortValues(record.corroborationEvidenceIds),suspiciousFlags:sortValues(record.suspiciousFlags)}); }
export function canonicalM5Fingerprint(record:Omit<CanonicalM5EligibilityRecord,"fingerprint">):string { return hash({version:CANONICAL_M5_RECORD_VERSION,...record,datasetPins:sortValues(record.datasetPins),evidenceIds:sortValues(record.evidenceIds),suspiciousFlags:sortValues(record.suspiciousFlags),reasonCodes:sortValues(record.reasonCodes),checks:sortValues(record.checks)}); }

export function canonicalM4RecordFromSnapshot(input:{snapshot:IntelligenceSnapshot;candidateId:string;canonicalIdentifier:string;assetClass:string;canonicalContextId:string;featureSetVersion:string;trendPolicyVersion:string;accelerationVersion:string;datasetPins:readonly string[];corroborationProviderIds:readonly string[];corroborationEvidenceIds:readonly string[];suspiciousFlags?:readonly string[]}):CanonicalM4AnalysisRecord {
  const trend=input.snapshot.trends[0]; if(!trend) throw new Error("CANONICAL_M4_TREND_MISSING"); const providers=[...new Set(input.corroborationProviderIds.map(value=>nonEmpty(value,"CANONICAL_PROVIDER_INVALID")))].sort();
  const representedEvidenceIds=new Set(input.snapshot.inputEvidence); const material=input.snapshot.materialEvidence.filter(value=>representedEvidenceIds.has(value.evidenceId)).map(value=>({evidenceId:nonEmpty(value.evidenceId,"CANONICAL_M4_EVIDENCE_INVALID"),availableAt:new Date(value.availableAt)})); if(!material.length||material.some(value=>!validDate(value.availableAt))) throw new Error("CANONICAL_M4_DATE_INVALID"); const availableAt=material.reduce((latest,value)=>value.availableAt>latest?value.availableAt:latest,material[0]!.availableAt);
  const record={analysisId:nonEmpty(input.snapshot.analysisId,"CANONICAL_M4_ID_INVALID"),candidateId:nonEmpty(input.candidateId,"CANONICAL_CANDIDATE_ID_INVALID"),canonicalIdentifier:nonEmpty(input.canonicalIdentifier,"CANONICAL_ASSET_ID_INVALID"),assetClass:nonEmpty(input.assetClass,"CANONICAL_ASSET_CLASS_INVALID"),canonicalContextId:nonEmpty(input.canonicalContextId,"CANONICAL_CONTEXT_ID_INVALID"),asOf:new Date(input.snapshot.asOf),availableAt,engineVersion:nonEmpty(input.snapshot.engineVersion,"CANONICAL_VERSION_INVALID"),featureSetVersion:nonEmpty(input.featureSetVersion,"CANONICAL_VERSION_INVALID"),trendPolicyVersion:nonEmpty(input.trendPolicyVersion,"CANONICAL_VERSION_INVALID"),accelerationVersion:nonEmpty(input.accelerationVersion,"CANONICAL_VERSION_INVALID"),datasetPins:pins(input.datasetPins),inputEvidenceIds:[...new Set(input.snapshot.inputEvidence)].sort(),trend:{status:trend.status,direction:trend.direction,signedChangeBps:trend.signedChangeBps,accelerationStatus:trend.accelerationStatus,accelerationBps:trend.accelerationBps,observationIds:[...trend.observationIds],previousWindowObservationIds:[...trend.previousWindowObservationIds],currentWindowObservationIds:[...trend.currentWindowObservationIds]},corroborationProviderIds:providers,corroborationEvidenceIds:[...new Set(input.corroborationEvidenceIds)].sort(),distinctProviderCount:providers.length,suspiciousFlags:[...new Set(input.suspiciousFlags??[])].sort(),integrityStatus:input.snapshot.integrityStatus,configHash:nonEmpty(input.snapshot.configHash,"CANONICAL_CONFIG_HASH_INVALID")};
  if(!validDate(record.asOf)||!validDate(record.availableAt)||record.availableAt>record.asOf) throw new Error("CANONICAL_M4_DATE_INVALID"); return {...record,fingerprint:canonicalM4Fingerprint(record)};
}

export function canonicalM5RecordFromEvaluation(input:{evaluation:{evaluationId:string;candidateId:string;asOf:string;policyVersion:string;profileVersion:string;status:CanonicalM5EligibilityRecord["status"];checks:readonly unknown[]};canonicalIdentifier:string;assetClass:string;canonicalContextId:string;availableAt:Date;evidenceIds:readonly string[];datasetPins:readonly string[];suspiciousFlags:readonly string[];suspiciousEvidenceStatus:SuspiciousEvidenceStatus;suspiciousAssessmentId:string;suspiciousAssessmentFingerprint:string;suspiciousAssessmentResult:"NO_FINDINGS"|"FINDINGS_PRESENT";assemblyFingerprint:string}):CanonicalM5EligibilityRecord {
 const reasonCodes=input.evaluation.checks.map(check=>typeof check==="object"&&check!==null&&"reasonCode" in check&&typeof check.reasonCode==="string"?check.reasonCode:"UNKNOWN"); const record={evaluationId:nonEmpty(input.evaluation.evaluationId,"CANONICAL_M5_ID_INVALID"),candidateId:nonEmpty(input.evaluation.candidateId,"CANONICAL_CANDIDATE_ID_INVALID"),canonicalIdentifier:nonEmpty(input.canonicalIdentifier,"CANONICAL_ASSET_ID_INVALID"),assetClass:nonEmpty(input.assetClass,"CANONICAL_ASSET_CLASS_INVALID"),canonicalContextId:nonEmpty(input.canonicalContextId,"CANONICAL_CONTEXT_ID_INVALID"),asOf:new Date(input.evaluation.asOf),availableAt:input.availableAt,policyVersion:nonEmpty(input.evaluation.policyVersion,"CANONICAL_VERSION_INVALID"),profileVersion:nonEmpty(input.evaluation.profileVersion,"CANONICAL_VERSION_INVALID"),status:input.evaluation.status,checks:[...input.evaluation.checks],reasonCodes,evidenceIds:[...new Set(input.evidenceIds)].sort(),suspiciousFlags:[...new Set(input.suspiciousFlags)].sort(),suspiciousEvidenceStatus:input.suspiciousEvidenceStatus,suspiciousAssessmentId:nonEmpty(input.suspiciousAssessmentId,"CANONICAL_M5_SUSPICIOUS_ASSESSMENT_ID_INVALID"),suspiciousAssessmentFingerprint:nonEmpty(input.suspiciousAssessmentFingerprint,"CANONICAL_M5_SUSPICIOUS_ASSESSMENT_FINGERPRINT_INVALID"),suspiciousAssessmentResult:input.suspiciousAssessmentResult,datasetPins:pins(input.datasetPins),assemblyFingerprint:nonEmpty(input.assemblyFingerprint,"CANONICAL_M5_ASSEMBLY_FINGERPRINT_INVALID")};
 if(!/^m5-suspicious-assessment:[a-f0-9]{64}$/.test(record.suspiciousAssessmentId)) throw new Error("CANONICAL_M5_SUSPICIOUS_ASSESSMENT_ID_INVALID"); if(!/^[a-f0-9]{64}$/.test(record.suspiciousAssessmentFingerprint)) throw new Error("CANONICAL_M5_SUSPICIOUS_ASSESSMENT_FINGERPRINT_INVALID"); if((record.suspiciousAssessmentResult==="NO_FINDINGS"&&record.suspiciousEvidenceStatus!=="CLEAN")||(record.suspiciousAssessmentResult==="FINDINGS_PRESENT"&&record.suspiciousEvidenceStatus!=="SUSPICIOUS")) throw new Error("CANONICAL_M5_SUSPICIOUS_BINDING_INVALID");
  if(!validDate(record.asOf)||!validDate(record.availableAt)||record.availableAt>record.asOf) throw new Error("CANONICAL_M5_DATE_INVALID"); if(!["ELIGIBLE","INELIGIBLE","INCOMPLETE"].includes(record.status)) throw new Error("CANONICAL_M5_STATUS_INVALID"); return {...record,fingerprint:canonicalM5Fingerprint(record)};
}
export function assertCanonicalM4Record(record:CanonicalM4AnalysisRecord):void { const {fingerprint,...body}=record; nonEmpty(record.canonicalContextId,"CANONICAL_CONTEXT_ID_INVALID"); if(record.distinctProviderCount!==new Set(record.corroborationProviderIds).size) throw new Error("CANONICAL_M4_PROVIDER_COUNT_MISMATCH"); if(canonicalM4Fingerprint(body)!==fingerprint) throw new Error("CANONICAL_M4_FINGERPRINT_MISMATCH"); }
export function assertCanonicalM5Record(record:CanonicalM5EligibilityRecord):void { const {fingerprint,...body}=record; nonEmpty(record.canonicalContextId,"CANONICAL_CONTEXT_ID_INVALID"); nonEmpty(record.assemblyFingerprint,"CANONICAL_M5_ASSEMBLY_FINGERPRINT_INVALID"); if(!/^m5-suspicious-assessment:[a-f0-9]{64}$/.test(record.suspiciousAssessmentId)) throw new Error("CANONICAL_M5_SUSPICIOUS_ASSESSMENT_ID_INVALID"); if(!validDate(record.asOf)||!validDate(record.availableAt)||record.availableAt>record.asOf) throw new Error("CANONICAL_M5_DATE_INVALID"); if(!["CLEAN","SUSPICIOUS","INCOMPLETE"].includes(record.suspiciousEvidenceStatus)) throw new Error("CANONICAL_M5_SUSPICIOUS_STATUS_INVALID"); if(!/^[a-f0-9]{64}$/.test(record.suspiciousAssessmentFingerprint)) throw new Error("CANONICAL_M5_SUSPICIOUS_ASSESSMENT_FINGERPRINT_INVALID"); if(record.status === "INCOMPLETE") throw new Error("CANONICAL_M5_INCOMPLETE_NOT_PERSISTABLE"); if((record.suspiciousAssessmentResult==="NO_FINDINGS"&&record.suspiciousEvidenceStatus!=="CLEAN")||(record.suspiciousAssessmentResult==="FINDINGS_PRESENT"&&record.suspiciousEvidenceStatus!=="SUSPICIOUS")) throw new Error("CANONICAL_M5_SUSPICIOUS_BINDING_INVALID"); if(canonicalM5Fingerprint(body)!==fingerprint) throw new Error("CANONICAL_M5_FINGERPRINT_MISMATCH"); }

export function joinCanonicalHighInterestEvidence(m4:readonly CanonicalM4AnalysisRecord[],m5:readonly CanonicalM5EligibilityRecord[],requestedAsOf:Date):readonly(CanonicalM4AnalysisRecord&{m5:CanonicalM5EligibilityRecord})[] {
  if(!validDate(requestedAsOf)) throw new Error("INVALID_AS_OF"); const pairs=m4.flatMap(analysis=>m5.filter(eligibility=>analysis.candidateId===eligibility.candidateId&&analysis.canonicalIdentifier===eligibility.canonicalIdentifier&&analysis.assetClass===eligibility.assetClass&&analysis.canonicalContextId===eligibility.canonicalContextId&&analysis.asOf.getTime()===eligibility.asOf.getTime()&&analysis.asOf<=requestedAsOf&&analysis.availableAt<=requestedAsOf&&eligibility.asOf<=requestedAsOf&&eligibility.availableAt<=requestedAsOf&&analysis.integrityStatus==="COMPLETE"&&eligibility.status==="ELIGIBLE"&&eligibility.suspiciousEvidenceStatus==="CLEAN").map(eligibility=>({analysis,eligibility})));
  const latest=new Map<string,(typeof pairs)[number]>(); const rank=(pair:(typeof pairs)[number])=>[pair.analysis.asOf.getTime(),pair.analysis.availableAt.getTime(),pair.eligibility.asOf.getTime(),pair.eligibility.availableAt.getTime(),pair.analysis.analysisId,pair.eligibility.evaluationId] as const;
  for(const pair of pairs){const key=`${pair.analysis.candidateId}|${pair.analysis.canonicalIdentifier}|${pair.analysis.assetClass}`;const old=latest.get(key);const a=rank(pair);let newer=!old;if(old){const b=rank(old);for(let i=0;i<4&&!newer;i++){if(a[i]!==b[i])newer=Number(a[i])>Number(b[i]);}if(!newer&&[0,1,2,3].every(i=>a[i]===b[i]))newer=`${a[4]}|${a[5]}`>`${b[4]}|${b[5]}`;}if(newer)latest.set(key,pair);}
  return [...latest.values()].map(pair=>({...pair.analysis,m5:pair.eligibility})).sort((a,b)=>a.candidateId.localeCompare(b.candidateId)||a.canonicalIdentifier.localeCompare(b.canonicalIdentifier)||a.analysisId.localeCompare(b.analysisId));
}
