import { createHash } from "node:crypto";
import type { IntelligenceStore, NewsEvent, MarketObservation } from "@/domain/intelligence/foundation";

export const INTELLIGENCE_ENGINE_VERSION = "intelligence-engine/v1";
export const INTELLIGENCE_FEATURE_SET_VERSION = "intelligence-feature-set/v1";
export const EVENT_SIGNATURE_VERSION = "event-signature/v1";
export const TREND_ANALYSIS_VERSION = "trend-analysis/v1";
export const REGIME_CLASSIFICATION_VERSION = "regime-classification/v1";
export const HISTORICAL_ANALOGUE_VERSION = "historical-analogue/v1";
export const TREND_ACCELERATION_VERSION = "trend-acceleration/v1";
export const HISTORICAL_ANALOGUE_FEATURE_SET_VERSION = "historical-analogue-feature-set/v1";
export type IntegrityStatus = "COMPLETE" | "INCOMPLETE" | "NO_DATA" | "INSUFFICIENT_DATA" | "UNSUPPORTED_DATASET" | "UNSUPPORTED_POLICY_VERSION";
export interface IntelligenceAnalysisConfig { readonly engineVersion: typeof INTELLIGENCE_ENGINE_VERSION; readonly featureSetVersion: typeof INTELLIGENCE_FEATURE_SET_VERSION; readonly asOf: Date; readonly providerDatasetPins: readonly { providerId: string; datasetVersion: string }[]; readonly eventSignatureVersion: typeof EVENT_SIGNATURE_VERSION; readonly trendPolicyVersion: typeof TREND_ANALYSIS_VERSION; readonly regimePolicyVersion: typeof REGIME_CLASSIFICATION_VERSION; readonly analoguePolicyVersion: typeof HISTORICAL_ANALOGUE_VERSION; readonly windowStart?: Date; readonly assetId?: string; readonly trendWindowMillis?: number; readonly analogueCandidateTimestamps?: readonly Date[]; readonly analogueLimit?: number; }
export interface TrendResult { readonly status: IntegrityStatus; readonly direction: "UP" | "DOWN" | "FLAT" | null; readonly signedChangeBps: string | null; readonly accelerationBps: string | null; readonly accelerationStatus: IntegrityStatus; readonly accelerationDirection: "ACCELERATING" | "DECELERATING" | "UNCHANGED" | null; readonly observationIds: readonly string[]; readonly previousWindowObservationIds: readonly string[]; readonly currentWindowObservationIds: readonly string[]; readonly version: typeof TREND_ANALYSIS_VERSION; readonly accelerationVersion: typeof TREND_ACCELERATION_VERSION; }
export interface IntelligenceSnapshot { readonly analysisId: string; readonly configHash: string; readonly asOf: string; readonly engineVersion: typeof INTELLIGENCE_ENGINE_VERSION; readonly datasets: readonly string[]; readonly inputEvidence: readonly string[]; readonly materialEvidence: readonly { evidenceId: string; availableAt: string }[]; readonly eventContexts: readonly { recordId: string; signature: string; classification: string; reasonCodes: readonly string[] }[]; readonly noveltyEvidence: readonly { signature: string; priorMatchCount: number; classification: "FIRST_SEEN" | "REPEATED" | "UNKNOWN" }[]; readonly corroborationEvidence: readonly { signature: string; distinctProviderCount: number; providerIds: readonly string[]; supportingRecordIds: readonly string[] }[]; readonly trends: readonly TrendResult[]; readonly regime: { status: IntegrityStatus; label: "RISK_ON" | "RISK_OFF" | "MIXED" | "UNKNOWN"; contributingObservationIds: readonly string[]; reasonCode: string; version: typeof REGIME_CLASSIFICATION_VERSION }; readonly analogues: readonly { candidateId: string; distance: string; candidateTimestamp: string }[]; readonly integrityStatus: IntegrityStatus; }
const canonical = (v: unknown) => JSON.stringify(v, (_, x) => x instanceof Date ? x.toISOString() : typeof x === "bigint" ? x.toString() : x);
const digest = (v: unknown) => createHash("sha256").update(canonical(v)).digest("hex");
const supported = (c: IntelligenceAnalysisConfig) => c.engineVersion === INTELLIGENCE_ENGINE_VERSION && c.featureSetVersion === INTELLIGENCE_FEATURE_SET_VERSION && c.eventSignatureVersion === EVENT_SIGNATURE_VERSION && c.trendPolicyVersion === TREND_ANALYSIS_VERSION && c.regimePolicyVersion === REGIME_CLASSIFICATION_VERSION && c.analoguePolicyVersion === HISTORICAL_ANALOGUE_VERSION;
const signature = (n: NewsEvent) => digest({ version: EVENT_SIGNATURE_VERSION, type: "NEWS", mappings: [...n.mappings].map(m => `${m.mappingKind}:${m.targetId}`).sort() });
const classification = (n: NewsEvent) => { const kinds = new Set(n.mappings.map(m => m.mappingKind)); if (kinds.has("COUNTRY") && kinds.has("TOPIC")) return "MACRO"; if (kinds.has("ASSET") || kinds.has("ENTITY")) return "MARKET"; return "UNKNOWN"; };
const bps = (first: bigint, last: bigint) => first === 0n ? null : ((last - first) * 10_000n / (first < 0n ? -first : first)).toString();
const trendAt = (rows: readonly MarketObservation[], at: Date, window: number): TrendResult => { const ordered=[...rows].filter(x=>x.observedAt<=at).sort((a,b)=>a.observedAt.getTime()-b.observedAt.getTime()||a.id.localeCompare(b.id)); const current=ordered.filter(x=>x.observedAt.getTime()>=at.getTime()-window); const previous=ordered.filter(x=>x.observedAt.getTime()>=at.getTime()-2*window&&x.observedAt.getTime()<at.getTime()-window); const calc=(r:readonly MarketObservation[])=>r.length>=2?bps(r[0]!.valueAtoms,r.at(-1)!.valueAtoms):null; const c=calc(current), p=calc(previous); const complete=c!==null; const accel=c!==null&&p!==null?(BigInt(c)-BigInt(p)).toString():null; return {status:complete?"COMPLETE":ordered.length?"INSUFFICIENT_DATA":"NO_DATA",direction:c===null?null:BigInt(c)>0n?"UP":BigInt(c)<0n?"DOWN":"FLAT",signedChangeBps:c,accelerationBps:accel,accelerationStatus:accel===null?(previous.length?"INCOMPLETE":"NO_DATA"):"COMPLETE",accelerationDirection:accel===null?null:BigInt(accel)>0n?"ACCELERATING":BigInt(accel)<0n?"DECELERATING":"UNCHANGED",observationIds:ordered.map(x=>x.id),previousWindowObservationIds:previous.map(x=>x.id),currentWindowObservationIds:current.map(x=>x.id),version:TREND_ANALYSIS_VERSION,accelerationVersion:TREND_ACCELERATION_VERSION}; };

export function analyzeIntelligenceAt(store: IntelligenceStore, config: IntelligenceAnalysisConfig): IntelligenceSnapshot {
  if (!supported(config)) throw new Error("UNSUPPORTED_POLICY_VERSION"); if (!Number.isFinite(config.asOf.getTime())) throw new Error("INVALID_AS_OF");
  const pins = [...config.providerDatasetPins].sort((a,b) => a.providerId.localeCompare(b.providerId) || a.datasetVersion.localeCompare(b.datasetVersion));
  const news = pins.flatMap(p => store.newsAvailableAt(config.asOf, p.datasetVersion).filter(n => n.providerId === p.providerId));
  const markets = pins.flatMap(p => store.marketAvailableAt(config.asOf, p.datasetVersion).filter(m => m.providerId === p.providerId && (!config.assetId || m.assetId === config.assetId) && m.observationType === "PRICE"));
  const contexts = news.map(n => ({ recordId: n.id, signature: signature(n), classification: classification(n), reasonCodes: ["STRUCTURED_MAPPINGS"] }));
  const novelty = contexts.map(c => { const prior = news.filter(n => signature(n) === c.signature && n.availableAt < config.asOf); return { signature: c.signature, priorMatchCount: prior.length, classification: prior.length ? "REPEATED" as const : "FIRST_SEEN" as const }; });
  const groups = new Map<string, NewsEvent[]>(); for (const n of news) { const key = signature(n); groups.set(key, [...(groups.get(key) ?? []), n]); }
  const corroboration = [...groups].map(([s, rows]) => ({ signature: s, distinctProviderCount: new Set(rows.map(r => r.providerId)).size, providerIds: [...new Set(rows.map(r => r.providerId))].sort(), supportingRecordIds: rows.map(r => r.id).sort() }));
  const trends: TrendResult[] = [trendAt(markets, config.asOf, config.trendWindowMillis ?? 31_536_000_000_000)];
  const trend = trends[0]!; const regimeLabel = trend.status === "COMPLETE" ? trend.direction === "UP" ? "RISK_ON" : trend.direction === "DOWN" ? "RISK_OFF" : "MIXED" : "UNKNOWN";
  const regime = { status: trend.status, label: regimeLabel, contributingObservationIds: trend.observationIds, reasonCode: trend.status === "COMPLETE" ? "TREND_DIRECTION" : "INSUFFICIENT_TREND_DATA", version: REGIME_CLASSIFICATION_VERSION } as IntelligenceSnapshot["regime"];
  const datasets = pins.map(p => `${p.providerId}:${p.datasetVersion}`); const inputEvidence = [...news.map(n => n.id), ...markets.map(m => m.id)].sort(); const configHash = digest({ ...config, asOf: config.asOf.toISOString(), providerDatasetPins: pins, analogueCandidateTimestamps: config.analogueCandidateTimestamps?.map(x=>x.toISOString()).sort() }); const analysisId = digest({ configHash, inputEvidence, algorithms: [INTELLIGENCE_ENGINE_VERSION, EVENT_SIGNATURE_VERSION, TREND_ANALYSIS_VERSION, TREND_ACCELERATION_VERSION, HISTORICAL_ANALOGUE_VERSION] });
  const queryTrend=trends[0]!; const analogueWindow=config.trendWindowMillis ?? 31_536_000_000_000; const candidates=(config.analogueCandidateTimestamps??[]).filter(c=>c<config.asOf).sort((a,b)=>a.getTime()-b.getTime()).map(c=>({candidateId:digest({c:c.toISOString(),datasets,featureSet:HISTORICAL_ANALOGUE_FEATURE_SET_VERSION}),candidateTimestamp:c.toISOString(),feature:trendAt(markets,c,analogueWindow)})).filter(x=>x.feature.status==="COMPLETE"&&x.feature.accelerationStatus==="COMPLETE").map(x=>({candidateId:x.candidateId,candidateTimestamp:x.candidateTimestamp,distance:(BigInt(queryTrend.signedChangeBps??0)-BigInt(x.feature.signedChangeBps??0)<0n?BigInt(x.feature.signedChangeBps??0)-BigInt(queryTrend.signedChangeBps??0):BigInt(queryTrend.signedChangeBps??0)-BigInt(x.feature.signedChangeBps??0))+(BigInt(queryTrend.accelerationBps??0)-BigInt(x.feature.accelerationBps??0)<0n?BigInt(x.feature.accelerationBps??0)-BigInt(queryTrend.accelerationBps??0):BigInt(queryTrend.accelerationBps??0)-BigInt(x.feature.accelerationBps??0))})).sort((a,b)=>BigInt(a.distance)<BigInt(b.distance)?-1:BigInt(a.distance)>BigInt(b.distance)?1:a.candidateTimestamp.localeCompare(b.candidateTimestamp)||a.candidateId.localeCompare(b.candidateId)).slice(0,config.analogueLimit??0).map(x=>({candidateId:x.candidateId,distance:x.distance.toString(),candidateTimestamp:x.candidateTimestamp}));
  const integrityStatus: IntegrityStatus = inputEvidence.length ? (trend.status === "COMPLETE" || news.length ? "COMPLETE" : trend.status) : "NO_DATA";
  const materialEvidence = [...new Map([...news, ...markets].map(item => [item.id, { evidenceId: item.id, availableAt: item.availableAt.toISOString() }])).values()].sort((a, b) => a.evidenceId.localeCompare(b.evidenceId));
  return Object.freeze({ analysisId, configHash, asOf: config.asOf.toISOString(), engineVersion: INTELLIGENCE_ENGINE_VERSION, datasets, inputEvidence, materialEvidence, eventContexts: contexts, noveltyEvidence: novelty, corroborationEvidence: corroboration, trends, regime, analogues: candidates, integrityStatus });
}
