import { createHash } from "node:crypto";

export const INTELLIGENCE_FOUNDATION_VERSION = "intelligence-foundation/v1";
export type ContentStorageMode = "METADATA_ONLY" | "LICENSED_EXCERPT" | "LICENSED_FULL_TEXT" | "PUBLIC_DOMAIN";
export type ProviderType = "COMPANY" | "REGULATOR" | "EXCHANGE" | "CENTRAL_BANK" | "STATISTICAL_AGENCY" | "PROFESSIONAL_NEWS" | "MARKET_DATA" | "MACRO_DATA" | "SYNTHETIC_FIXTURE";
export interface IntelligenceProvider { readonly providerId: string; readonly name: string; readonly providerType: ProviderType; readonly canonicalSource: string; readonly provenancePolicyVersion: string; readonly contentStorageMode: ContentStorageMode; }
export interface IntelligenceDataset { readonly datasetId: string; readonly providerId: string; readonly datasetVersion: string; readonly createdAt: Date; readonly sourceDescription: string; readonly contentStorageMode: ContentStorageMode; }
export interface Provenance { readonly providerId: string; readonly datasetId: string; readonly datasetVersion: string; readonly externalRecordId: string; readonly sourceUrl?: string; readonly sourceType: string; readonly sourceMetadata?: Readonly<Record<string, string>>; readonly payloadFingerprint: string; readonly foundationVersion: typeof INTELLIGENCE_FOUNDATION_VERSION; }
export interface NewsEvent { readonly id: string; readonly providerId: string; readonly datasetVersion: string; readonly externalRecordId: string; readonly revision: number; readonly publishedAt: Date; readonly availableAt: Date; readonly ingestedAt: Date; readonly title: string; readonly sourceUrl?: string; readonly sourceType: string; readonly provenance: Provenance; readonly mappings: readonly IntelligenceMapping[]; }
export interface MarketObservation { readonly id: string; readonly providerId: string; readonly datasetVersion: string; readonly externalRecordId: string; readonly assetId: string; readonly observedAt: Date; readonly availableAt: Date; readonly ingestedAt: Date; readonly observationType: "PRICE" | "VOLUME" | "VOLATILITY" | "MARKET_CAP"; readonly valueAtoms: bigint; readonly scale: number; readonly unit: string; readonly provenance: Provenance; }
export interface MacroObservation { readonly id: string; readonly providerId: string; readonly datasetVersion: string; readonly externalRecordId: string; readonly revision: number; readonly indicatorCode: string; readonly geography: string; readonly referencePeriodStart: Date; readonly referencePeriodEnd: Date; readonly observedAt?: Date; readonly publishedAt?: Date; readonly availableAt: Date; readonly ingestedAt: Date; readonly valueAtoms: bigint; readonly scale: number; readonly unit: string; readonly provenance: Provenance; }
export type MappingKind = "ENTITY" | "ASSET" | "TOPIC" | "SECTOR" | "COUNTRY";
export interface IntelligenceMapping { readonly recordId: string; readonly mappingKind: MappingKind; readonly targetId: string; readonly source: "SOURCE_PROVIDED" | "DETERMINISTIC_FIXTURE"; readonly evidence: string; }
const validDate = (d: Date) => Number.isFinite(d.getTime());
export function validateProvenance(p: Provenance): void { if (!p.providerId || !p.datasetId || !p.datasetVersion || !p.externalRecordId || !p.foundationVersion || !p.payloadFingerprint) throw new Error("INVALID_PROVENANCE"); }
export function validateNewsEvent(n: NewsEvent): void { validateProvenance(n.provenance); if (n.provenance.providerId !== n.providerId || n.provenance.datasetVersion !== n.datasetVersion || !n.externalRecordId || n.revision < 1 || !validDate(n.publishedAt) || !validDate(n.availableAt) || !validDate(n.ingestedAt) || n.availableAt.getTime() > n.ingestedAt.getTime()) throw new Error("INVALID_NEWS_EVENT"); }
export function validateMarketObservation(o: MarketObservation): void { validateProvenance(o.provenance); if (!o.assetId || o.valueAtoms < 0n || o.scale < 0 || !validDate(o.observedAt) || !validDate(o.availableAt) || !validDate(o.ingestedAt) || o.availableAt > o.ingestedAt) throw new Error("INVALID_MARKET_OBSERVATION"); }
export function validateMacroObservation(o: MacroObservation): void { validateProvenance(o.provenance); if (!o.indicatorCode || !o.geography || o.valueAtoms < 0n || o.scale < 0 || !validDate(o.referencePeriodStart) || !validDate(o.referencePeriodEnd) || o.referencePeriodStart > o.referencePeriodEnd || !validDate(o.availableAt) || !validDate(o.ingestedAt) || o.availableAt > o.ingestedAt) throw new Error("INVALID_MACRO_OBSERVATION"); }
export function payloadFingerprint(payload: unknown): string { return createHash("sha256").update(JSON.stringify(payload, (_, v) => typeof v === "bigint" ? v.toString() : v instanceof Date ? v.toISOString() : v)).digest("hex"); }
export interface IntelligenceStore { ingestNews(event: NewsEvent): NewsEvent; ingestMarket(observation: MarketObservation): MarketObservation; ingestMacro(observation: MacroObservation): MacroObservation; newsAvailableAt(asOf: Date, datasetVersion: string): readonly NewsEvent[]; marketAvailableAt(asOf: Date, datasetVersion: string): readonly MarketObservation[]; macroAvailableAt(asOf: Date, datasetVersion: string): readonly MacroObservation[]; }
export class InMemoryIntelligenceStore implements IntelligenceStore {
  private readonly news = new Map<string, NewsEvent>(); private readonly market = new Map<string, MarketObservation>(); private readonly macro = new Map<string, MacroObservation>();
  ingestNews(event: NewsEvent): NewsEvent { validateNewsEvent(event); const key = `${event.providerId}|${event.datasetVersion}|${event.externalRecordId}|${event.revision}`; const old = this.news.get(key); if (old && old.provenance.payloadFingerprint !== event.provenance.payloadFingerprint) throw new Error("SOURCE_RECORD_CONFLICT"); this.news.set(key, old ?? Object.freeze(event)); return old ?? event; }
  ingestMarket(o: MarketObservation): MarketObservation { validateMarketObservation(o); const key = `${o.providerId}|${o.datasetVersion}|${o.externalRecordId}`; const old = this.market.get(key); if (old && old.provenance.payloadFingerprint !== o.provenance.payloadFingerprint) throw new Error("SOURCE_RECORD_CONFLICT"); this.market.set(key, old ?? Object.freeze(o)); return old ?? o; }
  ingestMacro(o: MacroObservation): MacroObservation { validateMacroObservation(o); const key = `${o.providerId}|${o.datasetVersion}|${o.externalRecordId}|${o.revision}`; const old = this.macro.get(key); if (old && old.provenance.payloadFingerprint !== o.provenance.payloadFingerprint) throw new Error("SOURCE_RECORD_CONFLICT"); this.macro.set(key, old ?? Object.freeze(o)); return old ?? o; }
  newsAvailableAt(asOf: Date, datasetVersion: string): readonly NewsEvent[] { const visible = [...this.news.values()].filter(n => n.datasetVersion === datasetVersion && n.availableAt <= asOf); const latest = new Map<string, NewsEvent>(); for (const n of visible) { const old = latest.get(`${n.providerId}|${n.datasetVersion}|${n.externalRecordId}`); if (!old || n.revision > old.revision) latest.set(`${n.providerId}|${n.datasetVersion}|${n.externalRecordId}`, n); } return [...latest.values()].sort((a,b) => a.availableAt.getTime()-b.availableAt.getTime() || a.id.localeCompare(b.id)); }
  marketAvailableAt(asOf: Date, datasetVersion: string): readonly MarketObservation[] { return [...this.market.values()].filter(n => n.datasetVersion === datasetVersion && n.availableAt <= asOf).sort((a,b) => a.availableAt.getTime()-b.availableAt.getTime() || a.observedAt.getTime()-b.observedAt.getTime() || a.id.localeCompare(b.id)); }
  macroAvailableAt(asOf: Date, datasetVersion: string): readonly MacroObservation[] { const visible = [...this.macro.values()].filter(n => n.datasetVersion === datasetVersion && n.availableAt <= asOf); const latest = new Map<string, MacroObservation>(); for (const n of visible) { const key = `${n.providerId}|${n.datasetVersion}|${n.externalRecordId}`; const old = latest.get(key); if (!old || n.revision > old.revision) latest.set(key, n); } return [...latest.values()].sort((a,b) => a.availableAt.getTime()-b.availableAt.getTime() || a.id.localeCompare(b.id)); }
}
