import { canonicalSha256 } from "@/domain/intelligence/ingestion-provenance";

export const PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION = "m5-provider-asset-identity-assertion/v1" as const;
export type ProviderAssetIdentityType = "EVM_CONTRACT_ADDRESS";
export type ProviderAssetIdentityAssertion = Readonly<{ contractVersion: typeof PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION; providerAssetIdentityAssertionId: string; providerId: string; datasetId: string; datasetVersion: string; providerSourceNamespace: string; providerAssetId: string; identityType: ProviderAssetIdentityType; identityNamespace: string; identityValue: string; sourceArtifactId: string; sourceEnvelopeId: string; parserVersion: string; envelopeSchemaVersion: string; sourcePayloadFingerprint: string; fingerprint: string; recordedAt: string }>;
export type ProviderAssetIdentityAssertionInput = Omit<ProviderAssetIdentityAssertion, "contractVersion" | "providerAssetIdentityAssertionId" | "fingerprint"> & { readonly providerAssetIdentityAssertionId?: string; readonly fingerprint?: string; readonly contractVersion?: string };
const HASH = /^[a-f0-9]{64}$/; const TIME = /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/; const CHAIN = /^eip155:[1-9][0-9]*$/;
const nonblank = (value: unknown, code: string): string => { if (typeof value !== "string" || value !== value.trim() || !value) throw new Error(code); return value; };
const hash = (value: unknown, code: string) => { const result = nonblank(value, code); if (!HASH.test(result)) throw new Error(code); return result; };
const time = (value: unknown, code: string) => { const result = nonblank(value, code); if (!TIME.test(result) || Number.isNaN(Date.parse(result)) || new Date(result).toISOString() !== result) throw new Error(code); return result; };
type Material = Omit<ProviderAssetIdentityAssertion, "contractVersion" | "providerAssetIdentityAssertionId" | "fingerprint" | "recordedAt">;
type IdentityMaterial = Pick<Material, "providerId" | "datasetId" | "datasetVersion" | "providerSourceNamespace" | "providerAssetId" | "identityType" | "identityNamespace" | "identityValue" | "sourceArtifactId" | "sourceEnvelopeId" | "parserVersion" | "envelopeSchemaVersion">;
function material(input: ProviderAssetIdentityAssertionInput | Material): Readonly<Material> {
  const identityType = nonblank(input.identityType, "M5_PROVIDER_ASSET_IDENTITY_TYPE_INVALID"); if (identityType !== "EVM_CONTRACT_ADDRESS") throw new Error("M5_PROVIDER_ASSET_IDENTITY_TYPE_INVALID");
  const identityNamespace = nonblank(input.identityNamespace, "M5_PROVIDER_ASSET_IDENTITY_NAMESPACE_INVALID"); if (!CHAIN.test(identityNamespace)) throw new Error("M5_PROVIDER_ASSET_IDENTITY_NAMESPACE_INVALID");
  const identityValue = nonblank(input.identityValue, "M5_PROVIDER_ASSET_IDENTITY_VALUE_INVALID"); if (!/^0x[0-9a-fA-F]{40}$/.test(identityValue)) throw new Error("M5_PROVIDER_ASSET_IDENTITY_VALUE_INVALID");
  return Object.freeze({ providerId: nonblank(input.providerId, "M5_PROVIDER_ASSET_IDENTITY_PROVIDER_INVALID"), datasetId: nonblank(input.datasetId, "M5_PROVIDER_ASSET_IDENTITY_DATASET_INVALID"), datasetVersion: nonblank(input.datasetVersion, "M5_PROVIDER_ASSET_IDENTITY_DATASET_VERSION_INVALID"), providerSourceNamespace: nonblank(input.providerSourceNamespace, "M5_PROVIDER_ASSET_IDENTITY_PROVIDER_NAMESPACE_INVALID"), providerAssetId: nonblank(input.providerAssetId, "M5_PROVIDER_ASSET_IDENTITY_PROVIDER_ASSET_INVALID"), identityType: "EVM_CONTRACT_ADDRESS" as const, identityNamespace, identityValue: identityValue.toLowerCase(), sourceArtifactId: nonblank(input.sourceArtifactId, "M5_PROVIDER_ASSET_IDENTITY_ARTIFACT_INVALID"), sourceEnvelopeId: nonblank(input.sourceEnvelopeId, "M5_PROVIDER_ASSET_IDENTITY_ENVELOPE_INVALID"), parserVersion: nonblank(input.parserVersion, "M5_PROVIDER_ASSET_IDENTITY_PARSER_INVALID"), envelopeSchemaVersion: nonblank(input.envelopeSchemaVersion, "M5_PROVIDER_ASSET_IDENTITY_SCHEMA_INVALID"), sourcePayloadFingerprint: hash(input.sourcePayloadFingerprint, "M5_PROVIDER_ASSET_IDENTITY_PAYLOAD_FINGERPRINT_INVALID") });
}
export function providerAssetIdentityAssertionIdFor(input: Pick<ProviderAssetIdentityAssertion, keyof IdentityMaterial>): string { const value = material({ ...input, sourcePayloadFingerprint: "0".repeat(64) }); const identity: IdentityMaterial = { providerId: value.providerId, datasetId: value.datasetId, datasetVersion: value.datasetVersion, providerSourceNamespace: value.providerSourceNamespace, providerAssetId: value.providerAssetId, identityType: value.identityType, identityNamespace: value.identityNamespace, identityValue: value.identityValue, sourceArtifactId: value.sourceArtifactId, sourceEnvelopeId: value.sourceEnvelopeId, parserVersion: value.parserVersion, envelopeSchemaVersion: value.envelopeSchemaVersion }; return `m5-provider-asset-identity:${canonicalSha256({ contractVersion: PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION, ...identity })}`; }
export function providerAssetIdentityAssertionFingerprint(input: Omit<ProviderAssetIdentityAssertion, "fingerprint" | "recordedAt">): string { const value = material(input); return canonicalSha256({ contractVersion: PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION, providerAssetIdentityAssertionId: providerAssetIdentityAssertionIdFor(value), ...value }); }
export function createProviderAssetIdentityAssertion(input: ProviderAssetIdentityAssertionInput): ProviderAssetIdentityAssertion {
  if (input.contractVersion !== undefined && input.contractVersion !== PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION) throw new Error("M5_PROVIDER_ASSET_IDENTITY_CONTRACT_INVALID"); const value = material(input); const providerAssetIdentityAssertionId = providerAssetIdentityAssertionIdFor(value);
  if (input.providerAssetIdentityAssertionId !== undefined && nonblank(input.providerAssetIdentityAssertionId, "M5_PROVIDER_ASSET_IDENTITY_ID_INVALID") !== providerAssetIdentityAssertionId) throw new Error("M5_PROVIDER_ASSET_IDENTITY_ID_MISMATCH");
  const fingerprint = providerAssetIdentityAssertionFingerprint({ contractVersion: PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION, providerAssetIdentityAssertionId, ...value }); if (input.fingerprint !== undefined && hash(input.fingerprint, "M5_PROVIDER_ASSET_IDENTITY_FINGERPRINT_INVALID") !== fingerprint) throw new Error("M5_PROVIDER_ASSET_IDENTITY_FINGERPRINT_MISMATCH");
  return Object.freeze({ contractVersion: PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION, providerAssetIdentityAssertionId, ...value, fingerprint, recordedAt: time(input.recordedAt, "M5_PROVIDER_ASSET_IDENTITY_RECORDED_AT_INVALID") });
}
export function assertProviderAssetIdentityAssertion(value: ProviderAssetIdentityAssertion): void { createProviderAssetIdentityAssertion(value); }
