import { createHash } from "node:crypto";
import { canonicalSha256 } from "@/domain/intelligence/ingestion-provenance";

export const SEC_EVENT_BYTE_STORAGE_CONTRACT = "sec-event-document-byte-storage-decision/v1" as const;
export type SecRuntimeSourceProfileDescriptor=Readonly<{profileId:string;contractVersion:string;providerId:string;datasetId:string;datasetVersion:string;endpointProfile:string;pathTemplate:string;method:string;requestIdentityPolicy:string}>;
export function parseSecRuntimeSourceProfile(input:unknown):SecRuntimeSourceProfileDescriptor {
  if(!input||typeof input!=="object"||Array.isArray(input)||Object.getPrototypeOf(input)!==Object.prototype)throw new Error("SEC_EVENT_SOURCE_PROFILE_INVALID");
  const descriptors=Object.getOwnPropertyDescriptors(input);const keys=Object.keys(descriptors);const expected=["profileId","contractVersion","providerId","datasetId","datasetVersion","endpointProfile","pathTemplate","method","requestIdentityPolicy"];
  if(keys.length!==expected.length||keys.some(key=>!expected.includes(key))||Reflect.ownKeys(input).length!==expected.length||expected.some(key=>!descriptors[key]?.enumerable||!("value" in descriptors[key]!)))throw new Error("SEC_EVENT_SOURCE_PROFILE_INVALID");
  const value=Object.fromEntries(expected.map(key=>[key,descriptors[key]!.value])) as Record<string,unknown>;
  const patterns:Record<string,RegExp>={profileId:/^[a-z][a-z0-9-]*\/v[1-9][0-9]*$/,contractVersion:/^[a-z][a-z0-9-]*\/v[1-9][0-9]*$/,providerId:/^[A-Z][A-Z0-9_]*$/,datasetId:/^[a-z][a-z0-9-]*$/,datasetVersion:/^[a-z][a-z0-9-]*\/v[1-9][0-9]*$/,endpointProfile:/^[A-Z][A-Z0-9_]*$/,pathTemplate:/^\/(?!.*\.\.)(?!.*\s)[A-Za-z0-9_{}./-]+$/,method:/^[A-Z][A-Z0-9_-]*$/,requestIdentityPolicy:/^[a-z][a-z0-9-]*\/v[1-9][0-9]*$/};
  if(expected.some(key=>typeof value[key]!=="string"||!patterns[key]!.test(value[key] as string)))throw new Error("SEC_EVENT_SOURCE_PROFILE_INVALID");
  return Object.freeze(value as unknown as SecRuntimeSourceProfileDescriptor);
}
export const SEC_EVENT_RUNTIME_LIMITS = Object.freeze({ documentBytes: 8 * 1024 * 1024, packageBytes: 64 * 1024 * 1024, documents: 32, workerBytes: 96 * 1024 * 1024, documentTimeoutMs: 15_000, packageTimeoutMs: 8 * 60_000, transactionTimeoutMs: 2 * 60_000 });
export type SecRuntimeClockPort = Readonly<{nowMs():number}>;
export type SecRuntimeDeadlinePort = Readonly<{remainingMs(nowMs:number):number;expired(nowMs:number):boolean}>;
export function createSecRuntimeDeadline(startedAtMs:number,timeoutMs:number):SecRuntimeDeadlinePort {if(!Number.isFinite(startedAtMs)||startedAtMs<0||!Number.isSafeInteger(timeoutMs)||timeoutMs<=0)throw new Error("SEC_EVENT_DEADLINE_INVALID");return Object.freeze({remainingMs:(nowMs:number)=>Math.max(0,timeoutMs-(nowMs-startedAtMs)),expired:(nowMs:number)=>!Number.isFinite(nowMs)||nowMs-startedAtMs>=timeoutMs});}
export type SecRuntimeDocument = Readonly<{ locator:string; role:"FILING_INDEX"|"PRIMARY_DOCUMENT"|"EXHIBIT"; documentType:string; sequence:number; contentType:string; contentEncoding:"identity"; bytes:Uint8Array }>;
export type SecRuntimeReceipt = Readonly<{ receiptId:string; receivedAt:string; effectiveAvailableAt:string; responseStatus:number }>;
export type SecRuntimeMaterial = Readonly<{ profileId:string; profileFingerprint:string; cik:string; accession:string; form:"8-K"|"8-K/A"; filingDate:string; acceptanceAt:string; reportPeriod:string|null; amendmentParent:string|null; receipt:SecRuntimeReceipt; documents:readonly SecRuntimeDocument[] }>;
export type SecRuntimeDocumentAuthority = Readonly<{ blobId:string; sha256:string; byteLength:number; artifactId:string; fingerprint:string; locator:string; role:SecRuntimeDocument["role"]; documentType:string; sequence:number; contentType:string; canonicalizationVersion:"sec-document-entity-octets/v1"; bytes:Buffer }>;
export type SecRuntimePackageMaterial = Readonly<{sourceProfileId:string;sourceProfileFingerprint:string;filingIdentityId:string;cik:string;accessionNumber:string;form:string;filingDate:string;acceptanceTimestamp:string;reportPeriodDate:string|null;filingIndexArtifactId:string;filingIndexArtifactFingerprint:string;orderedDocumentMemberSet:readonly Readonly<{artifactId:string;artifactFingerprint:string;canonicalLocator:string;documentRole:string;documentType:string;sequenceOrdinal:number;sha256:string;byteLength:number}>[];memberCount:number;declaredDocumentCount:number;amendmentParentFilingIdentityId:string|null}>;
export type SecRuntimeTrustedBatch = Readonly<{ material:SecRuntimeMaterial; filingIdentityId:string; amendmentParentFilingIdentityId:string|null; requestId:string; attemptId:string; packageId:string; packageFingerprint:string; packageMaterial:SecRuntimePackageMaterial; documents:readonly SecRuntimeDocumentAuthority[]; receiptId:string; receiptFingerprint:string; responseMaterialFingerprint:string; lineageId:string; lineageFingerprint:string; profileFingerprint:string }>;
const trusted = new WeakSet<object>();
const sha = (b:Uint8Array) => { const hash=createHash("sha256");for(let offset=0;offset<b.byteLength;offset+=64*1024)hash.update(b.subarray(offset,Math.min(offset+64*1024,b.byteLength)));return hash.digest("hex"); };
const canonicalTime=(x:string)=>Number.isFinite(Date.parse(x))&&new Date(x).toISOString()===x;
const canonicalDate=(x:string|null)=>x===null||( /^\d{4}-\d{2}-\d{2}$/.test(x)&&Number.isFinite(Date.parse(`${x}T00:00:00.000Z`))&&new Date(`${x}T00:00:00.000Z`).toISOString().slice(0,10)===x );
const safeFixtureLocator=(x:string,cik:string,accession:string)=>x.startsWith(`/synthetic-edgar/archive/${cik}/${accession}/`)&&!x.includes("..")&&!x.includes("%")&&!x.includes("\\")&&!x.includes("?")&&!x.includes("#")&&/^\/synthetic-edgar\/archive\/[A-Z0-9-]+\/[A-Z0-9-]+\/[A-Za-z0-9._-]+$/.test(x);
// Reserve ingress + immutable snapshots, plus four per-document byte buffers
// for readback and driver encoding. This is a payload budget, not a V8 RSS cap.
export function secRuntimeBoundsAreValid(sizes:readonly number[],documentCount:number):boolean { return sizes.length===documentCount+1&&documentCount>=1&&documentCount<=SEC_EVENT_RUNTIME_LIMITS.documents&&sizes.every(n=>Number.isSafeInteger(n)&&n>=1&&n<=SEC_EVENT_RUNTIME_LIMITS.documentBytes)&&sizes.reduce((a,b)=>a+b,0)<=SEC_EVENT_RUNTIME_LIMITS.packageBytes&&2*sizes.reduce((a,b)=>a+b,0)+4*Math.max(...sizes)<=SEC_EVENT_RUNTIME_LIMITS.workerBytes; }
export function isTrustedSecRuntimeBatch(x:unknown): x is SecRuntimeTrustedBatch { return !!x && typeof x === "object" && trusted.has(x as object); }
export function createSecRuntimeBatch(material:SecRuntimeMaterial):SecRuntimeTrustedBatch {
  const docs=[...material.documents].sort((a,b)=>a.sequence-b.sequence);
  if(!/^sec-edgar-synthetic-fixture-profile\/v1$/.test(material.profileId) || !/^[0-9a-f]{64}$/.test(material.profileFingerprint) || !/^SYNTH-CIK-[0-9]{4}$/.test(material.cik) || !/^SYNTH-ACC-[A-Z0-9-]{4,32}$/.test(material.accession) || !["8-K","8-K/A"].includes(material.form) || (material.form==="8-K"&&material.amendmentParent!==null) || (material.form==="8-K/A"&&(!material.amendmentParent||material.amendmentParent===material.accession||!/^SYNTH-ACC-[A-Z0-9-]{4,32}$/.test(material.amendmentParent))) || !canonicalDate(material.filingDate)||!canonicalDate(material.reportPeriod)||!canonicalTime(material.acceptanceAt)||docs.length<2 || docs.length>SEC_EVENT_RUNTIME_LIMITS.documents+1 || !secRuntimeBoundsAreValid(docs.map(x=>x.bytes.byteLength),docs.filter(x=>x.role!=="FILING_INDEX").length) || new Set(docs.map(x=>x.locator)).size!==docs.length || docs.filter(x=>x.role==="FILING_INDEX").length!==1 || docs.filter(x=>x.role==="PRIMARY_DOCUMENT").length!==1 || docs.some((d,i)=>!(["FILING_INDEX","PRIMARY_DOCUMENT","EXHIBIT"].includes(d.role))||d.sequence!==i || d.contentEncoding!=="identity" || !safeFixtureLocator(d.locator,material.cik,material.accession)||!/^[a-z0-9.+-]+\/[a-z0-9.+-]+$/.test(d.contentType)) || !/^SYNTH-RECEIPT-[A-Z0-9-]{4,32}$/.test(material.receipt.receiptId)||material.receipt.responseStatus!==200 || !canonicalTime(material.receipt.receivedAt)||!canonicalTime(material.receipt.effectiveAvailableAt)) throw new Error("SEC_EVENT_RUNTIME_INPUT_INVALID");
  const filingIdentityId=canonicalSha256({sourceProfileId:material.profileId,sourceProfileFingerprint:material.profileFingerprint,cik:material.cik,accessionNumber:material.accession,form:material.form});
  const docAuthorities=docs.map(d=>{const snapshot=Buffer.from(d.bytes);const digest=sha(snapshot);const byteLength=snapshot.byteLength;const artifactMaterial={filingIdentityId,canonicalLocator:d.locator,documentRole:d.role,documentType:d.documentType,exactEntityBodyOctetsSha256:digest,contentType:d.contentType,byteLength,sequenceOrdinal:d.sequence,canonicalizationVersion:"sec-document-entity-octets/v1",noContentNormalization:true};const fingerprint=canonicalSha256(artifactMaterial);const artifactId=createHash("sha256").update("sec-event-document-id/v1:","utf8").update(fingerprint,"utf8").digest("hex");return Object.freeze({blobId:`sha256:${digest}:${byteLength}`,sha256:digest,byteLength,artifactId,fingerprint,locator:d.locator,role:d.role,documentType:d.documentType,sequence:d.sequence,contentType:d.contentType,canonicalizationVersion:"sec-document-entity-octets/v1" as const,get bytes(){return Buffer.from(snapshot);}});});
  const amendmentParentFilingIdentityId=material.amendmentParent?canonicalSha256({sourceProfileId:material.profileId,sourceProfileFingerprint:material.profileFingerprint,cik:material.cik,accessionNumber:material.amendmentParent,form:"8-K"}):null;
  const indexDoc=docAuthorities.find(d=>d.role==="FILING_INDEX")!;
  const packageMaterial={sourceProfileId:material.profileId,sourceProfileFingerprint:material.profileFingerprint,filingIdentityId,cik:material.cik,accessionNumber:material.accession,form:material.form,filingDate:material.filingDate,acceptanceTimestamp:material.acceptanceAt,reportPeriodDate:material.reportPeriod,filingIndexArtifactId:indexDoc.artifactId,filingIndexArtifactFingerprint:indexDoc.fingerprint,orderedDocumentMemberSet:docAuthorities.map(d=>({artifactId:d.artifactId,artifactFingerprint:d.fingerprint,canonicalLocator:d.locator,documentRole:d.role,documentType:d.documentType,sequenceOrdinal:d.sequence,sha256:d.sha256,byteLength:d.byteLength})),memberCount:docAuthorities.length,declaredDocumentCount:docAuthorities.length-1,amendmentParentFilingIdentityId};const packageFingerprint=canonicalSha256(packageMaterial);const packageId=createHash("sha256").update("sec-event-package-id/v1:","utf8").update(filingIdentityId,"utf8").update(":","utf8").update(packageFingerprint,"utf8").digest("hex");
  const requestId=`sec-request:${canonicalSha256({profileId:material.profileId,filingIdentityId})}`;const attemptId=`sec-attempt:${canonicalSha256({requestId,sourceReceiptId:material.receipt.receiptId,retrievedAt:material.receipt.receivedAt,effectiveAvailableAt:material.receipt.effectiveAvailableAt})}`;const responseMaterialFingerprint=canonicalSha256({responseStatus:material.receipt.responseStatus,contentEncoding:"identity",packageFingerprint,bodySha256:docAuthorities.map(d=>d.sha256)});const receiptFacts={requestId,attemptId,packageId,packageFingerprint,retrievedAt:material.receipt.receivedAt,effectiveAvailableAt:material.receipt.effectiveAvailableAt,responseStatus:material.receipt.responseStatus,contentEncoding:"identity",responseMaterialFingerprint};const receiptId=canonicalSha256(receiptFacts);const receiptFingerprint=canonicalSha256({...receiptFacts,sourceReceiptId:material.receipt.receiptId});
  const lineageMembers=docAuthorities.map((d,i)=>({packageId,packageFingerprint,packageMemberOrdinal:i,artifactId:d.artifactId,artifactFingerprint:d.fingerprint}));const lineageId=canonicalSha256({sourceProfileId:material.profileId,orderedPackageDocumentMemberReferences:lineageMembers,memberCount:lineageMembers.length});const amendmentParentChain=amendmentParentFilingIdentityId?[amendmentParentFilingIdentityId,filingIdentityId]:[filingIdentityId];const lineageFingerprint=canonicalSha256({lineageId,sourceProfileId:material.profileId,sourceProfileFingerprint:material.profileFingerprint,orderedPackageDocumentMemberSet:lineageMembers,memberCount:lineageMembers.length,rootFilingIdentityId:amendmentParentFilingIdentityId??filingIdentityId,amendmentParentChain});
  // Reuse each authority's private snapshot. Two full package snapshots would
  // exceed the 96 MiB worker budget for a maximum-size package.
  const sealedDocuments=Object.freeze(docs.map((d,i)=>Object.freeze({...d,get bytes(){return docAuthorities[i]!.bytes;}})));
  const sealedPackageMaterial=Object.freeze({...packageMaterial,orderedDocumentMemberSet:Object.freeze(packageMaterial.orderedDocumentMemberSet.map(member=>Object.freeze({...member})))});
  const batch=Object.freeze({material:Object.freeze({...material,receipt:Object.freeze({...material.receipt}),documents:sealedDocuments}),filingIdentityId,amendmentParentFilingIdentityId,requestId,attemptId,packageId,packageFingerprint,packageMaterial:sealedPackageMaterial,documents:Object.freeze(docAuthorities),receiptId,receiptFingerprint,responseMaterialFingerprint, lineageId,lineageFingerprint,profileFingerprint:material.profileFingerprint});trusted.add(batch);return batch;
}
export function hashExactEntityBody(bytes:Uint8Array):string{return sha(bytes);}
