import { canonicalSha256 } from "@/domain/intelligence/ingestion-provenance";
import { createHash } from "node:crypto";
import { types as utilTypes } from "node:util";

export const SEC_EVENT_PROVENANCE_DECISION_VERSION = "sec-edgar-event-source-provenance-decision/v1" as const;
export type ProvenanceDecisionStatus = "VALID" | "INVALID";
export type ReuseDisposition = "VALID" | "VALID_WITH_EXPLICIT_BINDING" | "INVALID";
export type ExistingProvenanceObject = Readonly<{
  table: string; semanticPurpose: string; identityMaterial: readonly string[];
  requiredParents: readonly string[]; requiresMarketObservation: boolean;
  requiresAvailabilityClaim: boolean; canonicalDocumentBytes: "YES" | "NO" | "CONDITIONAL";
  packageIndexExhibits: "YES" | "NO" | "CONDITIONAL"; amendmentHistory: "YES" | "NO" | "CONDITIONAL";
  scope: "PROVIDER_NEUTRAL" | "M5_SPECIFIC"; reuse: ReuseDisposition;
}>;
export type SecEventProvenanceDecision = Readonly<{
  contractVersion: typeof SEC_EVENT_PROVENANCE_DECISION_VERSION; status: ProvenanceDecisionStatus;
  selectedOption: "C"; rejectedOptions: readonly Readonly<{ option: "A" | "B"; reason: string }>[];
  existingObjects: readonly ExistingProvenanceObject[];
  authorityTables: readonly AuthorityTableDescriptor[];
  schemaObjectNames: Readonly<{ constraints:readonly string[]; indexes:readonly string[]; functions:readonly string[]; triggers:readonly string[] }>;
  authorityMaterial: Readonly<{ package: readonly string[]; document: readonly string[]; receipt: readonly string[]; lineage: readonly string[] }>;
  identityFormulas: Readonly<{filingIdentityId:string;documentArtifactId:string;documentArtifactFingerprint:string;packageFingerprint:string;packageId:string;receiptId:string;receiptFingerprint:string;lineageId:string;lineageFingerprint:string}>;
  byteIdentityPolicy: Readonly<{ hashedLayer: string; acceptedContentEncoding: readonly string[]; textCharset: string; newlineNormalization: string; unicodeNormalization: string; extractionTextRole: string; storageStatus: string; requiredStorageReadback: string }>;
  persistenceClassification: readonly Readonly<{ object: string; classification: "PERSISTED" | "DERIVED" | "EPHEMERAL" | "REJECTED"; reason: string }>[];
  schemaRules: Readonly<{nullableBranchChecks:readonly string[];packageSeal:readonly string[];lineageSeal:readonly string[];deferredInvariant:readonly string[];immutableMutation:string;rls:Readonly<{enabled:boolean;policyCount:number;revokedFrom:readonly string[];views:boolean;clientAccess:boolean}>;invariantFunctions:Readonly<{security:string;searchPath:string;executeRevokedFrom:readonly string[];securityDefiner:boolean}>}>;
  downstreamBindings: readonly Readonly<{ role: "event_source_provenance" | "issuer_evidence_provenance" | "asset_mapping_provenance"; binds: readonly string[]; excludes: readonly string[] }>[];
  persistence: Readonly<{ liveAcquisition: "BLOCKED"; sourceArtifact: "BLOCKED"; eventLineage: "BLOCKED"; issuerEvidence: "BLOCKED"; eventAuthority: "BLOCKED"; scheduler: "BLOCKED"; signals: "BLOCKED"; trading: "BLOCKED" }>;
  reviewedAt: string; recordedAt: string; fingerprint: string;
}>;
export type AuthorityTableDescriptor = Readonly<{ name:string; columns:readonly Readonly<{name:string;type:string}>[]; primaryKey:readonly string[]; uniqueKeys:readonly (readonly string[])[]; foreignKeys:readonly Readonly<{name:string;columns:readonly string[];parent:string;parentColumns:readonly string[]}>[]; indexes:readonly (readonly string[])[]; persistence:"REQUIRED"|"DERIVED"|"EPHEMERAL"|"REJECTED"|"EXISTING_PARENT_CATALOG" }>;

const tables: ExistingProvenanceObject[] = [
  { table:"intelligence_ingestion_requests", semanticPurpose:"Request identity, declared provider/dataset/version and adapter/parser contract", identityMaterial:["idempotency_key","provider_id","dataset_id","dataset_version","request_scope","request_fingerprint"], requiredParents:["intelligence_datasets(dataset_id,provider_id,dataset_version)"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_ingestion_attempts", semanticPurpose:"Attempt identity and immutable execution/parser versions", identityMaterial:["ingestion_request_id","attempt_number","attempt_fingerprint"], requiredParents:["intelligence_ingestion_requests"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_ingestion_events", semanticPurpose:"Append-only lifecycle/observation receipt events", identityMaterial:["ingestion_attempt_id","sequence","event_type","event_fingerprint","source_observation_id"], requiredParents:["intelligence_ingestion_attempts","intelligence_ingestion_source_observations for SOURCE_OBSERVED"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"CONDITIONAL", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_artifacts", semanticPurpose:"Provider-scoped artifact descriptor and content fingerprint", identityMaterial:["provider_id","dataset_id","dataset_version","provider_source_namespace","provider_external_record_id","provider_revision","payload_fingerprint","source_artifact_fingerprint"], requiredParents:["intelligence_datasets(dataset_id,provider_id,dataset_version)"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_envelopes", semanticPurpose:"Normalized/auditable payload envelope linked to an artifact", identityMaterial:["source_artifact_id","parser_contract_version","envelope_schema_version","payload_fingerprint","source_envelope_fingerprint"], requiredParents:["intelligence_source_artifacts(source_artifact_id,payload_fingerprint)"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_ingestion_source_observations", semanticPurpose:"Retrieved-at observation of an artifact in an attempt", identityMaterial:["ingestion_attempt_id","source_artifact_id","response_page_ordinal","item_ordinal","retrieved_at","observation_fingerprint"], requiredParents:["intelligence_ingestion_attempts","intelligence_source_artifacts"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_availability_claims", semanticPurpose:"Retrieval-observed effective availability", identityMaterial:["source_envelope_id","source_observation_id","source_artifact_id","effective_available_at","claim_fingerprint"], requiredParents:["intelligence_source_envelopes","intelligence_ingestion_source_observations"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_lineages", semanticPurpose:"Sealed provider/dataset/version set of retrieval-availability claims", identityMaterial:["provider_id","dataset_id","dataset_version","availability_claim_ids","member_count","fingerprint"], requiredParents:["intelligence_datasets"], requiresMarketObservation:false, requiresAvailabilityClaim:true, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"CONDITIONAL", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_lineage_members", semanticPurpose:"Ordinal member joining availability, artifact, envelope, observation and attempt", identityMaterial:["source_lineage_id","member_ordinal","availability_claim_id","source_artifact_id","source_envelope_id","source_observation_id","ingestion_attempt_id","provider_id","dataset_id","dataset_version","observed_at","effective_available_at","member_fingerprint"], requiredParents:["intelligence_source_lineages","intelligence_source_availability_claims","intelligence_source_artifacts","intelligence_source_envelopes","intelligence_ingestion_source_observations","intelligence_ingestion_attempts"], requiresMarketObservation:false, requiresAvailabilityClaim:true, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"CONDITIONAL", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_asset_mapping_revisions", semanticPurpose:"Canonical provider-asset identity revision scoped to M5 source lineage", identityMaterial:["mapping_revision_id","source_lineage_id","provider_id","dataset_id","dataset_version","canonical_asset_id","canonical_identifier","asset_class","fingerprint"], requiredParents:["intelligence_source_lineages","provider identity assertion"], requiresMarketObservation:false, requiresAvailabilityClaim:true, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"CONDITIONAL", scope:"M5_SPECIFIC", reuse:"INVALID" },
  { table:"market_observations", semanticPurpose:"Market measurement at an observed time, not a document publication", identityMaterial:["provider_id","dataset_id","asset_id","observed_at","price/volume material"], requiredParents:["market provider/dataset and asset identity"], requiresMarketObservation:true, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"INVALID" },
];

const external: AuthorityTableDescriptor[] = [
  {name:"intelligence_datasets",persistence:"EXISTING_PARENT_CATALOG",columns:[{name:"dataset_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_version",type:"text"}],primaryKey:["dataset_id"],uniqueKeys:[["provider_id","dataset_version"],["dataset_id","provider_id","dataset_version"]],foreignKeys:[],indexes:[]},
  {name:"intelligence_source_artifacts",persistence:"EXISTING_PARENT_CATALOG",columns:[{name:"source_artifact_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"},{name:"payload_fingerprint",type:"text"}],primaryKey:["source_artifact_id"],uniqueKeys:[["source_artifact_id","payload_fingerprint"],["source_artifact_id","provider_id","dataset_id","dataset_version"]],foreignKeys:[],indexes:[]},
  {name:"intelligence_source_lineages",persistence:"EXISTING_PARENT_CATALOG",columns:[{name:"source_lineage_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"}],primaryKey:["source_lineage_id"],uniqueKeys:[["source_lineage_id","provider_id","dataset_id","dataset_version"]],foreignKeys:[],indexes:[]},
  {name:"intelligence_source_lineage_members",persistence:"EXISTING_PARENT_CATALOG",columns:[{name:"source_lineage_id",type:"text"},{name:"member_ordinal",type:"integer"},{name:"availability_claim_id",type:"text"}],primaryKey:["source_lineage_id","member_ordinal"],uniqueKeys:[["source_lineage_id","availability_claim_id"]],foreignKeys:[],indexes:[]},
  {name:"intelligence_asset_mapping_revisions",persistence:"EXISTING_PARENT_CATALOG",columns:[{name:"mapping_revision_id",type:"text"},{name:"source_lineage_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"},{name:"canonical_asset_id",type:"text"},{name:"canonical_identifier",type:"text"},{name:"asset_class",type:"text"}],primaryKey:["mapping_revision_id"],uniqueKeys:[["mapping_revision_id","provider_id","dataset_id","dataset_version","canonical_asset_id","canonical_identifier","asset_class"],["mapping_revision_id","source_lineage_id","provider_id","dataset_id","dataset_version","canonical_asset_id","canonical_identifier","asset_class"]],foreignKeys:[],indexes:[]},
];
const eventTables: AuthorityTableDescriptor[] = [
  {name:"sec_event_source_profiles",persistence:"REQUIRED",columns:[{name:"profile_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"contract_version",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"},{name:"endpoint_profile",type:"text"},{name:"hostname_allowlist",type:"jsonb"},{name:"path_template",type:"text"},{name:"method",type:"text"},{name:"supported_forms",type:"jsonb"},{name:"authentication_kind",type:"text"},{name:"accepted_content_encoding",type:"jsonb"},{name:"request_identity_policy",type:"text"},{name:"max_timeout_ms",type:"integer"},{name:"max_response_bytes",type:"integer"},{name:"max_package_documents",type:"integer"}],primaryKey:["profile_id"],uniqueKeys:[["profile_id","fingerprint"],["provider_id","dataset_id","dataset_version"]],foreignKeys:[],indexes:[]},
  {name:"sec_event_filing_identities",persistence:"REQUIRED",columns:[{name:"filing_identity_id",type:"text"},{name:"profile_id",type:"text"},{name:"profile_fingerprint",type:"char(64)"},{name:"cik",type:"text"},{name:"accession_number",type:"text"},{name:"form",type:"text"},{name:"amendment_parent_filing_identity_id",type:"text"}],primaryKey:["filing_identity_id"],uniqueKeys:[["filing_identity_id","profile_id","profile_fingerprint","cik","accession_number","form"],["filing_identity_id","profile_id","cik"],["filing_identity_id","profile_id","profile_fingerprint"],["profile_id","cik","accession_number","form"]],foreignKeys:[{name:"sec_filing_profile_fk",columns:["profile_id","profile_fingerprint"],parent:"sec_event_source_profiles",parentColumns:["profile_id","fingerprint"]},{name:"sec_filing_amendment_parent_fk",columns:["amendment_parent_filing_identity_id","profile_id","cik"],parent:"sec_event_filing_identities",parentColumns:["filing_identity_id","profile_id","cik"]}],indexes:[["profile_id","profile_fingerprint"],["amendment_parent_filing_identity_id","profile_id","cik"]]},
  {name:"sec_event_acquisition_requests",persistence:"REQUIRED",columns:[{name:"request_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"idempotency_key",type:"text"},{name:"profile_id",type:"text"},{name:"profile_fingerprint",type:"char(64)"},{name:"filing_identity_id",type:"text"},{name:"requested_at",type:"timestamptz"}],primaryKey:["request_id"],uniqueKeys:[["request_id","fingerprint"],["request_id","filing_identity_id"],["profile_id","idempotency_key"]],foreignKeys:[{name:"sec_request_filing_scope_fk",columns:["filing_identity_id","profile_id","profile_fingerprint"],parent:"sec_event_filing_identities",parentColumns:["filing_identity_id","profile_id","profile_fingerprint"]}],indexes:[["profile_id","profile_fingerprint"],["filing_identity_id","profile_id","profile_fingerprint"]]},
  {name:"sec_event_acquisition_attempts",persistence:"REQUIRED",columns:[{name:"attempt_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"request_id",type:"text"},{name:"attempt_ordinal",type:"integer"},{name:"started_at",type:"timestamptz"}],primaryKey:["attempt_id"],uniqueKeys:[["attempt_id","fingerprint"],["attempt_id","request_id"],["request_id","attempt_ordinal"]],foreignKeys:[{name:"sec_attempt_request_fk",columns:["request_id"],parent:"sec_event_acquisition_requests",parentColumns:["request_id"]}],indexes:[["request_id","attempt_ordinal"]]},
  {name:"sec_event_document_artifacts",persistence:"REQUIRED",columns:[{name:"artifact_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"filing_identity_id",type:"text"},{name:"document_role",type:"text"},{name:"sequence_ordinal",type:"integer"},{name:"canonical_locator",type:"text"},{name:"content_sha256",type:"char(64)"},{name:"content_type",type:"text"},{name:"byte_length",type:"integer"},{name:"canonicalization_version",type:"text"}],primaryKey:["artifact_id"],uniqueKeys:[["artifact_id","fingerprint"],["artifact_id","fingerprint","filing_identity_id","document_role","sequence_ordinal","canonical_locator"],["artifact_id","fingerprint","document_role","sequence_ordinal"]],foreignKeys:[{name:"sec_document_filing_identity_fk",columns:["filing_identity_id"],parent:"sec_event_filing_identities",parentColumns:["filing_identity_id"]}],indexes:[["filing_identity_id","document_role","sequence_ordinal"]]},
  {name:"sec_event_filing_packages",persistence:"REQUIRED",columns:[{name:"package_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"filing_identity_id",type:"text"},{name:"filing_date",type:"date"},{name:"acceptance_at",type:"timestamptz"},{name:"report_period",type:"date"},{name:"filing_index_artifact_id",type:"text"},{name:"filing_index_artifact_fingerprint",type:"char(64)"},{name:"member_count",type:"integer"}],primaryKey:["package_id"],uniqueKeys:[["package_id","fingerprint"],["package_id","fingerprint","filing_identity_id"]],foreignKeys:[{name:"sec_package_identity_fk",columns:["filing_identity_id"],parent:"sec_event_filing_identities",parentColumns:["filing_identity_id"]},{name:"sec_package_index_fk",columns:["filing_index_artifact_id","filing_index_artifact_fingerprint"],parent:"sec_event_document_artifacts",parentColumns:["artifact_id","fingerprint"]}],indexes:[["filing_identity_id"],["filing_index_artifact_id","filing_index_artifact_fingerprint"]]},
  {name:"sec_event_package_document_members",persistence:"REQUIRED",columns:[{name:"package_id",type:"text"},{name:"package_fingerprint",type:"char(64)"},{name:"filing_identity_id",type:"text"},{name:"member_ordinal",type:"integer"},{name:"artifact_id",type:"text"},{name:"artifact_fingerprint",type:"char(64)"},{name:"document_role",type:"text"},{name:"sequence_ordinal",type:"integer"},{name:"canonical_locator",type:"text"},{name:"is_primary",type:"boolean"}],primaryKey:["package_id","package_fingerprint","member_ordinal"],uniqueKeys:[["package_id","package_fingerprint","artifact_id"],["package_id","package_fingerprint","canonical_locator"],["package_id","package_fingerprint","member_ordinal","artifact_id","artifact_fingerprint"]],foreignKeys:[{name:"sec_package_member_parent_fk",columns:["package_id","package_fingerprint","filing_identity_id"],parent:"sec_event_filing_packages",parentColumns:["package_id","fingerprint","filing_identity_id"]},{name:"sec_package_member_artifact_fk",columns:["artifact_id","artifact_fingerprint","filing_identity_id","document_role","sequence_ordinal","canonical_locator"],parent:"sec_event_document_artifacts",parentColumns:["artifact_id","fingerprint","filing_identity_id","document_role","sequence_ordinal","canonical_locator"]}],indexes:[["package_id","package_fingerprint","filing_identity_id"],["artifact_id","artifact_fingerprint","filing_identity_id","document_role","sequence_ordinal","canonical_locator"]]},
  {name:"sec_event_acquisition_receipts",persistence:"REQUIRED",columns:[{name:"receipt_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"request_id",type:"text"},{name:"attempt_id",type:"text"},{name:"filing_identity_id",type:"text"},{name:"package_id",type:"text"},{name:"package_fingerprint",type:"char(64)"},{name:"retrieved_at",type:"timestamptz"},{name:"effective_available_at",type:"timestamptz"},{name:"response_status",type:"integer"},{name:"response_material_fingerprint",type:"char(64)"}],primaryKey:["receipt_id"],uniqueKeys:[["receipt_id","fingerprint"]],foreignKeys:[{name:"sec_receipt_attempt_fk",columns:["attempt_id","request_id"],parent:"sec_event_acquisition_attempts",parentColumns:["attempt_id","request_id"]},{name:"sec_receipt_request_filing_fk",columns:["request_id","filing_identity_id"],parent:"sec_event_acquisition_requests",parentColumns:["request_id","filing_identity_id"]},{name:"sec_receipt_package_scope_fk",columns:["package_id","package_fingerprint","filing_identity_id"],parent:"sec_event_filing_packages",parentColumns:["package_id","fingerprint","filing_identity_id"]}],indexes:[["attempt_id","request_id"],["request_id","filing_identity_id"],["package_id","package_fingerprint","filing_identity_id"]]},
  {name:"sec_event_source_lineages",persistence:"REQUIRED",columns:[{name:"lineage_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"profile_id",type:"text"},{name:"profile_fingerprint",type:"char(64)"},{name:"member_count",type:"integer"},{name:"member_set_fingerprint",type:"char(64)"}],primaryKey:["lineage_id"],uniqueKeys:[["lineage_id","fingerprint"],["lineage_id","profile_id","profile_fingerprint"]],foreignKeys:[{name:"sec_lineage_profile_fk",columns:["profile_id","profile_fingerprint"],parent:"sec_event_source_profiles",parentColumns:["profile_id","fingerprint"]}],indexes:[["profile_id","profile_fingerprint"]]},
  {name:"sec_event_source_lineage_members",persistence:"REQUIRED",columns:[{name:"lineage_id",type:"text"},{name:"member_ordinal",type:"integer"},{name:"package_id",type:"text"},{name:"package_fingerprint",type:"char(64)"},{name:"package_member_ordinal",type:"integer"},{name:"artifact_id",type:"text"},{name:"artifact_fingerprint",type:"char(64)"}],primaryKey:["lineage_id","member_ordinal"],uniqueKeys:[["lineage_id","package_id","package_fingerprint","package_member_ordinal"]],foreignKeys:[{name:"sec_lineage_member_parent_fk",columns:["lineage_id"],parent:"sec_event_source_lineages",parentColumns:["lineage_id"]},{name:"sec_lineage_member_package_fk",columns:["package_id","package_fingerprint","package_member_ordinal","artifact_id","artifact_fingerprint"],parent:"sec_event_package_document_members",parentColumns:["package_id","package_fingerprint","member_ordinal","artifact_id","artifact_fingerprint"]}],indexes:[["lineage_id","member_ordinal"],["package_id","package_fingerprint","package_member_ordinal","artifact_id","artifact_fingerprint"]]},
];
const decisionTables = [...external,...eventTables];
const schemaObjectNames = Object.freeze({
  constraints:Object.freeze(decisionTables.flatMap(t=>[`${t.name}_pk`,...t.uniqueKeys.map((_,i)=>`${t.name}_uq_${i+1}`),...t.foreignKeys.map(f=>f.name)])),
  indexes:Object.freeze(decisionTables.flatMap(t=>t.indexes.map((_,i)=>`${t.name}_idx_${i+1}`))),
  functions:Object.freeze(["sec_event_assert_package_seal","sec_event_assert_lineage_seal","sec_event_assert_amendment_parent"]),
  triggers:Object.freeze([...eventTables.map(t=>`${t.name}_immutable`),"sec_event_filing_identity_amendment_deferred","sec_event_filing_package_seal_deferred","sec_event_package_document_member_seal_deferred","sec_event_source_lineage_seal_deferred","sec_event_source_lineage_member_seal_deferred"]),
});
function validateSchema(tables:readonly AuthorityTableDescriptor[]):void {
  const names=new Set<string>(); const map=new Map<string,AuthorityTableDescriptor>();
  for(const t of tables){ if(!/^[a-z][a-z0-9_]{0,62}$/.test(t.name)||names.has(t.name))throw new Error("SEC_EVENT_PROVENANCE_TABLE_INVALID"); names.add(t.name);map.set(t.name,t); const cols=t.columns.map(c=>c.name); if(new Set(cols).size!==cols.length||cols.some(c=>!/^[a-z][a-z0-9_]{0,62}$/.test(c))||t.primaryKey.length===0||new Set(t.primaryKey).size!==t.primaryKey.length||t.primaryKey.some(c=>!cols.includes(c))||new Set(t.uniqueKeys.map(k=>k.join("\u0000"))).size!==t.uniqueKeys.length||new Set(t.indexes.map(k=>k.join("\u0000"))).size!==t.indexes.length||t.uniqueKeys.some(k=>!k.length||new Set(k).size!==k.length||k.some(c=>!cols.includes(c)))||t.indexes.some(k=>!k.length||k.some(c=>!cols.includes(c)))||!(["REQUIRED","DERIVED","EPHEMERAL","REJECTED","EXISTING_PARENT_CATALOG"] as string[]).includes(t.persistence))throw new Error(`SEC_EVENT_PROVENANCE_COLUMN_OR_PK_INVALID:${t.name}`); }
  const fkNames=new Set<string>();
  for(const t of tables){ const cols=new Map(t.columns.map(c=>[c.name,c.type])); for(const fk of t.foreignKeys){if(!/^[a-z][a-z0-9_]{0,62}$/.test(fk.name)||fkNames.has(fk.name))throw new Error("SEC_EVENT_PROVENANCE_CONSTRAINT_NAME_INVALID");fkNames.add(fk.name); const p=map.get(fk.parent); if(!p||fk.columns.length===0||fk.columns.length!==fk.parentColumns.length||new Set(fk.columns).size!==fk.columns.length||new Set(fk.parentColumns).size!==fk.parentColumns.length)throw new Error(`SEC_EVENT_PROVENANCE_FK_INVALID:${t.name}:${fk.name}`); const parentKeys=[p.primaryKey,...p.uniqueKeys]; if(!parentKeys.some(k=>k.length===fk.parentColumns.length&&k.every((c,i)=>c===fk.parentColumns[i])))throw new Error(`SEC_EVENT_PROVENANCE_PARENT_KEY_INVALID:${t.name}:${fk.name}`); for(let i=0;i<fk.columns.length;i++)if(!cols.has(fk.columns[i])||p.columns.find(c=>c.name===fk.parentColumns[i])?.type!==cols.get(fk.columns[i]))throw new Error(`SEC_EVENT_PROVENANCE_FK_TYPE_INVALID:${t.name}:${fk.name}`); if(!t.indexes.some(ix=>ix.length>=fk.columns.length&&fk.columns.every((c,i)=>ix[i]===c)))throw new Error(`SEC_EVENT_PROVENANCE_CHILD_INDEX_INVALID:${t.name}:${fk.name}`); }}
  }
  for(const [kind,values] of [["constraint",schemaObjectNames.constraints],["index",schemaObjectNames.indexes],["function",schemaObjectNames.functions],["trigger",schemaObjectNames.triggers]] as const){ if(values.some(n=>!/^[a-z][a-z0-9_]{0,62}$/.test(n))||new Set(values).size!==values.length)throw new Error(`SEC_EVENT_PROVENANCE_${kind.toUpperCase()}_NAME_INVALID`); }
validateSchema(decisionTables);

const packageMaterial = ["sourceProfileId","sourceProfileFingerprint","filingIdentityId","cik","accessionNumber","form","filingDate","acceptanceTimestamp","reportPeriodDate","filingIndexArtifactId","filingIndexArtifactFingerprint","orderedDocumentMemberSet","memberCount","amendmentParentFilingIdentityId"] as const;
const documentMaterial = ["filingIdentityId","canonicalLocator","documentRole","documentType","exactEntityBodyOctetsSha256","contentType","byteLength","sequenceOrdinal","canonicalizationVersion","noContentNormalization"] as const;
const receiptMaterial = ["requestId","attemptId","receiptId","sourceProfileId","endpointProfile","responseStatus","contentEncoding","retrievedAt","effectiveAvailableAt","responseMaterialFingerprint","packageId","packageFingerprint"] as const;
const lineageMaterial = ["lineageId","lineageFingerprint","sourceProfileId","sourceProfileFingerprint","orderedPackageDocumentMemberSet","memberCount","contiguousOrdinals","rootFilingIdentityId","amendmentParentChain","recordedAtExcludedFromMaterialIdentity"] as const;
const identityFormulas = {
  filingIdentityId:"SHA256(canonical JSON of sourceProfileId + sourceProfileFingerprint + CIK + canonical accession + form).",
  documentArtifactId:"SHA256(UTF-8 bytes of the domain-separation prefix sec-event-document-id/v1 followed by the lowercase documentArtifactFingerprint). It does not include packageId/packageFingerprint or receipt fields.",
  documentArtifactFingerprint:"SHA256(canonical JSON of filingIdentityId + canonical locator + role + document type + exact entity-body SHA-256 + content type + byte length + sequence + canonicalization version; no raw JavaScript string hashing).",
  packageFingerprint:"SHA256(canonical JSON of filing metadata + filing-index artifact identity + exact ordered document-member tuples (artifact ID/fingerprint, role, sequence, locator) + count + amendment-parent filing identity).",
  packageId:"SHA256(UTF-8 bytes of the domain-separation prefix sec-event-package-id/v1 + filingIdentityId + packageFingerprint). Document artifacts reference filingIdentityId only, preventing package/member/document hash cycles.",
  receiptId:"SHA256(canonical JSON of requestId + attemptId + packageId + packageFingerprint + retrieval facts + response material fingerprint).",
  receiptFingerprint:"SHA256(canonical JSON of immutable receipt material; never an input to document or package identity).",
  lineageId:"SHA256(canonical JSON of sourceProfileId + exact ordered package-document member references + count).",
  lineageFingerprint:"SHA256(canonical JSON of lineage identity and sealed member scope; never part of a member's parent FK columns).",
} as const;
const byteIdentityPolicy = {
  hashedLayer:"Exact HTTP entity-body octets after transfer-framing removal and before content decoding or character decoding; request Accept-Encoding: identity and reject any non-identity Content-Encoding.",
  acceptedContentEncoding:["identity","absent"],
  textCharset:"For text extraction only: require declared UTF-8 or an explicitly approved profile default; strict UTF-8 decode with fatal errors.",
  newlineNormalization:"NONE; CR, LF and CRLF octets remain distinct in the document hash.",
  unicodeNormalization:"NONE; bytes are never NFC/NFD normalized before hashing.",
  extractionTextRole:"Derived non-authoritative parser input; never substitutes for or changes document-byte identity.",
  storageStatus:"BLOCKED_BACKEND_UNSELECTED",
  requiredStorageReadback:"Before persistence is enabled, select an approved immutable content-addressed byte store; reread exact stored octets and verify SHA-256 and byte length against the immutable artifact row. Fingerprint-only or normalized-text-only storage is insufficient.",
} as const;
const persistenceClassification = [
  {object:"versioned SEC source profile authority",classification:"PERSISTED" as const,reason:"A profile fingerprint must be an authoritative parent for provider/dataset/version, endpoint, form, request and content-encoding scope; no M5 registry is assumed generic."},
  {object:"SEC acquisition request and attempt",classification:"PERSISTED" as const,reason:"Distinct request identity and append-only attempt identity are required for receipt provenance; M5 request/attempt rows are operational M5 contracts and are not assumed to prove SEC profile scope."},
  {object:"filing identity and filing package revision",classification:"PERSISTED" as const,reason:"Filing key/metadata/index identity and exact declared document membership are durable authority material."},
  {object:"immutable document bytes and artifact metadata",classification:"PERSISTED" as const,reason:"Required eventual authority; currently BLOCKED until an approved immutable byte store and exact reread contract exist."},
  {object:"package-document membership",classification:"PERSISTED" as const,reason:"A separately sealed complete index-declared document set is not interchangeable with a downstream event evidence lineage."},
  {object:"acquisition receipt and effective availability",classification:"PERSISTED" as const,reason:"Receipt/retrieval provenance changes independently of document identity; effective availability is recorded on this receipt."},
  {object:"event-source lineage and members",classification:"PERSISTED" as const,reason:"A downstream selected/sealed evidence set can span original and amendment package revisions and differs from package completeness membership."},
  {object:"publication and report-period projections",classification:"DERIVED" as const,reason:"Publication/acceptance and report period are immutable filing metadata; derived projections must not duplicate them as independent authority."},
  {object:"normalized event claims and mapped claims",classification:"DERIVED" as const,reason:"Claims are derived from immutable document artifacts; mappings remain in the existing independent issuer and AssetMappingRevision authorities."},
  {object:"corroboration eligibility evaluation",classification:"EPHEMERAL" as const,reason:"Evaluation is reproducible from pinned policy and exact sealed inputs; this provenance decision does not persist it."},
  {object:"M5 market observations as SEC evidence",classification:"REJECTED" as const,reason:"A market measurement is not a filing or document authority."},
] as const;
const schemaRules = {
  nullableBranchChecks:["filing identity: base 8-K has amendment_parent_filing_identity_id IS NULL; 8-K/A has it IS NOT NULL; parent must share profile and CIK and must be an earlier accession; cycles and forks fail at deferred validation."],
  packageSeal:["one filing index artifact; one primary document; exact index-declared member count; contiguous zero-based ordinals; unique locator per package revision; no undeclared/missing members; package fingerprint binds index artifact and ordered member artifact IDs/fingerprints/roles/sequences/locators."],
  lineageSeal:["exact declared count; contiguous zero-based ordinals; each member references an exact package-document membership row; no duplicate member; lineage may select evidence across package revisions and is not the package-completeness set."],
  deferredInvariant:["DEFERRABLE INITIALLY DEFERRED constraint triggers validate package and lineage seals plus amendment parent scope, order, cycle/fork rules; invariant failures use SQLSTATE 23514 and stable sanitized codes."],
  immutableMutation:"All authority tables reject UPDATE and DELETE through the existing immutable mutation trigger when compatible.",
  rls:{enabled:true,policyCount:0,revokedFrom:["PUBLIC","anon","authenticated"],views:false,clientAccess:false},
  invariantFunctions:{security:"INVOKER",searchPath:"public, pg_temp",executeRevokedFrom:["PUBLIC","anon","authenticated"],securityDefiner:false},
} as const;
const bindings = [
  { role:"event_source_provenance" as const, binds:["SEC source-profile and filing identity","package revision and package-document membership","document artifact ID/fingerprint and exact entity-body byte hash","SEC event-source lineage ID plus exact package-member reference","filing/accession/form and document locator/role"], excludes:["M5 SourceLineage and AssetMappingRevision lineage","generic evidence.referenceId"] },
  { role:"issuer_evidence_provenance" as const, binds:["issuer authority evidence member ID/fingerprint","structured source-lineage/member scope resolved from immutable provenance"], excludes:["untyped referenceId as lineage ID","SEC claim provenance unless it is the same cited evidence authority"] },
  { role:"asset_mapping_provenance" as const, binds:["existing mapping_revision_id","its own source_lineage_id/provider_id/dataset_id/dataset_version","canonical_asset_id/canonical_identifier/asset_class"], excludes:["SEC source lineage","issuer evidence lineage","new canonical asset registry"] },
];

const iso = (x: unknown): x is string => typeof x === "string" && /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(x) && Number.isFinite(Date.parse(x)) && new Date(x).toISOString() === x;
const plain = (x: unknown): x is Record<string, unknown> => { try { if(!x||typeof x!=="object"||Object.getPrototypeOf(x)!==Object.prototype)return false; return Reflect.ownKeys(x).every(k=>typeof k==="string"&&"value" in Object.getOwnPropertyDescriptor(x,k)!); } catch { return false; } };
function strictTree(x:unknown,depth=0,budget={n:0}):boolean { try { if(depth>20||++budget.n>20_000)return false; if(x===null||typeof x==="string"||typeof x==="boolean"||(typeof x==="number"&&Number.isFinite(x)))return true; if(typeof x!=="object"||utilTypes.isProxy(x))return false; if(Array.isArray(x)){if(Object.getPrototypeOf(x)!==Array.prototype)return false;const keys=Reflect.ownKeys(x);if(keys.length!==x.length+1||keys.some(k=>k!=="length"&&(typeof k!=="string"||!/^(0|[1-9][0-9]*)$/.test(k)||Number(k)>=x.length||!("value" in Object.getOwnPropertyDescriptor(x,k)!))))return false;for(let i=0;i<x.length;i++)if(!Object.hasOwn(x,i)||!strictTree(x[i],depth+1,budget))return false;return true;}if(!plain(x))return false;for(const d of Object.values(Object.getOwnPropertyDescriptors(x)))if(!("value" in d))return false;for(const v of Object.values(x))if(!strictTree(v,depth+1,budget))return false;return true;}catch{return false;} }
const deepFreeze = <T>(x:T):T => { if(x && typeof x === "object" && !Object.isFrozen(x)){ for(const v of Object.values(x as Record<string,unknown>)) deepFreeze(v); Object.freeze(x); } return x; };

export type SecDocumentIdentityInput = Readonly<{filingIdentityId:string;canonicalLocator:string;documentRole:"FILING_INDEX"|"PRIMARY_DOCUMENT"|"EXHIBIT"|"OTHER";documentType:string;contentSha256:string;contentType:string;byteLength:number;sequenceOrdinal:number;canonicalizationVersion:"sec-document-entity-octets/v1"}>;
export type SecPackageMemberIdentity = Readonly<{ordinal:number;artifactId:string;artifactFingerprint:string;canonicalLocator:string;documentRole:SecDocumentIdentityInput["documentRole"];sequenceOrdinal:number;byteLength:number}>;
const SHA256=/^[a-f0-9]{64}$/;
const safeId=(value:string):boolean=>/^[a-z0-9][a-z0-9._:-]{0,127}$/.test(value)&&!/(https?:|www\.|api.?key|secret|bearer|credential|token)/i.test(value);
const safeLocator=(value:string):boolean=>value.length<=512&&/^\/Archives\/edgar\/data\/[0-9]+\/[0-9]{18}\/[A-Za-z0-9._-]+$/.test(value)&&!value.split("/").some(part=>part==="."||part==="..");
const canonicalDate=(value:string):boolean=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&new Date(`${value}T00:00:00.000Z`).toISOString().slice(0,10)===value;
/** Hash the exact accepted HTTP entity-body octets. No text decoding or normalization occurs here. */
export function secEventDocumentContentSha256(entityBodyOctets: Uint8Array): string {
  try { if (!(entityBodyOctets instanceof Uint8Array) || entityBodyOctets.byteLength > 20_000_000) throw new Error(); return createHash("sha256").update(entityBodyOctets).digest("hex"); } catch { throw new Error("SEC_EVENT_DOCUMENT_BYTES_INVALID"); }
}
/** Receipt data is intentionally absent: this is content/document identity only. */
export function secEventDocumentArtifactFingerprint(input: SecDocumentIdentityInput): string {
  if (!safeId(input.filingIdentityId) || !safeLocator(input.canonicalLocator) || !/^[A-Z][A-Z0-9_]{0,63}$/.test(input.documentType) || !SHA256.test(input.contentSha256) || !/^[a-z0-9.+-]+\/[a-z0-9.+-]+$/.test(input.contentType) || !Number.isSafeInteger(input.byteLength) || input.byteLength < 0 || input.byteLength > 20_000_000 || !Number.isSafeInteger(input.sequenceOrdinal) || input.sequenceOrdinal < 0 || input.canonicalizationVersion !== "sec-document-entity-octets/v1") throw new Error("SEC_EVENT_DOCUMENT_IDENTITY_INVALID");
  return canonicalSha256({contractVersion:SEC_EVENT_PROVENANCE_DECISION_VERSION,identity:input});
}
export function secEventDocumentArtifactId(fingerprint:string):string {
  if(!SHA256.test(fingerprint))throw new Error("SEC_EVENT_DOCUMENT_FINGERPRINT_INVALID");
  return createHash("sha256").update("sec-event-document-id/v1:","utf8").update(fingerprint,"utf8").digest("hex");
}
/** Package identity seals a canonical ordered member set and index bytes; members do not point back to package fingerprint. */
export function secEventFilingPackageFingerprint(input: Readonly<{filingIdentityId:string;filingDate:string;acceptanceAt:string|null;reportPeriod:string|null;filingIndexArtifactFingerprint:string;members:readonly SecPackageMemberIdentity[]}>): string {
  if (!safeId(input.filingIdentityId) || !canonicalDate(input.filingDate) || (input.acceptanceAt!==null&&!iso(input.acceptanceAt)) || (input.reportPeriod!==null&&!canonicalDate(input.reportPeriod)) || !SHA256.test(input.filingIndexArtifactFingerprint) || input.members.length<2 || input.members.length>1000) throw new Error("SEC_EVENT_PACKAGE_IDENTITY_INVALID");
  const members=[...input.members].sort((a,b)=>a.ordinal-b.ordinal);
  if(members.some((m,i)=>m.ordinal!==i||!safeId(m.artifactId)||!SHA256.test(m.artifactFingerprint)||!safeLocator(m.canonicalLocator)||!Number.isSafeInteger(m.sequenceOrdinal)||m.sequenceOrdinal<0||!Number.isSafeInteger(m.byteLength)||m.byteLength<0||m.byteLength>20_000_000||!("FILING_INDEX PRIMARY_DOCUMENT EXHIBIT OTHER".split(" ")).includes(m.documentRole))||members.reduce((sum,m)=>sum+m.byteLength,0)>20_000_000||new Set(members.map(m=>m.artifactId)).size!==members.length||new Set(members.map(m=>m.canonicalLocator)).size!==members.length||members.filter(m=>m.documentRole==="FILING_INDEX").length!==1||members.filter(m=>m.documentRole==="PRIMARY_DOCUMENT").length!==1||!members.some(m=>m.documentRole==="FILING_INDEX"&&m.artifactFingerprint===input.filingIndexArtifactFingerprint)) throw new Error("SEC_EVENT_PACKAGE_MEMBERS_INVALID");
  return canonicalSha256({contractVersion:SEC_EVENT_PROVENANCE_DECISION_VERSION,filingIdentityId:input.filingIdentityId,filingDate:input.filingDate,acceptanceAt:input.acceptanceAt,reportPeriod:input.reportPeriod,filingIndexArtifactFingerprint:input.filingIndexArtifactFingerprint,memberCount:members.length,members});
}
export function secEventFilingPackageId(filingIdentityId:string,packageFingerprint:string):string {
  if(!safeId(filingIdentityId)||!SHA256.test(packageFingerprint))throw new Error("SEC_EVENT_PACKAGE_FINGERPRINT_INVALID");
  return createHash("sha256").update("sec-event-package-id/v1:","utf8").update(filingIdentityId,"utf8").update(":","utf8").update(packageFingerprint,"utf8").digest("hex");
}
const trusted = new WeakSet<object>();
export function createCanonicalSecEventSourceProvenanceDecision(recordedAt: string, reviewedAt = "2026-10-02T00:00:00.000Z"): SecEventProvenanceDecision {
  if (!iso(recordedAt) || !iso(reviewedAt)) throw new Error("SEC_EVENT_PROVENANCE_DECISION_TIMESTAMP_INVALID");
  const material = { contractVersion:SEC_EVENT_PROVENANCE_DECISION_VERSION, status:"VALID" as const, selectedOption:"C" as const, rejectedOptions:[{option:"A" as const,reason:"Applied M5 lineage members require retrieval-availability claims whose effective time is an ingestion-source-observation retrieved_at; the parent has no filed-document package/member semantics."},{option:"B" as const,reason:"The existing artifact authority persists a payload fingerprint and metadata envelope, not the canonical SEC document bytes; external IDs do not prove byte-equivalence."}], existingObjects:tables, authorityTables:decisionTables, schemaObjectNames, authorityMaterial:{package:packageMaterial,document:documentMaterial,receipt:receiptMaterial,lineage:lineageMaterial}, identityFormulas, byteIdentityPolicy, persistenceClassification, schemaRules, downstreamBindings:bindings, persistence:{liveAcquisition:"BLOCKED" as const,sourceArtifact:"BLOCKED" as const,eventLineage:"BLOCKED" as const,issuerEvidence:"BLOCKED" as const,eventAuthority:"BLOCKED" as const,scheduler:"BLOCKED" as const,signals:"BLOCKED" as const,trading:"BLOCKED" as const}, reviewedAt };
  const result=deepFreeze({...material,recordedAt,fingerprint:canonicalSha256(material)}); trusted.add(result); return result;
}
export function parseSecEdgarEventSourceProvenanceDecision(input: unknown): SecEventProvenanceDecision {
  const topKeys=["contractVersion","status","selectedOption","rejectedOptions","existingObjects","authorityTables","schemaObjectNames","authorityMaterial","identityFormulas","byteIdentityPolicy","persistenceClassification","schemaRules","downstreamBindings","persistence","reviewedAt","recordedAt","fingerprint"];
  if(!strictTree(input)||!plain(input)||Reflect.ownKeys(input).length!==topKeys.length||Reflect.ownKeys(input).some(k=>!topKeys.includes(String(k)))) throw new Error("SEC_EVENT_PROVENANCE_DECISION_INVALID");
  const canonical=createCanonicalSecEventSourceProvenanceDecision(String(input.recordedAt),String(input.reviewedAt));
  const material={...(input as unknown as SecEventProvenanceDecision)} as Record<string,unknown>; delete material.recordedAt; delete material.fingerprint;
  try { validateSchema(input.authorityTables as readonly AuthorityTableDescriptor[]); } catch { throw new Error("SEC_EVENT_PROVENANCE_DECISION_INVALID"); }
  if(input.contractVersion!==canonical.contractVersion || input.status!=="VALID" || input.selectedOption!=="C" || input.fingerprint!==canonical.fingerprint || canonicalSha256(material)!==canonical.fingerprint || canonicalSha256(input.authorityTables)!==canonicalSha256(canonical.authorityTables) || canonicalSha256(input.existingObjects)!==canonicalSha256(canonical.existingObjects)) throw new Error("SEC_EVENT_PROVENANCE_DECISION_INVALID");
  return canonical;
}
export function isAuthenticSecEdgarEventSourceProvenanceDecision(x: unknown): x is SecEventProvenanceDecision { return !!x && typeof x === "object" && trusted.has(x as object); }
export function secEventProvenanceMaterialFingerprint(x: Omit<SecEventProvenanceDecision,"recordedAt"|"fingerprint">): string { return canonicalSha256(x); }
