import "server-only";
import { canonicalSha256 } from "./ingestion-provenance";

export const SEC_EDGAR_8K_QUALIFICATION_VERSION = "sec-edgar-8k-event-source-qualification/v1" as const;
export const SEC_EDGAR_8K_SOURCE_ID = "sec-edgar-8k" as const;
export const SEC_EDGAR_8K_USAGES = Object.freeze(["ACQUISITION", "RAW_STORAGE", "NORMALIZED_STORAGE", "AUTHORITY_ISSUANCE", "RETENTION", "REDISTRIBUTION", "COMMERCIAL_USE"] as const);
export type SecEdgar8kUsage = typeof SEC_EDGAR_8K_USAGES[number];
export type SecEdgar8kProfileId = "COMPANY_SUBMISSIONS_JSON" | "SUBMISSIONS_HISTORY_JSON" | "FILING_INDEX" | "PRIMARY_DOCUMENT" | "EXHIBIT_DOCUMENT" | "SUBMISSIONS_BULK_ZIP" | "LATEST_FILINGS_RSS";

export const SEC_EDGAR_8K_ENDPOINT_PROFILES = Object.freeze([
  Object.freeze({ profileId: "COMPANY_SUBMISSIONS_JSON", hostname: "data.sec.gov", pathTemplate: "/submissions/CIK{cik}.json", protocol: "https:", method: "GET", authentication: "NONE", requestHeaders: Object.freeze(["Accept: application/json", "User-Agent: IDENTIFIABLE_CONTACT_REQUIRED"]), responseKind: "JSON", allowedContentTypes: Object.freeze(["application/json"]) }),
  Object.freeze({ profileId: "SUBMISSIONS_HISTORY_JSON", hostname: "data.sec.gov", pathTemplate: "/submissions/{historyFilenameFromCikSubmissionsFiles}", protocol: "https:", method: "GET", authentication: "NONE", requestHeaders: Object.freeze(["Accept: application/json", "User-Agent: IDENTIFIABLE_CONTACT_REQUIRED"]), responseKind: "JSON", allowedContentTypes: Object.freeze(["application/json"]) }),
  Object.freeze({ profileId: "FILING_INDEX", hostname: "www.sec.gov", pathTemplate: "/Archives/edgar/data/{cikUnpadded}/{accessionDigits}/{accessionDashed}-index.htm", protocol: "https:", method: "GET", authentication: "NONE", requestHeaders: Object.freeze(["Accept: text/html", "User-Agent: IDENTIFIABLE_CONTACT_REQUIRED"]), responseKind: "HTML", allowedContentTypes: Object.freeze(["text/html"]) }),
  Object.freeze({ profileId: "PRIMARY_DOCUMENT", hostname: "www.sec.gov", pathTemplate: "/Archives/edgar/data/{cikUnpadded}/{accessionDigits}/{primaryDocument}", protocol: "https:", method: "GET", authentication: "NONE", requestHeaders: Object.freeze(["Accept: text/html, application/xhtml+xml, application/xml, text/xml, text/plain, application/pdf", "User-Agent: IDENTIFIABLE_CONTACT_REQUIRED"]), responseKind: "FILING_DOCUMENT", allowedContentTypes: Object.freeze(["text/html","application/xhtml+xml","application/xml","text/xml","text/plain","application/pdf"]) }),
  Object.freeze({ profileId: "EXHIBIT_DOCUMENT", hostname: "www.sec.gov", pathTemplate: "/Archives/edgar/data/{cikUnpadded}/{accessionDigits}/{documentFilename}", protocol: "https:", method: "GET", authentication: "NONE", requestHeaders: Object.freeze(["Accept: text/html, application/xhtml+xml, application/xml, text/xml, text/plain, application/pdf", "User-Agent: IDENTIFIABLE_CONTACT_REQUIRED"]), responseKind: "FILING_DOCUMENT", allowedContentTypes: Object.freeze(["text/html","application/xhtml+xml","application/xml","text/xml","text/plain","application/pdf"]) }),
  Object.freeze({ profileId: "SUBMISSIONS_BULK_ZIP", hostname: "www.sec.gov", pathTemplate: "/Archives/edgar/daily-index/bulkdata/submissions.zip", protocol: "https:", method: "GET", authentication: "NONE", requestHeaders: Object.freeze(["Accept: application/zip", "User-Agent: IDENTIFIABLE_CONTACT_REQUIRED"]), responseKind: "ZIP", allowedContentTypes: Object.freeze(["application/zip","application/octet-stream"]) }),
  Object.freeze({ profileId: "LATEST_FILINGS_RSS", hostname: "www.sec.gov", pathTemplate: "/cgi-bin/browse-edgar?action=getcurrent&CIK={cik}&type={form}&owner=exclude&output=atom", protocol: "https:", method: "GET", authentication: "NONE", requestHeaders: Object.freeze(["Accept: application/atom+xml, application/xml", "User-Agent: IDENTIFIABLE_CONTACT_REQUIRED"]), responseKind: "ATOM", allowedContentTypes: Object.freeze(["application/atom+xml","application/xml","text/xml"]) }),
] as const);

type Approval = Readonly<{ usage: SecEdgar8kUsage; status: "NOT_APPROVED" | "REQUIRES_REVIEW" | "APPROVED" }>;
type Evidence = Readonly<{ url: string; title: string; checkedAt: string; classification: "DOCUMENTED" | "OBSERVED" | "INFERRED" | "UNKNOWN"; claims: readonly string[] }>;
export type SecEdgar8kQualification = Readonly<{
  contractVersion: typeof SEC_EDGAR_8K_QUALIFICATION_VERSION; sourceId: typeof SEC_EDGAR_8K_SOURCE_ID; sourceKind: "REGULATORY_FILING"; authorityTier: "REGULATORY_PRIMARY";
  status: "QUALIFIED" | "PARTIAL" | "BLOCKED" | "INVALID"; jurisdiction: "US"; regulator: "US_SEC"; supportedRegistrantClass: "SEC_EDGAR_FILERS";
  supportedForms: readonly ["8-K", "8-K/A"]; unsupportedSeparateScopes: readonly ["10-K", "10-Q", "6-K", "REGISTRATION_STATEMENTS"];
  endpoints: typeof SEC_EDGAR_8K_ENDPOINT_PROFILES; hostnameAllowlist: readonly ["data.sec.gov", "www.sec.gov"];
  requestPolicy: Readonly<{ protocol: "https:"; method: "GET"; authentication: "NONE"; maxRequestsPerSecond: 10; userAgentPolicy: "IDENTIFIABLE_ORGANIZATION_AND_CONTACT"; concurrency: 1; redirects: "SAME_ALLOWLISTED_HOST_ONLY"; timeoutMsMax: number; responseBytesMax: number; pageCountMax: number; fileCountMax: number; attemptsMax: number; retryBaseDelayMs: number; retryMaxDelayMs: number; retryStatuses: readonly number[]; backoff: "DETERMINISTIC_CAPPED_EXPONENTIAL"; rawBodyLogging: "FORBIDDEN" }>;
  paginationUpdateSemantics: readonly string[]; historyBulkAvailability: readonly string[]; stableIdentityFields: readonly string[]; timestampFields: readonly string[]; documentDiscovery: readonly string[]; amendmentSupersessionPolicy: "APPEND_ONLY_LINK_ORIGINAL";
  completeness: "PROVEN_FOR_SCOPE" | "PARTIAL" | "UNKNOWN"; latency: "DOCUMENTED_TYPICAL_NOT_GUARANTEED" | "UNKNOWN"; correctionRetraction: "VERSIONED_WITH_KNOWN_LIMITS" | "UNKNOWN";
  rawStorage: "NOT_APPROVED" | "APPROVED" | "UNKNOWN"; normalizedStorage: "NOT_APPROVED" | "APPROVED" | "UNKNOWN"; approvals: readonly Approval[]; retention: "NOT_APPROVED" | "APPROVED" | "UNKNOWN"; redistribution: "NOT_APPROVED" | "APPROVED" | "UNKNOWN"; commercialUse: "NOT_APPROVED" | "APPROVED" | "UNKNOWN";
  evidence: readonly Evidence[]; blockers: readonly string[]; reviewedAt: string; effectiveFrom: string; expiresAt: string; recordedAt: string; qualificationId: string; fingerprint: string;
}>;
export type SecEdgar8kParse = Readonly<{ status: "VALID"; qualification: SecEdgar8kQualification }> | Readonly<{ status: "INVALID"; blocker: "SEC_EDGAR_8K_QUALIFICATION_INVALID" }>;
const INVALID: SecEdgar8kParse = Object.freeze({ status: "INVALID", blocker: "SEC_EDGAR_8K_QUALIFICATION_INVALID" });
const trusted = new WeakSet<object>();
// Runtime authority must come from separately reviewed, code-pinned material.
// This source slice has no qualified fingerprint, so parsing cannot mint one.
const QUALIFIED_RUNTIME_FINGERPRINTS = new Set<string>();
const FIELDS = ["contractVersion","sourceId","sourceKind","authorityTier","status","jurisdiction","regulator","supportedRegistrantClass","supportedForms","unsupportedSeparateScopes","endpoints","hostnameAllowlist","requestPolicy","paginationUpdateSemantics","historyBulkAvailability","stableIdentityFields","timestampFields","documentDiscovery","amendmentSupersessionPolicy","completeness","latency","correctionRetraction","rawStorage","normalizedStorage","approvals","retention","redistribution","commercialUse","evidence","blockers","reviewedAt","effectiveFrom","expiresAt","recordedAt","qualificationId","fingerprint"] as const;
const REQUEST_FIELDS = ["protocol","method","authentication","maxRequestsPerSecond","userAgentPolicy","concurrency","redirects","timeoutMsMax","responseBytesMax","pageCountMax","fileCountMax","attemptsMax","retryBaseDelayMs","retryMaxDelayMs","retryStatuses","backoff","rawBodyLogging"] as const;
const UTC = /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/;
const SECRET = /(?:https?:|ftp:|www\.|\b[a-z0-9-]+(?:\.[a-z0-9-]+)+(?:[:/?#]|$)|api[_-]?(?:key|token)|access[_-]?token|authorization|bearer|password|secret|credential)/i;
const OBJECT_INTRINSICS=new Set<PropertyKey>(["constructor","__defineGetter__","__defineSetter__","hasOwnProperty","__lookupGetter__","__lookupSetter__","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf","__proto__"]);
const ARRAY_INTRINSICS=new Set<PropertyKey>(["length","constructor","at","concat","copyWithin","fill","find","findIndex","findLast","findLastIndex","lastIndexOf","pop","push","reverse","shift","unshift","slice","sort","splice","includes","indexOf","join","keys","entries","values","forEach","filter","flat","flatMap","map","every","some","reduce","reduceRight","toLocaleString","toString","toReversed","toSorted","toSpliced","with",Symbol.iterator,Symbol.unscopables]);
const plain = (v: unknown, fields: readonly string[]): v is Record<string, unknown> => { try { if (!v || typeof v !== "object" || Object.getPrototypeOf(v) !== Object.prototype||Reflect.ownKeys(Object.prototype).some(k=>!OBJECT_INTRINSICS.has(k))) return false; const ks = Reflect.ownKeys(v); return ks.length === fields.length && ks.every(k => typeof k === "string" && fields.includes(k) && (() => { const d = Object.getOwnPropertyDescriptor(v,k); return !!d && "value" in d && d.get === undefined && d.set === undefined; })()); } catch { return false; } };
const arr = (v: unknown, max = 128): v is unknown[] => { try { if (!Array.isArray(v) || Object.getPrototypeOf(v) !== Array.prototype || Reflect.ownKeys(Array.prototype).some(k=>!ARRAY_INTRINSICS.has(k)) || v.length > max) return false; const ks = Reflect.ownKeys(v); if (ks.length !== v.length + 1 || ks.some(k => typeof k !== "string")) return false; for (let i=0;i<v.length;i++){const d=Object.getOwnPropertyDescriptor(v,String(i));if(!d||!("value" in d)||d.get||d.set)return false;}return true;}catch{return false;} };
const iso = (v: unknown): v is string => typeof v === "string" && UTC.test(v) && Number.isFinite(Date.parse(v)) && new Date(v).toISOString() === v;
const str = (v: unknown, max=160): v is string => typeof v === "string" && v.length>0 && v.length<=max && v.trim()===v && !SECRET.test(v);
const oneOf=(v:unknown,allowed:readonly string[]):v is string=>typeof v==="string"&&allowed.includes(v);
const canonList = (v: unknown, allowed?: readonly string[], max=128): v is string[] => arr(v,max) && v.every(x=>str(x) && (!allowed || allowed.includes(x))) && [...v].sort().every((x,i)=>x===v[i]) && new Set(v).size===v.length;
const exactList=(v:unknown,expected:readonly string[]):boolean=>canonList(v,expected)&&JSON.stringify(v)===JSON.stringify(expected);
const freeze = <T>(v:T):T => {if(v&&typeof v==="object"&&!Object.isFrozen(v)){for(const c of Object.values(v as Record<string,unknown>))freeze(c);Object.freeze(v);}return v;};
const endpointsEqual = (v: unknown): boolean => arr(v,SEC_EDGAR_8K_ENDPOINT_PROFILES.length) && v.length===SEC_EDGAR_8K_ENDPOINT_PROFILES.length && v.every((x,i)=>plain(x,["profileId","hostname","pathTemplate","protocol","method","authentication","requestHeaders","responseKind","allowedContentTypes"])&&arr(x.requestHeaders,4)&&arr(x.allowedContentTypes,8)&&JSON.stringify(x)===JSON.stringify(SEC_EDGAR_8K_ENDPOINT_PROFILES[i]));
const canonicalNumberList=(v:unknown,allowed:readonly number[]):v is number[]=>arr(v,allowed.length)&&v.every(n=>typeof n==="number"&&Number.isSafeInteger(n)&&allowed.includes(n))&&[...(v as number[])].sort((a:number,b:number)=>a-b).every((n:number,i:number)=>n===(v as number[])[i])&&new Set(v).size===v.length;
const MATERIAL_KEYS = FIELDS.filter(k=>k!=="recordedAt"&&k!=="qualificationId"&&k!=="fingerprint");
export function parseSecEdgar8kQualification(input: unknown): SecEdgar8kParse {
  try {
    if(!plain(input,FIELDS))return INVALID; const x=input;
    if(x.contractVersion!==SEC_EDGAR_8K_QUALIFICATION_VERSION||x.sourceId!==SEC_EDGAR_8K_SOURCE_ID||x.sourceKind!=="REGULATORY_FILING"||x.authorityTier!=="REGULATORY_PRIMARY"||!(["QUALIFIED","PARTIAL","BLOCKED","INVALID"] as unknown[]).includes(x.status)||x.jurisdiction!=="US"||x.regulator!=="US_SEC"||x.supportedRegistrantClass!=="SEC_EDGAR_FILERS")return INVALID;
    if(!canonList(x.supportedForms,["8-K","8-K/A"])||JSON.stringify(x.supportedForms)!==JSON.stringify(["8-K","8-K/A"])||!canonList(x.unsupportedSeparateScopes,["10-K","10-Q","6-K","REGISTRATION_STATEMENTS"])||JSON.stringify(x.unsupportedSeparateScopes)!==JSON.stringify(["10-K","10-Q","6-K","REGISTRATION_STATEMENTS"]))return INVALID;
    if(!endpointsEqual(x.endpoints)||!arr(x.hostnameAllowlist,2)||JSON.stringify(x.hostnameAllowlist)!==JSON.stringify(["data.sec.gov","www.sec.gov"]))return INVALID;
    if(!plain(x.requestPolicy,REQUEST_FIELDS))return INVALID;const p=x.requestPolicy;
    if(p.protocol!=="https:"||p.method!=="GET"||p.authentication!=="NONE"||p.maxRequestsPerSecond!==10||p.userAgentPolicy!=="IDENTIFIABLE_ORGANIZATION_AND_CONTACT"||p.concurrency!==1||p.redirects!=="SAME_ALLOWLISTED_HOST_ONLY"||p.timeoutMsMax!==30000||p.responseBytesMax!==25*1024*1024||p.pageCountMax!==100||p.fileCountMax!==100||p.attemptsMax!==3||p.retryBaseDelayMs!==1000||p.retryMaxDelayMs!==8000||!canonicalNumberList(p.retryStatuses,[429,503]))return INVALID;
    if(p.backoff!=="DETERMINISTIC_CAPPED_EXPONENTIAL"||p.rawBodyLogging!=="FORBIDDEN")return INVALID;
    for(const k of ["paginationUpdateSemantics","historyBulkAvailability","stableIdentityFields","timestampFields","documentDiscovery","blockers"] as const)if(!canonList(x[k]))return INVALID;
    const stringArrays=[x.paginationUpdateSemantics,x.historyBulkAvailability,x.stableIdentityFields,x.timestampFields,x.documentDiscovery,x.blockers] as string[][];
    if(stringArrays.slice(0,5).some(a=>a.length===0)||x.amendmentSupersessionPolicy!=="APPEND_ONLY_LINK_ORIGINAL")return INVALID;
    if(!exactList(x.paginationUpdateSemantics,["CURRENT_ROWS_PLUS_REFERENCED_HISTORY_FILES","RSS_IS_DISCOVERY_ONLY","SUBMISSIONS_API_UPDATES_DURING_DAY"])||!exactList(x.historyBulkAvailability,["AT_LEAST_ONE_YEAR_OR_1000_FILINGS","NIGHTLY_SUBMISSIONS_ZIP_APPROX_0300_ET","REFERENCED_HISTORICAL_SUBMISSION_FILES"])||!exactList(x.stableIdentityFields,["ACCESSION_DASHED_AND_DIGITS","CIK_ZERO_PADDED_10","DOCUMENT_SEQUENCE_AND_TYPE","FILING_INDEX_LOCATOR","FORM_TYPE","PRIMARY_DOCUMENT_FILENAME","REGISTRANT_IDENTITY_FROM_HEADER"])||!exactList(x.timestampFields,["ACCEPTANCE_DATETIME","EXPECTED_CLOSING_SEPARATE","FILING_DATE","PUBLICATION_DISCOVERY_TIME_SEPARATE","REPORT_DATE_OR_PERIOD","SIGNING_AND_COMPLETION_SEPARATE","SYSTEM_RECEIVED_AT"])||!exactList(x.documentDiscovery,["ACCESSION_BOUND_FILING_INDEX","EXHIBITS_FROM_INDEX","PRIMARY_DOCUMENT_FROM_INDEX"]))return INVALID;
    if(!oneOf(x.completeness,["PROVEN_FOR_SCOPE","PARTIAL","UNKNOWN"])||!oneOf(x.latency,["DOCUMENTED_TYPICAL_NOT_GUARANTEED","UNKNOWN"])||!oneOf(x.correctionRetraction,["VERSIONED_WITH_KNOWN_LIMITS","UNKNOWN"]))return INVALID;
    if(!oneOf(x.rawStorage,["NOT_APPROVED","APPROVED","UNKNOWN"])||!oneOf(x.normalizedStorage,["NOT_APPROVED","APPROVED","UNKNOWN"])||!oneOf(x.retention,["NOT_APPROVED","APPROVED","UNKNOWN"])||!oneOf(x.redistribution,["NOT_APPROVED","APPROVED","UNKNOWN"])||!oneOf(x.commercialUse,["NOT_APPROVED","APPROVED","UNKNOWN"]))return INVALID;
    if(!arr(x.approvals,SEC_EDGAR_8K_USAGES.length)||x.approvals.length!==SEC_EDGAR_8K_USAGES.length)return INVALID;const approvals:Approval[]=[];
    for(const a of x.approvals){if(!plain(a,["usage","status"])||!SEC_EDGAR_8K_USAGES.includes(a.usage as SecEdgar8kUsage)||!oneOf(a.status,["NOT_APPROVED","REQUIRES_REVIEW","APPROVED"]))return INVALID;approvals.push({usage:a.usage as SecEdgar8kUsage,status:a.status as Approval["status"]});} approvals.sort((a,b)=>a.usage.localeCompare(b.usage));if(new Set(approvals.map(a=>a.usage)).size!==SEC_EDGAR_8K_USAGES.length)return INVALID;
    if(!arr(x.evidence,64)||!x.evidence.length)return INVALID;const evidence:Evidence[]=[];for(const e of x.evidence){if(!plain(e,["url","title","checkedAt","classification","claims"])||typeof e.url!=="string"||!str(e.title,256)||!iso(e.checkedAt)||!(["DOCUMENTED","OBSERVED","INFERRED","UNKNOWN"] as unknown[]).includes(e.classification)||!canonList(e.claims,undefined,64)||!e.claims.length)return INVALID;const u=new URL(e.url);if(u.protocol!=="https:"||!(["sec.gov","www.sec.gov","data.sec.gov"].includes(u.hostname))||u.username||u.password||u.search||u.hash||u.href!==e.url)return INVALID;evidence.push({url:e.url,title:e.title,checkedAt:e.checkedAt,classification:e.classification as Evidence["classification"],claims:[...e.claims]});} evidence.sort((a,b)=>a.url.localeCompare(b.url));if(new Set(evidence.map(e=>e.url)).size!==evidence.length)return INVALID;
    if(!iso(x.reviewedAt)||!iso(x.effectiveFrom)||!iso(x.expiresAt)||!iso(x.recordedAt)||String(x.reviewedAt)>String(x.effectiveFrom)||String(x.effectiveFrom)>=String(x.expiresAt)||evidence.some(e=>e.checkedAt>String(x.reviewedAt)))return INVALID;
    if(x.status!=="QUALIFIED"&&stringArrays[5].length===0)return INVALID;
    const evidenceClaims=new Set(evidence.flatMap(e=>e.claims));
    const qualifiedEvidenceClaims=["ARCHIVE_INDEX_CORRECTIONS","ACCESSION_AND_CIK","CIK_ACCESSION_FORM_IDENTITY","FAIR_ACCESS_USER_AGENT","FORM_8K_ITEM_SEMANTICS","RSS_FILTERS_DISCOVERY_ONLY","SUBMISSIONS_HISTORY_BULK","TIMESTAMP_FIELDS"];
    if(x.status==="QUALIFIED"&&(evidence.some(e=>e.classification!=="DOCUMENTED")||qualifiedEvidenceClaims.some(c=>!evidenceClaims.has(c))))return INVALID;
    if(x.status==="QUALIFIED"&&(stringArrays[5].length>0||x.completeness!=="PROVEN_FOR_SCOPE"||x.correctionRetraction!=="VERSIONED_WITH_KNOWN_LIMITS"||x.rawStorage!=="APPROVED"||x.normalizedStorage!=="APPROVED"||approvals.some(a=>a.status!=="APPROVED")||x.retention!=="APPROVED"||x.redistribution!=="APPROVED"||x.commercialUse!=="APPROVED"))return INVALID;
    const material:Record<string,unknown>={};for(const k of MATERIAL_KEYS)material[k]=x[k];material.endpoints=SEC_EDGAR_8K_ENDPOINT_PROFILES;material.hostnameAllowlist=[...x.hostnameAllowlist as string[]];material.approvals=approvals;material.evidence=evidence;
    const fingerprint=canonicalSha256({contractVersion:SEC_EDGAR_8K_QUALIFICATION_VERSION,...material});if(x.fingerprint!==fingerprint||x.qualificationId!==`sec-edgar-8k-qualification:${fingerprint}`)return INVALID;
    if(x.status==="QUALIFIED"&&!QUALIFIED_RUNTIME_FINGERPRINTS.has(fingerprint))return INVALID;
    const parsed=freeze({...material,recordedAt:x.recordedAt,qualificationId:x.qualificationId,fingerprint}) as unknown as SecEdgar8kQualification;trusted.add(parsed);return freeze({status:"VALID" as const,qualification:parsed});
  }catch{return INVALID;}
}
export const isAuthenticSecEdgar8kQualification=(v:unknown):v is SecEdgar8kQualification=>!!v&&typeof v==="object"&&trusted.has(v);

export function secEdgarFilingIdentity(cik:unknown,accession:unknown,form:unknown):string|null{
  if(typeof cik!=="string"||!/^\d{10}$/.test(cik)||/^0{10}$/.test(cik)||typeof accession!=="string"||!/^\d{10}-\d{2}-\d{6}$/.test(accession)||!(form==="8-K"||form==="8-K/A"))return null;
  return `sec-edgar-filing:${cik}:${accession}:${form}`;
}
export function secEdgarAccessionDigits(accession:unknown):string|null{return typeof accession==="string"&&/^\d{10}-\d{2}-\d{6}$/.test(accession)?accession.replaceAll("-",""):null;}
export function secEdgarFilingIndexPath(cik:unknown,accession:unknown,form:unknown):string|null{
  const identity=secEdgarFilingIdentity(cik,accession,form);if(!identity)return null;
  return `/Archives/edgar/data/${String(Number(cik))}/${(accession as string).replaceAll("-","")}/${accession}-index.htm`;
}
/** Design only: an amendment relation is explicit lineage, never an overwrite or newest-wins rule. */
export type SecEdgar8kAmendmentLineageDesign=Readonly<{originalFilingIdentity:string;amendmentFilingIdentity:string;relation:"AMENDS_OR_CORRECTS";originalMetadataFingerprint:string;amendmentMetadataFingerprint:string;originalDocumentFingerprints:readonly string[];amendmentDocumentFingerprints:readonly string[];originalRetained:true}>;

export type SecEdgar8kRequestPlanInput=Readonly<{profileId:SecEdgar8kProfileId;form:string;cik:string;accession:string;documentFilename:string|null;userAgentIdentityRef:string;now:string;timeoutMs:number;maxResponseBytes:number;pageCount:number;fileCount:number;attempts:number;redirectHost:string;approvals:readonly SecEdgar8kUsage[]}>;
export type SecEdgar8kRequestPlan=Readonly<{method:"GET";url:string;profileId:SecEdgar8kProfileId;responseKind:string;allowedContentTypes:readonly string[];cik:string;accession:string;form:"8-K"|"8-K/A";userAgentIdentityRef:string;timeoutMs:number;maxResponseBytes:number;pageCount:number;fileCount:number;attempts:number;redirectHostPolicy:"SAME_ALLOWLISTED_HOST_ONLY";rawBodyLogging:"FORBIDDEN"}>;
const planTrusted=new WeakSet<object>();
const PLAN_INPUT_FIELDS=["profileId","form","cik","accession","documentFilename","userAgentIdentityRef","now","timeoutMs","maxResponseBytes","pageCount","fileCount","attempts","redirectHost","approvals"] as const;
export function createSecEdgar8kRequestPlan(q:unknown,input:SecEdgar8kRequestPlanInput):SecEdgar8kRequestPlan|null{
  try{if(!plain(input,PLAN_INPUT_FIELDS)||typeof input.profileId!=="string"||typeof input.form!=="string"||typeof input.cik!=="string"||typeof input.accession!=="string"||(input.documentFilename!==null&&typeof input.documentFilename!=="string")||typeof input.userAgentIdentityRef!=="string"||typeof input.redirectHost!=="string"||typeof input.now!=="string"||!Number.isSafeInteger(input.timeoutMs)||!Number.isSafeInteger(input.maxResponseBytes)||!Number.isSafeInteger(input.pageCount)||!Number.isSafeInteger(input.fileCount)||!Number.isSafeInteger(input.attempts)||!isAuthenticSecEdgar8kQualification(q)||q.status!=="QUALIFIED"||!iso(input.now)||Date.parse(input.now)<Date.parse(q.effectiveFrom)||Date.parse(input.now)>=Date.parse(q.expiresAt)||!(["8-K","8-K/A"] as string[]).includes(input.form)||!/^\d{10}$/.test(input.cik)||/^0{10}$/.test(input.cik)||!/^\d{10}-\d{2}-\d{6}$/.test(input.accession)||!str(input.userAgentIdentityRef)||!input.userAgentIdentityRef.startsWith("approved-identity:")||!SEC_EDGAR_8K_PROFILES.has(input.profileId)||!arr(input.approvals)||!canonList(input.approvals as unknown))return null;
    const p=q.requestPolicy;if(input.timeoutMs<=0||input.timeoutMs>p.timeoutMsMax||input.maxResponseBytes<=0||input.maxResponseBytes>p.responseBytesMax||input.pageCount<=0||input.pageCount>p.pageCountMax||input.fileCount<=0||input.fileCount>p.fileCountMax||input.attempts<=0||input.attempts>p.attemptsMax||SEC_EDGAR_8K_USAGES.some(u=>!input.approvals.includes(u))||q.approvals.some(a=>a.status!=="APPROVED"))return null;
    const profile=SEC_EDGAR_8K_ENDPOINT_PROFILES.find(e=>e.profileId===input.profileId)!;if(input.redirectHost!==profile.hostname)return null;let path=profile.pathTemplate.replace("{cik}",input.cik).replace("{cikUnpadded}",String(Number(input.cik))).replace("{accessionDigits}",input.accession.replaceAll("-","")).replace("{accessionDashed}",input.accession).replace("{form}",input.form);
    if(input.profileId==="SUBMISSIONS_HISTORY_JSON"){if(typeof input.documentFilename!=="string"||!new RegExp(`^CIK${input.cik}-submissions-[0-9]+\\.json$`).test(input.documentFilename))return null;path=path.replace("{historyFilenameFromCikSubmissionsFiles}",input.documentFilename);}
    else if(input.profileId==="PRIMARY_DOCUMENT"||input.profileId==="EXHIBIT_DOCUMENT"){if(typeof input.documentFilename!=="string"||!/^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$/.test(input.documentFilename)||input.documentFilename.includes(".."))return null;path=path.replace(input.profileId==="PRIMARY_DOCUMENT"?"{primaryDocument}":"{documentFilename}",input.documentFilename);}else if(input.documentFilename!==null)return null;
    const url=`https://${profile.hostname}${path}`;const result=freeze({method:"GET" as const,url,profileId:input.profileId,responseKind:profile.responseKind,allowedContentTypes:profile.allowedContentTypes,cik:input.cik,accession:input.accession,form:input.form as "8-K"|"8-K/A",userAgentIdentityRef:input.userAgentIdentityRef,timeoutMs:input.timeoutMs,maxResponseBytes:input.maxResponseBytes,pageCount:input.pageCount,fileCount:input.fileCount,attempts:input.attempts,redirectHostPolicy:"SAME_ALLOWLISTED_HOST_ONLY" as const,rawBodyLogging:"FORBIDDEN" as const});planTrusted.add(result);return result;
  }catch{return null;}
}
const SEC_EDGAR_8K_PROFILES=new Set<SecEdgar8kProfileId>(["COMPANY_SUBMISSIONS_JSON","SUBMISSIONS_HISTORY_JSON","FILING_INDEX","PRIMARY_DOCUMENT","EXHIBIT_DOCUMENT"]);
export const isAuthenticSecEdgar8kRequestPlan=(v:unknown):v is SecEdgar8kRequestPlan=>!!v&&typeof v==="object"&&planTrusted.has(v);

export const SEC_EDGAR_8K_PRODUCTION_DECISION=Object.freeze({contractVersion:"sec-edgar-8k-production-decision/v1",status:"BLOCKED",selectedAcquisitionProfile:null,productionAcquisition:"BLOCKED",rawStorage:"NOT_APPROVED",normalizedStorage:"NOT_APPROVED",authorityPersistence:"NOT_APPROVED",approvals:Object.freeze({ACQUISITION:"NOT_APPROVED",RAW_STORAGE:"NOT_APPROVED",NORMALIZED_STORAGE:"NOT_APPROVED",AUTHORITY_ISSUANCE:"NOT_APPROVED",RETENTION:"NOT_APPROVED",REDISTRIBUTION:"NOT_APPROVED",COMMERCIAL_USE:"NOT_APPROVED"}),retention:"UNKNOWN",redistribution:"NOT_APPROVED",commercialUse:"NOT_APPROVED",scheduler:"BLOCKED",eventExtraction:"BLOCKED",sourceMapping:null,blockers:Object.freeze(["SEC_8K_COVERAGE_AND_COMPLETENESS_NOT_PROVEN","SEC_STORAGE_AND_USAGE_APPROVALS_NOT_GRANTED","SEC_REQUEST_IDENTITY_AND_LIVE_ACQUISITION_NOT_APPROVED","SEC_EVENT_EXTRACTION_AND_AUTHORITY_NOT_IMPLEMENTED"])} as const);
