import { canonicalSha256 } from "@/domain/intelligence/ingestion-provenance";
import { types as utilTypes } from "node:util";

export const SEC_EVENT_PROVENANCE_DECISION_VERSION = "sec-edgar-event-source-provenance-decision/v1" as const;
export type ProvenanceDecisionStatus = "VALID" | "INVALID";
export type ReuseDisposition = "VALID" | "VALID_WITH_EXPLICIT_BINDING" | "INVALID";
export type ExistingProvenanceObject = Readonly<{
  table: string; semanticPurpose: string; identityMaterial: readonly string[];
  requiredParents: readonly string[]; requiresMarketObservation: boolean;
  requiresAvailabilityClaim: boolean; canonicalDocumentBytes: "YES" | "NO" | "CONDITIONAL";
  packageIndexExhibits: "YES" | "NO" | "CONDITIONAL"; amendmentHistory: "YES" | "NO" | "CONDITIONAL";
  scope: "PROVIDER_NEUTRAL" | "M5_SPECIFIC"; reuse: ReuseDisposition;
}>;
export type SecEventProvenanceDecision = Readonly<{
  contractVersion: typeof SEC_EVENT_PROVENANCE_DECISION_VERSION; status: ProvenanceDecisionStatus;
  selectedOption: "C"; rejectedOptions: readonly Readonly<{ option: "A" | "B"; reason: string }>[];
  existingObjects: readonly ExistingProvenanceObject[];
  authorityTables: readonly AuthorityTableDescriptor[];
  schemaObjectNames: Readonly<{ constraints:readonly string[]; indexes:readonly string[]; functions:readonly string[]; triggers:readonly string[] }>;
  authorityMaterial: Readonly<{ package: readonly string[]; document: readonly string[]; receipt: readonly string[]; lineage: readonly string[] }>;
  downstreamBindings: readonly Readonly<{ role: "event_source_provenance" | "issuer_evidence_provenance" | "asset_mapping_provenance"; binds: readonly string[]; excludes: readonly string[] }>[];
  persistence: Readonly<{ liveAcquisition: "BLOCKED"; sourceArtifact: "BLOCKED"; eventLineage: "BLOCKED"; issuerEvidence: "BLOCKED"; eventAuthority: "BLOCKED"; scheduler: "BLOCKED"; signals: "BLOCKED"; trading: "BLOCKED" }>;
  reviewedAt: string; recordedAt: string; fingerprint: string;
}>;
export type AuthorityTableDescriptor = Readonly<{ name:string; columns:readonly Readonly<{name:string;type:string}>[]; primaryKey:readonly string[]; uniqueKeys:readonly (readonly string[])[]; foreignKeys:readonly Readonly<{name:string;columns:readonly string[];parent:string;parentColumns:readonly string[]}>[]; indexes:readonly (readonly string[])[]; persistence:"REQUIRED"|"DERIVED"|"EPHEMERAL"|"REJECTED" }>;

const tables: ExistingProvenanceObject[] = [
  { table:"intelligence_ingestion_requests", semanticPurpose:"Request identity, declared provider/dataset/version and adapter/parser contract", identityMaterial:["idempotency_key","provider_id","dataset_id","dataset_version","request_scope","request_fingerprint"], requiredParents:["intelligence_datasets(dataset_id,provider_id,dataset_version)"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_ingestion_attempts", semanticPurpose:"Attempt identity and immutable execution/parser versions", identityMaterial:["ingestion_request_id","attempt_number","attempt_fingerprint"], requiredParents:["intelligence_ingestion_requests"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_ingestion_events", semanticPurpose:"Append-only lifecycle/observation receipt events", identityMaterial:["ingestion_attempt_id","sequence","event_type","event_fingerprint","source_observation_id"], requiredParents:["intelligence_ingestion_attempts","intelligence_ingestion_source_observations for SOURCE_OBSERVED"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"CONDITIONAL", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_artifacts", semanticPurpose:"Provider-scoped artifact descriptor and content fingerprint", identityMaterial:["provider_id","dataset_id","dataset_version","provider_source_namespace","provider_external_record_id","provider_revision","payload_fingerprint","source_artifact_fingerprint"], requiredParents:["intelligence_datasets(dataset_id,provider_id,dataset_version)"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_envelopes", semanticPurpose:"Normalized/auditable payload envelope linked to an artifact", identityMaterial:["source_artifact_id","parser_contract_version","envelope_schema_version","payload_fingerprint","source_envelope_fingerprint"], requiredParents:["intelligence_source_artifacts(source_artifact_id,payload_fingerprint)"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_ingestion_source_observations", semanticPurpose:"Retrieved-at observation of an artifact in an attempt", identityMaterial:["ingestion_attempt_id","source_artifact_id","response_page_ordinal","item_ordinal","retrieved_at","observation_fingerprint"], requiredParents:["intelligence_ingestion_attempts","intelligence_source_artifacts"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_availability_claims", semanticPurpose:"Retrieval-observed effective availability", identityMaterial:["source_envelope_id","source_observation_id","source_artifact_id","effective_available_at","claim_fingerprint"], requiredParents:["intelligence_source_envelopes","intelligence_ingestion_source_observations"], requiresMarketObservation:false, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_lineages", semanticPurpose:"Sealed provider/dataset/version set of retrieval-availability claims", identityMaterial:["provider_id","dataset_id","dataset_version","availability_claim_ids","member_count","fingerprint"], requiredParents:["intelligence_datasets"], requiresMarketObservation:false, requiresAvailabilityClaim:true, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"CONDITIONAL", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_source_lineage_members", semanticPurpose:"Ordinal member joining availability, artifact, envelope, observation and attempt", identityMaterial:["source_lineage_id","member_ordinal","availability_claim_id","source_artifact_id","source_envelope_id","source_observation_id","ingestion_attempt_id","provider_id","dataset_id","dataset_version","observed_at","effective_available_at","member_fingerprint"], requiredParents:["intelligence_source_lineages","intelligence_source_availability_claims","intelligence_source_artifacts","intelligence_source_envelopes","intelligence_ingestion_source_observations","intelligence_ingestion_attempts"], requiresMarketObservation:false, requiresAvailabilityClaim:true, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"CONDITIONAL", scope:"M5_SPECIFIC", reuse:"VALID_WITH_EXPLICIT_BINDING" },
  { table:"intelligence_asset_mapping_revisions", semanticPurpose:"Canonical provider-asset identity revision scoped to M5 source lineage", identityMaterial:["mapping_revision_id","source_lineage_id","provider_id","dataset_id","dataset_version","canonical_asset_id","canonical_identifier","asset_class","fingerprint"], requiredParents:["intelligence_source_lineages","provider identity assertion"], requiresMarketObservation:false, requiresAvailabilityClaim:true, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"CONDITIONAL", scope:"M5_SPECIFIC", reuse:"INVALID" },
  { table:"market_observations", semanticPurpose:"Market measurement at an observed time, not a document publication", identityMaterial:["provider_id","dataset_id","asset_id","observed_at","price/volume material"], requiredParents:["market provider/dataset and asset identity"], requiresMarketObservation:true, requiresAvailabilityClaim:false, canonicalDocumentBytes:"NO", packageIndexExhibits:"NO", amendmentHistory:"NO", scope:"M5_SPECIFIC", reuse:"INVALID" },
];

const external: AuthorityTableDescriptor[] = [
  {name:"intelligence_datasets",persistence:"REQUIRED",columns:[{name:"dataset_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_version",type:"text"}],primaryKey:["dataset_id","provider_id","dataset_version"],uniqueKeys:[["dataset_id","provider_id","dataset_version"]],foreignKeys:[],indexes:[]},
  {name:"intelligence_source_artifacts",persistence:"REQUIRED",columns:[{name:"source_artifact_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"},{name:"payload_fingerprint",type:"text"},{name:"source_artifact_fingerprint",type:"text"}],primaryKey:["source_artifact_id"],uniqueKeys:[["source_artifact_id","payload_fingerprint"],["source_artifact_id","provider_id","dataset_id","dataset_version"],["source_artifact_id","provider_id","dataset_id","dataset_version","payload_fingerprint","source_artifact_fingerprint"]],foreignKeys:[],indexes:[]},
  {name:"intelligence_source_lineages",persistence:"REQUIRED",columns:[{name:"source_lineage_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"},{name:"fingerprint",type:"text"}],primaryKey:["source_lineage_id"],uniqueKeys:[["source_lineage_id","provider_id","dataset_id","dataset_version"]],foreignKeys:[],indexes:[]},
  {name:"intelligence_source_lineage_members",persistence:"REQUIRED",columns:[{name:"source_lineage_id",type:"text"},{name:"member_ordinal",type:"integer"},{name:"member_fingerprint",type:"text"},{name:"availability_claim_id",type:"text"},{name:"source_artifact_id",type:"text"},{name:"source_envelope_id",type:"text"},{name:"source_observation_id",type:"text"},{name:"ingestion_attempt_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"},{name:"observed_at",type:"timestamptz"},{name:"effective_available_at",type:"timestamptz"}],primaryKey:["source_lineage_id","member_ordinal"],uniqueKeys:[["source_lineage_id","member_ordinal","member_fingerprint","availability_claim_id","source_artifact_id","source_envelope_id","source_observation_id","ingestion_attempt_id","provider_id","dataset_id","dataset_version","observed_at","effective_available_at"]],foreignKeys:[],indexes:[]},
  {name:"intelligence_asset_mapping_revisions",persistence:"REQUIRED",columns:[{name:"mapping_revision_id",type:"text"},{name:"source_lineage_id",type:"text"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"},{name:"canonical_asset_id",type:"text"},{name:"canonical_identifier",type:"text"},{name:"asset_class",type:"text"},{name:"fingerprint",type:"text"}],primaryKey:["mapping_revision_id"],uniqueKeys:[["mapping_revision_id","source_lineage_id","provider_id","dataset_id","dataset_version","canonical_asset_id","canonical_identifier","asset_class"]],foreignKeys:[],indexes:[]},
];
const eventTables: AuthorityTableDescriptor[] = [
  {name:"sec_event_filing_packages",persistence:"REQUIRED",columns:[{name:"package_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"provider_id",type:"text"},{name:"dataset_id",type:"text"},{name:"dataset_version",type:"text"},{name:"cik",type:"text"},{name:"accession_number",type:"text"},{name:"form",type:"text"}],primaryKey:["package_id"],uniqueKeys:[["package_id","fingerprint"],["package_id","provider_id","dataset_id","dataset_version","cik","accession_number","form"]],foreignKeys:[{name:"sec_filing_dataset_fk",columns:["dataset_id","provider_id","dataset_version"],parent:"intelligence_datasets",parentColumns:["dataset_id","provider_id","dataset_version"]}],indexes:[["dataset_id","provider_id","dataset_version"]]},
  {name:"sec_event_document_artifacts",persistence:"REQUIRED",columns:[{name:"artifact_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"package_id",type:"text"},{name:"package_fingerprint",type:"char(64)"},{name:"document_role",type:"text"},{name:"sequence_ordinal",type:"integer"},{name:"canonical_locator",type:"text"},{name:"content_sha256",type:"char(64)"},{name:"content_type",type:"text"},{name:"byte_length",type:"integer"}],primaryKey:["artifact_id"],uniqueKeys:[["artifact_id","fingerprint"],["artifact_id","fingerprint","package_id","package_fingerprint","document_role","sequence_ordinal"]],foreignKeys:[{name:"sec_document_package_fk",columns:["package_id","package_fingerprint"],parent:"sec_event_filing_packages",parentColumns:["package_id","fingerprint"]}],indexes:[["package_id","package_fingerprint"],["package_id","document_role","sequence_ordinal"]]},
  {name:"sec_event_acquisition_receipts",persistence:"REQUIRED",columns:[{name:"receipt_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"package_id",type:"text"},{name:"package_fingerprint",type:"char(64)"},{name:"request_id",type:"text"},{name:"attempt_id",type:"text"},{name:"retrieved_at",type:"timestamptz"},{name:"effective_available_at",type:"timestamptz"}],primaryKey:["receipt_id"],uniqueKeys:[["receipt_id","fingerprint"]],foreignKeys:[{name:"sec_receipt_package_fk",columns:["package_id","package_fingerprint"],parent:"sec_event_filing_packages",parentColumns:["package_id","fingerprint"]}],indexes:[["package_id","package_fingerprint"]]},
  {name:"sec_event_source_lineages",persistence:"REQUIRED",columns:[{name:"lineage_id",type:"text"},{name:"fingerprint",type:"char(64)"},{name:"root_package_id",type:"text"},{name:"root_package_fingerprint",type:"char(64)"},{name:"member_count",type:"integer"}],primaryKey:["lineage_id"],uniqueKeys:[["lineage_id","fingerprint"],["lineage_id","fingerprint","root_package_id","root_package_fingerprint"]],foreignKeys:[{name:"sec_lineage_package_fk",columns:["root_package_id","root_package_fingerprint"],parent:"sec_event_filing_packages",parentColumns:["package_id","fingerprint"]}],indexes:[["root_package_id","root_package_fingerprint"]]},
  {name:"sec_event_source_lineage_members",persistence:"REQUIRED",columns:[{name:"lineage_id",type:"text"},{name:"lineage_fingerprint",type:"char(64)"},{name:"member_ordinal",type:"integer"},{name:"package_id",type:"text"},{name:"package_fingerprint",type:"char(64)"},{name:"artifact_id",type:"text"},{name:"artifact_fingerprint",type:"char(64)"},{name:"document_role",type:"text"},{name:"sequence_ordinal",type:"integer"}],primaryKey:["lineage_id","member_ordinal"],uniqueKeys:[["lineage_id","artifact_id","document_role","sequence_ordinal"]],foreignKeys:[{name:"sec_member_parent_fk",columns:["lineage_id","lineage_fingerprint"],parent:"sec_event_source_lineages",parentColumns:["lineage_id","fingerprint"]},{name:"sec_member_document_fk",columns:["artifact_id","artifact_fingerprint","package_id","package_fingerprint","document_role","sequence_ordinal"],parent:"sec_event_document_artifacts",parentColumns:["artifact_id","fingerprint","package_id","package_fingerprint","document_role","sequence_ordinal"]}],indexes:[["lineage_id","lineage_fingerprint"],["artifact_id","artifact_fingerprint","package_id","package_fingerprint","document_role","sequence_ordinal"]]},
];
const decisionTables = [...external,...eventTables];
const schemaObjectNames = Object.freeze({
  constraints:Object.freeze(decisionTables.flatMap(t=>[`${t.name}_pk`,...t.uniqueKeys.map((_,i)=>`${t.name}_uq_${i+1}`),...t.foreignKeys.map(f=>f.name)])),
  indexes:Object.freeze(decisionTables.flatMap(t=>t.indexes.map((_,i)=>`${t.name}_idx_${i+1}`))),
  functions:Object.freeze(["sec_event_assert_package_seal","sec_event_assert_lineage_seal","sec_event_assert_amendment_parent"]),
  triggers:Object.freeze(eventTables.flatMap(t=>[`${t.name}_immutable`,`${t.name}_sealed_deferred`])),
});
function validateSchema(tables:readonly AuthorityTableDescriptor[]):void {
  const names=new Set<string>(); const map=new Map<string,AuthorityTableDescriptor>();
  for(const t of tables){ if(!/^[a-z][a-z0-9_]{0,62}$/.test(t.name)||names.has(t.name))throw new Error("SEC_EVENT_PROVENANCE_TABLE_INVALID"); names.add(t.name);map.set(t.name,t); const cols=t.columns.map(c=>c.name); if(new Set(cols).size!==cols.length||cols.some(c=>!/^[a-z][a-z0-9_]{0,62}$/.test(c))||t.primaryKey.length===0||new Set(t.primaryKey).size!==t.primaryKey.length||t.primaryKey.some(c=>!cols.includes(c))||new Set(t.uniqueKeys.map(k=>k.join("\u0000"))).size!==t.uniqueKeys.length||new Set(t.indexes.map(k=>k.join("\u0000"))).size!==t.indexes.length||t.uniqueKeys.some(k=>!k.length||new Set(k).size!==k.length||k.some(c=>!cols.includes(c)))||t.indexes.some(k=>!k.length||k.some(c=>!cols.includes(c)))||!(["REQUIRED","DERIVED","EPHEMERAL","REJECTED"] as string[]).includes(t.persistence))throw new Error("SEC_EVENT_PROVENANCE_COLUMN_OR_PK_INVALID"); }
  const fkNames=new Set<string>();
  for(const t of tables){ const cols=new Map(t.columns.map(c=>[c.name,c.type])); for(const fk of t.foreignKeys){if(!/^[a-z][a-z0-9_]{0,62}$/.test(fk.name)||fkNames.has(fk.name))throw new Error("SEC_EVENT_PROVENANCE_CONSTRAINT_NAME_INVALID");fkNames.add(fk.name); const p=map.get(fk.parent); if(!p||fk.columns.length===0||fk.columns.length!==fk.parentColumns.length||new Set(fk.columns).size!==fk.columns.length||new Set(fk.parentColumns).size!==fk.parentColumns.length)throw new Error(`SEC_EVENT_PROVENANCE_FK_INVALID:${t.name}:${fk.name}`); const parentKeys=[p.primaryKey,...p.uniqueKeys]; if(!parentKeys.some(k=>k.length===fk.parentColumns.length&&k.every((c,i)=>c===fk.parentColumns[i])))throw new Error(`SEC_EVENT_PROVENANCE_PARENT_KEY_INVALID:${t.name}:${fk.name}`); for(let i=0;i<fk.columns.length;i++)if(!cols.has(fk.columns[i])||p.columns.find(c=>c.name===fk.parentColumns[i])?.type!==cols.get(fk.columns[i]))throw new Error(`SEC_EVENT_PROVENANCE_FK_TYPE_INVALID:${t.name}:${fk.name}`); if(!t.indexes.some(ix=>ix.length>=fk.columns.length&&fk.columns.every((c,i)=>ix[i]===c)))throw new Error(`SEC_EVENT_PROVENANCE_CHILD_INDEX_INVALID:${t.name}:${fk.name}`); }}
  }
  for(const [kind,values] of [["constraint",schemaObjectNames.constraints],["index",schemaObjectNames.indexes],["function",schemaObjectNames.functions],["trigger",schemaObjectNames.triggers]] as const){ if(values.some(n=>!/^[a-z][a-z0-9_]{0,62}$/.test(n))||new Set(values).size!==values.length)throw new Error(`SEC_EVENT_PROVENANCE_${kind.toUpperCase()}_NAME_INVALID`); }
validateSchema(decisionTables);

const packageMaterial = ["providerId","datasetId","datasetVersion","contractVersion","cik","accessionNumber","form","filingDate","acceptanceAtOrPublicationAt","reportPeriod","filingIndexIdentity","amendmentParentIdentity","requestProfileVersion"] as const;
const documentMaterial = ["filingPackageId","filingPackageFingerprint","canonicalLocator","documentRole","documentType","canonicalUtf8BytesSha256","contentType","byteLength","sequenceOrdinal","artifactId","artifactFingerprint","canonicalizationVersion"] as const;
const receiptMaterial = ["requestId","attemptId","receiptId","endpointProfile","responseStatus","retrievedAt","effectiveAvailableAt","responseMaterialFingerprint"] as const;
const lineageMaterial = ["lineageId","lineageFingerprint","providerId","datasetId","datasetVersion","packageId","packageFingerprint","memberCount","contiguousOrdinals","exactDocumentArtifactSet","amendmentParent","recordedAtExcludedFromMaterialIdentity"] as const;
const bindings = [
  { role:"event_source_provenance" as const, binds:["SEC package/document IDs and fingerprints","SEC source-lineage ID plus exact scoped member identity","filing/accession/form and document locator/role"], excludes:["AssetMappingRevision lineage","generic evidence.referenceId"] },
  { role:"issuer_evidence_provenance" as const, binds:["issuer authority evidence member ID/fingerprint","structured source-lineage/member scope resolved from immutable provenance"], excludes:["untyped referenceId as lineage ID","SEC claim provenance unless it is the same cited evidence authority"] },
  { role:"asset_mapping_provenance" as const, binds:["existing mapping_revision_id","its own source_lineage_id/provider_id/dataset_id/dataset_version","canonical_asset_id/canonical_identifier/asset_class"], excludes:["SEC source lineage","issuer evidence lineage","new canonical asset registry"] },
];

const iso = (x: unknown): x is string => typeof x === "string" && /^\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d\.\d{3}Z$/.test(x) && Number.isFinite(Date.parse(x)) && new Date(x).toISOString() === x;
const plain = (x: unknown): x is Record<string, unknown> => { try { if(!x||typeof x!=="object"||Object.getPrototypeOf(x)!==Object.prototype)return false; return Reflect.ownKeys(x).every(k=>typeof k==="string"&&"value" in Object.getOwnPropertyDescriptor(x,k)!); } catch { return false; } };
function strictTree(x:unknown,depth=0,budget={n:0}):boolean { try { if(depth>20||++budget.n>20_000)return false; if(x===null||typeof x==="string"||typeof x==="boolean"||(typeof x==="number"&&Number.isFinite(x)))return true; if(typeof x!=="object"||utilTypes.isProxy(x))return false; if(Array.isArray(x)){if(Object.getPrototypeOf(x)!==Array.prototype)return false;const keys=Reflect.ownKeys(x);if(keys.length!==x.length+1||keys.some(k=>k!=="length"&&(typeof k!=="string"||!/^(0|[1-9][0-9]*)$/.test(k)||Number(k)>=x.length||!("value" in Object.getOwnPropertyDescriptor(x,k)!))))return false;for(let i=0;i<x.length;i++)if(!Object.hasOwn(x,i)||!strictTree(x[i],depth+1,budget))return false;return true;}if(!plain(x))return false;for(const d of Object.values(Object.getOwnPropertyDescriptors(x)))if(!("value" in d))return false;for(const v of Object.values(x))if(!strictTree(v,depth+1,budget))return false;return true;}catch{return false;} }
const deepFreeze = <T>(x:T):T => { if(x && typeof x === "object" && !Object.isFrozen(x)){ for(const v of Object.values(x as Record<string,unknown>)) deepFreeze(v); Object.freeze(x); } return x; };
const trusted = new WeakSet<object>();
export function createCanonicalSecEventSourceProvenanceDecision(recordedAt: string, reviewedAt = "2026-10-02T00:00:00.000Z"): SecEventProvenanceDecision {
  if (!iso(recordedAt) || !iso(reviewedAt)) throw new Error("SEC_EVENT_PROVENANCE_DECISION_TIMESTAMP_INVALID");
  const material = { contractVersion:SEC_EVENT_PROVENANCE_DECISION_VERSION, status:"VALID" as const, selectedOption:"C" as const, rejectedOptions:[{option:"A" as const,reason:"Applied M5 lineage members require retrieval-availability claims whose effective time is an ingestion-source-observation retrieved_at; the parent has no filed-document package/member semantics."},{option:"B" as const,reason:"The existing artifact authority persists a payload fingerprint and metadata envelope, not the canonical SEC document bytes; external IDs do not prove byte-equivalence."}], existingObjects:tables, authorityTables:decisionTables, schemaObjectNames, authorityMaterial:{package:packageMaterial,document:documentMaterial,receipt:receiptMaterial,lineage:lineageMaterial}, downstreamBindings:bindings, persistence:{liveAcquisition:"BLOCKED" as const,sourceArtifact:"BLOCKED" as const,eventLineage:"BLOCKED" as const,issuerEvidence:"BLOCKED" as const,eventAuthority:"BLOCKED" as const,scheduler:"BLOCKED" as const,signals:"BLOCKED" as const,trading:"BLOCKED" as const}, reviewedAt };
  const result=deepFreeze({...material,recordedAt,fingerprint:canonicalSha256(material)}); trusted.add(result); return result;
}
export function parseSecEdgarEventSourceProvenanceDecision(input: unknown): SecEventProvenanceDecision {
  const topKeys=["contractVersion","status","selectedOption","rejectedOptions","existingObjects","authorityTables","schemaObjectNames","authorityMaterial","downstreamBindings","persistence","reviewedAt","recordedAt","fingerprint"];
  if(!strictTree(input)||!plain(input)||Reflect.ownKeys(input).length!==topKeys.length||Reflect.ownKeys(input).some(k=>!topKeys.includes(String(k)))) throw new Error("SEC_EVENT_PROVENANCE_DECISION_INVALID");
  const canonical=createCanonicalSecEventSourceProvenanceDecision(String(input.recordedAt),String(input.reviewedAt));
  const material={...(input as unknown as SecEventProvenanceDecision)} as Record<string,unknown>; delete material.recordedAt; delete material.fingerprint;
  try { validateSchema(input.authorityTables as readonly AuthorityTableDescriptor[]); } catch { throw new Error("SEC_EVENT_PROVENANCE_DECISION_INVALID"); }
  if(input.contractVersion!==canonical.contractVersion || input.status!=="VALID" || input.selectedOption!=="C" || input.fingerprint!==canonical.fingerprint || canonicalSha256(material)!==canonical.fingerprint || canonicalSha256(input.authorityTables)!==canonicalSha256(canonical.authorityTables) || canonicalSha256(input.existingObjects)!==canonicalSha256(canonical.existingObjects)) throw new Error("SEC_EVENT_PROVENANCE_DECISION_INVALID");
  return canonical;
}
export function isAuthenticSecEdgarEventSourceProvenanceDecision(x: unknown): x is SecEventProvenanceDecision { return !!x && typeof x === "object" && trusted.has(x as object); }
export function secEventProvenanceMaterialFingerprint(x: Omit<SecEventProvenanceDecision,"recordedAt"|"fingerprint">): string { return canonicalSha256(x); }
