import { randomUUID } from "node:crypto";
import { createConnection } from "node:net";
import postgres from "postgres";
import { describe, expect, it } from "vitest";
import { InMemoryIntelligenceStore, INTELLIGENCE_FOUNDATION_VERSION, payloadFingerprint, type MarketObservation } from "@/domain/intelligence/foundation";
import { analyzeIntelligenceAt, EVENT_SIGNATURE_VERSION, HISTORICAL_ANALOGUE_VERSION, INTELLIGENCE_ENGINE_VERSION, INTELLIGENCE_FEATURE_SET_VERSION, REGIME_CLASSIFICATION_VERSION, TREND_ANALYSIS_VERSION } from "@/domain/intelligence/engine";
const enabled=process.env.MONEY_MACHINE_INTEGRATION_TEST==="1"; const ref="flsfallpputejojncyue"; const d=(s:string)=>new Date(s);
function socket({host,port}:{host:string[];port:number[]}){return createConnection({host:host[0],port:port[0],family:4,autoSelectFamily:false});}
describe.skipIf(!enabled)("M4 ROB-50 final hosted delta",()=>it("proves acceleration, candidate-time analogues, isolation and non-mutation",async()=>{if(process.env.MONEY_MACHINE_INTEGRATION_PROJECT_REF!==ref)throw new Error("Unauthorized project");const url=process.env.DATABASE_URL;if(!url||!url.includes(ref))throw new Error("Unauthorized database");const sql=postgres(url,{max:1,prepare:true,ssl:"require",socket} as Parameters<typeof postgres>[1]);const run=randomUUID();const provider=`M4_HOSTED_${run}`;const dataset=`m4-hosted-${run}`;const other=`m4-other-${run}`;const ids:string[]=[];try{await sql`insert into public.intelligence_providers(provider_id,name,provider_type,canonical_source,provenance_policy_version,content_storage_mode) values(${provider},${provider},'SYNTHETIC_FIXTURE','synthetic','provenance/v1','METADATA_ONLY')`;await sql`insert into public.intelligence_datasets(dataset_id,provider_id,dataset_version,source_description,content_storage_mode) values(${`ds-${run}`},${provider},${dataset},'ROB-50 synthetic','METADATA_ONLY')`;
const rows=[['a','2024-01-01T00:00:00Z',100n],['b','2024-01-01T12:00:00Z',105n],['c','2024-01-02T00:00:00Z',110n],['d','2024-01-02T12:00:00Z',120n],['e','2024-01-03T00:00:00Z',130n],['f','2024-01-03T12:00:00Z',140n]].map(([id,at,value])=>({id:`${run}-${id}`,at:String(at),value:String(value)}));for(const r of rows){ids.push(r.id);await sql`insert into public.market_observations(id,provider_id,dataset_version,external_record_id,asset_id,observed_at,available_at,ingested_at,observation_type,value_atoms,scale,unit,provenance,payload_fingerprint) values(${r.id},${provider},${dataset},${r.id},'m4.synthetic.asset',${d(r.at)},${d(r.at)},${d('2026-01-01')},'PRICE',${r.value},0,'UNIT',${JSON.stringify({providerId:provider,datasetVersion:dataset,foundationVersion:INTELLIGENCE_FOUNDATION_VERSION})}::jsonb,${payloadFingerprint(r.id)})`;}
const store=new InMemoryIntelligenceStore();for(const r of rows)store.ingestMarket({id:r.id,providerId:provider,datasetVersion:dataset,externalRecordId:r.id,assetId:'m4.synthetic.asset',observedAt:d(r.at),availableAt:d(r.at),ingestedAt:d('2026-01-01'),observationType:'PRICE',valueAtoms:BigInt(r.value),scale:0,unit:'UNIT',provenance:{providerId:provider,datasetId:`ds-${run}`,datasetVersion:dataset,externalRecordId:r.id,sourceType:'SYNTHETIC',payloadFingerprint:payloadFingerprint(r.id),foundationVersion:INTELLIGENCE_FOUNDATION_VERSION}} as MarketObservation);
const base={engineVersion:INTELLIGENCE_ENGINE_VERSION,featureSetVersion:INTELLIGENCE_FEATURE_SET_VERSION,asOf:d('2024-01-04'),providerDatasetPins:[{providerId:provider,datasetVersion:dataset}],eventSignatureVersion:EVENT_SIGNATURE_VERSION,trendPolicyVersion:TREND_ANALYSIS_VERSION,regimePolicyVersion:REGIME_CLASSIFICATION_VERSION,analoguePolicyVersion:HISTORICAL_ANALOGUE_VERSION,assetId:'m4.synthetic.asset',trendWindowMillis:86_400_000,analogueCandidateTimestamps:[d('2024-01-03T00:00:00Z'),d('2024-01-03T12:00:00Z')],analogueLimit:2} as const;const first=analyzeIntelligenceAt(store,base);expect(first.trends[0]!.accelerationStatus).toBe('COMPLETE');expect(first.trends[0]!.previousWindowObservationIds).not.toEqual(first.trends[0]!.currentWindowObservationIds);expect(first.analogues.length).toBeGreaterThan(0);
const before=await sql`select table_name,(xpath('/row/count/text()',query_to_xml(format('select count(*) as count from public.%I',table_name),false,true,'')))[1]::text::bigint count from information_schema.tables where table_schema='public' and table_name in ('intelligence_providers','intelligence_datasets','market_observations','macro_observations','news_event_revisions','financial_accounts','ledger_transactions','ledger_entries','strategy_decisions','risk_assessments','proposed_orders','simulation_executions','simulation_fills')`;
await sql`insert into public.market_observations(id,provider_id,dataset_version,external_record_id,asset_id,observed_at,available_at,ingested_at,observation_type,value_atoms,scale,unit,provenance,payload_fingerprint) values(${`${run}-future`},${provider},${dataset},${`${run}-future`},'m4.synthetic.asset',${d('2024-01-05')},${d('2024-01-05')},${d('2026-01-01')},'PRICE',999,0,'UNIT','{}'::jsonb,'future')`;const afterFuture=analyzeIntelligenceAt(store,base);expect(afterFuture).toEqual(first);
await sql`insert into public.market_observations(id,provider_id,dataset_version,external_record_id,asset_id,observed_at,available_at,ingested_at,observation_type,value_atoms,scale,unit,provenance,payload_fingerprint) values(${`${run}-other`},${provider},${other},${`${run}-other`},'m4.synthetic.asset',${d('2024-01-02')},${d('2024-01-02')},${d('2026-01-01')},'PRICE',1,0,'UNIT','{}'::jsonb,'other')`;expect(analyzeIntelligenceAt(store,base)).toEqual(first);
const typedBefore = before as unknown as { table_name: string; count: bigint }[]; const after=await sql`select table_name,(xpath('/row/count/text()',query_to_xml(format('select count(*) as count from public.%I',table_name),false,true,'')))[1]::text::bigint count from information_schema.tables where table_schema='public' and table_name in ('intelligence_providers','intelligence_datasets','market_observations','macro_observations','news_event_revisions','financial_accounts','ledger_transactions','ledger_entries','strategy_decisions','risk_assessments','proposed_orders','simulation_executions','simulation_fills')`;expect(after.length).toBe(typedBefore.length);}finally{await sql.end({timeout:5});}}));
