import { fileURLToPath } from "node:url";
import postgres from "postgres";
import { describe, expect, it, vi } from "vitest";
import { createPostgresManualIngestionToLineageUnitOfWork } from "@/infrastructure/postgres/manual-ingestion-to-lineage-uow";

const databaseUrl = process.env.DATABASE_URL;
const enabled = process.env.MONEY_MACHINE_COINGECKO_ACQUISITION_INGESTION_INTEGRATION === "1" && Boolean(databaseUrl);
const now = "2026-09-25T12:00:00.000Z";
const expiry = "2027-09-25T12:00:00.000Z";
const weth = "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2";
const providerId = "coingecko";
const datasetId = "coingecko-market-chart";
const datasetVersion = "coingecko-market-chart/range-v1";
const registryModule = fileURLToPath(new URL("../../config/m5/provider-approval-authorities.production.json", import.meta.url));

function assertLoopback(value: string) { const host = new URL(value).hostname; if (!["localhost", "127.0.0.1", "::1"].includes(host)) throw new Error("M5_COINGECKO_INTEGRATION_REQUIRES_LOCAL_DATABASE"); }
const body = new TextEncoder().encode(`{"prices":[${Array.from({ length: 15 }, (_, i) => `[${1767225600000 + i * 86400000},9007199254740993]`).join(",")}],"market_caps":[${Array.from({ length: 15 }, (_, i) => `[${1767225600000 + i * 86400000},1]`).join(",")}],"total_volumes":[${Array.from({ length: 15 }, (_, i) => `[${1767225600000 + i * 86400000},2]`).join(",")}]}`);

describe.skipIf(!enabled)("M5 CoinGecko acquisition ingestion PostgreSQL happy path", () => {
  it("persists fifteen authenticated CoinGecko records into a sealed lineage", async () => {
    assertLoopback(databaseUrl!); vi.resetModules();
    const approvalModule = await import("@/domain/intelligence/m5-provider-approval-authority");
    const approval = approvalModule.createM5ProviderApprovalAuthority({ contractVersion: "m5-provider-approval-authority/v1", policyVersion: "m5-provider-approval-policy/v1", authorityVersion: "integration/v1", providerId, datasetId, datasetVersion, reviewedAt: now, effectiveFrom: now, expiresAt: expiry, recordedAt: now, usageDecisions: ["AUTHORITY_PERSISTENCE", "COMMERCIAL_USE", "NETWORK_ACQUISITION", "NORMALIZED_STORAGE", "RAW_PAYLOAD_PROCESSING", "RAW_PAYLOAD_STORAGE", "REDISTRIBUTION"].map(usage => ({ usage, decision: "APPROVED", evidence: [{ kind: "IDENTIFIER", value: "review/synthetic-approval/v1" }] })), retentionDecision: { decision: "APPROVED", evidence: [{ kind: "SHA256", value: "a".repeat(64) }] } });
    vi.doMock(registryModule, () => ({ default: { contractVersion: "m5-provider-approval-authority-registry/v1", entries: [{ approvalAuthorityId: approval.approvalAuthorityId, approvalAuthorityFingerprint: approval.approvalAuthorityFingerprint, providerId, datasetId, datasetVersion }], authorities: [approval] } }));
    const ready = await import("@/application/intelligence/evaluate-m5-provider-readiness"); const aggregateModule = await import("@/application/intelligence/evaluate-m5-provider-readiness-aggregate"); const acquire = await import("@/application/intelligence/m5-provider-live-acquisition"); const handoff = await import("@/application/intelligence/m5-coingecko-acquisition-ingestion-handoff");
    const config = { configVersion: "m5-provider-readiness-config/v1", providerNamespace: "test:coingecko", providerId, datasetId, datasetVersion, reviewedAt: now, reviewReference: "test/review", documentationUrls: ["https://docs.example.test"], termsUrls: ["https://terms.example.test"], capabilities: ready.M5_DEFAULT_REQUIRED_CAPABILITIES.map(({ capability }) => ({ capability, status: "SUPPORTED", completeness: "COMPLETE", reviewedAt: now, reviewReference: "test/review", documentationUrls: ["https://docs.example.test"], termsUrls: ["https://terms.example.test"], limitations: [], ...(capability === "VENUE_COMPLETE_UNIVERSE" ? { zeroVenuePolicy: "ALLOWED_EMPTY" } : {}) })), usageDecisions: ready.M5_DEFAULT_REQUESTED_USAGES.map(usage => ({ usage, approval: "APPROVED", reviewedAt: now, reviewReference: "test/review", limitations: [] })), limitations: [], approvalExpiresAt: expiry, metadata: { sourceKind: "SYNTHETIC_FIXTURE", policyVersion: "m5-provider-readiness-policy/v1" } };
    const evaluation = ready.evaluateM5ProviderReadinessConfig({ config, evaluatedAt: now, requiredCapabilities: [...ready.M5_DEFAULT_REQUIRED_CAPABILITIES].sort((a, b) => a.capability.localeCompare(b.capability)) }); const source = { ...aggregateModule.bindM5ProviderReadinessAggregateSource(config, evaluation), approvalAuthorityId: approval.approvalAuthorityId, approvalAuthorityFingerprint: approval.approvalAuthorityFingerprint };
    const aggregate = aggregateModule.evaluateM5ProviderReadinessAggregate({ config: { contractVersion: "m5-provider-readiness-aggregate/v1", policyVersion: "m5-provider-readiness-aggregate-policy/v1", aggregateId: "integration", reviewedAt: now, reviewReference: "test/review", sources: [source], capabilityAssignments: ready.M5_DEFAULT_REQUIRED_CAPABILITIES.map(({ capability }) => ({ capability, mode: "ALL_OF", sourceIds: [source.sourceId] })), usageDecisions: ["AUTHORITY_PERSISTENCE", "COMMERCIAL_USE", "NETWORK_ACQUISITION", "NORMALIZED_STORAGE", "RAW_PAYLOAD_PROCESSING", "RAW_PAYLOAD_STORAGE", "REDISTRIBUTION", "RETENTION"].map(usage => ({ sourceId: source.sourceId, usage, approval: "APPROVED", reviewedAt: now, reviewReference: "test/review", approvalExpiresAt: expiry })) }, sources: [{ sourceId: source.sourceId, config, evaluation }], evaluatedAt: now }); expect(aggregate.result).toBe("READY");
    const lease = vi.fn(async () => true); const credential = "integration-credential-sentinel"; const resolve = vi.fn(async () => ({ kind: "API_KEY" as const, value: credential })); const send = vi.fn(async () => ({ status: 200, headers: { "content-type": "application/json" }, body, retrievedAt: now }));
    const acquisition = await acquire.executeM5ProviderLiveAcquisition({ aggregate, readiness: evaluation, request: { providerId, coinId: "ethereum", contractAddress: weth, from: "2026-01-01T00:00:00.000Z", to: "2026-02-01T00:00:00.000Z", datasetVersion }, asOf: now, currentTime: () => now, credential: { kind: "API_KEY", reference: "env:coingecko-pro-api-key" }, credentials: { resolve }, transport: { send }, rateLimit: { acquire: lease }, requestedAt: now, startedAt: now, recordedAt: now, now: () => now, monotonicNow: () => 0 });
    if (acquisition.status !== "READY" || !acquisition.ingestionHandoffBinding) throw new Error(acquisition.status === "READY" ? "binding" : acquisition.code);
    const sql = postgres(databaseUrl!, { max: 1, prepare: true });
    try {
      await sql`insert into public.intelligence_providers (provider_id,name,provider_type,canonical_source,provenance_policy_version,content_storage_mode) values (${providerId},${providerId},'SYNTHETIC_FIXTURE','integration','provenance/v1','METADATA_ONLY') on conflict (provider_id) do nothing`;
      await sql`insert into public.intelligence_datasets (dataset_id,provider_id,dataset_version,source_description,content_storage_mode) values (${datasetId},${providerId},${datasetVersion},'integration','METADATA_ONLY') on conflict (dataset_id) do nothing`;
      const result = await handoff.executeM5CoinGeckoAcquisitionIngestionHandoff({ acquisition, asOf: now, scope: acquisition.ingestionHandoffBinding, apply: true, unitOfWork: createPostgresManualIngestionToLineageUnitOfWork(sql) });
      expect(result.status).toBe("READY"); if (result.status !== "READY" || result.ingestion.status !== "PERSISTED") throw new Error("persist");
      const reread = postgres(databaseUrl!, { max: 1, prepare: true }); try {
        const counts = await reread`select (select count(*) from public.intelligence_ingestion_requests where provider_id=${providerId})::int requests,(select count(*) from public.intelligence_ingestion_attempts where ingestion_request_id=${result.ingestion.requestId})::int attempts,(select count(*) from public.intelligence_ingestion_events where ingestion_attempt_id=${result.ingestion.attemptId})::int events,(select count(*) from public.intelligence_source_artifacts where provider_id=${providerId})::int artifacts,(select count(*) from public.intelligence_source_envelopes where source_artifact_id in (select source_artifact_id from public.intelligence_source_artifacts where provider_id=${providerId}))::int envelopes,(select count(*) from public.intelligence_ingestion_source_observations where ingestion_attempt_id=${result.ingestion.attemptId})::int observations,(select count(*) from public.intelligence_source_availability_claims where source_artifact_id in (select source_artifact_id from public.intelligence_source_artifacts where provider_id=${providerId}))::int claims,(select count(*) from public.intelligence_source_lineages where source_lineage_id=${result.ingestion.sourceLineageId})::int lineages,(select count(*) from public.intelligence_source_lineage_members where source_lineage_id=${result.ingestion.sourceLineageId})::int members`;
        expect(counts[0]).toMatchObject({ requests: 1, attempts: 1, events: 17, artifacts: 15, envelopes: 15, observations: 15, claims: 15, lineages: 1, members: 15 }); expect(send).toHaveBeenCalledTimes(1); expect(lease).toHaveBeenCalledTimes(1); expect(JSON.stringify(result)).not.toContain(credential); expect(acquisition.ingestionHandoffBinding).toMatchObject({ providerId, datasetId, datasetVersion, contractAddress: weth });
      } finally { await reread.end({ timeout: 5 }); }
    } finally { await sql.end({ timeout: 5 }); vi.doUnmock(registryModule); vi.resetModules(); }
  });
});
