import { describe, expect, it } from "vitest";
import { canonicalM4Fingerprint, canonicalM4RecordFromSnapshot, canonicalM5Fingerprint, canonicalM5RecordFromEvaluation, joinCanonicalHighInterestEvidence, type CanonicalM4AnalysisRecord, type CanonicalM5EligibilityRecord } from "@/domain/intelligence/canonical-evidence";
import { INTELLIGENCE_ENGINE_VERSION, INTELLIGENCE_FEATURE_SET_VERSION, TREND_ANALYSIS_VERSION, TREND_ACCELERATION_VERSION, type IntelligenceSnapshot } from "@/domain/intelligence/engine";
import { ASSET_ELIGIBILITY_VERSION, SYNTHETIC_PROFILE_VERSION } from "@/domain/discovery/asset-eligibility";
import { deriveHighInterestCandidates } from "@/domain/notifications/high-interest-source";
const at=(value:string)=>new Date(value);
const withoutFingerprint=<T extends {fingerprint:string}>({fingerprint,...body}:T)=>{expect(fingerprint).toEqual(expect.any(String));return body;};
const snapshot=(asOf:string,analysisId="analysis-a"):IntelligenceSnapshot=>({analysisId,configHash:"config-a",asOf,engineVersion:INTELLIGENCE_ENGINE_VERSION,datasets:["p:v1"],inputEvidence:["market-a"],eventContexts:[],noveltyEvidence:[],corroborationEvidence:[{signature:"asset-a",distinctProviderCount:2,providerIds:["p1","p2"],supportingRecordIds:["news-a","news-b"]}],trends:[{status:"COMPLETE",direction:"UP",signedChangeBps:"500",accelerationStatus:"COMPLETE",accelerationBps:"100",accelerationDirection:"ACCELERATING",observationIds:["market-a"],previousWindowObservationIds:[],currentWindowObservationIds:["market-a"],version:TREND_ANALYSIS_VERSION,accelerationVersion:TREND_ACCELERATION_VERSION}],regime:{status:"COMPLETE",label:"RISK_ON",contributingObservationIds:["market-a"],reasonCode:"TREND_DIRECTION",version:"regime-classification/v1"},analogues:[],integrityStatus:"COMPLETE"});
const m4=(asOf:string,analysisId="analysis-a",providers=["p1","p2"]):CanonicalM4AnalysisRecord=>canonicalM4RecordFromSnapshot({snapshot:snapshot(asOf,analysisId),candidateId:"candidate-a",canonicalIdentifier:"asset-a",assetClass:"CRYPTO",availableAt:new Date(at(asOf).getTime()+60000),featureSetVersion:INTELLIGENCE_FEATURE_SET_VERSION,trendPolicyVersion:TREND_ANALYSIS_VERSION,accelerationVersion:TREND_ACCELERATION_VERSION,datasetPins:["p:v1"],corroborationProviderIds:providers,corroborationEvidenceIds:providers.map(p=>`news-${p}`)});
const m5=(asOf:string,evaluationId="evaluation-a",status:CanonicalM5EligibilityRecord["status"]="ELIGIBLE",pins=["p:v1"],suspiciousEvidenceStatus:"CLEAN"|"SUSPICIOUS"|"INCOMPLETE"="CLEAN"):CanonicalM5EligibilityRecord=>canonicalM5RecordFromEvaluation({evaluation:{evaluationId,candidateId:"candidate-a",asOf,policyVersion:ASSET_ELIGIBILITY_VERSION,profileVersion:SYNTHETIC_PROFILE_VERSION,status,checks:[{requirementCode:"MIN",reasonCode:"MEETS_THRESHOLD",status:"PASS"}]},canonicalIdentifier:"asset-a",assetClass:"CRYPTO",availableAt:new Date(at(asOf).getTime()+60000),evidenceIds:["news-a","market-a"],datasetPins:pins,suspiciousFlags:suspiciousEvidenceStatus==="SUSPICIOUS"?["CRITICAL"]:[],suspiciousEvidenceStatus});

describe("canonical M4/M5 evidence",()=>{
 it("maps explicit identity, class and provider context; providers are asset-specific",()=>{const record=m4("2026-01-01T10:00:00Z","a",["p1"]);expect(record.distinctProviderCount).toBe(1);expect(deriveHighInterestCandidates([{candidateId:record.candidateId,assetDisplayIdentifier:record.canonicalIdentifier,assetClass:record.assetClass,eligibilityStatus:"ELIGIBLE",trendStatus:"COMPLETE",trendDirection:"UP",signedChangeBps:500n,accelerationStatus:"COMPLETE",accelerationBps:100n,distinctProviderCount:record.distinctProviderCount,suspiciousFlags:[],asOf:record.asOf,availableAt:record.availableAt,datasetPins:record.datasetPins,evidenceIds:record.corroborationEvidenceIds}],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(m4("2026-01-01T10:00:00Z","a",["p1","p2"]).distinctProviderCount).toBe(2);});
 it("normalizes semantic permutations and changes material fingerprints",()=>{const a=m4("2026-01-01T10:00:00Z","a",["p1","p2"]);const b={...a,datasetPins:["p:v1"].reverse(),corroborationProviderIds:["p2","p1"],corroborationEvidenceIds:["news-p2","news-p1"]};expect(canonicalM4Fingerprint(withoutFingerprint(b))).toBe(a.fingerprint);expect(m4("2026-01-01T10:00:00Z","a",["p1"]).fingerprint).not.toBe(a.fingerprint);const e=m5("2026-01-01T10:00:00Z");const ePerm={...e,checks:[...e.checks].reverse(),evidenceIds:["market-a","news-a"]};expect(canonicalM5Fingerprint(withoutFingerprint(ePerm))).toBe(e.fingerprint);expect(m5("2026-01-01T10:00:00Z","evaluation-a","INELIGIBLE").fingerprint).not.toBe(e.fingerprint);});
 it("pairs only temporally visible compatible evidence",()=>{const a=m4("2026-01-01T10:00:00Z","a");const b=m4("2026-01-01T11:00:00Z","b");const ma=m5("2026-01-01T10:05:00Z","ma");const mb=m5("2026-01-01T10:30:00Z","mb");expect(joinCanonicalHighInterestEvidence([a,b],[ma,mb],at("2026-01-01T10:04:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([a,b],[ma,mb],at("2026-01-01T10:20:00Z")).map(x=>x.analysisId)).toEqual(["a"]);expect(joinCanonicalHighInterestEvidence([a,b],[ma,mb],at("2026-01-01T10:45:00Z")).map(x=>x.analysisId)).toEqual(["a"]);expect(joinCanonicalHighInterestEvidence([a,b],[ma,mb],at("2026-01-01T11:30:00Z")).map(x=>x.analysisId)).toEqual(["b"]);});
 it("fails closed for delayed visibility, pins, status and suspicious evidence",()=>{const delayed={...m4("2026-01-01T10:00:00Z"),availableAt:at("2026-01-01T10:10:00Z")};expect(joinCanonicalHighInterestEvidence([delayed],[m5("2026-01-01T10:00:00Z")],at("2026-01-01T10:05:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([m4("2026-01-01T10:00:00Z")],[m5("2026-01-01T10:00:00Z","e","ELIGIBLE",["p:v2"])],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([m4("2026-01-01T10:00:00Z")],[m5("2026-01-01T10:00:00Z","e","INELIGIBLE")],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([m4("2026-01-01T10:00:00Z")],[m5("2026-01-01T10:00:00Z","e","ELIGIBLE",["p:v1"],"INCOMPLETE")],at("2026-01-01T10:30:00Z"))).toEqual([]);});
 it("returns an empty healthy source and excludes incomplete M4",()=>{expect(joinCanonicalHighInterestEvidence([],[],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([{...m4("2026-01-01T10:00:00Z"),integrityStatus:"INCOMPLETE"}],[m5("2026-01-01T10:00:00Z")],at("2026-01-01T10:30:00Z"))).toEqual([]);});
});
