import { describe, expect, it } from "vitest";
import { CANONICAL_CONTEXT_VERSION, canonicalM4Fingerprint, canonicalM4RecordFromSnapshot, canonicalM5Fingerprint, canonicalM5RecordFromEvaluation, deriveCanonicalContextId, joinCanonicalHighInterestEvidence, type CanonicalM4AnalysisRecord, type CanonicalM5EligibilityRecord } from "@/domain/intelligence/canonical-evidence";
import { INTELLIGENCE_ENGINE_VERSION, INTELLIGENCE_FEATURE_SET_VERSION, TREND_ANALYSIS_VERSION, TREND_ACCELERATION_VERSION, type IntelligenceSnapshot } from "@/domain/intelligence/engine";
import { ASSET_ELIGIBILITY_VERSION, SYNTHETIC_PROFILE_VERSION } from "@/domain/discovery/asset-eligibility";
import { deriveHighInterestCandidates } from "@/domain/notifications/high-interest-source";
const at=(value:string)=>new Date(value);
const withoutFingerprint=<T extends {fingerprint:string}>({fingerprint,...body}:T)=>{expect(fingerprint).toEqual(expect.any(String));return body;};
const contextId=(asOf:string,overrides:Partial<{candidateId:string;canonicalIdentifier:string;assetClass:string;assetId:string;contextVersion:string}>={})=>deriveCanonicalContextId({candidateId:overrides.candidateId??"candidate-a",canonicalIdentifier:overrides.canonicalIdentifier??"asset-a",assetClass:overrides.assetClass??"CRYPTO",assetId:overrides.assetId??"asset-id-a",asOf,contextVersion:overrides.contextVersion});
const snapshot=(asOf:string,analysisId="analysis-a",materialEvidence=[{evidenceId:"market-a",availableAt:asOf}]):IntelligenceSnapshot=>({analysisId,configHash:"config-a",asOf,engineVersion:INTELLIGENCE_ENGINE_VERSION,datasets:["p:v1"],inputEvidence:materialEvidence.map(x=>x.evidenceId),materialEvidence,eventContexts:[],noveltyEvidence:[],corroborationEvidence:[{signature:"asset-a",distinctProviderCount:2,providerIds:["p1","p2"],supportingRecordIds:["news-a","news-b"]}],trends:[{status:"COMPLETE",direction:"UP",signedChangeBps:"500",accelerationStatus:"COMPLETE",accelerationBps:"100",accelerationDirection:"ACCELERATING",observationIds:["market-a"],previousWindowObservationIds:[],currentWindowObservationIds:["market-a"],version:TREND_ANALYSIS_VERSION,accelerationVersion:TREND_ACCELERATION_VERSION}],regime:{status:"COMPLETE",label:"RISK_ON",contributingObservationIds:["market-a"],reasonCode:"TREND_DIRECTION",version:"regime-classification/v1"},analogues:[],integrityStatus:"COMPLETE"});
const m4=(asOf:string,analysisId="analysis-a",providers=["p1","p2"],pins=["p:v1"],canonicalContextId=contextId(asOf),materialEvidence=[{evidenceId:"market-a",availableAt:asOf}]):CanonicalM4AnalysisRecord=>canonicalM4RecordFromSnapshot({snapshot:snapshot(asOf,analysisId,materialEvidence),candidateId:"candidate-a",canonicalIdentifier:"asset-a",assetClass:"CRYPTO",canonicalContextId,featureSetVersion:INTELLIGENCE_FEATURE_SET_VERSION,trendPolicyVersion:TREND_ANALYSIS_VERSION,accelerationVersion:TREND_ACCELERATION_VERSION,datasetPins:pins,corroborationProviderIds:providers,corroborationEvidenceIds:providers.map(p=>`news-${p}`)});
const m5=(asOf:string,evaluationId="evaluation-a",status:CanonicalM5EligibilityRecord["status"]="ELIGIBLE",pins=["p:v1"],suspiciousEvidenceStatus:"CLEAN"|"SUSPICIOUS"|"INCOMPLETE"="CLEAN",canonicalContextId=contextId(asOf),availableAt=asOf):CanonicalM5EligibilityRecord=>canonicalM5RecordFromEvaluation({evaluation:{evaluationId,candidateId:"candidate-a",asOf,policyVersion:ASSET_ELIGIBILITY_VERSION,profileVersion:SYNTHETIC_PROFILE_VERSION,status,checks:[{requirementCode:"MIN",reasonCode:"MEETS_THRESHOLD",status:"PASS"}]},canonicalIdentifier:"asset-a",assetClass:"CRYPTO",canonicalContextId,availableAt:new Date(availableAt),evidenceIds:["news-a","market-a"],datasetPins:pins,suspiciousFlags:suspiciousEvidenceStatus==="SUSPICIOUS"?["CRITICAL"]:[],suspiciousEvidenceStatus,assemblyFingerprint:"assembly-fingerprint"});

describe("canonical M4/M5 evidence",()=>{
 it("maps explicit identity, class and provider context; providers are asset-specific",()=>{const record=m4("2026-01-01T10:00:00Z","a",["p1"]);expect(record.distinctProviderCount).toBe(1);expect(deriveHighInterestCandidates([{candidateId:record.candidateId,assetDisplayIdentifier:record.canonicalIdentifier,assetClass:record.assetClass,eligibilityStatus:"ELIGIBLE",trendStatus:"COMPLETE",trendDirection:"UP",signedChangeBps:500n,accelerationStatus:"COMPLETE",accelerationBps:100n,distinctProviderCount:record.distinctProviderCount,suspiciousFlags:[],asOf:record.asOf,availableAt:record.availableAt,m4DatasetPins:record.datasetPins,m5DatasetPins:["m5:v1"],evidenceIds:record.corroborationEvidenceIds}],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(m4("2026-01-01T10:00:00Z","a",["p1","p2"]).distinctProviderCount).toBe(2);});
 it("normalizes semantic permutations and changes material fingerprints",()=>{const a=m4("2026-01-01T10:00:00Z","a",["p1","p2"]);const b={...a,datasetPins:["p:v1"].reverse(),corroborationProviderIds:["p2","p1"],corroborationEvidenceIds:["news-p2","news-p1"]};expect(canonicalM4Fingerprint(withoutFingerprint(b))).toBe(a.fingerprint);expect(m4("2026-01-01T10:00:00Z","a",["p1"]).fingerprint).not.toBe(a.fingerprint);const e=m5("2026-01-01T10:00:00Z");const ePerm={...e,checks:[...e.checks].reverse(),evidenceIds:["market-a","news-a"]};expect(canonicalM5Fingerprint(withoutFingerprint(ePerm))).toBe(e.fingerprint);expect(m5("2026-01-01T10:00:00Z","evaluation-a","INELIGIBLE").fingerprint).not.toBe(e.fingerprint);});
 it("derives a stable context from shared material only",()=>{const asOf="2026-01-01T10:00:00Z";const id=contextId(asOf);expect(contextId(asOf)).toBe(id);expect(contextId("2026-01-01T10:01:00Z")).not.toBe(id);expect(contextId(asOf,{candidateId:"candidate-b"})).not.toBe(id);expect(contextId(asOf,{canonicalIdentifier:"asset-b"})).not.toBe(id);expect(contextId(asOf,{assetClass:"EQUITY"})).not.toBe(id);expect(contextId(asOf,{contextVersion:"canonical-context/v2"})).not.toBe(id);expect(CANONICAL_CONTEXT_VERSION).toBe("canonical-context/v1");});
 it("pairs exact visible shared context while preserving heterogeneous pins",()=>{const t10="2026-01-01T10:00:00Z",t11="2026-01-01T11:00:00Z";const a=m4(t10,"a",["p1","p2"],["price:v7","news:v3"]);const b=m4(t11,"b",["p1","p2"],["price:v8"]);const ma=m5(t10,"ma","ELIGIBLE",["liquidity:v2","holder:v5"]);const mb=m5(t11,"mb","ELIGIBLE",["liquidity:v3"]);expect(joinCanonicalHighInterestEvidence([a,b],[ma,mb],at("2026-01-01T09:59:30Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([a,b],[ma,mb],at("2026-01-01T10:00:00Z")).map(x=>x.analysisId)).toEqual(["a"]);expect(joinCanonicalHighInterestEvidence([a,b],[ma,mb],at("2026-01-01T10:45:00Z")).map(x=>x.analysisId)).toEqual(["a"]);expect(joinCanonicalHighInterestEvidence([a,b],[ma,mb],at("2026-01-01T11:30:00Z")).map(x=>x.analysisId)).toEqual(["b"]);});
 it("fails closed for delayed visibility, mismatched context/asOf, status and suspicious evidence",()=>{const delayed={...m4("2026-01-01T10:00:00Z"),availableAt:at("2026-01-01T10:10:00Z")};expect(joinCanonicalHighInterestEvidence([delayed],[m5("2026-01-01T10:00:00Z")],at("2026-01-01T10:05:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([m4("2026-01-01T10:00:00Z")],[m5("2026-01-01T10:00:00Z","e","ELIGIBLE",["p:v2"],"CLEAN",contextId("2026-01-01T10:00:00Z",{candidateId:"candidate-b"}))],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([m4("2026-01-01T10:00:00Z")],[m5("2026-01-01T10:01:00Z")],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([m4("2026-01-01T10:00:00Z")],[m5("2026-01-01T10:00:00Z","e","INELIGIBLE")],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([m4("2026-01-01T10:00:00Z")],[m5("2026-01-01T10:00:00Z","e","ELIGIBLE",["p:v1"],"INCOMPLETE")],at("2026-01-01T10:30:00Z"))).toEqual([]);});
 it("keeps record-specific pins and fingerprints independent of the shared context",()=>{const asOf="2026-01-01T10:00:00Z";const a=m4(asOf,"a",["p1","p2"],["price:v7"]);const changedM4=m4(asOf,"a",["p1","p2"],["price:v8"]);const e=m5(asOf,"e","ELIGIBLE",["liquidity:v2"]);const changedM5=m5(asOf,"e","ELIGIBLE",["liquidity:v3"]);expect(changedM4.canonicalContextId).toBe(a.canonicalContextId);expect(changedM4.fingerprint).not.toBe(a.fingerprint);expect(changedM5.canonicalContextId).toBe(e.canonicalContextId);expect(changedM5.fingerprint).not.toBe(e.fingerprint);});
 it("returns an empty healthy source and excludes incomplete M4",()=>{expect(joinCanonicalHighInterestEvidence([],[],at("2026-01-01T10:30:00Z"))).toEqual([]);expect(joinCanonicalHighInterestEvidence([{...m4("2026-01-01T10:00:00Z"),integrityStatus:"INCOMPLETE"}],[m5("2026-01-01T10:00:00Z")],at("2026-01-01T10:30:00Z"))).toEqual([]);});
 it("derives M4 material availability from represented evidence only",()=>{const asOf="2026-01-01T10:00:00Z";const base=snapshot(asOf,"material",[{evidenceId:"early",availableAt:"2026-01-01T09:00:00.000Z"},{evidenceId:"late",availableAt:"2026-01-01T09:30:00.000Z"},{evidenceId:"unused",availableAt:"2026-01-01T09:45:00.000Z"}]);const input={snapshot:{...base,inputEvidence:["early","late"]},candidateId:"candidate-a",canonicalIdentifier:"asset-a",assetClass:"CRYPTO",canonicalContextId:contextId(asOf),featureSetVersion:INTELLIGENCE_FEATURE_SET_VERSION,trendPolicyVersion:TREND_ANALYSIS_VERSION,accelerationVersion:TREND_ACCELERATION_VERSION,datasetPins:["p:v1"],corroborationProviderIds:["p1"],corroborationEvidenceIds:[]};const record=canonicalM4RecordFromSnapshot(input);expect(record.availableAt.toISOString()).toBe("2026-01-01T09:30:00.000Z");expect(canonicalM4RecordFromSnapshot(input).availableAt.toISOString()).toBe("2026-01-01T09:30:00.000Z");});
 it("accepts M4 availability before and at asOf and rejects future availability",()=>{const before=m4("2026-01-01T10:00:00Z","before",["p1"],["p:v1"],contextId("2026-01-01T10:00:00Z"),[{evidenceId:"e",availableAt:"2026-01-01T09:00:00.000Z"}]);expect(before.availableAt.getTime()).toBeLessThan(before.asOf.getTime());const equal=m4("2026-01-01T10:00:00Z","equal",["p1"],["p:v1"],contextId("2026-01-01T10:00:00Z"),[{evidenceId:"e",availableAt:"2026-01-01T10:00:00.000Z"}]);expect(equal.availableAt).toEqual(equal.asOf);const futureSnapshot={...snapshot("2026-01-01T10:00:00Z","future"),inputEvidence:["e"],materialEvidence:[{evidenceId:"e",availableAt:"2026-01-01T10:01:00.000Z"}]};expect(()=>canonicalM4RecordFromSnapshot({snapshot:futureSnapshot,candidateId:"candidate-a",canonicalIdentifier:"asset-a",assetClass:"CRYPTO",canonicalContextId:contextId("2026-01-01T10:00:00Z"),featureSetVersion:INTELLIGENCE_FEATURE_SET_VERSION,trendPolicyVersion:TREND_ANALYSIS_VERSION,accelerationVersion:TREND_ACCELERATION_VERSION,datasetPins:["p:v1"],corroborationProviderIds:["p1"],corroborationEvidenceIds:[]})).toThrow("CANONICAL_M4_DATE_INVALID");});
 it("accepts M5 availability before and at asOf and rejects future availability",()=>{expect(m5("2026-01-01T10:00:00Z","before","ELIGIBLE",["p:v1"],"CLEAN",contextId("2026-01-01T10:00:00Z"),"2026-01-01T09:00:00.000Z").availableAt.getTime()).toBeLessThan(at("2026-01-01T10:00:00Z").getTime());expect(m5("2026-01-01T10:00:00Z","equal").availableAt).toEqual(at("2026-01-01T10:00:00Z"));expect(()=>m5("2026-01-01T10:00:00Z","future","ELIGIBLE",["p:v1"],"CLEAN",contextId("2026-01-01T10:00:00Z"),"2026-01-01T10:01:00.000Z")).toThrow("CANONICAL_M5_DATE_INVALID");});
 it("requires assembly lineage in canonical M5 fingerprint material",()=>{const record=m5("2026-01-01T10:00:00Z");const changed={...record,assemblyFingerprint:"assembly-fingerprint-2"};expect(canonicalM5Fingerprint(withoutFingerprint(changed))).not.toBe(record.fingerprint);expect(()=>canonicalM5RecordFromEvaluation({evaluation:{evaluationId:"e",candidateId:"candidate-a",asOf:"2026-01-01T10:00:00.000Z",policyVersion:ASSET_ELIGIBILITY_VERSION,profileVersion:SYNTHETIC_PROFILE_VERSION,status:"ELIGIBLE",checks:[]},canonicalIdentifier:"asset-a",assetClass:"CRYPTO",canonicalContextId:contextId("2026-01-01T10:00:00Z"),availableAt:at("2026-01-01T09:00:00Z"),evidenceIds:["e"],datasetPins:["p:v1"],suspiciousFlags:[],suspiciousEvidenceStatus:"CLEAN",assemblyFingerprint:""})).toThrow("CANONICAL_M5_ASSEMBLY_FINGERPRINT_INVALID");});
 it("rejects M4 snapshots with no represented material evidence before availability reduction",()=>{const input={snapshot:{...snapshot("2026-01-01T10:00:00Z","empty",[]),inputEvidence:[]},candidateId:"candidate-a",canonicalIdentifier:"asset-a",assetClass:"CRYPTO",canonicalContextId:contextId("2026-01-01T10:00:00Z"),featureSetVersion:INTELLIGENCE_FEATURE_SET_VERSION,trendPolicyVersion:TREND_ANALYSIS_VERSION,accelerationVersion:TREND_ACCELERATION_VERSION,datasetPins:["p:v1"],corroborationProviderIds:["p1"],corroborationEvidenceIds:[]};expect(()=>canonicalM4RecordFromSnapshot(input)).toThrow("CANONICAL_M4_DATE_INVALID");});
 });
