import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import { createContractVerificationEligibilityEvidence, createQuantitativeEligibilityEvidence, createSuspiciousEligibilityEvidence, createVenueEligibilityEvidence } from "@/domain/intelligence/eligibility-evidence";
import { createRawEligibilityEvidenceRepository, mapQuantitativeEligibilityEvidenceRow, mapReferenceEligibilityEvidenceRow, mapSuspiciousEligibilityEvidenceRow, mapVenueEligibilityEvidenceRow } from "@/infrastructure/postgres/eligibility-evidence-repository";
import { createAssetMappingRevision } from "@/domain/intelligence/asset-mapping-revision";

const base=(overrides:Record<string,unknown>={})=>({evidenceId:"e1",candidateId:"c1",assetId:"a1",canonicalIdentifier:"asset:a1",assetClass:"CRYPTO",providerId:"p1",datasetId:"d1",datasetVersion:"v1",mappingRevisionId:"mapping-1",sourceLineageId:"lineage-1",observedAt:"2026-09-13T10:00:00.000Z",availableAt:"2026-09-13T10:01:00.000Z",provenance:{sourceType:"M5_SOURCE_LINEAGE",sourceRecordIds:["r1"],payloadFingerprint:"a".repeat(64)},...overrides});
const quantitative=(overrides:Record<string,unknown>={})=>createQuantitativeEligibilityEvidence(base({metricKind:"VOLATILITY",valueAtoms:9007199254740993123n,scale:0,unit:"BPS",semanticsVersion:"raw/v1",window:{startAt:"2026-09-12T10:00:00.000Z",endAt:"2026-09-13T10:00:00.000Z"},...overrides}) as never);
const row=(e:ReturnType<typeof quantitative>)=>({evidence_id:e.evidenceId,candidate_id:e.candidateId,asset_id:e.assetId,canonical_identifier:e.canonicalIdentifier,asset_class:e.assetClass,provider_id:e.providerId,dataset_id:e.datasetId,dataset_version:e.datasetVersion,mapping_revision_id:e.mappingRevisionId,source_lineage_id:e.sourceLineageId,observed_at:e.observedAt,available_at:e.availableAt,provenance:e.provenance,fingerprint:e.fingerprint,metric_kind:e.metricKind,value_atoms:e.valueAtoms.toString(),scale:e.scale,unit:e.unit,semantics_version:e.semanticsVersion,currency_code:e.currencyCode??null,window_start_at:e.window?.startAt??null,window_end_at:e.window?.endAt??null,qualification_basis:e.qualificationBasis??null});
const fake=(rows:Record<string,unknown[]>={},fail=false)=>{const calls:{sql:string;values:unknown[]}[]=[];const client=async(strings:TemplateStringsArray,...values:unknown[])=>{const sql=strings.join("?");calls.push({sql,values});if(fail)throw new Error("DATABASE_FAILURE");if(sql.startsWith("insert"))return [{evidence_id:"e"}];if(sql.includes("eligibility_quantitative_evidence"))return rows.quantitative??[];if(sql.includes("eligibility_reference_evidence"))return rows.reference??[];if(sql.includes("eligibility_venue_evidence"))return rows.venue??[];if(sql.includes("eligibility_suspicious_evidence"))return rows.suspicious??[];return [];};return{client,calls};};
const scope={candidateId:"c1",assetId:"a1",canonicalIdentifier:"asset:a1",assetClass:"CRYPTO",asOf:"2026-09-13T11:00:00.000Z",pins:[{providerId:"p1",datasetId:"d1",datasetVersion:"v1"}]};
const mapping=createAssetMappingRevision({mappingRevisionVersion:"mapping/v1",providerAssetIdentityAssertionId:"m5-provider-asset-identity:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",providerId:"p1",datasetId:"d1",datasetVersion:"v1",sourceLineageId:"lineage-1",providerAssetNamespace:"FIXTURE",providerAssetId:"asset-1",canonicalAssetId:"a1",canonicalIdentifier:"asset:a1",assetClass:"CRYPTO",validFrom:"2026-01-01T00:00:00.000Z",observedAt:"2026-01-01T00:00:00.000Z",availableAt:"2026-01-01T00:01:00.000Z",sourceRecordIds:["mapping-source"],payloadFingerprint:"mapping-payload",recordedAt:"2026-01-02T00:00:00.000Z"});
const mappingRepository={readById:async()=>mapping};

describe("M5 raw evidence persistence",()=>{
 it("keeps the migration structurally hardened without policy maxima",()=>{const sql=readFileSync("supabase/migrations/20260913231740_m5_raw_evidence.sql","utf8");for(const table of ["eligibility_quantitative_evidence","eligibility_reference_evidence","eligibility_venue_evidence","eligibility_suspicious_evidence"])expect(sql).toContain(`public.${table}`);expect(sql).toContain("value_atoms = trunc(value_atoms)");expect(sql).toContain("asset_class <> 'UNKNOWN'");expect(sql).toContain("value_atoms <= 10000");expect(sql).not.toContain("value_atoms <= 20000");expect(sql).toContain("enable row level security");expect(sql).toContain("revoke all on public.eligibility_quantitative_evidence from anon, authenticated");expect(sql).toContain("before update or delete");});
 it("maps all four raw families and preserves tri-state, severity, and bigint",()=>{const q=quantitative(),r=row(q);expect(mapQuantitativeEligibilityEvidenceRow(r).valueAtoms).toBe(9007199254740993123n);for(const state of ["VERIFIED","UNVERIFIED","UNKNOWN"] as const){const e=createContractVerificationEligibilityEvidence(base({evidenceId:state,verificationState:state}) as never);expect(mapReferenceEligibilityEvidenceRow({...r,evidence_id:e.evidenceId,fingerprint:e.fingerprint,reference_kind:"CONTRACT_VERIFICATION",verification_state:state})).toMatchObject({verificationState:state});}const v=createVenueEligibilityEvidence(base({evidenceId:"venue",venueId:"venue-1",eligibilityState:"ELIGIBLE"}) as never);expect(mapVenueEligibilityEvidenceRow({...r,evidence_id:v.evidenceId,fingerprint:v.fingerprint,venue_id:v.venueId,eligibility_state:v.eligibilityState}).venueId).toBe("venue-1");const s=createSuspiciousEligibilityEvidence(base({evidenceId:"s",flagCode:"WASH",severity:"LOW",sourceSignalId:"signal"}) as never);expect(mapSuspiciousEligibilityEvidenceRow({...r,evidence_id:s.evidenceId,fingerprint:s.fingerprint,flag_code:s.flagCode,severity:s.severity,source_signal_id:s.sourceSignalId}).severity).toBe("LOW");});
 it("fails closed for corrupt persisted facts",()=>{const r=row(quantitative());expect(()=>mapQuantitativeEligibilityEvidenceRow({...r,value_atoms:"1.5"})).toThrow("M5_RAW_ROW_VALUE_INVALID");expect(()=>mapQuantitativeEligibilityEvidenceRow({...r,asset_class:"UNKNOWN"})).toThrow();expect(()=>mapQuantitativeEligibilityEvidenceRow({...r,fingerprint:"wrong"})).toThrow("M5_RAW_ROW_FINGERPRINT_MISMATCH");});
 it("writes idempotently and conflicts without update/delete",async()=>{const e=quantitative(),f=fake();await createRawEligibilityEvidenceRepository(f.client as never,mappingRepository).save(e);expect(f.calls[0]!.sql).toContain("insert into public.eligibility_quantitative_evidence");expect(f.calls[0]!.sql).toContain("on conflict (evidence_id) do nothing");expect(f.calls[0]!.sql).not.toMatch(/update|delete/i);});
 it("validates mapping lineage before insert for all four evidence families",async()=>{const records=[quantitative(),createContractVerificationEligibilityEvidence(base({evidenceId:"reference",verificationState:"VERIFIED"}) as never),createVenueEligibilityEvidence(base({evidenceId:"venue",venueId:"venue-1",eligibilityState:"ELIGIBLE"}) as never),createSuspiciousEligibilityEvidence(base({evidenceId:"suspicious",flagCode:"FLAG",severity:"LOW",sourceSignalId:"signal"}) as never)];for(const record of records){const f=fake();await createRawEligibilityEvidenceRepository(f.client as never,mappingRepository).save(record);expect(f.calls[0]!.sql).toContain("insert into public.");}await expect(createRawEligibilityEvidenceRepository(fake().client as never,{readById:async()=>undefined}).save(quantitative())).rejects.toThrow("M5_RAW_MAPPING_NOT_FOUND");await expect(createRawEligibilityEvidenceRepository(fake().client as never,{readById:async()=>mapping}).save(quantitative({providerId:"other"}))).rejects.toThrow("M5_RAW_MAPPING_LINEAGE_MISMATCH");await expect(createRawEligibilityEvidenceRepository(fake().client as never,{readById:async()=>{throw new Error("DATABASE_FAILURE");}}).save(quantitative())).rejects.toThrow("DATABASE_FAILURE");});
 it("validates scope and returns raw pinned visible rows in deterministic order",async()=>{const a=quantitative({evidenceId:"z"}),b=quantitative({evidenceId:"a",metricKind:"VOLUME",valueAtoms:1n,unit:"MINOR",currencyCode:"USD"}),f=fake({quantitative:[row(a),row(b)]});const result=await createRawEligibilityEvidenceRepository(f.client as never,mappingRepository).readAt({...scope,pins:[...scope.pins,...scope.pins]});expect(result.map(x=>x.evidenceId)).toEqual(["z","a"]);expect(f.calls).toHaveLength(4);expect(f.calls.every(call=>call.sql.includes("available_at<=?")&&call.sql.includes("observed_at<=?"))).toBe(true);await expect(createRawEligibilityEvidenceRepository(f.client as never,mappingRepository).readAt({...scope,pins:[]})).rejects.toThrow("INVALID_READ_SCOPE");});
 it("preserves multiple raw facts and propagates database failure",async()=>{const a=quantitative({evidenceId:"a"}),b=quantitative({evidenceId:"b",valueAtoms:25000n}),f=fake({quantitative:[row(b),row(a)]});expect((await createRawEligibilityEvidenceRepository(f.client as never,mappingRepository).readAt(scope)).map(x=>x.evidenceId)).toEqual(["a","b"]);await expect(createRawEligibilityEvidenceRepository(fake({},true).client as never,mappingRepository).readAt(scope)).rejects.toThrow("DATABASE_FAILURE");});
});
