import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { getSourcePortfolioDecision, evaluateSourcePortfolioRouting, type SyntheticRoutingMaterial } from "@/domain/intelligence/event-intelligence-source-portfolio-routing-decision";
import { EVIDENCE_REVIEW_QUEUE_PRODUCTION_CONFIG, parseEvidenceReviewQueueProductionConfig } from "@/domain/intelligence/event-intelligence-evidence-review-queue-production";
import { REVIEW_PRIORITIES, getEvidenceReviewQueueContract, parseEvidenceReviewQueueContract, projectRoutingResultToEvidenceReviewItem, sealEvidenceReviewQueueSet, sortEvidenceReviewItems, isAuthenticEvidenceReviewItem, isAuthenticEvidenceReviewQueueSet } from "@/domain/intelligence/event-intelligence-evidence-review-queue";

const base = (patch: Partial<SyntheticRoutingMaterial> = {}): SyntheticRoutingMaterial => {
  const jurisdiction = patch.jurisdiction ?? "US_SEC";
  const listingScopes = patch.listingScopes ?? (jurisdiction === "US_SEC" ? ["listing:us-sec"] : jurisdiction === "GB_LSE" ? ["listing:lse"] : jurisdiction === "AU_ASX" ? ["listing:asx"] : jurisdiction === "DUAL_LISTED" ? ["listing:lse", "listing:asx"] : []);
  const out = { provenance: "SYNTHETIC" as const, candidateId: "candidate:queue-0001", jurisdiction, listingScopes, eventHint: "PURCHASE_INTENT" as const, seenFamilies: ["DISCOVERY_AGGREGATOR"] as SyntheticRoutingMaterial["seenFamilies"], availableFamilies: ["FILING_AUTHORITY", "ISSUER_ATTRIBUTED_RELEASE"] as SyntheticRoutingMaterial["availableFamilies"], issuerMapped: false, assetMapped: false, duplicate: false, rightsApproved: true, credentialAvailable: true, completionMaterialPresent: false, primaryAvailable: true, qualificationComplete: true, correctionPresent: false, correctionResolved: true, correctionFieldHints: patch.correctionFieldHints ?? (patch.correctionPresent ? ["OTHER"] : []), retracted: false, conflicts: [] as SyntheticRoutingMaterial["conflicts"], stale: false, originBindings: [] as SyntheticRoutingMaterial["originBindings"], publicationAt: "2026-10-01T00:00:00.000Z", discoveredAt: "2026-10-01T00:01:00.000Z", receivedAt: "2026-10-01T00:02:00.000Z", correctionAvailableAt: null as string | null, evaluationAsOf: "2026-10-03T00:00:00.000Z", ...patch };
  return { ...out, availableFamilies: out.availableFamilies.filter(f => !out.seenFamilies.includes(f)) };
};
function routingAt(state: string, patch: Partial<SyntheticRoutingMaterial> = {}) {
  const decision = getSourcePortfolioDecision();
  const stablePatch = { ...patch };
  const journey = base({ ...stablePatch, seenFamilies: ["FILING_AUTHORITY"], availableFamilies: ["ISSUER_ATTRIBUTED_RELEASE"], issuerMapped: true, assetMapped: true });
  let result = evaluateSourcePortfolioRouting(decision, journey);
  const allowed = ["DISCOVERED", "SOURCE_RETRIEVAL_REQUIRED", "ISSUER_MAPPING_REQUIRED", "ASSET_MAPPING_REQUIRED", "PRIMARY_DISCLOSURE_REQUIRED", "CORRECTION_REVIEW_REQUIRED", "CORROBORATION_REVIEW_REQUIRED", "ELIGIBILITY_REVIEW_REQUIRED"];
  while (result && result.nextState !== state && result.nextState !== "STOPPED_BLOCKED" && result.nextState !== "NON_AUTHORITATIVE_REVIEW_COMPLETE" && allowed.includes(result.nextState)) result = evaluateSourcePortfolioRouting(decision, journey, result);
  if (!result || result.nextState === "STOPPED_BLOCKED" || result.nextState === "NON_AUTHORITATIVE_REVIEW_COMPLETE" || result.nextState !== state) return result;
  const finalMaterial = base({ ...stablePatch, issuerMapped: patch.issuerMapped ?? true, assetMapped: patch.assetMapped ?? true });
  return evaluateSourcePortfolioRouting(decision, finalMaterial, result);
}
function item(state = "SOURCE_RETRIEVAL_REQUIRED", patch: Partial<SyntheticRoutingMaterial> = {}) {
  const routing = routingAt(state, patch);
  return routing ? projectRoutingResultToEvidenceReviewItem(getSourcePortfolioDecision(), routing) : null;
}

describe("event intelligence evidence review queue contract", () => {
  it("maps a missing primary source to a retrieval task with explicit blocker", () => { const v = item("SOURCE_RETRIEVAL_REQUIRED", { primaryAvailable: false, issuerMapped: true, assetMapped: true }); expect(v).toMatchObject({ itemType: "PRIMARY_SOURCE_RETRIEVAL_REVIEW", status: "OPEN", requiredNextAction: "RETRIEVE_PRIMARY_SOURCE" }); expect(v?.blockerReasons.map(x => x.code)).toContain("PRIMARY_SOURCE_MISSING"); });
  it("keeps issuer and asset mapping blockers distinct", () => { expect(item("ISSUER_MAPPING_REQUIRED", { issuerMapped: false })?.itemType).toBe("ISSUER_MAPPING_REVIEW"); expect(item("ASSET_MAPPING_REQUIRED", { issuerMapped: true, assetMapped: false })?.itemType).toBe("ASSET_MAPPING_REVIEW"); });
  it("creates jurisdiction review for unknown scope", () => { expect(item("DISCOVERED", { jurisdiction: "UNKNOWN", listingScopes: [] })?.itemType).toBe("JURISDICTION_REVIEW"); });
  it("prioritizes unresolved correction and marks resolved correction non-authoritatively", () => { const unresolved = item("CORRECTION_REVIEW_REQUIRED", { eventHint: "CORRECTION_AMENDMENT", correctionPresent: true, correctionResolved: false, correctionAvailableAt: "2026-10-02T00:00:00.000Z" }); expect(unresolved).toMatchObject({ itemType: "CORRECTION_LINEAGE_REVIEW", status: "BLOCKED", priority: "URGENT_CORRECTION_REVIEW" }); const resolved = item("CORRECTION_REVIEW_REQUIRED", { eventHint: "CORRECTION_AMENDMENT", correctionPresent: true, correctionResolved: true, correctionAvailableAt: "2026-10-02T00:00:00.000Z" }); expect(resolved?.status).toBe("RESOLVED_NON_AUTHORITATIVE"); });
  it("carries declared correction fields without treating them as verified changes", () => { const v = item("CORRECTION_REVIEW_REQUIRED", { eventHint: "CORRECTION_AMENDMENT", correctionPresent: true, correctionResolved: false, correctionFieldHints: ["AMOUNT", "ASSET"], correctionAvailableAt: "2026-10-02T00:00:00.000Z" }); expect(v?.correctionFieldHints).toEqual(["AMOUNT", "ASSET"]); expect(v?.authorityIssued).toBe(false); expect(routingAt("DISCOVERED", { correctionPresent: true, correctionFieldHints: [] })).toBeNull(); });
  it("retraction is visible, terminal and higher priority than duplicate no-action", () => { const v = item("DISCOVERED", { eventHint: "RETRACTION_WITHDRAWAL", retracted: true, duplicate: true }); expect(v).toMatchObject({ itemType: "RETRACTION_REVIEW", status: "RETRACTED", priority: "URGENT_RETRACTION_REVIEW" }); });
  it("maps source and lifecycle conflicts to blocked conflict review", () => { expect(item("DISCOVERED", { conflicts: ["SOURCE_MATERIAL_CONFLICT"] })?.itemType).toBe("SOURCE_CONFLICT_REVIEW"); expect(item("DISCOVERED", { conflicts: ["LIFECYCLE_CONFLICT"] })?.status).toBe("BLOCKED"); });
  it("shows origin grouping without counting syndication as corroboration", () => { const v = item("CORROBORATION_REVIEW_REQUIRED", { seenFamilies: ["FILING_AUTHORITY"], issuerMapped: true, assetMapped: true, originBindings: [{ sourceRecordId: "record:original", retrievalArtifactId: "artifact:original", publicationId: "release:one", issuerOriginId: "origin:issuer", distributionCopyOf: null }, { sourceRecordId: "record:copy", retrievalArtifactId: "artifact:copy", publicationId: "release:one", issuerOriginId: "origin:issuer", distributionCopyOf: "record:original" }] }); expect(v).toMatchObject({ itemType: "ORIGIN_GROUP_REVIEW", status: "BLOCKED", originGroupCount: 1, syndicatedCopyCount: 1 }); expect(v?.blockerReasons.map(x => x.code)).toContain("INDEPENDENT_CORROBORATION_UNSUPPORTED"); });
  it("keeps rights as a distinct blocked item", () => { expect(item("DISCOVERED", { rightsApproved: false })?.itemType).toBe("RIGHTS_APPROVAL_REVIEW"); });
  it("blocks unsupported corroboration and never turns completion into authority", () => { const v = item("CORROBORATION_REVIEW_REQUIRED", { seenFamilies: ["FILING_AUTHORITY"], issuerMapped: true, assetMapped: true }); expect(v).toMatchObject({ itemType: "BLOCKED_UNSUPPORTED_CORROBORATION", status: "BLOCKED", authorityIssued: false, signalEligible: false, tradingEligible: false }); });
  it("keeps routine review categorical and source-count independent", () => { const one = item("SOURCE_RETRIEVAL_REQUIRED", { seenFamilies: ["FILING_AUTHORITY"], issuerMapped: true, assetMapped: true }); const many = item("SOURCE_RETRIEVAL_REQUIRED", { seenFamilies: ["FILING_AUTHORITY"], issuerMapped: true, assetMapped: true, originBindings: Array.from({ length: 2 }, (_, i) => ({ sourceRecordId: `record:${i}`, retrievalArtifactId: `artifact:${i}`, publicationId: `release:${i}`, issuerOriginId: `origin:${i}`, distributionCopyOf: null })) }); expect(one?.priority).toBe("ROUTINE_DISCOVERY_REVIEW"); expect(many?.priority).toBe(one?.priority); });
  it("duplicate replay maps to NO_ACTION and cannot suppress correction review", () => { expect(item("DISCOVERED", { duplicate: true })?.status).toBe("NO_ACTION"); expect(item("DISCOVERED", { duplicate: true, correctionPresent: true, correctionResolved: false, correctionAvailableAt: "2026-10-02T00:00:00.000Z" })?.itemType).toBe("CORRECTION_LINEAGE_REVIEW"); });
  it("represents non-authoritative completion while remaining blocked by unsupported corroboration", () => { const v = item("ELIGIBILITY_REVIEW_REQUIRED", { seenFamilies: ["FILING_AUTHORITY"], issuerMapped: true, assetMapped: true }); expect(v).toMatchObject({ itemType: "NON_AUTHORITATIVE_REVIEW_COMPLETE", status: "BLOCKED", authorityIssued: false }); });
  it("keeps completed-purchase claims blocked without separate completion material", () => { const v = item("PRIMARY_DISCLOSURE_REQUIRED", { eventHint: "COMPLETED_PURCHASE", seenFamilies: ["FILING_AUTHORITY"], issuerMapped: true, assetMapped: true, completionMaterialPresent: false }); expect(v).toMatchObject({ status: "BLOCKED", authorityIssued: false }); });
  it("produces distinct immutable snapshots before and after a later correction", () => { const before = item("SOURCE_RETRIEVAL_REQUIRED", { evaluationAsOf: "2026-10-01T00:03:00.000Z" }); const after = item("SOURCE_RETRIEVAL_REQUIRED", { correctionPresent: true, correctionResolved: false, correctionAvailableAt: "2026-10-02T00:00:00.000Z" }); expect(before?.itemId).not.toBe(after?.itemId); expect(before?.correctionPresent).toBe(false); expect(after?.status).toBe("BLOCKED"); });
  it("rejects future evidence at the routing boundary", () => { expect(routingAt("DISCOVERED", { receivedAt: "2026-10-04T00:00:00.000Z" })).toBeNull(); });
  it("rejects copied and serialized routing results", () => { const routing = routingAt("DISCOVERED")!; expect(projectRoutingResultToEvidenceReviewItem(getSourcePortfolioDecision(), { ...routing })).toBeNull(); expect(projectRoutingResultToEvidenceReviewItem(getSourcePortfolioDecision(), JSON.parse(JSON.stringify(routing)))).toBeNull(); });
  it("does not reopen terminal routing results", () => { const terminal = routingAt("ELIGIBILITY_REVIEW_REQUIRED")!; expect(terminal.nextState).toBe("NON_AUTHORITATIVE_REVIEW_COMPLETE"); expect(evaluateSourcePortfolioRouting(getSourcePortfolioDecision(), base(), terminal)).toBeNull(); });
  it("binds candidate identity and evaluation cutoff across routing stages", () => { const d = getSourcePortfolioDecision(); const initial = evaluateSourcePortfolioRouting(d, base())!; expect(evaluateSourcePortfolioRouting(d, base({ candidateId: "candidate:queue-0002" }), initial)).toBeNull(); expect(evaluateSourcePortfolioRouting(d, base({ evaluationAsOf: "2026-10-04T00:00:00.000Z" }), initial)).toBeNull(); });
  it("rejects stage-history, degradation and conflict tampering", () => { const v = item()!; expect(projectRoutingResultToEvidenceReviewItem(getSourcePortfolioDecision(), { ...routingAt("SOURCE_RETRIEVAL_REQUIRED")!, stageHistory: ["DISCOVERED"] })).toBeNull(); expect(isAuthenticEvidenceReviewItem({ ...v, degradationReasons: [] })).toBe(false); const conflict = item("DISCOVERED", { conflicts: ["SOURCE_MATERIAL_CONFLICT"] })!; expect(isAuthenticEvidenceReviewItem({ ...conflict, conflictReasons: [] })).toBe(false); });
  it("replays to the same identity and changes identity when cutoff or material changes", () => { const a = item("SOURCE_RETRIEVAL_REQUIRED"); const replay = item("SOURCE_RETRIEVAL_REQUIRED"); const later = item("SOURCE_RETRIEVAL_REQUIRED", { evaluationAsOf: "2026-10-04T00:00:00.000Z" }); expect(a?.itemId).toBe(replay?.itemId); expect(a?.itemId).not.toBe(later?.itemId); });
  it("rejects same-ID repeated members and detects material changes before identity comparison", () => { const d = getSourcePortfolioDecision(); const result = routingAt("SOURCE_RETRIEVAL_REQUIRED")!; const sealed = sealEvidenceReviewQueueSet(d, [result]); expect(sealed.status).toBe("SEALED"); expect(sealEvidenceReviewQueueSet(d, [result, result]).status).toBe("INVALID"); expect(item("SOURCE_RETRIEVAL_REQUIRED", { correctionPresent: true, correctionResolved: true, correctionAvailableAt: "2026-10-02T00:00:00.000Z" })?.itemId).not.toBe(item("SOURCE_RETRIEVAL_REQUIRED")?.itemId); });
  it("sorts by versioned categorical priority then UTC publication and stable identity", () => { const ordinary = item("SOURCE_RETRIEVAL_REQUIRED")!; const correction = item("CORRECTION_REVIEW_REQUIRED", { eventHint: "CORRECTION_AMENDMENT", correctionPresent: true, correctionResolved: false, correctionAvailableAt: "2026-10-02T00:00:00.000Z" })!; const sorted = sortEvidenceReviewItems([ordinary, correction])!; expect(sorted[0]?.priority).toBe("URGENT_CORRECTION_REVIEW"); expect(REVIEW_PRIORITIES[0]).toBe("URGENT_RETRACTION_REVIEW"); expect(sortEvidenceReviewItems([ordinary, ordinary])).toBeNull(); expect(sortEvidenceReviewItems(new Proxy([], { get() { throw new Error("trap"); } }))).toBeNull(); });
  it("seals exact member count, contiguous ordinals, canonical order and a single historical cutoff", () => { const d = getSourcePortfolioDecision(); const results = [routingAt("SOURCE_RETRIEVAL_REQUIRED")!, routingAt("CORRECTION_REVIEW_REQUIRED", { eventHint: "CORRECTION_AMENDMENT", correctionPresent: true, correctionResolved: false, correctionAvailableAt: "2026-10-02T00:00:00.000Z" })]; const sealed = sealEvidenceReviewQueueSet(d, results); expect(sealed.status).toBe("SEALED"); if (sealed.status === "SEALED") { expect(sealed.queueSet.memberCount).toBe(2); expect(sealed.queueSet.members.map(x => x.ordinal)).toEqual([0, 1]); expect(isAuthenticEvidenceReviewQueueSet(sealed.queueSet)).toBe(true); expect(isAuthenticEvidenceReviewQueueSet({ ...sealed.queueSet })).toBe(false); expect(sealEvidenceReviewQueueSet(d, [results[0]!, routingAt("SOURCE_RETRIEVAL_REQUIRED", { evaluationAsOf: "2026-10-04T00:00:00.000Z" })!]).status).toBe("INVALID"); } });
  it("rejects sparse, accessor and proxy result arrays", () => { const d = getSourcePortfolioDecision(); const sparse = new Array(1); expect(sealEvidenceReviewQueueSet(d, sparse).status).toBe("INVALID"); const accessor: unknown[] = []; Object.defineProperty(accessor, "0", { enumerable: true, get() { throw new Error("trap"); } }); Object.defineProperty(accessor, "length", { value: 1 }); expect(sealEvidenceReviewQueueSet(d, accessor).status).toBe("INVALID"); expect(sealEvidenceReviewQueueSet(d, new Proxy([], { get() { throw new Error("trap"); } })).status).toBe("INVALID"); });
  it("does not treat source count or amount as priority", () => { const a = item("SOURCE_RETRIEVAL_REQUIRED")!; const b = item("SOURCE_RETRIEVAL_REQUIRED", { originBindings: [{ sourceRecordId: "record:1", retrievalArtifactId: "artifact:1", publicationId: "release:1", issuerOriginId: "origin:1", distributionCopyOf: null }] })!; expect(a.priority).toBe(b.priority); expect(a).not.toHaveProperty("amount"); expect(a).not.toHaveProperty("confidence"); });
  it("keeps internal trust, fingerprints, raw candidate text and authority fields out of the deferred view model", () => { const v = item()!; expect(JSON.stringify(v)).not.toContain("WeakSet"); expect(v).not.toHaveProperty("rawPayload"); expect(v).not.toHaveProperty("credential"); expect(v.forbiddenConclusions).toContain("NO_EVENT_AUTHORITY"); expect(isAuthenticEvidenceReviewItem(JSON.parse(JSON.stringify(v)))).toBe(false); });
  it("parses the versioned contract without upgrading caller copies to trust", () => { const contract = getEvidenceReviewQueueContract(); expect(parseEvidenceReviewQueueContract(JSON.parse(JSON.stringify(contract))).status).toBe("VALID"); expect(parseEvidenceReviewQueueContract({ ...contract, itemTypes: [] }).status).toBe("INVALID"); const accessor = { ...contract }; let invoked = false; Object.defineProperty(accessor, "itemTypes", { enumerable: true, get() { invoked = true; return contract.itemTypes; } }); expect(parseEvidenceReviewQueueContract(accessor).status).toBe("INVALID"); expect(invoked).toBe(false); });
  it("rejects unsafe contract shapes, symbols, inherited values and proxies", () => { const contract = getEvidenceReviewQueueContract(); expect(parseEvidenceReviewQueueContract(Object.assign(Object.create({ x: 1 }), contract)).status).toBe("INVALID"); expect(parseEvidenceReviewQueueContract({ ...contract, [Symbol("unsafe")]: true }).status).toBe("INVALID"); expect(parseEvidenceReviewQueueContract(new Proxy({}, { get() { throw new Error("trap"); } })).status).toBe("INVALID"); });
  it("rejects malformed correction hints and preserves the original material identity", () => { const parsed = base({ correctionPresent: true, correctionFieldHints: ["AMOUNT", "AMOUNT"] }); expect(evaluateSourcePortfolioRouting(getSourcePortfolioDecision(), parsed)).toBeNull(); const sparse = base({ correctionPresent: true, correctionFieldHints: new Array(1) as never }); expect(evaluateSourcePortfolioRouting(getSourcePortfolioDecision(), sparse)).toBeNull(); });
  it("keeps production queue, persistence, scheduler, notifications and approvals blocked", () => { expect(EVIDENCE_REVIEW_QUEUE_PRODUCTION_CONFIG.queueProjection).toBe("BLOCKED"); expect(EVIDENCE_REVIEW_QUEUE_PRODUCTION_CONFIG.queuePersistence).toBe("BLOCKED"); expect(Object.values(EVIDENCE_REVIEW_QUEUE_PRODUCTION_CONFIG.approvals as Record<string, unknown>).every(x => x === "NOT_APPROVED")).toBe(true); const config = JSON.parse(JSON.stringify(EVIDENCE_REVIEW_QUEUE_PRODUCTION_CONFIG)); config.notifications = "READY"; expect(parseEvidenceReviewQueueProductionConfig(config)).toBeNull(); expect(parseEvidenceReviewQueueProductionConfig(new Proxy({}, { get() { throw new Error("trap"); } }))).toBeNull(); });
  it("has no source, persistence, scheduler, notification, UI, credential or sibling integration", () => { const source = readFileSync("src/domain/intelligence/event-intelligence-evidence-review-queue.ts", "utf8"); expect(source).not.toMatch(/from\s+["'][^"']*(gdelt|newsapi|issuer-release|exchange-announcement|discovery-inbox|supabase|tests\/fixtures)[^"']*["']/i); expect(source).not.toMatch(/\b(fetch|createConnection|createClient|dns\.lookup|https\.request)\s*\(/); expect(source).not.toContain("process.env"); });
});
