import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
import { EVENT_INTELLIGENCE_SOURCE_PORTFOLIO_PRODUCTION, parseSourcePortfolioProductionConfig } from "@/domain/intelligence/event-intelligence-source-portfolio-routing-production";
import { DEGRADATION_REASONS, getSourcePortfolioDecision, evaluateSourcePortfolioRouting, parseSourcePortfolioDecision, parseSyntheticRoutingMaterial, type SyntheticRoutingMaterial } from "@/domain/intelligence/event-intelligence-source-portfolio-routing-decision";

const states = ["DISCOVERED", "SOURCE_RETRIEVAL_REQUIRED", "ISSUER_MAPPING_REQUIRED", "ASSET_MAPPING_REQUIRED", "PRIMARY_DISCLOSURE_REQUIRED", "CORRECTION_REVIEW_REQUIRED", "CORROBORATION_REVIEW_REQUIRED", "ELIGIBILITY_REVIEW_REQUIRED", "NON_AUTHORITATIVE_REVIEW_COMPLETE"] as const;
const base = (overrides: Partial<SyntheticRoutingMaterial> = {}): SyntheticRoutingMaterial => { const jurisdiction = overrides.jurisdiction ?? "US_SEC"; const listingScopes = overrides.listingScopes ?? (jurisdiction === "US_SEC" ? ["listing:us-sec"] : jurisdiction === "GB_LSE" ? ["listing:lse"] : jurisdiction === "AU_ASX" ? ["listing:asx"] : jurisdiction === "DUAL_LISTED" ? ["listing:lse", "listing:asx"] : []); const out = { provenance: "SYNTHETIC" as const, candidateId: "candidate:portfolio-0001", jurisdiction, listingScopes, eventHint: "PURCHASE_INTENT" as const, seenFamilies: ["DISCOVERY_AGGREGATOR"] as SyntheticRoutingMaterial["seenFamilies"], availableFamilies: ["FILING_AUTHORITY", "ISSUER_ATTRIBUTED_RELEASE"] as SyntheticRoutingMaterial["availableFamilies"], issuerMapped: false, assetMapped: false, duplicate: false, rightsApproved: true, credentialAvailable: true, completionMaterialPresent: false, primaryAvailable: true, qualificationComplete: true, correctionPresent: false, correctionResolved: true, retracted: false, conflicts: [] as SyntheticRoutingMaterial["conflicts"], stale: false, originBindings: [] as SyntheticRoutingMaterial["originBindings"], publicationAt: "2026-10-01T00:00:00.000Z", discoveredAt: "2026-10-01T00:01:00.000Z", receivedAt: "2026-10-01T00:02:00.000Z", correctionAvailableAt: null as string | null, evaluationAsOf: "2026-10-03T00:00:00.000Z", ...overrides }; return { ...out, availableFamilies: out.availableFamilies.filter(f => !out.seenFamilies.includes(f)) }; };
const route = (overrides: Partial<SyntheticRoutingMaterial> & { currentState?: string; stageHistory?: readonly string[] } = {}) => {
  const { currentState: requestedState = "DISCOVERED", stageHistory: _untrustedHistory, ...provided } = overrides;
  void _untrustedHistory;
  if (!states.includes(requestedState as typeof states[number])) return null;
  const decision = getSourcePortfolioDecision();
  let material = base({ ...provided, seenFamilies: ["FILING_AUTHORITY"], availableFamilies: ["ISSUER_ATTRIBUTED_RELEASE"], issuerMapped: true, assetMapped: true });
  let previous = evaluateSourcePortfolioRouting(decision, material);
  while (previous && previous.nextState !== requestedState && previous.nextState !== "STOPPED_BLOCKED" && previous.nextState !== "NON_AUTHORITATIVE_REVIEW_COMPLETE") {
    previous = evaluateSourcePortfolioRouting(decision, material, previous);
  }
  if (requestedState !== "DISCOVERED" && previous?.nextState === "STOPPED_BLOCKED") return previous;
  material = base({ ...provided, issuerMapped: provided.issuerMapped ?? true, assetMapped: provided.assetMapped ?? true });
  return evaluateSourcePortfolioRouting(decision, material, requestedState === "DISCOVERED" ? undefined : previous);
};

describe("versioned source portfolio routing decision", () => {
  it("routes SEC registrants to filings first and never emits authority", () => { const r = route(); expect(r?.nextState).toBe("SOURCE_RETRIEVAL_REQUIRED"); expect(r?.nextSourceFamily).toBe("FILING_AUTHORITY"); expect(r?.authorityIssued).toBe(false); });
  it("degrades visibly when a US filing source is unavailable before selecting issuer release discovery", () => { const r = route({ jurisdiction: "US_SEC", availableFamilies: ["ISSUER_ATTRIBUTED_RELEASE", "DISCOVERY_AGGREGATOR"], seenFamilies: [] }); expect(r?.nextSourceFamily).toBe("ISSUER_ATTRIBUTED_RELEASE"); expect(r?.degradationReasons).toContain("PRIMARY_SOURCE_UNAVAILABLE"); });
  it("routes LSE and ASX candidates to their jurisdictional disclosure family", () => { expect(route({ jurisdiction: "GB_LSE", availableFamilies: ["REGULATORY_OR_EXCHANGE_DISCLOSURE"], seenFamilies: [] })?.nextSourceFamily).toBe("REGULATORY_OR_EXCHANGE_DISCLOSURE"); expect(route({ jurisdiction: "AU_ASX", availableFamilies: ["REGULATORY_OR_EXCHANGE_DISCLOSURE"], seenFamilies: [] })?.nextSourceFamily).toBe("REGULATORY_OR_EXCHANGE_DISCLOSURE"); });
  it("degrades unknown jurisdictions and stops dual-listed scope pending explicit mapping", () => { expect(route({ jurisdiction: "UNKNOWN" })?.degradationReasons).toContain("UNSUPPORTED_JURISDICTION"); expect(route({ jurisdiction: "DUAL_LISTED" })?.nextState).toBe("STOPPED_BLOCKED"); });
  it("keeps NewsAPI and GDELT in discovery-only strength", () => { expect(route({ seenFamilies: ["DISCOVERY_AGGREGATOR"] })?.sourceStrength).toBe("DISCOVERY_ONLY"); });
  it.each(["ISSUER_ATTRIBUTED_RELEASE", "DISCOVERY_AGGREGATOR", "REGULATORY_OR_EXCHANGE_DISCLOSURE", "FILING_AUTHORITY"] as const)("does not count %s delivery copies as factual corroboration", (family) => { const r = route({ seenFamilies: [family], originBindings: [{ sourceRecordId: "record:1", retrievalArtifactId: "artifact:1", publicationId: "release:1", issuerOriginId: "issuer-origin:1", distributionCopyOf: null }, { sourceRecordId: "record:2", retrievalArtifactId: "artifact:2", publicationId: "release:1", issuerOriginId: "issuer-origin:1", distributionCopyOf: "record:1" }] }); expect(r?.publicationOriginGroupCount).toBe(1); expect(r?.independentFactualOriginGroups).toBe(0); expect(r?.independentFactualCorroboration).toBe("UNSUPPORTED"); });
  it("keeps distinct origin candidates distinct without declaring corroboration", () => { const r = route({ originBindings: [{ sourceRecordId: "record:one", retrievalArtifactId: "artifact:one", publicationId: "release:one", issuerOriginId: "issuer-origin:one", distributionCopyOf: null }, { sourceRecordId: "record:two", retrievalArtifactId: "artifact:two", publicationId: "release:two", issuerOriginId: "issuer-origin:two", distributionCopyOf: null }] }); expect(r?.independentFactualCorroboration).toBe("UNSUPPORTED"); });
  it.each(["PURCHASE_INTENT", "BOARD_AUTHORIZATION", "TREASURY_POLICY"] as const)("keeps %s in candidate retrieval", hint => { expect(route({ eventHint: hint })?.nextState).toBe("SOURCE_RETRIEVAL_REQUIRED"); });
  it.each(["BINDING_AGREEMENT", "EXPECTED_CLOSING"] as const)("requires primary disclosure for %s", hint => { expect(route({ eventHint: hint, currentState: "PRIMARY_DISCLOSURE_REQUIRED", issuerMapped: true, assetMapped: true, seenFamilies: ["FILING_AUTHORITY"] })?.nextState).toBe("CORRECTION_REVIEW_REQUIRED"); });
  it("requires distinct completion material before reviewing a completed-purchase claim", () => { expect(route({ eventHint: "COMPLETED_PURCHASE", currentState: "PRIMARY_DISCLOSURE_REQUIRED", issuerMapped: true, assetMapped: true, seenFamilies: ["FILING_AUTHORITY"], completionMaterialPresent: false })?.nextState).toBe("STOPPED_BLOCKED"); });
  it("requires separately observed completion material for a completed-purchase claim", () => { const r = route({ eventHint: "COMPLETED_PURCHASE", seenFamilies: ["DISCOVERY_AGGREGATOR"], currentState: "PRIMARY_DISCLOSURE_REQUIRED" }); expect(r?.degradationReasons).toContain("PRIMARY_SOURCE_UNAVAILABLE"); expect(r?.authorityIssued).toBe(false); });
  it("routes corrections for review and stops unresolved corrections/retractions", () => { expect(route({ eventHint: "CORRECTION_AMENDMENT", currentState: "CORRECTION_REVIEW_REQUIRED", correctionPresent: true, correctionResolved: false })?.nextState).toBe("STOPPED_BLOCKED"); expect(route({ eventHint: "RETRACTION_WITHDRAWAL", retracted: true })?.nextState).toBe("STOPPED_BLOCKED"); });
  it("allows a resolved correction to proceed to non-authoritative corroboration review", () => { const r = route({ eventHint: "CORRECTION_AMENDMENT", currentState: "CORRECTION_REVIEW_REQUIRED", correctionPresent: true, correctionResolved: true, correctionAvailableAt: "2026-10-02T00:00:00.000Z", seenFamilies: ["FILING_AUTHORITY"] }); expect(r).toMatchObject({ currentState: "CORRECTION_REVIEW_REQUIRED", nextState: "CORROBORATION_REVIEW_REQUIRED" }); });
  it("excludes future correction material at a historical evaluation cutoff", () => { expect(parseSyntheticRoutingMaterial(base({ correctionPresent: true, correctionAvailableAt: "2026-10-04T00:00:00.000Z" })).status).toBe("INVALID"); });
  it("rejects caller-supplied skipped routing history and copied evaluator results", () => { expect(parseSyntheticRoutingMaterial({ ...base(), currentState: "ELIGIBILITY_REVIEW_REQUIRED", stageHistory: ["DISCOVERED", "ELIGIBILITY_REVIEW_REQUIRED"] }).status).toBe("INVALID"); const first = route(); expect(evaluateSourcePortfolioRouting(getSourcePortfolioDecision(), base(), { ...first! })).toBeNull(); });
  it("does not carry stage progress across a changed historical evaluation cutoff", () => { const d = getSourcePortfolioDecision(); const m = base(); const prior = evaluateSourcePortfolioRouting(d, m)!; expect(evaluateSourcePortfolioRouting(d, base({ evaluationAsOf: "2026-10-04T00:00:00.000Z" }), prior)).toBeNull(); });
  it("keeps publication, discovery, receipt and evaluation timestamps ordered", () => { expect(parseSyntheticRoutingMaterial(base({ discoveredAt: "2026-09-30T00:00:00.000Z" })).status).toBe("INVALID"); expect(parseSyntheticRoutingMaterial(base({ receivedAt: "2026-10-04T00:00:00.000Z" })).status).toBe("INVALID"); });
  it("rejects contradictory relabeling of one publication as a second origin", () => { const parsed = parseSyntheticRoutingMaterial(base({ originBindings: [{ sourceRecordId: "record:a", retrievalArtifactId: "artifact:a", publicationId: "release:same", issuerOriginId: "origin:a", distributionCopyOf: null }, { sourceRecordId: "record:b", retrievalArtifactId: "artifact:b", publicationId: "release:same", issuerOriginId: "origin:b", distributionCopyOf: null }] })); expect(parsed.status).toBe("INVALID"); });
  it("does not skip issuer and asset mapping states", () => { expect(route({ currentState: "ISSUER_MAPPING_REQUIRED", issuerMapped: false })?.nextState).toBe("STOPPED_BLOCKED"); expect(route({ currentState: "ASSET_MAPPING_REQUIRED", issuerMapped: true, assetMapped: false })?.nextState).toBe("STOPPED_BLOCKED"); });
  it("keeps ETH and WETH ambiguity represented only by unresolved mapping state", () => { const r = route({ currentState: "ASSET_MAPPING_REQUIRED", issuerMapped: true, assetMapped: false }); expect(r?.degradationReasons).toContain("MAPPING_INCOMPLETE"); });
  it.each(["AMOUNT_CURRENCY_CONFLICT", "LIFECYCLE_CONFLICT", "SOURCE_MATERIAL_CONFLICT"] as const)("stops on %s without winner selection", conflict => { const r = route({ conflicts: [conflict] }); expect(r?.nextState).toBe("STOPPED_BLOCKED"); expect(r?.conflictReasons).toContain(conflict); });
  it("stops when rights or credentials are unavailable", () => { expect(route({ rightsApproved: false })?.degradationReasons).toContain("RIGHTS_UNAPPROVED"); expect(route({ credentialAvailable: false })?.degradationReasons).toContain("CREDENTIAL_MISSING"); });
  it("degrades explicitly when a primary source is unavailable", () => { const r = route({ currentState: "SOURCE_RETRIEVAL_REQUIRED", primaryAvailable: false }); expect(r?.nextState).toBe("STOPPED_BLOCKED"); expect(r?.degradationReasons).toContain("PRIMARY_SOURCE_UNAVAILABLE"); });
  it("marks exact duplicates NO_ACTION_DUPLICATE", () => { expect(route({ duplicate: true })?.operationalPriority).toBe("NO_ACTION_DUPLICATE"); });
  it("prioritizes correction review without assigning investment score", () => { const r = route({ correctionPresent: true }); expect(r?.operationalPriority).toBe("URGENT_CORRECTION_REVIEW"); expect(r).not.toHaveProperty("confidence"); expect(r).not.toHaveProperty("score"); });
  it("can end only in explicitly non-authoritative review completion", () => { const r = route({ currentState: "ELIGIBILITY_REVIEW_REQUIRED", seenFamilies: ["FILING_AUTHORITY"], issuerMapped: true, assetMapped: true, primaryAvailable: true, qualificationComplete: true, correctionResolved: true }); expect(r?.nextState).toBe("NON_AUTHORITATIVE_REVIEW_COMPLETE"); expect(r?.authorityIssued).toBe(false); expect(r?.signalEligible).toBe(false); expect(r?.tradingEligible).toBe(false); expect(r?.degradationReasons).toContain("INDEPENDENT_CORROBORATION_UNAVAILABLE"); });
  it("walks the entire allowlisted graph in order and cannot resume its terminal result", () => { const d = getSourcePortfolioDecision(); const m = base({ seenFamilies: ["FILING_AUTHORITY"], availableFamilies: ["ISSUER_ATTRIBUTED_RELEASE"], issuerMapped: true, assetMapped: true }); const results = [evaluateSourcePortfolioRouting(d, m)!]; while (results.at(-1)!.nextState !== "NON_AUTHORITATIVE_REVIEW_COMPLETE") results.push(evaluateSourcePortfolioRouting(d, m, results.at(-1))!); expect(results.map(x => x.currentState)).toEqual(states.slice(0, -1)); expect(results.at(-1)?.nextState).toBe("NON_AUTHORITATIVE_REVIEW_COMPLETE"); expect(evaluateSourcePortfolioRouting(d, m, results.at(-1))).toBeNull(); expect(Object.isFrozen(results.at(-1))).toBe(true); });
  it("rejects illegal transitions and caller skip attempts", () => { expect(route({ currentState: "DISCOVERED" })?.nextState).toBe("SOURCE_RETRIEVAL_REQUIRED"); expect(route({ currentState: "DISCOVERED", issuerMapped: true, assetMapped: true })?.nextState).not.toBe("ELIGIBILITY_REVIEW_REQUIRED"); });
  it("does not trust copied, JSON, or caller-fabricated decisions", () => { const d = getSourcePortfolioDecision(); expect(evaluateSourcePortfolioRouting({ ...d }, base())).toBeNull(); expect(evaluateSourcePortfolioRouting(JSON.parse(JSON.stringify(d)), base())).toBeNull(); expect(parseSourcePortfolioDecision(JSON.parse(JSON.stringify(d))).status).toBe("VALID"); });
  it("keeps recordedAt outside decision identity and rejects nested accessors without invoking them", () => { const d = JSON.parse(JSON.stringify(getSourcePortfolioDecision())) as Record<string, unknown>; d.recordedAt = "2026-10-03T10:00:00.000Z"; expect(parseSourcePortfolioDecision(d).status).toBe("VALID"); const unsafe = JSON.parse(JSON.stringify(getSourcePortfolioDecision())) as Record<string, unknown>; let called = false; const family = Object.create(null) as Record<string, unknown>; Object.defineProperty(family, "family", { enumerable: true, get() { called = true; return "DISCOVERY_AGGREGATOR"; } }); Object.assign(family, { maxRequestsPerRun: 2, maxBytes: 524288, maxRecords: 25, timeoutMs: 5000, retries: 0, historicalBackfill: "BLOCKED", concurrentAcquisitions: 0 }); (unsafe.budgets as unknown[])[0] = family; expect(parseSourcePortfolioDecision(unsafe).status).toBe("INVALID"); expect(called).toBe(false); });
  it("rejects unsafe shapes, inherited values, accessors, symbols, sparse arrays and proxies", () => { const input = base() as unknown as Record<string, unknown>; expect(parseSyntheticRoutingMaterial({ ...input, unexpected: true }).status).toBe("INVALID"); const inherited = Object.create({ candidateId: "bad" }); expect(parseSyntheticRoutingMaterial(inherited).status).toBe("INVALID"); let called = false; const accessor = { ...input }; Object.defineProperty(accessor, "candidateId", { enumerable: true, get() { called = true; return "candidate:bad"; } }); expect(parseSyntheticRoutingMaterial(accessor).status).toBe("INVALID"); expect(called).toBe(false); expect(parseSyntheticRoutingMaterial(new Proxy({}, { get() { throw new Error("trap"); } })).status).toBe("INVALID"); const sparse = ["DISCOVERY_AGGREGATOR", , "FILING_AUTHORITY"]; expect(parseSyntheticRoutingMaterial({ ...input, seenFamilies: sparse }).status).toBe("INVALID"); expect(parseSyntheticRoutingMaterial({ ...input, [Symbol("x")]: 1 }).status).toBe("INVALID"); });
  it("rejects fingerprint collision claims because only canonical built-in material is trusted", () => { const d = getSourcePortfolioDecision(); expect(parseSourcePortfolioDecision({ ...d, fingerprint: "a".repeat(64) }).status).toBe("INVALID"); });
  it("keeps production config wholly blocked with all approvals denied", () => { expect(EVENT_INTELLIGENCE_SOURCE_PORTFOLIO_PRODUCTION.selectedSourcePortfolio).toBeNull(); expect(EVENT_INTELLIGENCE_SOURCE_PORTFOLIO_PRODUCTION.acquisition).toBe("BLOCKED"); expect(Object.values(EVENT_INTELLIGENCE_SOURCE_PORTFOLIO_PRODUCTION.approvals as Record<string, unknown>).every(x => x === "NOT_APPROVED")).toBe(true); const candidate = JSON.parse(JSON.stringify(EVENT_INTELLIGENCE_SOURCE_PORTFOLIO_PRODUCTION)); candidate.acquisition = "READY"; expect(parseSourcePortfolioProductionConfig(candidate)).toBeNull(); expect(parseSourcePortfolioProductionConfig(new Proxy({}, { get() { throw new Error("trap"); } }))).toBeNull(); });
  it("has no active independent-factual-corroboration source or operative ports", () => { expect(getSourcePortfolioDecision().sourceFamilies).toContain("INDEPENDENT_FACTUAL_CORROBORATION"); expect(getSourcePortfolioDecision().productionBlockers).toContain("INDEPENDENT_FACTUAL_CORROBORATION_UNSUPPORTED"); expect(DEGRADATION_REASONS).toContain("INDEPENDENT_CORROBORATION_UNAVAILABLE"); });
  it("rejects unsupported factual corroboration as observed or available input", () => { expect(parseSyntheticRoutingMaterial(base({ seenFamilies: ["INDEPENDENT_FACTUAL_CORROBORATION"] })).status).toBe("INVALID"); expect(parseSyntheticRoutingMaterial(base({ availableFamilies: ["INDEPENDENT_FACTUAL_CORROBORATION"] })).status).toBe("INVALID"); });
  it("reports acquisition disabled as categorical degradation", () => { expect(route()?.degradationReasons).toContain("ACQUISITION_DISABLED"); });
  it("keeps production decision graph free of sibling imports and operative ports", () => { const source = readFileSync("src/domain/intelligence/event-intelligence-source-portfolio-routing-decision.ts", "utf8"); expect(source).not.toMatch(/from\s+["'][^"']*(gdelt|newsapi|issuer-release|exchange-announcement|discovery-inbox|tests\/fixtures)[^"']*["']/i); expect(source).not.toMatch(/\b(fetch|createConnection|createClient|dns\.lookup|https\.request)\s*\(/); expect(source).not.toContain("process.env"); });
});
