import { describe, expect, it } from "vitest";
import { InMemoryIntelligenceStore, INTELLIGENCE_FOUNDATION_VERSION, payloadFingerprint, type NewsEvent, type MarketObservation } from "@/domain/intelligence/foundation";
import { analyzeIntelligenceAt, EVENT_SIGNATURE_VERSION, HISTORICAL_ANALOGUE_VERSION, INTELLIGENCE_ENGINE_VERSION, INTELLIGENCE_FEATURE_SET_VERSION, REGIME_CLASSIFICATION_VERSION, TREND_ANALYSIS_VERSION, type IntelligenceAnalysisConfig } from "@/domain/intelligence/engine";
const d=(s:string)=>new Date(s); const config: IntelligenceAnalysisConfig={engineVersion:INTELLIGENCE_ENGINE_VERSION,featureSetVersion:INTELLIGENCE_FEATURE_SET_VERSION,asOf:d("2024-01-03"),providerDatasetPins:[{providerId:"P",datasetVersion:"D"}],eventSignatureVersion:EVENT_SIGNATURE_VERSION,trendPolicyVersion:TREND_ANALYSIS_VERSION,regimePolicyVersion:REGIME_CLASSIFICATION_VERSION,analoguePolicyVersion:HISTORICAL_ANALOGUE_VERSION,assetId:"a"};
const prov=(id:string)=>({providerId:"P",datasetId:"ds",datasetVersion:"D",externalRecordId:id,sourceType:"SYNTHETIC",payloadFingerprint:payloadFingerprint(id),foundationVersion:INTELLIGENCE_FOUNDATION_VERSION as typeof INTELLIGENCE_FOUNDATION_VERSION});
const n=(id:string,at:string,mappings:NewsEvent["mappings"]=[]) : NewsEvent=>({id,providerId:"P",datasetVersion:"D",externalRecordId:id,revision:1,publishedAt:d("2024-01-01"),availableAt:d(at),ingestedAt:d("2025-01-01"),title:"fixture",sourceType:"SYNTHETIC",provenance:prov(id),mappings});
const m=(id:string,at:string,v:bigint):MarketObservation=>({id,providerId:"P",datasetVersion:"D",externalRecordId:id,assetId:"a",observedAt:d(at),availableAt:d(at),ingestedAt:d("2025-01-01"),observationType:"PRICE",valueAtoms:v,scale:2,unit:"NOK",provenance:prov(id)});
describe("M4 deterministic intelligence",()=>{it("returns explicit NO_DATA",()=>expect(analyzeIntelligenceAt(new InMemoryIntelligenceStore(),config).integrityStatus).toBe("NO_DATA"));it("excludes future and other datasets",()=>{const s=new InMemoryIntelligenceStore();s.ingestNews(n("future","2024-01-04"));expect(analyzeIntelligenceAt(s,config).inputEvidence).toEqual([]);});it("creates order-independent event signatures and novelty",()=>{const s=new InMemoryIntelligenceStore();const maps=[{recordId:"x",mappingKind:"ASSET" as const,targetId:"b",source:"DETERMINISTIC_FIXTURE" as const,evidence:"e"},{recordId:"x",mappingKind:"TOPIC" as const,targetId:"a",source:"DETERMINISTIC_FIXTURE" as const,evidence:"e"}];s.ingestNews(n("one","2024-01-01",maps));const a=analyzeIntelligenceAt(s,{...config,asOf:d("2024-01-01")});expect(a.noveltyEvidence[0]!.classification).toBe("FIRST_SEEN");expect(a.eventContexts[0]!.classification).toBe("MARKET");});it("computes deterministic trend and regime",()=>{const s=new InMemoryIntelligenceStore();s.ingestMarket(m("m1","2024-01-01",100n));s.ingestMarket(m("m2","2024-01-02",110n));const a=analyzeIntelligenceAt(s,config);expect(a.trends[0]).toMatchObject({status:"COMPLETE",direction:"UP",signedChangeBps:"1000"});expect(a.regime.label).toBe("RISK_ON");expect(a).toEqual(analyzeIntelligenceAt(s,config));});it("rejects unsupported algorithms",()=>expect(()=>analyzeIntelligenceAt(new InMemoryIntelligenceStore(),{...config,engineVersion:"x" as never})).toThrow("UNSUPPORTED_POLICY_VERSION"));});
it("computes adjacent-window acceleration and deterministic analogue ranking",()=>{const s=new InMemoryIntelligenceStore();s.ingestMarket(m("a","2024-01-01T12:00:00Z",100n));s.ingestMarket(m("b","2024-01-01T18:00:00Z",105n));s.ingestMarket(m("c","2024-01-02T12:00:00Z",110n));s.ingestMarket(m("d","2024-01-02T18:00:00Z",120n));const a=analyzeIntelligenceAt(s,{...config,asOf:d("2024-01-03"),trendWindowMillis:86400000,analogueCandidateTimestamps:[d("2024-01-02T23:00:00Z")],analogueLimit:1});expect(a.trends[0]!.accelerationStatus).toBe("COMPLETE");expect(a.trends[0]!.accelerationBps).toBeTruthy();expect(a.analogues).toHaveLength(1);});
