import { describe, expect, it } from "vitest";
import { InMemoryIntelligenceStore, INTELLIGENCE_FOUNDATION_VERSION, payloadFingerprint, validateMacroObservation, validateMarketObservation, validateNewsEvent, type MacroObservation, type MarketObservation, type NewsEvent } from "@/domain/intelligence/foundation";

const times = { publishedAt: new Date("2024-01-01T00:00:00Z"), observedAt: new Date("2024-01-01T01:00:00Z"), availableAt: new Date("2024-01-02T00:00:00Z"), ingestedAt: new Date("2026-01-01T00:00:00Z") };
const provenance = (externalRecordId: string, version = "fixture/v1") => ({ providerId: "MM_FIXTURE", datasetId: "fixture", datasetVersion: version, externalRecordId, sourceType: "SYNTHETIC_FIXTURE", payloadFingerprint: payloadFingerprint(externalRecordId), foundationVersion: INTELLIGENCE_FOUNDATION_VERSION as typeof INTELLIGENCE_FOUNDATION_VERSION });
const news = (id: string, revision = 1): NewsEvent => ({ id: `${id}-${revision}`, providerId: "MM_FIXTURE", datasetVersion: "fixture/v1", externalRecordId: id, revision, ...times, title: "Synthetic event", sourceType: "SYNTHETIC_FIXTURE", provenance: provenance(id), mappings: [] });
const market = (id: string, version = "fixture/v1"): MarketObservation => ({ id, providerId: "MM_FIXTURE", datasetVersion: version, externalRecordId: id, assetId: "mm.fixture.global.v1", observedAt: times.observedAt, availableAt: times.availableAt, ingestedAt: times.ingestedAt, observationType: "PRICE", valueAtoms: 5000n, scale: 4, unit: "NOK", provenance: provenance(id, version) });
const macro = (id: string): MacroObservation => ({ id, providerId: "MM_FIXTURE", datasetVersion: "fixture/v1", externalRecordId: id, revision: 1, indicatorCode: "CPI", geography: "NO", referencePeriodStart: new Date("2024-01-01"), referencePeriodEnd: new Date("2024-01-31"), publishedAt: times.publishedAt, availableAt: times.availableAt, ingestedAt: times.ingestedAt, valueAtoms: 100n, scale: 2, unit: "INDEX", provenance: provenance(id) });

describe("M3 intelligence foundation", () => {
  it("validates typed News, Market and Macro records", () => { validateNewsEvent(news("n1")); validateMarketObservation(market("m1")); validateMacroObservation(macro("x1")); });
  it("keeps published/observed/available/ingested times distinct", () => expect(times.ingestedAt > times.availableAt && times.availableAt > times.publishedAt).toBe(true));
  it("enforces exact availability boundary and excludes future records", () => { const s = new InMemoryIntelligenceStore(); s.ingestNews(news("n1")); const before = s.newsAvailableAt(new Date("2024-01-01T23:59:59Z"), "fixture/v1"); expect(before).toHaveLength(0); expect(s.newsAvailableAt(times.availableAt, "fixture/v1")).toHaveLength(1); });
  it("pins datasets and preserves deterministic ordering", () => { const s = new InMemoryIntelligenceStore(); s.ingestMarket(market("b")); s.ingestMarket(market("a")); expect(s.marketAvailableAt(times.ingestedAt, "fixture/v1").map(x => x.id)).toEqual(["a", "b"]); expect(s.marketAvailableAt(times.ingestedAt, "other/v1")).toHaveLength(0); });
  it("deduplicates identical records and rejects immutable conflicts", () => { const s = new InMemoryIntelligenceStore(); const first = s.ingestNews(news("n1")); expect(s.ingestNews(news("n1"))).toBe(first); expect(() => s.ingestNews({ ...news("n1"), title: "changed", provenance: { ...news("n1").provenance, payloadFingerprint: "different" } })).toThrow("SOURCE_RECORD_CONFLICT"); });
  it("keeps revisions historically visible at their availability boundaries", () => { const s = new InMemoryIntelligenceStore(); s.ingestNews(news("n1", 1)); s.ingestNews({ ...news("n1", 2), id: "n1-2", availableAt: new Date("2024-01-05"), provenance: provenance("n1-r2") }); expect(s.newsAvailableAt(new Date("2024-01-03"), "fixture/v1").map(x => x.revision)).toEqual([1]); expect(s.newsAvailableAt(new Date("2024-01-06"), "fixture/v1").map(x => x.revision)).toEqual([2]); });
  it("preserves mapping and source provenance without financial authority", () => { const event = { ...news("mapped"), mappings: [{ recordId: "mapped-1", mappingKind: "ASSET" as const, targetId: "mm.fixture.global.v1", source: "DETERMINISTIC_FIXTURE" as const, evidence: "fixture registry" }] }; const s = new InMemoryIntelligenceStore(); expect(s.ingestNews(event).mappings[0]!.targetId).toBe("mm.fixture.global.v1"); expect(Object.keys(event)).not.toContain("approval"); });
  it("rejects malformed timestamp ordering and unsupported temporal queries remain empty", () => expect(() => validateNewsEvent({ ...news("bad"), availableAt: new Date("2027-01-01"), ingestedAt: new Date("2026-01-01") })).toThrow("INVALID_NEWS_EVENT"));
});
