import { describe, expect, it } from "vitest";
import { assembleM5Evidence, M5_EVIDENCE_MANIFEST_VERSION, type M5AssemblyContext, type M5EvidenceManifest, type M5EvidenceSemanticCompatibility } from "@/application/intelligence/assemble-m5-evidence";
import { canonicalM5HandoffFromAssembly } from "@/application/intelligence/m5-canonical-handoff";
import { createAgeReferenceEligibilityEvidence, createQuantitativeEligibilityEvidence, createSuspiciousEligibilityEvidence, createVenueEligibilityEvidence, type RawEligibilityEvidence } from "@/domain/intelligence/eligibility-evidence";
import { createM5SuspiciousAssessment } from "@/domain/intelligence/m5-suspicious-assessment";
import { encodeM5DatasetPin } from "@/domain/intelligence/m5-dataset-pin";
import { evaluateAssetEligibility } from "@/domain/discovery/asset-eligibility";

const base = (o: Record<string, unknown> = {}) => ({ evidenceId: "e", candidateId: "candidate", assetId: "asset", canonicalIdentifier: "asset:one", assetClass: "CRYPTO", providerId: "provider", datasetId: "dataset", datasetVersion: "v1", mappingRevisionId: "mapping-1", sourceLineageId: "lineage-1", observedAt: "2026-09-10T00:00:00.000Z", availableAt: "2026-09-12T00:00:00.000Z", provenance: { sourceType: "M5_SOURCE_LINEAGE", sourceRecordIds: ["source"], payloadFingerprint: "a".repeat(64) }, ...o });
const ref = (e: RawEligibilityEvidence) => ({ evidenceId: e.evidenceId, fingerprint: e.fingerprint });
const context = (o: Record<string, unknown> = {}): M5AssemblyContext => ({ candidateId: "candidate", assetId: "asset", canonicalIdentifier: "asset:one", assetClass: "CRYPTO", asOf: "2026-09-13T00:00:00.000Z", allowedPins: [{ providerId: "provider", datasetId: "dataset", datasetVersion: "v1" }], ...o });
const compatibility = (): M5EvidenceSemanticCompatibility => ({ version: "m5-compatibility/v1", permittedAgeBases: ["ASSET_INCEPTION"], ageCalculationVersion: "age-days/v1", historySpanSemanticsVersions: ["history/v1"], historySpanQualificationBases: ["QUALIFYING"], volatilitySemanticsVersions: ["volatility/v1"], monetaryCurrency: "USD", monetaryUnit: "MINOR", monetaryScale: 0, liquiditySemanticsVersions: ["monetary/v1"], volumeSemanticsVersions: ["monetary/v1"], marketCapSemanticsVersions: ["monetary/v1"] });
const metric = (id: string, kind: string, value: bigint) => createQuantitativeEligibilityEvidence(base({ evidenceId: id, metricKind: kind, valueAtoms: value, scale: 0, unit: kind === "HISTORY_SPAN" ? "DAYS" : kind.includes("CONCENTRATION") || kind === "VOLATILITY" ? "BPS" : "MINOR", semanticsVersion: kind === "HISTORY_SPAN" ? "history/v1" : kind === "VOLATILITY" ? "volatility/v1" : "monetary/v1", currencyCode: ["LIQUIDITY", "VOLUME", "MARKET_CAP"].includes(kind) ? "USD" : undefined, qualificationBasis: kind === "HISTORY_SPAN" ? "QUALIFYING" : undefined, ...(kind.includes("CONCENTRATION") ? { holderSnapshotId: "snapshot-1", holderSnapshotFingerprint: "b".repeat(64), holderDerivationFingerprint: "c".repeat(64), asOf: "2026-09-13T00:00:00.000Z" } : {}), ...(kind === "HISTORY_SPAN" || kind === "VOLATILITY" ? { dailySeriesAuthorityId: "authority-1", dailySeriesAuthorityFingerprint: "d".repeat(64), dailySeriesDerivationFingerprint: "e".repeat(64), asOf: "2026-09-13T00:00:00.000Z" } : {}), ...(kind === "LIQUIDITY" || kind === "VOLUME" || kind === "MARKET_CAP" ? { marketMetricsAuthorityId: "market-authority-1", marketMetricsAuthorityFingerprint: "f".repeat(64), marketMetricsDerivationFingerprint: "a".repeat(64), asOf: "2026-09-13T00:00:00.000Z" } : {}), window: kind === "MARKET_CAP" || kind.includes("CONCENTRATION") ? undefined : { startAt: "2026-09-09T00:00:00.000Z", endAt: "2026-09-10T00:00:00.000Z" } }) as never);
function fixture(findings: RawEligibilityEvidence[] = []) {
  const age = createAgeReferenceEligibilityEvidence(base({ evidenceId: "age", referenceKind: "ASSET_INCEPTION", ageBasis: "ASSET_INCEPTION", referenceAt: "2026-08-01T00:00:00.000Z" }) as never);
  const history = metric("history", "HISTORY_SPAN", 14n), liquidity = metric("liquidity", "LIQUIDITY", 1n), volume = metric("volume", "VOLUME", 1n), cap = metric("cap", "MARKET_CAP", 1n), top = metric("top", "TOP10_CONCENTRATION", 100n), single = metric("single", "SINGLE_CONCENTRATION", 100n), volatility = metric("volatility", "VOLATILITY", 10n);
  const venue = createVenueEligibilityEvidence(base({ evidenceId: "venue", venueId: "m5-venue-member-a", eligibilityState: "ELIGIBLE", venueAuthorityId: "venue-authority-1", venueAuthorityFingerprint: "b".repeat(64), venueMemberId: "m5-venue-member-a", venueMemberFingerprint: "c".repeat(64), venueAuthorityMemberCount: 1, asOf: "2026-09-13T00:00:00.000Z" }) as never);
  const raw = [age, history, liquidity, volume, cap, top, single, volatility, venue, ...findings] as RawEligibilityEvidence[];
  const assessment = createM5SuspiciousAssessment({ contractVersion: "m5-suspicious-assessment/v1", providerId: "provider", datasetId: "dataset", datasetVersion: "v1", candidateId: "candidate", assetId: "asset", canonicalIdentifier: "asset:one", assetClass: "CRYPTO", mappingRevisionId: "mapping-1", sourceLineageId: "lineage-1", ruleSetVersion: "rules/v1", ruleSetFingerprint: "b".repeat(64), detectorVersion: "detector/v1", coveredRuleIds: ["RULE_A"], result: findings.length ? "FINDINGS_PRESENT" : "NO_FINDINGS", findingReferences: findings.map(ref), asOf: "2026-09-13T00:00:00.000Z", observedAt: "2026-09-10T00:00:00.000Z", availableAt: "2026-09-12T00:00:00.000Z", sourceRecordIds: ["source"], payloadFingerprint: "a".repeat(64), datasetPins: [encodeM5DatasetPin({ providerId: "provider", datasetId: "dataset", datasetVersion: "v1" })], recordedAt: "2026-09-13T00:00:00.000Z" });
  const manifest: M5EvidenceManifest = { version: M5_EVIDENCE_MANIFEST_VERSION, age: ref(age), historySpan: ref(history), liquidity: ref(liquidity), volume: ref(volume), marketCap: ref(cap), top10HolderConcentration: ref(top), singleHolderConcentration: ref(single), volatility: ref(volatility), venues: [ref(venue)], suspiciousAssessment: { assessmentId: assessment.suspiciousAssessmentId, fingerprint: assessment.fingerprint } };
  return { raw, manifest, assessment };
}
const assemble = (f: ReturnType<typeof fixture>, extra: Partial<Parameters<typeof assembleM5Evidence>[0]> = {}) => assembleM5Evidence({ context: context(), manifest: f.manifest, compatibility: compatibility(), rawEvidence: f.raw, suspiciousAssessment: f.assessment, suspiciousFindings: f.raw.filter(v => v.evidenceKind === "SUSPICIOUS") as never[], requiredRuleIds: ["RULE_A"], ...extra });

describe("M5 evidence assembly suspicious assessment binding", () => {
  it("requires explicit NO_FINDINGS assessment and reaches COMPLETE", () => { const f = fixture(); const result = assemble(f); expect(result.status).toBe("COMPLETE"); if (result.status === "COMPLETE") expect(result.evidence.suspiciousFlags).toEqual([]); });
  it("maps exact findings and rejects missing or extra membership", () => { const finding = createSuspiciousEligibilityEvidence(base({ evidenceId: "finding", flagCode: "WASH", severity: "LOW", sourceSignalId: "signal" }) as never); const f = fixture([finding]); expect(assemble(f).status).toBe("COMPLETE"); expect(assemble(f, { suspiciousFindings: [] }).status).toBe("INVALID_MANIFEST"); });
  it("fails closed on manifest reference, rule coverage and scope mismatch", () => { const f = fixture(); expect(assemble(f, { manifest: { ...f.manifest, suspiciousAssessment: { ...f.manifest.suspiciousAssessment, fingerprint: "c".repeat(64) } } }).status).toBe("INVALID_MANIFEST"); expect(assemble(f, { requiredRuleIds: ["RULE_B"] }).status).toBe("INVALID_MANIFEST"); expect(assemble(f, { context: context({ candidateId: "other" }) }).status).toBe("INVALID_MANIFEST"); });
  it("rejects caller-authoritative venue evidence without persisted authority binding", () => { const f = fixture(); const unbound = createVenueEligibilityEvidence(base({ evidenceId: "unbound-venue", venueId: "venue-a", eligibilityState: "ELIGIBLE" }) as never); expect(assemble({ ...f, raw: [...f.raw.filter(value => value.evidenceId !== "venue"), unbound], manifest: { ...f.manifest, venues: [ref(unbound)] } }).status).toBe("INVALID_MANIFEST"); });
  it("returns INCOMPLETE for missing non-suspicious authority and never hands it to evaluator", () => { const f = fixture(); const result = assemble(f, { manifest: { ...f.manifest, historySpan: undefined } }); expect(result.status).toBe("INCOMPLETE"); const handoff = canonicalM5HandoffFromAssembly({ assembly: result, sourceContext: { candidateId: "candidate", assetId: "asset", canonicalIdentifier: "asset:one", assetClass: "CRYPTO", asOf: "2026-09-13T00:00:00.000Z", providerDatasetPins: [{ providerId: "provider", datasetVersion: "v1" }], relevantEvidence: [] } }); expect(handoff.status).toBe("INCOMPLETE"); });
  it("returns INCOMPLETE for absent suspicious assessment", () => { const f = fixture(); expect(assembleM5Evidence({ context: context(), manifest: f.manifest, compatibility: compatibility(), rawEvidence: f.raw }).status).toBe("INCOMPLETE"); });
  it("is permutation invariant and binds assessment to the assembly fingerprint", () => { const f = fixture(); const a = assemble(f); const b = assemble({ ...f, raw: [...f.raw].reverse(), manifest: { ...f.manifest, venues: [...f.manifest.venues].reverse() } }); expect(b).toEqual(a); });
  it("invokes evaluator exactly once only for COMPLETE", () => { const f = fixture(); let calls = 0; const evaluate = (evidence: Parameters<typeof evaluateAssetEligibility>[0], asOf: Date) => { calls += 1; return evaluateAssetEligibility(evidence, asOf); }; const complete = assemble(f); canonicalM5HandoffFromAssembly({ assembly: complete, sourceContext: { candidateId: "candidate", assetId: "asset", canonicalIdentifier: "asset:one", assetClass: "CRYPTO", asOf: "2026-09-13T00:00:00.000Z", providerDatasetPins: [{ providerId: "provider", datasetVersion: "v1" }], relevantEvidence: [] }, evaluate }); expect(calls).toBe(1); const incomplete = assemble(f, { manifest: { ...f.manifest, historySpan: undefined } }); canonicalM5HandoffFromAssembly({ assembly: incomplete, sourceContext: { candidateId: "candidate", assetId: "asset", canonicalIdentifier: "asset:one", assetClass: "CRYPTO", asOf: "2026-09-13T00:00:00.000Z", providerDatasetPins: [{ providerId: "provider", datasetVersion: "v1" }], relevantEvidence: [] }, evaluate }); expect(calls).toBe(1); });
  it("does not invoke evaluator for INVALID assembly", () => { const f = fixture(); let calls = 0; const evaluate = (evidence: Parameters<typeof evaluateAssetEligibility>[0], asOf: Date) => { calls += 1; return evaluateAssetEligibility(evidence, asOf); }; const invalid = assemble(f, { manifest: { ...f.manifest, suspiciousAssessment: { ...f.manifest.suspiciousAssessment, fingerprint: "c".repeat(64) } } }); const handoff = canonicalM5HandoffFromAssembly({ assembly: invalid, sourceContext: { candidateId: "candidate", assetId: "asset", canonicalIdentifier: "asset:one", assetClass: "CRYPTO", asOf: "2026-09-13T00:00:00.000Z", providerDatasetPins: [{ providerId: "provider", datasetVersion: "v1" }], relevantEvidence: [] }, evaluate }); expect(handoff.status).toBe("INVALID_ASSEMBLY"); expect(calls).toBe(0); });
});
