import { describe, expect, it } from "vitest";
import { parseM5ReportedCirculatingMarketCapQualification as parse, isAuthenticM5ReportedCapQualification } from "@/domain/intelligence/m5-reported-circulating-market-cap-source-qualification";
import { projectM5ReportedCirculatingMarketCap } from "@/domain/intelligence/m5-reported-circulating-market-cap-projection-guard";

const t="2026-09-30T12:00:00.000Z";
function fixture(overrides:Record<string,unknown>={}) { const claims=["STABLE_PROVIDER_ASSET_ID","PROVIDER_CALCULATED_CIRCULATING_VALUE","CIRCULATING_SUPPLY_METHODOLOGY","VALUE_SUPPLY_QUOTE_TIMESTAMP_BOUND","NULL_MISSING_POLICY","FRESHNESS_POLICY","CORRECTION_REVISION_POLICY","QUOTE_CURRENCY"]; return { contractVersion:"m5-reported-circulating-market-cap-source-qualification/v1",metricKind:"REPORTED_CIRCULATING_MARKET_CAP",providerId:"coingecko",datasetId:"coingecko-contract-market-chart",datasetVersion:"contract-market-chart/range-v1",providerAssetId:"wrapped-ether",chain:"eip155:1",contractAddress:"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",providerAssetName:"WETH",providerAssetSymbol:"WETH",canonicalRepresentation:"WETH",expectedCanonicalAssetId:"ethereum/erc20:0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",mappingRevisionId:"unmapped",mappingRevisionFingerprint:"a".repeat(64),quoteCurrency:"USD",reportedValueBasis:"PROVIDER_CALCULATED_CIRCULATING",supplyBasis:"CIRCULATING",priceBasis:"provider-reference-price",providerMethodologyVersion:"v1",providerValueTimestamp:t,supplyTimestamp:t,quoteTimestamp:t,effectiveAsOf:t,nullMissingPolicy:"reject-null",freshnessPolicy:"max-age-1h",correctionRevisionPolicy:"versioned",evidenceReferences:[{url:"https://docs.coingecko.com/reference/contract-address-market-chart-range",title:"Pro API Reference",checkedAt:t,classification:"DOCUMENTED",claims}],usageApproval:"APPROVED",storageApproval:"APPROVED",retentionApproval:"APPROVED",redistributionApproval:"APPROVED",commercialApproval:"APPROVED",blockers:[],reviewedAt:t,effectiveFrom:t,expiresAt:"2027-09-30T12:00:00.000Z",recordedAt:t,...overrides }; }
describe("M5 reported circulating market-cap qualification",()=>{
  it("strictly parses, freezes deeply and excludes recordedAt from identity",()=>{const a=parse(fixture()), b=parse(fixture({recordedAt:"2026-09-30T12:01:00.000Z"})); expect(a.status).toBe("VALID"); if(a.status!=="VALID"||b.status!=="VALID")return; expect(a.qualification.status).toBe("QUALIFIED"); expect(Object.isFrozen(a.qualification.evidenceReferences[0]?.claims)).toBe(true); expect(b.qualification.qualificationFingerprint).toBe(a.qualification.qualificationFingerprint); expect(isAuthenticM5ReportedCapQualification({...a.qualification})).toBe(false);});
  it.each([fixture({unknown:true}),fixture({providerAssetId:"https://example.test"}),fixture({contractAddress:"0xC02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"}),fixture({providerValueTimestamp:null}),fixture({blockers:["M5_X","M5_X"]}),fixture({reportedValueBasis:"TOTAL_SUPPLY",supplyBasis:"TOTAL"}),fixture({reportedValueBasis:"FDV"}),fixture({providerId:"wrong"})])("rejects malformed or noncanonical qualification inputs",x=>expect(parse(x).status).toBe("INVALID"));
  it("rejects inherited properties and accessors without invoking them",()=>{const inherited=Object.assign(Object.create({bad:true}),fixture()); expect(parse(inherited).status).toBe("INVALID"); let called=false; const x=fixture() as Record<string,unknown>; Object.defineProperty(x,"providerId",{get(){called=true;return "coingecko"},enumerable:true}); expect(parse(x).status).toBe("INVALID"); expect(called).toBe(false);});
  it("fails closed for partial candidates, absent mapping and approval mismatch",()=>{const p=parse(fixture({blockers:["M5_SEMANTICS_UNKNOWN"]})); expect(p.status).toBe("VALID"); if(p.status!=="VALID")return; expect(p.qualification.status).toBe("PARTIAL"); const base={qualification:p.qualification,providerId:"coingecko",datasetId:"coingecko-contract-market-chart",datasetVersion:"contract-market-chart/range-v1",providerAssetId:"wrapped-ether",chain:"eip155:1",contractAddress:"0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",quoteCurrency:"USD",metricKind:"REPORTED_CIRCULATING_MARKET_CAP" as const,reportedValueBasis:"PROVIDER_CALCULATED_CIRCULATING" as const,valueAtoms:"123",supplyTimestamp:t,quoteTimestamp:t,effectiveAsOf:t,now:t,mappingAuthority:null}; expect(projectM5ReportedCirculatingMarketCap(base)).toBeNull();});
});
