import { describe, expect, it } from "vitest";
import { formFromPreferences, minorUnitsFromMajorInput, NOTIFICATION_CATEGORIES, preferencesBodyFromForm, unsavedNotificationForm } from "@/domain/notifications/preferences-ui";
import { detectPushState } from "@/components/notification-controls";

describe("notification preference UI contract", () => {
  it("provides editable unsaved defaults for a null GET", () => { const form = unsavedNotificationForm(); expect(form.currency).toBe("NOK"); expect(form.quietHoursEnabled).toBe(true); expect(form.pnlMilestoneThresholdMajor).toBe("1000.00"); expect(form.enabledCategories).toEqual(NOTIFICATION_CATEGORIES); });
  it("populates exact persisted values", () => { expect(formFromPreferences({ enabledCategories: ["RISK_BLOCKED"], pnlMilestoneThresholdMinor: "100000", currency: "EUR", quietHoursEnabled: false, quietHoursStart: "01:02", quietHoursEnd: "03:04", timezone: "UTC", maxNonCriticalPerHour: 7 })).toEqual({ enabledCategories: ["RISK_BLOCKED"], pnlMilestoneThresholdMajor: "1000.00", currency: "EUR", quietHoursEnabled: false, quietHoursStart: "01:02", quietHoursEnd: "03:04", timezone: "UTC", maxNonCriticalPerHour: "7" }); });
  it("converts exact major-unit strings to integer minor units", () => { expect(minorUnitsFromMajorInput("1000.00")).toBe("100000"); expect(minorUnitsFromMajorInput("1.2")).toBe("120"); });
  it("rejects malformed, negative, zero, and excessive-decimal thresholds", () => { for (const value of ["0", "-1.00", "1.234", "abc", ""]) expect(() => minorUnitsFromMajorInput(value)).toThrow("INVALID_PNL_THRESHOLD_INPUT"); });
  it("builds a valid PUT body with categories and quiet-hour settings", () => { expect(preferencesBodyFromForm({ enabledCategories: ["SIMULATION_FILL", "SYSTEM_CRITICAL"], pnlMilestoneThresholdMajor: "1000.00", currency: "nok", quietHoursEnabled: true, quietHoursStart: "22:00", quietHoursEnd: "07:00", timezone: "Europe/Oslo", maxNonCriticalPerHour: "10" })).toEqual({ enabledCategories: ["SIMULATION_FILL", "SYSTEM_CRITICAL"], pnlMilestoneThresholdMinor: "100000", currency: "NOK", quietHoursEnabled: true, quietHoursStart: "22:00", quietHoursEnd: "07:00", timezone: "Europe/Oslo", maxNonCriticalPerHour: 10 }); });
  it("uses the actual PushManager subscription state", async () => { const getSubscription = async () => null; const notification = { permission: "granted" }; Object.defineProperty(globalThis, "window", { configurable: true, value: { PushManager: class {}, Notification: notification } }); Object.defineProperty(globalThis, "navigator", { configurable: true, value: { serviceWorker: { getRegistration: async () => ({ pushManager: { getSubscription } }) } } }); Object.defineProperty(globalThis, "Notification", { configurable: true, value: notification }); expect(await detectPushState()).toBe("NOT_SUBSCRIBED"); });
});
