import { currencyScale } from "@/domain/financial/currency";
import { formatMoney, money } from "@/domain/financial/money";
import type { PortfolioProjection } from "@/domain/portfolio/portfolio-projection";

function decimal(atoms: string, scale: number) {
  const value = BigInt(atoms); const negative = value < 0n;
  const digits = (negative ? -value : value).toString().padStart(scale + 1, "0");
  return `${negative ? "−" : ""}${scale ? `${digits.slice(0, -scale)}.${digits.slice(-scale)}` : digits}`;
}

/** Server-rendered, read-only presentation of the sanitized projection. */
export function PortfolioView({ portfolio: p }: { portfolio: PortfolioProjection }) {
  const amount = (value: string | null) => value === null ? "Unavailable" : formatMoney(money(p.baseCurrency, BigInt(value)));
  const cards = [["Net asset value", p.nav], ["Cash", p.cash], ["Invested", p.investedMarketValue], ["Unrealized P&L", p.unrealizedPnl]] as const;
  return <section aria-label="Portfolio valuation" className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3 border-b border-[var(--border)] pb-5">
      <div><p className="text-xs uppercase tracking-widest text-[var(--muted)]">Portfolio overview</p><h2 className="mt-2 text-2xl font-semibold">Your simulated portfolio</h2></div>
      <span className={`rounded-full border px-3 py-1 text-xs font-semibold ${p.valuationStatus === "COMPLETE" ? "border-[var(--border)] text-[var(--accent)]" : "border-amber-500/50 text-amber-200"}`}>{p.valuationStatus === "COMPLETE" ? "Complete valuation" : "Incomplete valuation"}</span>
    </div>
    {p.valuationStatus === "INCOMPLETE" && <div role="status" className="rounded-xl border border-amber-500/40 bg-amber-500/10 p-4 text-sm text-amber-100"><p className="font-semibold">Some portfolio values are unavailable.</p><p className="mt-1">Cash and verified individual values remain visible. Totals requiring missing or inconsistent evidence are withheld.</p><ul className="mt-2 list-inside list-disc">{p.violations.map(code => <li key={code}>{code.replaceAll("_", " ").toLowerCase()}</li>)}</ul></div>}
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value]) => <article key={label} className="rounded-2xl border border-[var(--border)] bg-[var(--panel)] p-6"><h3 className="text-sm text-[var(--muted)]">{label}</h3><p className={`mt-4 break-words text-2xl font-semibold tabular-nums ${label === "Unrealized P&L" && value !== null && BigInt(value) < 0n ? "text-rose-200" : ""}`}>{amount(value)}</p><p className="mt-2 text-xs text-[var(--muted)]">{label === "Cash" ? "From the cash ledger" : label === "Unrealized P&L" ? "Includes acquisition fees" : label === "Invested" ? "Eligible fixture prices" : "Cash plus valued holdings"}</p></article>)}</div>
    <div className="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--panel)]"><div className="flex items-center justify-between gap-4 border-b border-[var(--border)] px-6 py-5"><h3 className="font-semibold">Holdings</h3><span className="text-xs text-[var(--muted)]">{p.holdings.length} assets · {p.baseCurrency}</span></div>
      {p.holdings.length === 0 ? <div className="px-6 py-12 text-center"><p>No asset holdings at this time.</p><p className="mt-2 text-sm text-[var(--muted)]">Available cash remains part of your portfolio value.</p></div> : <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Ledger-derived holdings valued at eligible fixture prices</caption><thead className="text-xs text-[var(--muted)]"><tr>{["Asset", "Quantity", "Market price", "Market value", "Cost basis", "Unrealized P&L", "Portfolio weight"].map(h => <th scope="col" className="whitespace-nowrap px-5 py-4 font-medium" key={h}>{h}</th>)}</tr></thead><tbody className="divide-y divide-[var(--border)]">{p.holdings.map(h => <tr key={h.assetId}><th scope="row" className="px-5 py-5 font-medium">{h.code}<span className="mt-1 block text-xs font-normal text-[var(--muted)]">Synthetic fixture</span></th><td className="whitespace-nowrap px-5 py-5 tabular-nums">{h.quantityScale === null ? "Unknown scale" : decimal(h.quantityAtoms, h.quantityScale)}</td><td className="whitespace-nowrap px-5 py-5 tabular-nums">{h.selectedPrice ? `${decimal(h.selectedPrice.priceAtoms, h.selectedPrice.priceScale + currencyScale(p.baseCurrency))} ${p.baseCurrency}` : "Unavailable"}</td><td className="whitespace-nowrap px-5 py-5 tabular-nums">{amount(h.marketValueMinor)}</td><td className="whitespace-nowrap px-5 py-5 tabular-nums">{amount(h.openCostBasisMinor)}</td><td className="whitespace-nowrap px-5 py-5 tabular-nums">{amount(h.unrealizedPnlMinor)}</td><td className="whitespace-nowrap px-5 py-5 tabular-nums">{h.portfolioWeightBps === null ? "—" : `${decimal(h.portfolioWeightBps, 2)}%`}</td></tr>)}</tbody></table></div>}
      <div className="flex flex-wrap gap-x-8 gap-y-2 border-t border-[var(--border)] px-6 py-4 text-xs text-[var(--muted)]"><span>Cash weight: {p.cashWeightBps === null ? "Not applicable" : `${decimal(p.cashWeightBps, 2)}%`}</span><span>Weight rounding residue: {p.allocationRoundingResidueBps === null ? "Not applicable" : `${p.allocationRoundingResidueBps} bps`}</span></div>
    </div>
    <details className="rounded-xl border border-[var(--border)] px-5 py-4 text-sm text-[var(--muted)]"><summary className="cursor-pointer text-[var(--foreground)]">Valuation evidence</summary><dl className="mt-4 grid gap-3 text-xs sm:grid-cols-2"><div><dt>As of (UTC)</dt><dd className="mt-1 text-[var(--foreground)]"><time dateTime={p.asOf}>{p.asOf}</time></dd></div><div><dt>Price dataset</dt><dd className="mt-1">{p.versions.dataset}</dd></div><div><dt>Calculation policies</dt><dd className="mt-1">{p.versions.projection} · {p.versions.valuation} · {p.versions.fifo}</dd></div><div><dt>Source fingerprint</dt><dd className="mt-1 break-all font-mono">{p.provenance.sourceHash}</dd></div></dl><ul className="mt-4 space-y-2 text-xs">{p.holdings.filter(h => h.selectedPrice).map(h => <li key={h.assetId} className="break-all">{h.code}: price {h.selectedPrice!.recordId}, available {h.selectedPrice!.availableAt}; {h.lots.length} open acquisition lots.</li>)}</ul></details>
  </section>;
}
