import "server-only";
import postgres, { type Sql, type TransactionSql } from "postgres";
import type { CanonicalHighInterestEvidence } from "@/domain/notifications/high-interest-source";
import { assertCanonicalM4Record, assertCanonicalM5Record, joinCanonicalHighInterestEvidence, type CanonicalM4AnalysisRecord, type CanonicalM5EligibilityRecord } from "@/domain/intelligence/canonical-evidence";

type DbClient = Sql | TransactionSql;
const connection=()=>{const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_UNCONFIGURED");return postgres(url,{max:1,prepare:true,ssl:"require"});};
const json=(value:unknown)=>JSON.stringify(value,(_,item)=>item instanceof Date?item.toISOString():typeof item==="bigint"?item.toString():item);
const array=(value:unknown):string[]=>Array.isArray(value)?value.map(String):[];
const object=(value:unknown):Record<string,unknown>=>value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};

async function saveM4(client:DbClient,record:CanonicalM4AnalysisRecord){assertCanonicalM4Record(record);const inserted=await client`insert into public.canonical_m4_analysis_snapshots (analysis_id,candidate_id,canonical_identifier,asset_class,canonical_context_id,as_of,available_at,engine_version,feature_set_version,trend_policy_version,acceleration_version,dataset_pins,input_evidence_ids,trend,corroboration_provider_ids,corroboration_evidence_ids,distinct_provider_count,suspicious_flags,integrity_status,config_hash,fingerprint) values (${record.analysisId},${record.candidateId},${record.canonicalIdentifier},${record.assetClass},${record.canonicalContextId},${record.asOf},${record.availableAt},${record.engineVersion},${record.featureSetVersion},${record.trendPolicyVersion},${record.accelerationVersion},${json(record.datasetPins)}::jsonb,${json(record.inputEvidenceIds)}::jsonb,${json(record.trend)}::jsonb,${json(record.corroborationProviderIds)}::jsonb,${json(record.corroborationEvidenceIds)}::jsonb,${record.distinctProviderCount},${json(record.suspiciousFlags)}::jsonb,${record.integrityStatus},${record.configHash},${record.fingerprint}) on conflict (analysis_id) do nothing returning analysis_id`;if(!inserted.length){const existing=await client`select fingerprint from public.canonical_m4_analysis_snapshots where analysis_id=${record.analysisId}`;if(String(existing[0]?.fingerprint)!==record.fingerprint)throw new Error("CANONICAL_EVIDENCE_CONFLICT");}}
async function saveM5(client:DbClient,record:CanonicalM5EligibilityRecord){assertCanonicalM5Record(record);const inserted=await client`insert into public.canonical_m5_eligibility_evaluations (evaluation_id,candidate_id,canonical_identifier,asset_class,canonical_context_id,as_of,available_at,policy_version,profile_version,status,checks,reason_codes,evidence_ids,suspicious_flags,suspicious_evidence_status,dataset_pins,assembly_fingerprint,fingerprint) values (${record.evaluationId},${record.candidateId},${record.canonicalIdentifier},${record.assetClass},${record.canonicalContextId},${record.asOf},${record.availableAt},${record.policyVersion},${record.profileVersion},${record.status},${json(record.checks)}::jsonb,${json(record.reasonCodes)}::jsonb,${json(record.evidenceIds)}::jsonb,${json(record.suspiciousFlags)}::jsonb,${record.suspiciousEvidenceStatus},${json(record.datasetPins)}::jsonb,${record.assemblyFingerprint},${record.fingerprint}) on conflict (evaluation_id) do nothing returning evaluation_id`;if(!inserted.length){const existing=await client`select fingerprint from public.canonical_m5_eligibility_evaluations where evaluation_id=${record.evaluationId}`;if(String(existing[0]?.fingerprint)!==record.fingerprint)throw new Error("CANONICAL_EVIDENCE_CONFLICT");}}

async function readEvidence(client:DbClient,asOf:Date):Promise<readonly CanonicalHighInterestEvidence[]>{const rows=await client`with pairs as (select m4.analysis_id,m4.candidate_id,m4.canonical_identifier,m4.asset_class,m4.canonical_context_id,m4.as_of,m4.available_at,m4.engine_version,m4.feature_set_version,m4.trend_policy_version,m4.acceleration_version,m4.dataset_pins,m4.input_evidence_ids,m4.trend,m4.corroboration_provider_ids,m4.corroboration_evidence_ids,m4.distinct_provider_count,m4.suspicious_flags,m4.integrity_status,m4.config_hash,m4.fingerprint,m5.evaluation_id,m5.as_of as m5_as_of,m5.available_at as m5_available_at,m5.policy_version,m5.profile_version,m5.status as m5_status,m5.checks as m5_checks,m5.reason_codes as m5_reason_codes,m5.evidence_ids as m5_evidence_ids,m5.suspicious_flags as m5_suspicious_flags,m5.suspicious_evidence_status,m5.dataset_pins as m5_dataset_pins,m5.assembly_fingerprint as m5_assembly_fingerprint,m5.fingerprint as m5_fingerprint from public.canonical_m4_analysis_snapshots m4 join public.canonical_m5_eligibility_evaluations m5 on m5.candidate_id=m4.candidate_id and m5.canonical_identifier=m4.canonical_identifier and m5.asset_class=m4.asset_class and m5.canonical_context_id=m4.canonical_context_id and m5.as_of=m4.as_of where m4.as_of<=${asOf} and m4.available_at<=${asOf} and m5.as_of<=${asOf} and m5.available_at<=${asOf}), ranked as (select pairs.*,row_number() over(partition by candidate_id,canonical_identifier,asset_class order by as_of desc,available_at desc,m5_available_at desc,analysis_id desc,evaluation_id desc) as pair_rank from pairs where integrity_status='COMPLETE' and m5_status='ELIGIBLE' and suspicious_evidence_status='CLEAN') select * from ranked where pair_rank=1 order by candidate_id,canonical_identifier,analysis_id,evaluation_id`;
 const m4:CanonicalM4AnalysisRecord[]=[];const m5:CanonicalM5EligibilityRecord[]=[];for(const row of rows){const trend=object(row.trend);const canonicalContextId=typeof row.canonical_context_id==="string"?row.canonical_context_id:"";const a:CanonicalM4AnalysisRecord={analysisId:String(row.analysis_id),candidateId:String(row.candidate_id),canonicalIdentifier:String(row.canonical_identifier),assetClass:String(row.asset_class),canonicalContextId,asOf:new Date(String(row.as_of)),availableAt:new Date(String(row.available_at)),engineVersion:String(row.engine_version),featureSetVersion:String(row.feature_set_version),trendPolicyVersion:String(row.trend_policy_version),accelerationVersion:String(row.acceleration_version),datasetPins:array(row.dataset_pins),inputEvidenceIds:array(row.input_evidence_ids),trend:{status:String(trend.status) as CanonicalM4AnalysisRecord["trend"]["status"],direction:trend.direction===null?null:String(trend.direction) as CanonicalM4AnalysisRecord["trend"]["direction"],signedChangeBps:trend.signedChangeBps===null?null:String(trend.signedChangeBps),accelerationStatus:String(trend.accelerationStatus) as CanonicalM4AnalysisRecord["trend"]["accelerationStatus"],accelerationBps:trend.accelerationBps===null?null:String(trend.accelerationBps),observationIds:array(trend.observationIds),previousWindowObservationIds:array(trend.previousWindowObservationIds),currentWindowObservationIds:array(trend.currentWindowObservationIds)},corroborationProviderIds:array(row.corroboration_provider_ids),corroborationEvidenceIds:array(row.corroboration_evidence_ids),distinctProviderCount:Number(row.distinct_provider_count),suspiciousFlags:array(row.suspicious_flags),integrityStatus:String(row.integrity_status) as CanonicalM4AnalysisRecord["integrityStatus"],configHash:String(row.config_hash),fingerprint:String(row.fingerprint)};const e:CanonicalM5EligibilityRecord={evaluationId:String(row.evaluation_id),candidateId:a.candidateId,canonicalIdentifier:a.canonicalIdentifier,assetClass:a.assetClass,canonicalContextId,asOf:new Date(String(row.m5_as_of)),availableAt:new Date(String(row.m5_available_at)),policyVersion:String(row.policy_version),profileVersion:String(row.profile_version),status:String(row.m5_status) as CanonicalM5EligibilityRecord["status"],checks:Array.isArray(row.m5_checks)?row.m5_checks:[],reasonCodes:array(row.m5_reason_codes),evidenceIds:array(row.m5_evidence_ids),suspiciousFlags:array(row.m5_suspicious_flags),suspiciousEvidenceStatus:String(row.suspicious_evidence_status) as CanonicalM5EligibilityRecord["suspiciousEvidenceStatus"],datasetPins:array(row.m5_dataset_pins),assemblyFingerprint:typeof row.m5_assembly_fingerprint==="string"?row.m5_assembly_fingerprint:"",fingerprint:String(row.m5_fingerprint)};try{assertCanonicalM4Record(a);assertCanonicalM5Record(e);m4.push(a);m5.push(e);}catch{ /* Invalid immutable source is excluded fail-closed. */}}
 const joined=joinCanonicalHighInterestEvidence(m4,m5,asOf);return joined.map(item=>({candidateId:item.candidateId,assetDisplayIdentifier:item.canonicalIdentifier,assetClass:item.assetClass,eligibilityStatus:item.m5.status,trendStatus:item.trend.status==="COMPLETE"?"COMPLETE":"INCOMPLETE",trendDirection:item.trend.direction,signedChangeBps:item.trend.signedChangeBps===null?null:BigInt(item.trend.signedChangeBps),accelerationStatus:item.trend.accelerationStatus==="COMPLETE"?"COMPLETE":"INCOMPLETE",accelerationBps:item.trend.accelerationBps===null?null:BigInt(item.trend.accelerationBps),distinctProviderCount:item.distinctProviderCount,suspiciousFlags:[...new Set([...item.suspiciousFlags,...item.m5.suspiciousFlags])],asOf:item.asOf,availableAt:item.availableAt,m4DatasetPins:item.datasetPins,m5DatasetPins:item.m5.datasetPins,evidenceIds:[...new Set([...item.inputEvidenceIds,...item.m5.evidenceIds])] }));}

export interface CanonicalEvidenceRepository{readonly saveM4Analysis:(record:CanonicalM4AnalysisRecord)=>Promise<void>;readonly saveM5Eligibility:(record:CanonicalM5EligibilityRecord)=>Promise<void>;readonly readHighInterestEvidence:(asOf:Date)=>Promise<readonly CanonicalHighInterestEvidence[]>;}
export async function withCanonicalEvidenceTransaction<T>(work:(repository:CanonicalEvidenceRepository)=>Promise<T>):Promise<T>{const sql=connection();try{return await sql.begin(async transaction=>work({saveM4Analysis:record=>saveM4(transaction,record),saveM5Eligibility:record=>saveM5(transaction,record),readHighInterestEvidence:asOf=>readEvidence(transaction,asOf)})) as unknown as T;}finally{await sql.end({timeout:5});}}
export async function saveCanonicalM4Analysis(record:CanonicalM4AnalysisRecord){const sql=connection();try{await saveM4(sql,record);}finally{await sql.end({timeout:5});}}
export async function saveCanonicalM5Eligibility(record:CanonicalM5EligibilityRecord){const sql=connection();try{await saveM5(sql,record);}finally{await sql.end({timeout:5});}}
export async function readCanonicalHighInterestEvidence(_adminUserId:string,asOf:Date){const sql=connection();try{return await readEvidence(sql,asOf);}finally{await sql.end({timeout:5});}}
