import type { Sql, TransactionSql } from "postgres";
import { assertM5MarketMetricsAuthority, createM5MarketMetricsAuthority, type M5MarketMetricsAuthorityAggregate, type MarketSourceMaterial } from "@/domain/intelligence/m5-market-metrics-authority";
import type { M5MarketMetricsEvidenceUnitOfWork } from "@/application/intelligence/m5-market-metrics-evidence";
import type { M5MarketMetricsAuthorityPersistenceRepositories, M5MarketMetricsAuthorityPersistenceUnitOfWork } from "@/application/intelligence/m5-market-metrics-authority-persistence";
import { createSourceLineageRepository } from "./source-lineage-repository";
import { createProviderAssetIdentityReadRepository } from "./provider-asset-identity-repository";
import { createAssetMappingRevisionRepository } from "./asset-mapping-revision-repository";
import { createRawEligibilityEvidenceRepository } from "./eligibility-evidence-repository";

const text = (v: unknown, code: string): string => { if (typeof v !== "string" || !v) throw new Error(code); return v; };
const time = (v: unknown, code: string): string => { const s = v instanceof Date ? v.toISOString() : text(v, code); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(s)) throw new Error(code); return s; };
const bigintValue = (v: unknown, code: string): bigint => { const s = String(v); if (!/^(0|[1-9][0-9]*)$/.test(s)) throw new Error(code); return BigInt(s); };
const arr = (v: unknown, code: string): string[] => { if (!Array.isArray(v) || v.some(x => typeof x !== "string")) throw new Error(code); return v; };

function mapAggregate(parent: Record<string, unknown>, materials: readonly Record<string, unknown>[], derivations: readonly Record<string, unknown>[]): M5MarketMetricsAuthorityAggregate {
  const materialRows: MarketSourceMaterial[] = materials.map(row => ({ metricKind: text(row.metric_kind, "M5_MARKET_REPOSITORY_MATERIAL_INVALID") as MarketSourceMaterial["metricKind"], sourceArtifactId: text(row.source_artifact_id, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), sourceEnvelopeId: text(row.source_envelope_id, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), sourceObservationId: text(row.source_observation_id, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), providerExternalRecordId: text(row.provider_external_record_id, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), payloadFingerprint: text(row.payload_fingerprint, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), valueAtoms: bigintValue(row.value_atoms, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), scale: Number(row.source_scale), quoteCurrency: text(row.quote_currency, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), observedAt: time(row.observed_at, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), availableAt: time(row.available_at, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), basis: text(row.basis, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), ...(row.window_start_at ? { windowStart: time(row.window_start_at, "M5_MARKET_REPOSITORY_MATERIAL_INVALID") } : {}), ...(row.window_end_at ? { windowEnd: time(row.window_end_at, "M5_MARKET_REPOSITORY_MATERIAL_INVALID") } : {}), ...(row.coverage_version ? { coverageVersion: text(row.coverage_version, "M5_MARKET_REPOSITORY_MATERIAL_INVALID") } : {}), ...(row.component_ids ? { componentIds: arr(row.component_ids, "M5_MARKET_REPOSITORY_MATERIAL_INVALID") } : {}), ...(row.components ? { components: (Array.isArray(row.components) ? row.components : []).map((c: Record<string, unknown>) => ({ id: text(c.id, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), valueAtoms: bigintValue(c.valueAtoms, "M5_MARKET_REPOSITORY_MATERIAL_INVALID"), scale: Number(c.scale), quoteCurrency: text(c.quoteCurrency, "M5_MARKET_REPOSITORY_MATERIAL_INVALID") })) } : {}) }));
  const rebuilt = createM5MarketMetricsAuthority({ providerId: text(parent.provider_id, "M5_MARKET_REPOSITORY_PARENT_INVALID"), datasetId: text(parent.dataset_id, "M5_MARKET_REPOSITORY_PARENT_INVALID"), datasetVersion: text(parent.dataset_version, "M5_MARKET_REPOSITORY_PARENT_INVALID"), sourceLineageId: text(parent.source_lineage_id, "M5_MARKET_REPOSITORY_PARENT_INVALID"), asOf: time(parent.as_of, "M5_MARKET_REPOSITORY_PARENT_INVALID"), quoteCurrency: text(parent.quote_currency, "M5_MARKET_REPOSITORY_PARENT_INVALID"), materials: materialRows, recordedAt: time(parent.recorded_at, "M5_MARKET_REPOSITORY_PARENT_INVALID") });
  if (rebuilt.status !== "READY" || rebuilt.authority.authorityId !== text(parent.authority_id, "M5_MARKET_REPOSITORY_PARENT_INVALID") || rebuilt.authority.fingerprint !== text(parent.fingerprint, "M5_MARKET_REPOSITORY_PARENT_INVALID")) throw new Error("M5_MARKET_REPOSITORY_PARENT_FINGERPRINT_INVALID");
  if (derivations.length !== 3) throw new Error("M5_MARKET_REPOSITORY_SEALED_SET_INVALID");
  const byMetric = new Map(derivations.map(row => [text(row.metric_kind, "M5_MARKET_REPOSITORY_DERIVATION_INVALID"), row]));
  if (byMetric.size !== 3) throw new Error("M5_MARKET_REPOSITORY_SEALED_SET_INVALID");
  for (const derivation of rebuilt.derivations) {
    const row = byMetric.get(derivation.metricKind);
    if (!row || text(row.fingerprint, "M5_MARKET_REPOSITORY_DERIVATION_INVALID") !== derivation.fingerprint || bigintValue(row.value_atoms, "M5_MARKET_REPOSITORY_DERIVATION_INVALID") !== derivation.valueAtoms || text(row.authority_id, "M5_MARKET_REPOSITORY_DERIVATION_INVALID") !== derivation.authorityId) throw new Error("M5_MARKET_REPOSITORY_DERIVATION_INVALID");
  }
  assertM5MarketMetricsAuthority(rebuilt.authority);
  return freezeAggregate({ authority: rebuilt.authority, derivations: rebuilt.derivations });
}
const freezeAggregate = (v: M5MarketMetricsAuthorityAggregate): M5MarketMetricsAuthorityAggregate => Object.freeze({ authority: v.authority, derivations: Object.freeze([...v.derivations]) as M5MarketMetricsAuthorityAggregate["derivations"] });

export function createM5MarketMetricsAuthorityTransactionRepository(client: TransactionSql) {
  const readById = async (id: string): Promise<M5MarketMetricsAuthorityAggregate | undefined> => {
    const p = await client`select * from public.intelligence_m5_market_metric_authorities where authority_id=${id} for update`; if (!p.length) return undefined;
    const m = await client`select * from public.intelligence_m5_market_metric_materials where authority_id=${id} order by material_ordinal`;
    const d = await client`select * from public.intelligence_m5_market_metric_derivations where authority_id=${id} order by metric_kind`;
    return mapAggregate(p[0] as Record<string, unknown>, m as Record<string, unknown>[], d as Record<string, unknown>[]);
  };
  const save = async (aggregate: M5MarketMetricsAuthorityAggregate): Promise<M5MarketMetricsAuthorityAggregate> => {
    const a = aggregate.authority;
    const inserted = await client`insert into public.intelligence_m5_market_metric_authorities (authority_id,contract_version,provider_id,dataset_id,dataset_version,source_lineage_id,as_of,quote_currency,currency_minor_unit_policy,market_cap_basis,volume_window_basis,liquidity_coverage_basis,material_ids,derivation_ids,derivation_fingerprints,observed_at,effective_available_at,fingerprint,recorded_at) values (${a.authorityId},${a.contractVersion},${a.providerId},${a.datasetId},${a.datasetVersion},${a.sourceLineageId},${a.asOf},${a.quoteCurrency},${a.currencyMinorUnitPolicy},${a.marketCapBasis},${a.volumeWindowBasis},${a.liquidityCoverageBasis},${client.json(a.materials.map(m=>m.sourceObservationId))},${client.json(a.derivations.map(d=>d.metricKind))},${client.json(a.derivations.map(d=>d.fingerprint))},${a.observedAt},${a.effectiveAvailableAt},${a.fingerprint},${a.recordedAt}) on conflict (authority_id) do nothing returning authority_id`;
    if (inserted.length) for (const [ordinal, m] of a.materials.entries()) await client`insert into public.intelligence_m5_market_metric_materials (authority_id,material_ordinal,metric_kind,source_artifact_id,source_envelope_id,source_observation_id,provider_external_record_id,payload_fingerprint,value_atoms,source_scale,quote_currency,observed_at,available_at,basis,window_start_at,window_end_at,coverage_version,component_ids,components) values (${a.authorityId},${ordinal},${m.metricKind},${m.sourceArtifactId},${m.sourceEnvelopeId},${m.sourceObservationId},${m.providerExternalRecordId},${m.payloadFingerprint},${m.valueAtoms.toString()},${m.scale},${m.quoteCurrency},${m.observedAt},${m.availableAt},${m.basis},${m.windowStart ?? null},${m.windowEnd ?? null},${m.coverageVersion ?? null},${m.componentIds ? client.json(m.componentIds) : null},${m.components ? client.json(m.components.map(c => ({ id: c.id, valueAtoms: c.valueAtoms.toString(), scale: c.scale, quoteCurrency: c.quoteCurrency }))) : null}) on conflict do nothing`;
    if (inserted.length) for (const d of a.derivations) await client`insert into public.intelligence_m5_market_metric_derivations (authority_id,metric_kind,derivation_version,value_atoms,unit,scale,quote_currency,basis,window_start_at,window_end_at,coverage_version,material_ids,material_fingerprints,observed_at,available_at,as_of,fingerprint) values (${a.authorityId},${d.metricKind},${"m5-market-metrics-authority/v1"},${d.valueAtoms.toString()},${d.unit},${d.scale},${d.quoteCurrency},${d.basis},${d.windowStart ?? null},${d.windowEnd ?? null},${d.coverageVersion ?? null},${client.json(d.materialIds)},${client.json(d.materialFingerprints)},${d.observedAt},${d.availableAt},${d.asOf},${d.fingerprint}) on conflict do nothing`;
    const reread = await readById(a.authorityId); if (!reread) throw new Error("M5_MARKET_REPOSITORY_REREAD_MISSING"); return reread;
  };
  return { readById, save };
}

export function createM5MarketMetricsEvidenceUnitOfWork(sql: Sql): M5MarketMetricsEvidenceUnitOfWork {
  return { withTransaction: <T>(work: Parameters<M5MarketMetricsEvidenceUnitOfWork["withTransaction"]>[0]) => sql.begin(async tx => { const lineage = createSourceLineageRepository(tx); const assertion = createProviderAssetIdentityReadRepository(tx); const mappingBase = createAssetMappingRevisionRepository(tx, lineage, assertion); const mapping = { readById: async (id: string) => mappingBase.readById ? mappingBase.readById(id) : undefined }; const evidence = createRawEligibilityEvidenceRepository(tx, mapping, lineage); const market = createM5MarketMetricsAuthorityTransactionRepository(tx); return work({ mapping, lineage, assertion, market, evidence }); }) as unknown as Promise<T> };
}

export function createM5MarketMetricsAuthorityPersistenceUnitOfWork(sql: Sql): M5MarketMetricsAuthorityPersistenceUnitOfWork {
  return { withTransaction: <T>(work: (repositories: M5MarketMetricsAuthorityPersistenceRepositories) => Promise<T>) => sql.begin(async tx => work(Object.freeze({ sourceLineage: createSourceLineageRepository(tx), market: createM5MarketMetricsAuthorityTransactionRepository(tx) }))) as unknown as Promise<T> };
}
