/* eslint-disable @typescript-eslint/no-explicit-any */
import "server-only";
import type { Sql, TransactionSql } from "postgres";
import { createM5SuspiciousRuleSetAuthority, M5_SUSPICIOUS_RULE_SET_AUTHORITY_CONTRACT_VERSION, type M5SuspiciousRuleSetAuthority } from "@/domain/intelligence/m5-suspicious-rule-set";
import { canonicalSha256 } from "@/domain/intelligence/ingestion-provenance";
import { assertM5SuspiciousCoverageAuthority, type M5SuspiciousCoverageAuthority } from "@/domain/intelligence/m5-suspicious-coverage";
import type { M5SuspiciousCoveragePersistenceUnitOfWork } from "@/application/intelligence/m5-suspicious-coverage-persistence";

type Row = Record<string, unknown>;
const text = (value: unknown, code: string): string => { if (typeof value !== "string" || !value.trim()) throw new Error(code); return value; };
const json = <T>(value: unknown, code: string): T => { try { return (typeof value === "string" ? JSON.parse(value) : value) as T; } catch { throw new Error(code); } };
const strings = (value: unknown, code: string): readonly string[] => { const parsed = json<unknown>(value, code); if (!Array.isArray(parsed) || parsed.some(item => typeof item !== "string")) throw new Error(code); return Object.freeze(parsed as string[]); };
const time = (value: unknown, code: string): string => { const out = value instanceof Date ? value.toISOString() : text(value, code); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(out)) throw new Error(code); return out; };

function mapRuleSet(row: Row, rows: readonly Row[]): M5SuspiciousRuleSetAuthority {
  const rules = [...rows].sort((a, b) => Number(a.rule_ordinal) - Number(b.rule_ordinal)).map(rule => {
    const material = json<Record<string, unknown>>(rule.rule_material, "M5_RULE_ROW_INVALID");
    const value = { ruleId: text(rule.rule_id, "M5_RULE_ROW_INVALID"), contractVersion: text(rule.rule_contract_version, "M5_RULE_ROW_INVALID"), enabled: rule.enabled === true, required: rule.required === true, supportedAssetClasses: strings(material.supportedAssetClasses ?? [], "M5_RULE_ROW_INVALID"), inputRequirements: strings(material.inputRequirements ?? [], "M5_RULE_ROW_INVALID"), configuration: (material.configuration ?? {}) as Record<string, unknown>, evaluatorVersion: text(material.evaluatorVersion, "M5_RULE_ROW_INVALID"), fingerprint: text(rule.rule_fingerprint, "M5_RULE_ROW_INVALID") };
    const expected = canonicalSha256({ ...value, fingerprint: undefined });
    if (value.fingerprint !== expected) throw new Error("M5_RULE_ROW_FINGERPRINT_INVALID");
    return value;
  });
  return createM5SuspiciousRuleSetAuthority({ contractVersion: "m5-suspicious-rule-set-authority/v1", ruleSetVersion: text(row.rule_set_version, "M5_RULE_SET_ROW_INVALID"), providerId: text(row.provider_id, "M5_RULE_SET_ROW_INVALID"), datasetId: text(row.dataset_id, "M5_RULE_SET_ROW_INVALID"), datasetVersion: text(row.dataset_version, "M5_RULE_SET_ROW_INVALID"), detectorVersion: text(row.detector_version, "M5_RULE_SET_ROW_INVALID"), requiredRuleIds: rules.filter(rule => rule.required && rule.enabled).map(rule => rule.ruleId), ruleSetAuthorityId: text(row.rule_set_authority_id, "M5_RULE_SET_ROW_INVALID"), rules, fingerprint: text(row.rule_set_fingerprint, "M5_RULE_SET_ROW_INVALID") });
}
function mapCoverage(row: Row): M5SuspiciousCoverageAuthority {
  const record = { contractVersion: "m5-suspicious-coverage-authority/v1" as const, coverageAuthorityId: text(row.coverage_authority_id, "M5_COVERAGE_ROW_INVALID"), ruleSetAuthorityId: text(row.rule_set_authority_id, "M5_COVERAGE_ROW_INVALID"), ruleSetFingerprint: text(row.rule_set_fingerprint, "M5_COVERAGE_ROW_INVALID"), providerId: text(row.provider_id, "M5_COVERAGE_ROW_INVALID"), datasetId: text(row.dataset_id, "M5_COVERAGE_ROW_INVALID"), datasetVersion: text(row.dataset_version, "M5_COVERAGE_ROW_INVALID"), mappingRevisionId: text(row.mapping_revision_id, "M5_COVERAGE_ROW_INVALID"), providerAssetIdentityAssertionId: text(row.provider_asset_identity_assertion_id, "M5_COVERAGE_ROW_INVALID"), sourceLineageId: text(row.source_lineage_id, "M5_COVERAGE_ROW_INVALID"), sourceLineageFingerprint: text(row.source_lineage_fingerprint, "M5_COVERAGE_ROW_INVALID"), candidateId: text(row.candidate_id, "M5_COVERAGE_ROW_INVALID"), assetId: text(row.asset_id, "M5_COVERAGE_ROW_INVALID"), canonicalIdentifier: text(row.canonical_identifier, "M5_COVERAGE_ROW_INVALID"), assetClass: text(row.asset_class, "M5_COVERAGE_ROW_INVALID"), asOf: time(row.as_of, "M5_COVERAGE_ROW_INVALID"), requiredRuleIds: strings(row.required_rule_ids, "M5_COVERAGE_ROW_INVALID"), evaluatedRuleIds: strings(row.evaluated_rule_ids, "M5_COVERAGE_ROW_INVALID"), materials: json(row.source_materials, "M5_COVERAGE_ROW_INVALID"), status: text(row.coverage_status, "M5_COVERAGE_ROW_INVALID") as M5SuspiciousCoverageAuthority["status"], observedAt: time(row.observed_at, "M5_COVERAGE_ROW_INVALID"), availableAt: time(row.available_at, "M5_COVERAGE_ROW_INVALID"), fingerprint: text(row.coverage_fingerprint, "M5_COVERAGE_ROW_INVALID"), recordedAt: time(row.recorded_at, "M5_COVERAGE_ROW_INVALID") } as M5SuspiciousCoverageAuthority;
  assertM5SuspiciousCoverageAuthority(record); return record;
}
export function createM5SuspiciousCoverageRepositories(client: TransactionSql) {
  const ruleSets = { readById: async (id: string) => { const parents = await client`select * from public.m5_suspicious_rule_set_authorities where rule_set_authority_id=${id} for update`; if (!parents.length) return undefined; const rows = await client`select * from public.m5_suspicious_rule_set_rules where rule_set_authority_id=${id} order by rule_ordinal`; return mapRuleSet(parents[0] as Row, rows as Row[]); }, save: async (authority: M5SuspiciousRuleSetAuthority) => { const storedAuthority = authority.contractVersion === M5_SUSPICIOUS_RULE_SET_AUTHORITY_CONTRACT_VERSION ? authority : createM5SuspiciousRuleSetAuthority({ ...authority, contractVersion: M5_SUSPICIOUS_RULE_SET_AUTHORITY_CONTRACT_VERSION, fingerprint: undefined }); const inserted = await client`insert into public.m5_suspicious_rule_set_authorities (rule_set_authority_id,contract_version,rule_set_version,provider_id,dataset_id,dataset_version,detector_version,rule_count,rule_set_fingerprint,recorded_at) values (${storedAuthority.ruleSetAuthorityId},${M5_SUSPICIOUS_RULE_SET_AUTHORITY_CONTRACT_VERSION},${storedAuthority.ruleSetVersion},${storedAuthority.providerId},${storedAuthority.datasetId},${storedAuthority.datasetVersion},${storedAuthority.detectorVersion},${storedAuthority.ruleCount},${storedAuthority.fingerprint},${new Date().toISOString()}) on conflict (rule_set_authority_id) do nothing returning rule_set_authority_id`; if (inserted.length) for (const [ordinal, rule] of storedAuthority.rules.entries()) await client`insert into public.m5_suspicious_rule_set_rules (rule_set_authority_id,rule_ordinal,rule_id,rule_contract_version,enabled,required,rule_material,rule_fingerprint) values (${storedAuthority.ruleSetAuthorityId},${ordinal},${rule.ruleId},${rule.contractVersion},${rule.enabled},${rule.required},${client.json({ supportedAssetClasses: [...rule.supportedAssetClasses], inputRequirements: [...rule.inputRequirements], configuration: { ...rule.configuration }, evaluatorVersion: rule.evaluatorVersion } as any)},${rule.fingerprint}) on conflict do nothing`; const read = await ruleSets.readById(storedAuthority.ruleSetAuthorityId); if (!read || read.fingerprint !== storedAuthority.fingerprint) throw new Error("M5_RULE_SET_REPLAY_CONFLICT"); return read; } };
  const coverage = { readById: async (id: string) => { const rows = await client`select * from public.m5_suspicious_coverage_authorities where coverage_authority_id=${id} for update`; if (!rows.length) return undefined; const value = mapCoverage(rows[0] as Row); const members = await client`select rule_ordinal,rule_id,rule_fingerprint,input_material from public.m5_suspicious_coverage_rule_inputs where coverage_authority_id=${id} order by rule_ordinal`; if (value.status === "COMPLETE") { if (members.length !== value.evaluatedRuleIds.length || members.some((row, index) => Number((row as Row).rule_ordinal) !== index || String((row as Row).rule_id) !== value.evaluatedRuleIds[index] || !/^[a-f0-9]{64}$/.test(String((row as Row).rule_fingerprint)))) throw new Error("M5_COVERAGE_RULE_INPUT_SET_INVALID"); } return value; }, save: async (authority: M5SuspiciousCoverageAuthority) => { assertM5SuspiciousCoverageAuthority(authority); await client`insert into public.m5_suspicious_coverage_authorities (coverage_authority_id,contract_version,rule_set_authority_id,rule_set_fingerprint,provider_id,dataset_id,dataset_version,mapping_revision_id,provider_asset_identity_assertion_id,source_lineage_id,source_lineage_fingerprint,candidate_id,asset_id,canonical_identifier,asset_class,as_of,required_rule_ids,evaluated_rule_ids,source_materials,coverage_status,observed_at,available_at,coverage_fingerprint,recorded_at) values (${authority.coverageAuthorityId},${authority.contractVersion},${authority.ruleSetAuthorityId},${authority.ruleSetFingerprint},${authority.providerId},${authority.datasetId},${authority.datasetVersion},${authority.mappingRevisionId},${authority.providerAssetIdentityAssertionId},${authority.sourceLineageId},${authority.sourceLineageFingerprint},${authority.candidateId},${authority.assetId},${authority.canonicalIdentifier},${authority.assetClass},${authority.asOf},${client.json(authority.requiredRuleIds)},${client.json(authority.evaluatedRuleIds)},${client.json(authority.materials)},${authority.status},${authority.observedAt},${authority.availableAt},${authority.fingerprint},${authority.recordedAt}) on conflict (coverage_authority_id) do nothing`; for (const [ordinal, ruleId] of authority.evaluatedRuleIds.entries()) { const material = authority.materials[ordinal % authority.materials.length]; await client`insert into public.m5_suspicious_coverage_rule_inputs (coverage_authority_id,rule_ordinal,rule_id,rule_fingerprint,input_material) values (${authority.coverageAuthorityId},${ordinal},${ruleId},${canonicalSha256({ ruleId, material })},${client.json({ materialId: material.materialId, artifactId: material.artifactId, envelopeId: material.envelopeId, observationId: material.observationId, payloadFingerprint: material.payloadFingerprint })}) on conflict do nothing`; } const read = await coverage.readById(authority.coverageAuthorityId); if (!read || read.fingerprint !== authority.fingerprint) throw new Error("M5_COVERAGE_REPLAY_CONFLICT"); return read; } };
  return Object.freeze({ ruleSets, coverage });
}
export function createM5SuspiciousCoveragePersistenceUnitOfWork(sql: Sql): M5SuspiciousCoveragePersistenceUnitOfWork { return Object.freeze({ withTransaction: <T>(work: Parameters<M5SuspiciousCoveragePersistenceUnitOfWork["withTransaction"]>[0]) => sql.begin(async tx => work(createM5SuspiciousCoverageRepositories(tx))) as unknown as Promise<T> }); }
