import "server-only";
import type { Sql, TransactionSql } from "postgres";
import { assertM5VenueAuthority, type M5VenueAuthority, type VenueAuthorityMember, type VenueAuthoritySourceMaterial } from "@/domain/intelligence/m5-venue-authority";
import type { M5VenueAuthorityPersistenceUnitOfWork, M5VenueAuthorityRepository } from "@/application/intelligence/m5-venue-authority-persistence";
import { createSourceLineageRepository } from "./source-lineage-repository";

type Row = Record<string, unknown>;
const text = (value: unknown, code: string): string => { if (typeof value !== "string" || value.trim() === "") throw new Error(code); return value; };
const time = (value: unknown, code: string): string => { const result = value instanceof Date ? value.toISOString() : text(value, code); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(result)) throw new Error(code); return result; };
const json = <T>(value: unknown, code: string): T => { if (typeof value === "string") { try { return JSON.parse(value) as T; } catch { throw new Error(code); } } return value as T; };
const strings = (value: unknown, code: string): readonly string[] => { const result = json<unknown>(value, code); if (!Array.isArray(result) || result.some(item => typeof item !== "string")) throw new Error(code); return result as string[]; };

function mapMember(row: Row): VenueAuthorityMember {
  const sourceObservationRetrievedAt = time(row.source_observation_retrieved_at, "M5_VENUE_REPOSITORY_MEMBER_INVALID");
  return Object.freeze({ contractVersion: "m5-venue-universe-authority/v1" as const, memberId: text(row.member_id, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), venueNamespace: text(row.venue_namespace, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), venueId: text(row.venue_id, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), ...(row.venue_type == null ? {} : { venueType: text(row.venue_type, "M5_VENUE_REPOSITORY_MEMBER_INVALID") }), ...(row.chain_id == null ? {} : { chainId: text(row.chain_id, "M5_VENUE_REPOSITORY_MEMBER_INVALID") }), sourceRecordIds: strings(row.source_record_ids, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), sourceArtifactIds: strings(row.source_artifact_ids, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), sourceEnvelopeIds: strings(row.source_envelope_ids, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), sourceObservationIds: strings(row.source_observation_ids, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), sourceObservationRetrievedAt, payloadFingerprints: strings(row.payload_fingerprints, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), observedAt: time(row.observed_at, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), availableAt: time(row.available_at, "M5_VENUE_REPOSITORY_MEMBER_INVALID"), fingerprint: text(row.fingerprint, "M5_VENUE_REPOSITORY_MEMBER_INVALID") });
}
function mapAuthority(parent: Row, rows: readonly Row[]): M5VenueAuthority {
  const sourceMaterials = json<VenueAuthoritySourceMaterial[]>(parent.source_materials, "M5_VENUE_REPOSITORY_PARENT_INVALID");
  if (!Array.isArray(sourceMaterials)) throw new Error("M5_VENUE_REPOSITORY_PARENT_INVALID");
  const members = [...rows].sort((a: Row, b: Row) => Number(a.member_ordinal) - Number(b.member_ordinal)).map(mapMember);
  const authority = Object.freeze({ authorityId: text(parent.authority_id, "M5_VENUE_REPOSITORY_PARENT_INVALID"), contractVersion: text(parent.contract_version, "M5_VENUE_REPOSITORY_PARENT_INVALID") as M5VenueAuthority["contractVersion"], providerId: text(parent.provider_id, "M5_VENUE_REPOSITORY_PARENT_INVALID"), datasetId: text(parent.dataset_id, "M5_VENUE_REPOSITORY_PARENT_INVALID"), datasetVersion: text(parent.dataset_version, "M5_VENUE_REPOSITORY_PARENT_INVALID"), sourceLineageId: text(parent.source_lineage_id, "M5_VENUE_REPOSITORY_PARENT_INVALID"), asOf: time(parent.as_of, "M5_VENUE_REPOSITORY_PARENT_INVALID"), coverageKind: text(parent.coverage_kind, "M5_VENUE_REPOSITORY_PARENT_INVALID") as M5VenueAuthority["coverageKind"], coverageVersion: text(parent.coverage_version, "M5_VENUE_REPOSITORY_PARENT_INVALID"), universeNamespace: text(parent.universe_namespace, "M5_VENUE_REPOSITORY_PARENT_INVALID"), universeId: text(parent.universe_id, "M5_VENUE_REPOSITORY_PARENT_INVALID"), expectedPageCount: Number(parent.expected_page_count), expectedRecordCount: Number(parent.expected_record_count), finalPageOrdinal: Number(parent.final_page_ordinal), sourceMaterials, members, observedAt: time(parent.observed_at, "M5_VENUE_REPOSITORY_PARENT_INVALID"), effectiveAvailableAt: time(parent.effective_available_at, "M5_VENUE_REPOSITORY_PARENT_INVALID"), fingerprint: text(parent.fingerprint, "M5_VENUE_REPOSITORY_PARENT_INVALID"), recordedAt: time(parent.recorded_at, "M5_VENUE_REPOSITORY_PARENT_INVALID") });
  assertM5VenueAuthority(authority);
  return authority;
}
export function createM5VenueAuthorityTransactionRepository(client: TransactionSql): M5VenueAuthorityRepository {
  const readById = async (id: string): Promise<M5VenueAuthority | undefined> => { const parents = await client`select * from public.intelligence_m5_venue_authorities where authority_id=${id} for update`; if (!parents.length) return undefined; const members = await client`select * from public.intelligence_m5_venue_authority_members where authority_id=${id} order by member_ordinal`; return mapAuthority(parents[0] as Row, members as Row[]); };
  const save = async (authority: M5VenueAuthority): Promise<M5VenueAuthority> => {
    assertM5VenueAuthority(authority);
    const inserted = await client`insert into public.intelligence_m5_venue_authorities (authority_id,contract_version,provider_id,dataset_id,dataset_version,source_lineage_id,as_of,coverage_kind,coverage_version,universe_namespace,universe_id,expected_page_count,expected_record_count,final_page_ordinal,source_materials,member_ids,member_fingerprints,observed_at,effective_available_at,fingerprint,recorded_at) values (${authority.authorityId},${authority.contractVersion},${authority.providerId},${authority.datasetId},${authority.datasetVersion},${authority.sourceLineageId},${authority.asOf},${authority.coverageKind},${authority.coverageVersion},${authority.universeNamespace},${authority.universeId},${authority.expectedPageCount},${authority.expectedRecordCount},${authority.finalPageOrdinal},${client.json(authority.sourceMaterials)},${client.json(authority.members.map(member => member.memberId))},${client.json(authority.members.map(member => member.fingerprint))},${authority.observedAt},${authority.effectiveAvailableAt},${authority.fingerprint},${authority.recordedAt}) on conflict (authority_id) do nothing returning authority_id`;
    if (inserted.length) for (const [ordinal, member] of authority.members.entries()) await client`insert into public.intelligence_m5_venue_authority_members (authority_id,member_ordinal,member_id,venue_namespace,venue_id,venue_type,chain_id,provider_id,dataset_id,dataset_version,source_artifact_id,source_envelope_id,source_observation_id,source_observation_retrieved_at,source_record_ids,source_artifact_ids,source_envelope_ids,source_observation_ids,payload_fingerprints,observed_at,available_at,fingerprint) values (${authority.authorityId},${ordinal},${member.memberId},${member.venueNamespace},${member.venueId},${member.venueType ?? null},${member.chainId ?? null},${authority.providerId},${authority.datasetId},${authority.datasetVersion},${member.sourceArtifactIds[0]},${member.sourceEnvelopeIds[0]},${member.sourceObservationIds[0]},${member.sourceObservationRetrievedAt},${client.json(member.sourceRecordIds)},${client.json(member.sourceArtifactIds)},${client.json(member.sourceEnvelopeIds)},${client.json(member.sourceObservationIds)},${client.json(member.payloadFingerprints)},${member.observedAt},${member.availableAt},${member.fingerprint}) on conflict do nothing`;
    const reread = await readById(authority.authorityId); if (!reread) throw new Error("M5_VENUE_REPOSITORY_REREAD_MISSING"); if (reread.fingerprint !== authority.fingerprint || reread.members.length !== authority.members.length) throw new Error("M5_VENUE_REPOSITORY_CONFLICT"); return reread;
  };
  return Object.freeze({ readById, save });
}

export function createM5VenueAuthorityPersistenceUnitOfWork(sql: Sql): M5VenueAuthorityPersistenceUnitOfWork {
  return Object.freeze({
    withTransaction: <T>(work: Parameters<M5VenueAuthorityPersistenceUnitOfWork["withTransaction"]>[0]) => sql.begin(async transaction => work({ sourceLineage: createSourceLineageRepository(transaction), venue: createM5VenueAuthorityTransactionRepository(transaction) })) as unknown as Promise<T>,
  });
}
