import "server-only";
import { createHash } from "node:crypto";
import postgres from "postgres";
import webpush from "web-push";
import { assertWebPushConfigured, testNotificationEventId, toSafePushPayload, type AlertCandidate, type NotificationPreferences } from "@/domain/notifications/alerts";
import type { NotificationOperationalRecord } from "@/domain/notifications/processor";

const connection = () => {
  const url = process.env.DATABASE_URL;
  if (!url) throw new Error("DATABASE_UNCONFIGURED");
  return postgres(url, { max: 1, prepare: true, ssl: "require" });
};
const subscriptionId = (endpoint: string) => createHash("sha256").update(endpoint).digest("hex");

export async function savePushSubscription(userId: string, subscription: { endpoint: string; keys: { p256dh: string; auth: string } }, deviceLabel?: string) {
  const sql = connection();
  try { const id = subscriptionId(subscription.endpoint); await sql`insert into public.push_subscriptions (subscription_id,user_id,endpoint,p256dh,auth,device_label,active) values (${id},${userId},${subscription.endpoint},${subscription.keys.p256dh},${subscription.keys.auth},${deviceLabel ?? null},true) on conflict (endpoint) do update set user_id=excluded.user_id,p256dh=excluded.p256dh,auth=excluded.auth,device_label=excluded.device_label,active=true,updated_at=now()`; return id; }
  finally { await sql.end({ timeout: 5 }); }
}
export async function deactivatePushSubscription(userId: string, endpoint: string) { const sql = connection(); try { await sql`update public.push_subscriptions set active=false,updated_at=now() where user_id=${userId} and endpoint=${endpoint}`; } finally { await sql.end({ timeout: 5 }); } }
export async function getNotificationPreferences(userId: string): Promise<NotificationPreferences | null> { const sql = connection(); try { const rows = await sql`select enabled_categories,currency,pnl_milestone_threshold_minor,quiet_hours_enabled,to_char(quiet_hours_start,'HH24:MI') quiet_hours_start,to_char(quiet_hours_end,'HH24:MI') quiet_hours_end,timezone,max_non_critical_per_hour from public.admin_notification_preferences where user_id=${userId}`; const row = rows[0]; return row ? { enabledCategories: ((row.enabled_categories as string[]) ?? []) as NotificationPreferences["enabledCategories"], currency: String(row.currency), pnlMilestoneThresholdMinor: BigInt(String(row.pnl_milestone_threshold_minor)), quietHoursEnabled: Boolean(row.quiet_hours_enabled), quietHoursStart: String(row.quiet_hours_start), quietHoursEnd: String(row.quiet_hours_end), timezone: String(row.timezone), maxNonCriticalPerHour: Number(row.max_non_critical_per_hour) } : null; } finally { await sql.end({ timeout: 5 }); } }
export async function saveNotificationPreferences(userId: string, preferences: NotificationPreferences) { const sql = connection(); try { await sql`insert into public.admin_notification_preferences (user_id,enabled_categories,pnl_milestone_threshold_minor,currency,quiet_hours_enabled,quiet_hours_start,quiet_hours_end,timezone,max_non_critical_per_hour) values (${userId},string_to_array(${[...preferences.enabledCategories].join(",")}, ','),${preferences.pnlMilestoneThresholdMinor.toString()},${preferences.currency},${preferences.quietHoursEnabled},${preferences.quietHoursStart},${preferences.quietHoursEnd},${preferences.timezone},${preferences.maxNonCriticalPerHour}) on conflict (user_id) do update set enabled_categories=excluded.enabled_categories,pnl_milestone_threshold_minor=excluded.pnl_milestone_threshold_minor,currency=excluded.currency,quiet_hours_enabled=excluded.quiet_hours_enabled,quiet_hours_start=excluded.quiet_hours_start,quiet_hours_end=excluded.quiet_hours_end,timezone=excluded.timezone,max_non_critical_per_hour=excluded.max_non_critical_per_hour,updated_at=now()`; } finally { await sql.end({ timeout: 5 }); } }

export async function getActivePushSubscriptions(userId: string): Promise<{ subscriptionId: string; active: boolean }[]> { const sql = connection(); try { const rows = await sql`select subscription_id from public.push_subscriptions where user_id=${userId} and active=true order by subscription_id`; return rows.map(row => ({ subscriptionId: String(row.subscription_id), active: true })); } finally { await sql.end({ timeout: 5 }); } }

export async function getNotificationOperationalHistory(userId: string): Promise<NotificationOperationalRecord[]> { const sql = connection(); try { const rows = await sql`select d.alert_event_id,d.subscription_id,d.status,d.attempted_at,d.failure_code,d.deferred_until,d.category from public.notification_delivery_attempts d join public.push_subscriptions s on s.subscription_id=d.subscription_id where s.user_id=${userId} union all select alert_event_id,null,status,occurred_at,reason_code,deferred_until,category from public.notification_suppression_events where user_id=${userId} order by attempted_at`; return rows.map(row => ({ alertEventId: String(row.alert_event_id), category: String(row.category) as NotificationOperationalRecord["category"], status: String(row.status) as NotificationOperationalRecord["status"], occurredAt: new Date(String(row.attempted_at)), subscriptionId: row.subscription_id ? String(row.subscription_id) : undefined, reasonCode: row.failure_code ? String(row.failure_code) : undefined, deferredUntil: row.deferred_until ? new Date(String(row.deferred_until)).toISOString() : undefined })); } finally { await sql.end({ timeout: 5 }); } }

export async function persistNotificationOutcome(userId: string, outcome: NotificationOperationalRecord): Promise<void> { const sql = connection(); try { if (outcome.subscriptionId) { const deliveryId = createHash("sha256").update(`${outcome.alertEventId}:${outcome.subscriptionId}`).digest("hex"); await sql`insert into public.notification_delivery_attempts (delivery_id,alert_event_id,subscription_id,status,attempt,attempted_at,delivered_at,failure_code,deferred_until) values (${deliveryId},${outcome.alertEventId},${outcome.subscriptionId},${outcome.status},1,${outcome.occurredAt},${outcome.status === "SENT" ? outcome.occurredAt : null},${outcome.reasonCode ?? null},${outcome.deferredUntil ?? null}) on conflict (alert_event_id,subscription_id) do nothing`; } else { const suppressionId = createHash("sha256").update(`${userId}:${outcome.alertEventId}:${outcome.reasonCode ?? ""}`).digest("hex"); await sql`insert into public.notification_suppression_events (suppression_id,user_id,alert_event_id,category,status,reason_code,occurred_at,deferred_until,cooldown_key) values (${suppressionId},${userId},${outcome.alertEventId},${outcome.category},${outcome.status},${outcome.reasonCode ?? ""},${outcome.occurredAt},${outcome.deferredUntil ?? null},${outcome.cooldownKey ?? null}) on conflict (user_id,alert_event_id,reason_code) do nothing`; } } finally { await sql.end({ timeout: 5 }); } }

export async function claimNotificationDelivery(alertEventId: string, subscriptionId: string, asOf: Date): Promise<boolean> { const sql = connection(); try { const rows = await sql`insert into public.notification_delivery_claims (alert_event_id,subscription_id,claim_status,attempt,claimed_at,claim_expires_at) values (${alertEventId},${subscriptionId},'CLAIMED',1,${asOf},${new Date(asOf.getTime() + 5 * 60_000)}) on conflict (alert_event_id,subscription_id) do nothing returning alert_event_id`; return rows.length === 1; } finally { await sql.end({ timeout: 5 }); } }

export async function completeNotificationClaim(alertEventId: string, subscriptionId: string, status: "SENT" | "FAILED", asOf: Date, failureCode?: string): Promise<void> { const sql = connection(); try { await sql`update public.notification_delivery_claims set claim_status=${status},completed_at=${asOf},failure_code=${failureCode ?? null} where alert_event_id=${alertEventId} and subscription_id=${subscriptionId} and claim_status='CLAIMED'`; } finally { await sql.end({ timeout: 5 }); } }

export async function sendWebPushCandidate(candidate: AlertCandidate, subscriptionId: string): Promise<"SENT" | "FAILED"> { assertWebPushConfigured(); webpush.setVapidDetails(process.env.VAPID_SUBJECT!, process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY!, process.env.VAPID_PRIVATE_KEY!); const sql = connection(); try { const rows = await sql`select endpoint,p256dh,auth from public.push_subscriptions where subscription_id=${subscriptionId} and active=true`; const row = rows[0]; if (!row) return "FAILED"; await webpush.sendNotification({ endpoint: String(row.endpoint), keys: { p256dh: String(row.p256dh), auth: String(row.auth) } }, JSON.stringify(toSafePushPayload(candidate))); return "SENT"; } catch { return "FAILED"; } finally { await sql.end({ timeout: 5 }); } }
export async function sendTestNotification(userId: string, existingInvocationNumber?: bigint): Promise<{ sent: number; invocationNumber: string; payload: Readonly<Record<string, unknown>> }> {
  assertWebPushConfigured();
  webpush.setVapidDetails(process.env.VAPID_SUBJECT!, process.env.NEXT_PUBLIC_VAPID_PUBLIC_KEY!, process.env.VAPID_PRIVATE_KEY!);
  const sql = connection();
  try {
    const invocationRows = existingInvocationNumber === undefined
      ? await sql`insert into public.notification_test_invocations (user_id) values (${userId}) returning invocation_number`
      : await sql`select invocation_number from public.notification_test_invocations where user_id=${userId} and invocation_number=${existingInvocationNumber.toString()}`;
    const invocationNumber = invocationRows[0]?.invocation_number;
    if (invocationNumber === undefined) throw new Error("TEST_INVOCATION_NOT_FOUND");
    const eventId = testNotificationEventId(userId, String(invocationNumber));
    const rows = await sql`select subscription_id,endpoint,p256dh,auth from public.push_subscriptions where user_id=${userId} and active=true order by subscription_id`;
    const candidate: AlertCandidate = { alertEventId: eventId, alertFingerprint: eventId, category: "SYSTEM_CRITICAL", severity: "INFO", title: "TEST NOTIFICATION", body: "TEST — Web Push transport is working.", occurredAt: new Date().toISOString(), safeRelativeUrl: "/admin/activity?category=SYSTEM%2FERROR&event=test", reasonCodes: ["TEST_NOTIFICATION"], simulation: true };
    const payload = JSON.stringify(toSafePushPayload(candidate)); let sent = 0;
    for (const row of rows) { const existing = await sql`select 1 from public.notification_delivery_attempts where alert_event_id=${candidate.alertEventId} and subscription_id=${row.subscription_id} and status='SENT'`; if (existing.length) continue; const deliveryId = createHash("sha256").update(`${candidate.alertEventId}:${row.subscription_id}`).digest("hex"); try { await webpush.sendNotification({ endpoint: String(row.endpoint), keys: { p256dh: String(row.p256dh), auth: String(row.auth) } }, payload); await sql`insert into public.notification_delivery_attempts (delivery_id,alert_event_id,subscription_id,status,attempt,attempted_at,delivered_at) values (${deliveryId},${candidate.alertEventId},${row.subscription_id},'SENT',1,now(),now()) on conflict (alert_event_id,subscription_id) do nothing`; sent++; } catch { await sql`insert into public.notification_delivery_attempts (delivery_id,alert_event_id,subscription_id,status,attempt,attempted_at,failure_code) values (${deliveryId},${candidate.alertEventId},${row.subscription_id},'FAILED',1,now(),'PUSH_DELIVERY_FAILED') on conflict (alert_event_id,subscription_id) do nothing`; } }
    return { sent, invocationNumber: String(invocationNumber), payload: toSafePushPayload(candidate) };
  } finally { await sql.end({ timeout: 5 }); }
}
