import "server-only";
import postgres, { type Sql, type TransactionSql } from "postgres";
import { assertProviderAssetIdentityAssertion, createProviderAssetIdentityAssertion, PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION, type ProviderAssetIdentityAssertion } from "@/domain/intelligence/provider-asset-identity-assertion";
import { mapSourceArtifactRow, mapSourceEnvelopeRow } from "@/infrastructure/postgres/ingestion-provenance-repository";
import type { ProviderAssetIdentityAssertionRepositories, ProviderAssetIdentityAssertionUnitOfWork } from "@/application/intelligence/provider-asset-identity-repository";

type RawRow = Record<string, unknown>;
const text = (value: unknown, code: string) => { if (typeof value !== "string" || value !== value.trim() || !value) throw new Error(code); return value; };
const timestamp = (value: unknown, code: string) => { const result = value instanceof Date ? value.toISOString() : text(value, code); if (!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(result) || Number.isNaN(Date.parse(result)) || new Date(result).toISOString() !== result) throw new Error(code); return result; };
export function mapProviderAssetIdentityAssertionRow(value: RawRow): ProviderAssetIdentityAssertion {
  const id = text(value.provider_asset_identity_assertion_id, "M5_PROVIDER_ASSET_IDENTITY_ROW_ID_INVALID"); const fingerprint = text(value.fingerprint, "M5_PROVIDER_ASSET_IDENTITY_ROW_FINGERPRINT_INVALID");
  if (text(value.contract_version, "M5_PROVIDER_ASSET_IDENTITY_ROW_CONTRACT_INVALID") !== PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION) throw new Error("M5_PROVIDER_ASSET_IDENTITY_ROW_CONTRACT_INVALID");
  const record = createProviderAssetIdentityAssertion({ contractVersion: PROVIDER_ASSET_IDENTITY_ASSERTION_CONTRACT_VERSION, providerAssetIdentityAssertionId: id, providerId: text(value.provider_id, "M5_PROVIDER_ASSET_IDENTITY_ROW_PROVIDER_INVALID"), datasetId: text(value.dataset_id, "M5_PROVIDER_ASSET_IDENTITY_ROW_DATASET_INVALID"), datasetVersion: text(value.dataset_version, "M5_PROVIDER_ASSET_IDENTITY_ROW_DATASET_VERSION_INVALID"), providerSourceNamespace: text(value.provider_source_namespace, "M5_PROVIDER_ASSET_IDENTITY_ROW_NAMESPACE_INVALID"), providerAssetId: text(value.provider_asset_id, "M5_PROVIDER_ASSET_IDENTITY_ROW_ASSET_INVALID"), identityType: text(value.identity_type, "M5_PROVIDER_ASSET_IDENTITY_ROW_TYPE_INVALID") as ProviderAssetIdentityAssertion["identityType"], identityNamespace: text(value.identity_namespace, "M5_PROVIDER_ASSET_IDENTITY_ROW_IDENTITY_NAMESPACE_INVALID"), identityValue: text(value.identity_value, "M5_PROVIDER_ASSET_IDENTITY_ROW_IDENTITY_VALUE_INVALID"), sourceArtifactId: text(value.source_artifact_id, "M5_PROVIDER_ASSET_IDENTITY_ROW_ARTIFACT_INVALID"), sourceEnvelopeId: text(value.source_envelope_id, "M5_PROVIDER_ASSET_IDENTITY_ROW_ENVELOPE_INVALID"), parserVersion: text(value.parser_version, "M5_PROVIDER_ASSET_IDENTITY_ROW_PARSER_INVALID"), envelopeSchemaVersion: text(value.envelope_schema_version, "M5_PROVIDER_ASSET_IDENTITY_ROW_SCHEMA_INVALID"), sourcePayloadFingerprint: text(value.source_payload_fingerprint, "M5_PROVIDER_ASSET_IDENTITY_ROW_PAYLOAD_FINGERPRINT_INVALID"), fingerprint, recordedAt: timestamp(value.recorded_at, "M5_PROVIDER_ASSET_IDENTITY_ROW_RECORDED_INVALID") });
  if (record.providerAssetIdentityAssertionId !== id) throw new Error("M5_PROVIDER_ASSET_IDENTITY_ROW_ID_MISMATCH"); if (record.fingerprint !== fingerprint) throw new Error("M5_PROVIDER_ASSET_IDENTITY_ROW_FINGERPRINT_MISMATCH"); return record;
}
function repositories(client: TransactionSql): ProviderAssetIdentityAssertionRepositories {
  const artifacts = { readById: async (id: string) => { const rows = await client`select * from public.intelligence_source_artifacts where source_artifact_id=${id}`; return rows.length ? mapSourceArtifactRow(rows[0] as RawRow) : undefined; } };
  const envelopes = { readById: async (id: string) => { const rows = await client`select * from public.intelligence_source_envelopes where source_envelope_id=${id}`; return rows.length ? mapSourceEnvelopeRow(rows[0] as RawRow) : undefined; } };
  const assertions = { readById: async (id: string) => { const rows = await client`select * from public.intelligence_provider_asset_identity_assertions where provider_asset_identity_assertion_id=${id}`; return rows.length ? mapProviderAssetIdentityAssertionRow(rows[0] as RawRow) : undefined; }, save: async (input: ProviderAssetIdentityAssertion) => {
    assertProviderAssetIdentityAssertion(input); const record = createProviderAssetIdentityAssertion(input); const artifact = await artifacts.readById(record.sourceArtifactId); if (!artifact) throw new Error("M5_PROVIDER_ASSET_IDENTITY_ARTIFACT_NOT_FOUND"); const envelope = await envelopes.readById(record.sourceEnvelopeId); if (!envelope) throw new Error("M5_PROVIDER_ASSET_IDENTITY_ENVELOPE_NOT_FOUND");
    if (envelope.sourceArtifactId !== artifact.sourceArtifactId) throw new Error("M5_PROVIDER_ASSET_IDENTITY_ENVELOPE_ARTIFACT_MISMATCH"); if (artifact.providerId !== record.providerId || artifact.datasetId !== record.datasetId || artifact.datasetVersion !== record.datasetVersion || artifact.providerSourceNamespace !== record.providerSourceNamespace || artifact.providerExternalRecordId !== record.providerAssetId) throw new Error("M5_PROVIDER_ASSET_IDENTITY_PARENT_MISMATCH"); if (envelope.parserContractVersion !== record.parserVersion || envelope.envelopeSchemaVersion !== record.envelopeSchemaVersion || envelope.payloadFingerprint !== record.sourcePayloadFingerprint || artifact.payloadFingerprint !== record.sourcePayloadFingerprint || envelope.temporalQualityStatus !== "RESOLVED") throw new Error("M5_PROVIDER_ASSET_IDENTITY_PARENT_MISMATCH");
    await client`insert into public.intelligence_provider_asset_identity_assertions (provider_asset_identity_assertion_id,contract_version,provider_id,dataset_id,dataset_version,provider_source_namespace,provider_asset_id,identity_type,identity_namespace,identity_value,source_artifact_id,source_envelope_id,parser_version,envelope_schema_version,source_payload_fingerprint,fingerprint,recorded_at) values (${record.providerAssetIdentityAssertionId},${record.contractVersion},${record.providerId},${record.datasetId},${record.datasetVersion},${record.providerSourceNamespace},${record.providerAssetId},${record.identityType},${record.identityNamespace},${record.identityValue},${record.sourceArtifactId},${record.sourceEnvelopeId},${record.parserVersion},${record.envelopeSchemaVersion},${record.sourcePayloadFingerprint},${record.fingerprint},${record.recordedAt}) on conflict (provider_asset_identity_assertion_id) do nothing`;
    const stored = await assertions.readById(record.providerAssetIdentityAssertionId); if (!stored) throw new Error("M5_PROVIDER_ASSET_IDENTITY_REREAD_NOT_FOUND"); if (stored.fingerprint !== record.fingerprint) throw new Error("M5_PROVIDER_ASSET_IDENTITY_ASSERTION_CONFLICT"); return stored;
  } };
  return Object.freeze({ artifacts, envelopes, assertions });
}
export function createProviderAssetIdentityAssertionUnitOfWork(client: Sql): ProviderAssetIdentityAssertionUnitOfWork { return Object.freeze({ withTransaction: <T>(work: (value: ProviderAssetIdentityAssertionRepositories) => Promise<T>) => client.begin(transaction => work(repositories(transaction))) as unknown as Promise<T> }); }
export function createProviderAssetIdentityReadRepository(client: TransactionSql) { return Object.freeze({ readById: repositories(client).assertions.readById }); }
export const createProviderAssetIdentitySql = (url: string): Sql => postgres(url, { max: 1, prepare: true, ssl: "require" });
