import "server-only";
import postgres, { type Sql } from "postgres";
import { canonicalSha256 } from "@/domain/intelligence/ingestion-provenance";
import { hashExactEntityBody, isTrustedSecRuntimeBatch, type SecRuntimeDocumentAuthority, type SecRuntimeTrustedBatch } from "@/domain/intelligence/sec-edgar-event-source-provenance-runtime";

export type SecProvenancePersisted = Readonly<{ profileId:string; filingIdentityId:string; packageId:string; packageFingerprint:string; receiptId:string; lineageId:string; documentCount:number; memberCount:number; blobCount:number; status:"PERSISTED_VERIFIED"; classification:"SYNTHETIC_NON_AUTHORITATIVE"; eventAuthorityEligible:false }>;
export type SecProvenanceWritePhase="TRANSACTION_STARTED"|"SOURCE_PROFILE"|"FILING_IDENTITY"|"REQUEST"|"REQUEST_ATTEMPT"|"BLOB_VERIFIED"|"DOCUMENT_ARTIFACTS"|"PACKAGE_PARENT"|"PACKAGE_MEMBERS"|"RECEIPT"|"LINEAGE_PARENT"|"LINEAGE_MEMBERS"|"AUTHORITATIVE_REREAD"|"BEFORE_COMMIT";
export type SecProvenancePhaseObserver=(phase:SecProvenanceWritePhase)=>void|Promise<void>;
type Tx=Sql<Record<string, never>>;
const same=(actual:unknown,expected:unknown)=>canonicalSha256(actual)===canonicalSha256(expected);
const sameTimestamp=(actual:unknown,expected:string)=>{try{return actual instanceof Date?actual.toISOString()===expected:new Date(String(actual)).toISOString()===expected;}catch{return false;}};
const sameDate=(actual:unknown,expected:string|null)=>{if(expected===null)return actual===null;try{return actual instanceof Date?actual.toISOString().slice(0,10)===expected:String(actual).slice(0,10)===expected;}catch{return false;}};
// An internal persistence record, never a trusted application command. The only
// production caller derives it after the same-runtime batch guard above SQL.
export type SecDocumentArtifactWrite = Readonly<{
  filingIdentityId:string;
  profileId:string;
  profileFingerprint:string;
  document:Omit<SecRuntimeDocumentAuthority,"bytes">;
}>;
async function persistDocumentArtifact(tx:Tx,input:SecDocumentArtifactWrite):Promise<void>{
  const d=input.document;
  const docMaterial={filingIdentityId:input.filingIdentityId,canonicalLocator:d.locator,documentRole:d.role,documentType:d.documentType,exactEntityBodyOctetsSha256:d.sha256,contentType:d.contentType,byteLength:d.byteLength,sequenceOrdinal:d.sequence,canonicalizationVersion:d.canonicalizationVersion,noContentNormalization:true};
  await tx`insert into public.sec_event_document_artifacts(artifact_id,fingerprint,filing_identity_id,blob_id,content_sha256,byte_length,document_role,document_type,sequence_ordinal,canonical_locator,content_type,canonicalization_version,material) values(${d.artifactId},${d.fingerprint},${input.filingIdentityId},${d.blobId},${d.sha256},${d.byteLength},${d.role},${d.documentType},${d.sequence},${d.locator},${d.contentType},${d.canonicalizationVersion},${tx.json(docMaterial)}) on conflict do nothing returning artifact_id`;
  const artifactRows=await tx`select a.fingerprint,a.filing_identity_id,a.blob_id,a.content_sha256,a.byte_length,a.document_role,a.document_type,a.sequence_ordinal,a.canonical_locator,a.content_type,a.canonicalization_version,a.material,f.profile_id,f.profile_fingerprint from public.sec_event_document_artifacts a join public.sec_event_filing_identities f on f.filing_identity_id=a.filing_identity_id where a.artifact_id=${d.artifactId}`;
  const artifact=artifactRows[0];
  if(artifactRows.length!==1||artifact?.filing_identity_id!==input.filingIdentityId||artifact?.profile_id!==input.profileId||artifact?.profile_fingerprint?.trim()!==input.profileFingerprint||artifact?.blob_id!==d.blobId||artifact?.content_sha256?.trim()!==d.sha256||Number(artifact?.byte_length)!==d.byteLength||artifact?.document_role!==d.role||artifact?.document_type!==d.documentType||Number(artifact?.sequence_ordinal)!==d.sequence||artifact?.canonical_locator!==d.locator||artifact?.content_type!==d.contentType||artifact?.canonicalization_version!==d.canonicalizationVersion||artifact?.fingerprint?.trim()!==d.fingerprint||!same(artifact?.material,docMaterial))throw new Error("SEC_EVENT_DOCUMENT_ARTIFACT_AUTHORITY_CONFLICT");
}
export async function persistSecEventProvenance(tx:Tx,b:SecRuntimeTrustedBatch, observePhase?:SecProvenancePhaseObserver):Promise<SecProvenancePersisted>{
  if(!isTrustedSecRuntimeBatch(b))throw new Error("SEC_EVENT_TRUSTED_INPUT_REQUIRED");
  const isolation=await tx`show transaction_isolation`;if(String(isolation[0]?.transaction_isolation).toLowerCase()!=="read committed")throw new Error("SEC_EVENT_TRANSACTION_ISOLATION_INVALID");
  await tx`set local statement_timeout = '120s'`;
  const m=b.material;
  const profileMaterial={contractVersion:m.profileId,provider:"SYNTHETIC_FIXTURE",dataset:"sec-edgar-8k-fixture",version:"sec-edgar-8k-fixture-package/v1",endpointProfile:"SYNTHETIC_FIXTURE_ADAPTER",hostnameAllowlist:[] as string[],pathTemplate:"/synthetic-edgar/archive/{cik}/{accession}",method:"FIXTURE_ADAPTER",supportedForms:["8-K","8-K/A"],authenticationKind:"NONE",acceptedContentEncoding:["identity"],requestIdentityPolicy:"synthetic-fixture-replay/v1",maxTimeoutMs:15_000,maxResponseBytes:8*1024*1024,maxPackageDocuments:32,classification:"SYNTHETIC_NON_AUTHORITATIVE"};
  await tx`insert into public.sec_event_source_profiles(profile_id,fingerprint,contract_version,provider_id,dataset_id,dataset_version,endpoint_profile,hostname_allowlist,path_template,method,supported_forms,authentication_kind,accepted_content_encoding,request_identity_policy,max_timeout_ms,max_response_bytes,max_package_documents,material) values(${m.profileId},${b.profileFingerprint},${m.profileId},'SYNTHETIC_FIXTURE','sec-edgar-8k-fixture','sec-edgar-8k-fixture-package/v1','SYNTHETIC_FIXTURE_ADAPTER',${tx.json([])},'/synthetic-edgar/archive/{cik}/{accession}','FIXTURE_ADAPTER',${tx.json(["8-K","8-K/A"])},'NONE',${tx.json(["identity"])},'synthetic-fixture-replay/v1',15000,8388608,32,${tx.json(profileMaterial)}) on conflict do nothing`;
  const profileRows=await tx`select fingerprint,contract_version,provider_id,dataset_id,dataset_version,endpoint_profile,hostname_allowlist,path_template,method,supported_forms,authentication_kind,accepted_content_encoding,request_identity_policy,max_timeout_ms,max_response_bytes,max_package_documents,material from public.sec_event_source_profiles where profile_id=${m.profileId}`;
  const profileRow=profileRows[0];
  if(profileRows.length!==1||profileRow?.fingerprint?.trim()!==b.profileFingerprint||profileRow?.contract_version!==m.profileId||profileRow?.provider_id!=="SYNTHETIC_FIXTURE"||profileRow?.dataset_id!=="sec-edgar-8k-fixture"||profileRow?.dataset_version!=="sec-edgar-8k-fixture-package/v1"||profileRow?.endpoint_profile!=="SYNTHETIC_FIXTURE_ADAPTER"||!same(profileRow?.hostname_allowlist,[])||profileRow?.path_template!=="/synthetic-edgar/archive/{cik}/{accession}"||profileRow?.method!=="FIXTURE_ADAPTER"||!same(profileRow?.supported_forms,["8-K","8-K/A"])||profileRow?.authentication_kind!=="NONE"||!same(profileRow?.accepted_content_encoding,["identity"])||profileRow?.request_identity_policy!=="synthetic-fixture-replay/v1"||Number(profileRow?.max_timeout_ms)!==15000||Number(profileRow?.max_response_bytes)!==8388608||Number(profileRow?.max_package_documents)!==32||!same(profileRow?.material,profileMaterial))throw new Error("SEC_EVENT_SOURCE_PROFILE_AUTHORITY_CONFLICT");
  await observePhase?.("SOURCE_PROFILE");
  const filingMaterial={sourceProfileId:m.profileId,sourceProfileFingerprint:b.profileFingerprint,cik:m.cik,accessionNumber:m.accession,form:m.form};
  if(b.amendmentParentFilingIdentityId){const parentMaterial={sourceProfileId:m.profileId,sourceProfileFingerprint:b.profileFingerprint,cik:m.cik,accessionNumber:m.amendmentParent,form:"8-K"};const parentRows=await tx`select profile_id,profile_fingerprint,cik,accession_number,form,amendment_parent_filing_identity_id,material from public.sec_event_filing_identities where filing_identity_id=${b.amendmentParentFilingIdentityId}`;const parent=parentRows[0];if(parentRows.length!==1||parent?.profile_id!==m.profileId||parent?.profile_fingerprint?.trim()!==b.profileFingerprint||parent?.cik!==m.cik||parent?.accession_number!==m.amendmentParent||parent?.form!=="8-K"||parent?.amendment_parent_filing_identity_id!==null||!same(parent?.material,parentMaterial))throw new Error("SEC_EVENT_FILING_PARENT_AUTHORITY_CONFLICT");}
  await tx`insert into public.sec_event_filing_identities(filing_identity_id,profile_id,profile_fingerprint,cik,accession_number,form,amendment_parent_filing_identity_id,material) values(${b.filingIdentityId},${m.profileId},${b.profileFingerprint},${m.cik},${m.accession},${m.form},${b.amendmentParentFilingIdentityId},${tx.json(filingMaterial)}) on conflict do nothing`;
  const filingRows=await tx`select profile_id,profile_fingerprint,cik,accession_number,form,amendment_parent_filing_identity_id,material from public.sec_event_filing_identities where filing_identity_id=${b.filingIdentityId}`;const filing=filingRows[0];if(filingRows.length!==1||filing?.profile_id!==m.profileId||filing?.profile_fingerprint?.trim()!==b.profileFingerprint||filing?.cik!==m.cik||filing?.accession_number!==m.accession||filing?.form!==m.form||filing?.amendment_parent_filing_identity_id!==(b.amendmentParentFilingIdentityId??null)||!same(filing?.material,filingMaterial))throw new Error("SEC_EVENT_FILING_IDENTITY_AUTHORITY_CONFLICT");
  await observePhase?.("FILING_IDENTITY");
  const requestId=b.requestId;const requestFp=b.packageFingerprint;const requestMaterial={requestId,fingerprint:requestFp,filingIdentityId:b.filingIdentityId,profileId:m.profileId,idempotencyKey:b.packageId,requestedAt:m.acceptanceAt};
  await tx`insert into public.sec_event_acquisition_requests(request_id,fingerprint,idempotency_key,profile_id,profile_fingerprint,filing_identity_id,requested_at,material) values(${requestId},${requestFp},${b.packageId},${m.profileId},${b.profileFingerprint},${b.filingIdentityId},${m.acceptanceAt},${tx.json(requestMaterial)}) on conflict do nothing`;const requestRows=await tx`select fingerprint,idempotency_key,profile_id,profile_fingerprint,filing_identity_id,requested_at,material from public.sec_event_acquisition_requests where request_id=${requestId}`;const request=requestRows[0];if(requestRows.length!==1||request?.fingerprint?.trim()!==requestFp||request?.idempotency_key!==b.packageId||request?.profile_id!==m.profileId||request?.profile_fingerprint?.trim()!==b.profileFingerprint||request?.filing_identity_id!==b.filingIdentityId||!sameTimestamp(request?.requested_at,m.acceptanceAt)||!same(request?.material,requestMaterial))throw new Error("SEC_EVENT_ACQUISITION_REQUEST_AUTHORITY_CONFLICT");
  await observePhase?.("REQUEST");
  const attemptId=b.attemptId;const priorAttempt=await tx`select attempt_ordinal from public.sec_event_acquisition_attempts where attempt_id=${attemptId}`;const maxAttempt=await tx`select coalesce(max(attempt_ordinal),-1)::int as ordinal from public.sec_event_acquisition_attempts where request_id=${requestId}`;const attemptOrdinal=priorAttempt.length?Number(priorAttempt[0]?.attempt_ordinal):Number(maxAttempt[0]?.ordinal)+1;const attemptMaterial={attemptId,requestId,ordinal:attemptOrdinal,startedAt:m.receipt.receivedAt};await tx`insert into public.sec_event_acquisition_attempts(attempt_id,fingerprint,request_id,attempt_ordinal,started_at,material) values(${attemptId},${b.receiptFingerprint},${requestId},${attemptOrdinal},${m.receipt.receivedAt},${tx.json(attemptMaterial)}) on conflict do nothing`;const attemptRows=await tx`select fingerprint,request_id,attempt_ordinal,started_at,material from public.sec_event_acquisition_attempts where attempt_id=${attemptId}`;const attempt=attemptRows[0];if(attemptRows.length!==1||attempt?.fingerprint?.trim()!==b.receiptFingerprint||attempt?.request_id!==requestId||Number(attempt?.attempt_ordinal)!==attemptOrdinal||!sameTimestamp(attempt?.started_at,m.receipt.receivedAt)||!same(attempt?.material,attemptMaterial))throw new Error("SEC_EVENT_ACQUISITION_ATTEMPT_AUTHORITY_CONFLICT");
  await observePhase?.("REQUEST_ATTEMPT");
  const uniqueBlobs=[...new Map(b.documents.map(d=>[d.blobId,d])).values()].sort((a,b)=>a.blobId<b.blobId?-1:a.blobId>b.blobId?1:0);const blobCount=uniqueBlobs.length;
  for(const d of uniqueBlobs){
    const blobMaterial={blobId:d.blobId,sha256:d.sha256,byteLength:d.byteLength,contractVersion:"sec-event-document-byte-storage-decision/v1",readbackVerified:true,retentionClassification:"NOT_APPROVED",deletionLegalHoldStatus:"NOT_APPROVED"};
    const expectedBytes=d.bytes;
    await tx`insert into public.sec_event_content_blobs(blob_id,sha256,byte_length,storage_contract_version,entity_body,readback_verified,retention_classification,deletion_legal_hold_status,material) values(${d.blobId},${d.sha256},${d.byteLength},'sec-event-document-byte-storage-decision/v1',${expectedBytes},true,'NOT_APPROVED','NOT_APPROVED',${tx.json(blobMaterial)}) on conflict do nothing`;
    const rows=await tx`select blob_id,sha256,byte_length,storage_contract_version,entity_body,readback_verified,retention_classification,deletion_legal_hold_status,material from public.sec_event_content_blobs where sha256=${d.sha256}`;
    const row=rows[0];
    if(rows.length!==1||row?.blob_id!==d.blobId||row?.sha256?.trim()!==d.sha256||Number(row?.byte_length)!==d.byteLength||row?.storage_contract_version!=="sec-event-document-byte-storage-decision/v1"||row?.readback_verified!==true||row?.retention_classification!=="NOT_APPROVED"||row?.deletion_legal_hold_status!=="NOT_APPROVED"||!Buffer.isBuffer(row?.entity_body)||!row.entity_body.equals(expectedBytes)||row.entity_body.byteLength!==d.byteLength||hashExactEntityBody(row.entity_body)!==d.sha256||!same(row?.material,blobMaterial))throw new Error("SEC_EVENT_BLOB_READBACK_MISMATCH");
  }
  await observePhase?.("BLOB_VERIFIED");
  for(const d of [...b.documents].sort((a,b)=>a.artifactId<b.artifactId?-1:a.artifactId>b.artifactId?1:0)){
    await persistDocumentArtifact(tx,{filingIdentityId:b.filingIdentityId,profileId:m.profileId,profileFingerprint:b.profileFingerprint,document:d});
  }
  await observePhase?.("DOCUMENT_ARTIFACTS");
  const index=b.documents.find(d=>d.role==="FILING_INDEX")!;
  const packageMaterial=b.packageMaterial;
  await tx`insert into public.sec_event_filing_packages(package_id,fingerprint,filing_identity_id,filing_date,acceptance_at,report_period,filing_index_artifact_id,filing_index_artifact_fingerprint,member_count,declared_document_count,material) values(${b.packageId},${b.packageFingerprint},${b.filingIdentityId},${m.filingDate},${m.acceptanceAt},${m.reportPeriod},${index.artifactId},${index.fingerprint},${b.documents.length},${b.documents.length-1},${tx.json(packageMaterial)}) on conflict do nothing`;
  const packageAuthorityRows=await tx`select fingerprint,filing_identity_id,filing_date,acceptance_at,report_period,filing_index_artifact_id,filing_index_artifact_fingerprint,member_count,declared_document_count,material from public.sec_event_filing_packages where package_id=${b.packageId}`;const packageRow=packageAuthorityRows[0];
  if(packageAuthorityRows.length!==1||packageRow?.fingerprint?.trim()!==b.packageFingerprint||packageRow?.filing_identity_id!==b.filingIdentityId||!sameDate(packageRow?.filing_date,m.filingDate)||!sameTimestamp(packageRow?.acceptance_at,m.acceptanceAt)||!sameDate(packageRow?.report_period,m.reportPeriod)||packageRow?.filing_index_artifact_id!==index.artifactId||packageRow?.filing_index_artifact_fingerprint?.trim()!==index.fingerprint||Number(packageRow?.member_count)!==b.documents.length||Number(packageRow?.declared_document_count)!==b.documents.length-1||!same(packageRow?.material,packageMaterial))throw new Error("SEC_EVENT_FILING_PACKAGE_AUTHORITY_CONFLICT");
  await observePhase?.("PACKAGE_PARENT");
  for(let i=0;i<b.documents.length;i++){const d=b.documents[i]!;const memberMaterial={packageId:b.packageId,packageFingerprint:b.packageFingerprint,ordinal:i,artifactId:d.artifactId,fingerprint:d.fingerprint,role:d.role,documentType:d.documentType,sequence:d.sequence,locator:d.locator,isPrimary:d.role==="PRIMARY_DOCUMENT"};await tx`insert into public.sec_event_package_document_members(package_id,package_fingerprint,filing_identity_id,member_ordinal,artifact_id,artifact_fingerprint,document_role,document_type,sequence_ordinal,canonical_locator,is_primary,material) values(${b.packageId},${b.packageFingerprint},${b.filingIdentityId},${i},${d.artifactId},${d.fingerprint},${d.role},${d.documentType},${d.sequence},${d.locator},${d.role==='PRIMARY_DOCUMENT'},${tx.json(memberMaterial)}) on conflict do nothing`;const rr=await tx`select material from public.sec_event_package_document_members where package_id=${b.packageId} and package_fingerprint=${b.packageFingerprint} and member_ordinal=${i}`;if(rr.length!==1||!same(rr[0]?.material,memberMaterial))throw new Error("SEC_EVENT_AUTHORITY_CONFLICT");}
  const packageRows=await tx`select member_ordinal,artifact_id,artifact_fingerprint,document_role,document_type,sequence_ordinal,canonical_locator,is_primary from public.sec_event_package_document_members where package_id=${b.packageId} and package_fingerprint=${b.packageFingerprint} order by member_ordinal`;
  if(packageRows.length!==b.documents.length||packageRows.some((row,i)=>{const d=b.documents[i]!;return Number(row.member_ordinal)!==i||row.artifact_id!==d.artifactId||row.artifact_fingerprint!==d.fingerprint||row.document_role!==d.role||row.document_type!==d.documentType||Number(row.sequence_ordinal)!==d.sequence||row.canonical_locator!==d.locator||row.is_primary!==(d.role==="PRIMARY_DOCUMENT");}))throw new Error("SEC_EVENT_PACKAGE_MEMBER_SET_MISMATCH");
  await observePhase?.("PACKAGE_MEMBERS");
  const receiptMaterial={requestId,attemptId,packageId:b.packageId,packageFingerprint:b.packageFingerprint,retrievedAt:m.receipt.receivedAt,effectiveAvailableAt:m.receipt.effectiveAvailableAt,responseStatus:m.receipt.responseStatus,contentEncoding:"identity",responseMaterialFingerprint:b.responseMaterialFingerprint,sourceReceiptId:m.receipt.receiptId};await tx`insert into public.sec_event_acquisition_receipts(receipt_id,fingerprint,request_id,attempt_id,filing_identity_id,package_id,package_fingerprint,retrieved_at,effective_available_at,response_status,content_encoding,response_material_fingerprint,material) values(${b.receiptId},${b.receiptFingerprint},${requestId},${attemptId},${b.filingIdentityId},${b.packageId},${b.packageFingerprint},${m.receipt.receivedAt},${m.receipt.effectiveAvailableAt},${m.receipt.responseStatus},'identity',${b.responseMaterialFingerprint},${tx.json(receiptMaterial)}) on conflict do nothing`;const receiptRows=await tx`select fingerprint,request_id,attempt_id,filing_identity_id,package_id,package_fingerprint,retrieved_at,effective_available_at,response_status,content_encoding,response_material_fingerprint,material from public.sec_event_acquisition_receipts where receipt_id=${b.receiptId}`;const receipt=receiptRows[0];if(receiptRows.length!==1||receipt?.fingerprint?.trim()!==b.receiptFingerprint||receipt?.request_id!==requestId||receipt?.attempt_id!==attemptId||receipt?.filing_identity_id!==b.filingIdentityId||receipt?.package_id!==b.packageId||receipt?.package_fingerprint?.trim()!==b.packageFingerprint||!sameTimestamp(receipt?.retrieved_at,m.receipt.receivedAt)||!sameTimestamp(receipt?.effective_available_at,m.receipt.effectiveAvailableAt)||Number(receipt?.response_status)!==m.receipt.responseStatus||receipt?.content_encoding!=="identity"||receipt?.response_material_fingerprint?.trim()!==b.responseMaterialFingerprint||!same(receipt?.material,receiptMaterial))throw new Error("SEC_EVENT_ACQUISITION_RECEIPT_AUTHORITY_CONFLICT");
  await observePhase?.("RECEIPT");
  const lineageMaterial={lineageId:b.lineageId,sourceProfileId:m.profileId,sourceProfileFingerprint:b.profileFingerprint,orderedPackageDocumentMemberSet:b.documents.map((d,i)=>({packageId:b.packageId,packageFingerprint:b.packageFingerprint,packageMemberOrdinal:i,artifactId:d.artifactId,artifactFingerprint:d.fingerprint})),memberCount:b.documents.length,rootFilingIdentityId:b.amendmentParentFilingIdentityId??b.filingIdentityId,amendmentParentChain:b.amendmentParentFilingIdentityId?[b.amendmentParentFilingIdentityId,b.filingIdentityId]:[b.filingIdentityId]};await tx`insert into public.sec_event_source_lineages(lineage_id,fingerprint,profile_id,profile_fingerprint,member_count,member_set_fingerprint,material) values(${b.lineageId},${b.lineageFingerprint},${m.profileId},${b.profileFingerprint},${b.documents.length},${b.lineageFingerprint},${tx.json(lineageMaterial)}) on conflict do nothing`;
  const lineageAuthorityRows=await tx`select fingerprint,profile_id,profile_fingerprint,member_count,member_set_fingerprint,material from public.sec_event_source_lineages where lineage_id=${b.lineageId}`;const lineage=lineageAuthorityRows[0];
  if(lineageAuthorityRows.length!==1||lineage?.fingerprint?.trim()!==b.lineageFingerprint||lineage?.profile_id!==m.profileId||lineage?.profile_fingerprint?.trim()!==b.profileFingerprint||Number(lineage?.member_count)!==b.documents.length||lineage?.member_set_fingerprint?.trim()!==b.lineageFingerprint||!same(lineage?.material,lineageMaterial))throw new Error("SEC_EVENT_SOURCE_LINEAGE_AUTHORITY_CONFLICT");
  await observePhase?.("LINEAGE_PARENT");
  for(let i=0;i<b.documents.length;i++){const d=b.documents[i]!;const lm={lineageId:b.lineageId,ordinal:i,packageId:b.packageId,packageFingerprint:b.packageFingerprint,packageMemberOrdinal:i,artifactId:d.artifactId,artifactFingerprint:d.fingerprint};await tx`insert into public.sec_event_source_lineage_members(lineage_id,member_ordinal,package_id,package_fingerprint,package_member_ordinal,artifact_id,artifact_fingerprint,material) values(${b.lineageId},${i},${b.packageId},${b.packageFingerprint},${i},${d.artifactId},${d.fingerprint},${tx.json(lm)}) on conflict do nothing`;const rr=await tx`select material from public.sec_event_source_lineage_members where lineage_id=${b.lineageId} and member_ordinal=${i}`;if(rr.length!==1||!same(rr[0]?.material,lm))throw new Error("SEC_EVENT_AUTHORITY_CONFLICT");}
  const lineageRows=await tx`select member_ordinal,package_id,package_fingerprint,package_member_ordinal,artifact_id,artifact_fingerprint from public.sec_event_source_lineage_members where lineage_id=${b.lineageId} order by member_ordinal`;
  if(lineageRows.length!==b.documents.length||lineageRows.some((row,i)=>{const d=b.documents[i]!;return Number(row.member_ordinal)!==i||row.package_id!==b.packageId||row.package_fingerprint!==b.packageFingerprint||Number(row.package_member_ordinal)!==i||row.artifact_id!==d.artifactId||row.artifact_fingerprint!==d.fingerprint;}))throw new Error("SEC_EVENT_LINEAGE_MEMBER_SET_MISMATCH");
  await observePhase?.("LINEAGE_MEMBERS");
  const tables=["sec_event_source_profiles","sec_event_filing_identities","sec_event_content_blobs","sec_event_document_artifacts","sec_event_filing_packages","sec_event_package_document_members","sec_event_acquisition_requests","sec_event_acquisition_attempts","sec_event_acquisition_receipts","sec_event_source_lineages","sec_event_source_lineage_members"];
  for(const table of tables){const rows=await tx`select count(*)::int as count from public.${tx(table)}`;if(Number(rows[0]?.count)<1)throw new Error("SEC_EVENT_AUTHORITY_REREAD_FAILED");}
  await observePhase?.("AUTHORITATIVE_REREAD");
  return Object.freeze({profileId:m.profileId,filingIdentityId:b.filingIdentityId,packageId:b.packageId,packageFingerprint:b.packageFingerprint,receiptId:b.receiptId,lineageId:b.lineageId,documentCount:b.documents.filter(d=>d.role!=="FILING_INDEX").length,memberCount:b.documents.length,blobCount,status:"PERSISTED_VERIFIED",classification:"SYNTHETIC_NON_AUTHORITATIVE",eventAuthorityEligible:false});
}
export function createSecEventProvenanceUnitOfWork(databaseUrl:string){
  const sql=postgres(databaseUrl,{max:1,prepare:true});
  return Object.freeze({
    persist:async(input:unknown,observePhase?:SecProvenancePhaseObserver)=>{
      // Reject trust copies before postgres.js opens a transaction or connection.
      if(!isTrustedSecRuntimeBatch(input))throw new Error("SEC_EVENT_RUNTIME_TRUST_REQUIRED");
      return sql.begin(async tx=>{
        await tx`set transaction isolation level read committed`;
        await tx`set local transaction_timeout = '120s'`;
        await observePhase?.("TRANSACTION_STARTED");
        const result=await persistSecEventProvenance(tx as unknown as Tx,input,observePhase);
        await observePhase?.("BEFORE_COMMIT");return result;
      });
    },
    close:()=>sql.end({timeout:5}),
  });
}
