import { createHash } from "node:crypto";
import type { IntelligenceStore } from "@/domain/intelligence/foundation";
export const ASSET_DISCOVERY_VERSION="asset-discovery/v1", ASSET_IDENTITY_VERSION="asset-identity/v1", ASSET_QUARANTINE_VERSION="asset-quarantine/v1", ASSET_EVIDENCE_VERSION="asset-evidence/v1", ASSET_ELIGIBILITY_VERSION="asset-eligibility-policy/v1", SYNTHETIC_PROFILE_VERSION="mm-synthetic-eligibility-profile/v1";
export interface CandidateIdentity { identityVersion: typeof ASSET_IDENTITY_VERSION; assetClass:string; namespace:string; canonicalIdentifier:string; chainNamespace?:string; contractIdentifier?:string; providerExternalIds:readonly string[]; }
export interface DiscoveryConfig { asOf:Date; discoveryVersion:typeof ASSET_DISCOVERY_VERSION; identityVersion:typeof ASSET_IDENTITY_VERSION; providerDatasetPins:readonly {providerId:string;datasetVersion:string}[]; approvedAssetIds?:readonly string[]; }
export interface Candidate { candidateId:string; discoveredAt:string; asOf:string; identity:CandidateIdentity; evidenceIds:readonly string[]; reasons:readonly string[]; discoveryVersion:typeof ASSET_DISCOVERY_VERSION; quarantineStatus:"QUARANTINED"; }
export interface EligibilityEvidence { candidateId:string; assetClass:string; ageDays?:bigint; historySpanDays?:bigint; distinctEligibleVenueCount?:bigint; liquidityMinor?:bigint; volumeMinor?:bigint; marketCapMinor?:bigint; top10HolderConcentrationBps?:bigint; singleHolderConcentrationBps?:bigint; volatilityBps?:bigint; contractVerified?:boolean; suspiciousFlags?:readonly string[]; currency?:string; evidenceIds:readonly string[]; }
export interface EligibilityCheck { requirementCode:string; status:"PASS"|"FAIL"|"INCOMPLETE"|"NOT_APPLICABLE"; observedValue?:string; threshold?:string; unit?:string; evidenceIds:readonly string[]; reasonCode:string; }
export interface EligibilityEvaluation { evaluationId:string; candidateId:string; asOf:string; policyVersion:typeof ASSET_ELIGIBILITY_VERSION; profileVersion:typeof SYNTHETIC_PROFILE_VERSION; status:"ELIGIBLE"|"INELIGIBLE"|"INCOMPLETE"; checks:readonly EligibilityCheck[]; fingerprint:string; }
const digest=(v:unknown)=>createHash("sha256").update(JSON.stringify(v,(_,x)=>typeof x==="bigint"?x.toString():x instanceof Date?x.toISOString():x)).digest("hex");
export function discoverAssetCandidates(store:IntelligenceStore,config:DiscoveryConfig):readonly Candidate[]{if(config.discoveryVersion!==ASSET_DISCOVERY_VERSION||config.identityVersion!==ASSET_IDENTITY_VERSION)throw new Error("UNSUPPORTED_POLICY_VERSION");const approved=new Set(config.approvedAssetIds??[]), out=new Map<string,Candidate>();for(const pin of config.providerDatasetPins){for(const n of store.newsAvailableAt(config.asOf,pin.datasetVersion).filter(x=>x.providerId===pin.providerId)){for(const m of n.mappings.filter(x=>x.mappingKind==="ASSET")){if(approved.has(m.targetId))continue;const identity:CandidateIdentity={identityVersion:ASSET_IDENTITY_VERSION,assetClass:"UNKNOWN",namespace:"m3",canonicalIdentifier:m.targetId,providerExternalIds:[n.externalRecordId]};const key=identity.canonicalIdentifier;const old=out.get(key);out.set(key,{candidateId:digest({identity,config}),discoveredAt:n.availableAt.toISOString(),asOf:config.asOf.toISOString(),identity,evidenceIds:[...(old?.evidenceIds??[]),n.id],reasons:[...(old?.reasons??[]),"ASSET_MAPPING_OBSERVED"],discoveryVersion:ASSET_DISCOVERY_VERSION,quarantineStatus:"QUARANTINED"});}}}return [...out.values()].sort((a,b)=>a.candidateId.localeCompare(b.candidateId));}
export function evaluateAssetEligibility(e:EligibilityEvidence,asOf:Date):EligibilityEvaluation{const checks:EligibilityCheck[]=[];const check=(code:string,v:bigint|undefined,threshold:bigint,unit:string,cmp:(x:bigint)=>boolean)=>checks.push(v===undefined?{requirementCode:code,status:"INCOMPLETE",threshold:threshold.toString(),unit,evidenceIds:e.evidenceIds,reasonCode:"MISSING_EVIDENCE"}:{requirementCode:code,status:cmp(v)?"PASS":"FAIL",observedValue:v.toString(),threshold:threshold.toString(),unit,evidenceIds:e.evidenceIds,reasonCode:cmp(v)?"MEETS_THRESHOLD":"BELOW_THRESHOLD"});check("MIN_AGE_DAYS",e.ageDays,30n,"days",x=>x>=30n);check("MIN_HISTORY_DAYS",e.historySpanDays,14n,"days",x=>x>=14n);check("MIN_VENUES",e.distinctEligibleVenueCount,2n,"count",x=>x>=2n);check("MIN_LIQUIDITY",e.liquidityMinor,1000000n,"minor",x=>x>=1000000n);check("MIN_VOLUME",e.volumeMinor,500000n,"minor",x=>x>=500000n);check("MIN_MARKET_CAP",e.marketCapMinor,10000000n,"minor",x=>x>=10000000n);check("MAX_TOP10",e.top10HolderConcentrationBps,8000n,"bps",x=>x<=8000n);check("MAX_SINGLE",e.singleHolderConcentrationBps,3000n,"bps",x=>x<=3000n);check("MAX_VOLATILITY",e.volatilityBps,20000n,"bps",x=>x<=20000n);if(e.suspiciousFlags?.length)checks.push({requirementCode:"SUSPICIOUS_ACTIVITY",status:"FAIL",evidenceIds:e.evidenceIds,reasonCode:"CRITICAL_SUSPICIOUS_FLAG"});if(e.assetClass==="CONTRACT")checks.push({requirementCode:"CONTRACT_VERIFIED",status:e.contractVerified===true?"PASS":e.contractVerified===false?"FAIL":"INCOMPLETE",evidenceIds:e.evidenceIds,reasonCode:e.contractVerified===true?"VERIFIED":"CONTRACT_EVIDENCE_MISSING"});const status=checks.some(x=>x.status==="FAIL")?"INELIGIBLE":checks.some(x=>x.status==="INCOMPLETE")?"INCOMPLETE":"ELIGIBLE";const body={candidateId:e.candidateId,asOf:asOf.toISOString(),checks,profile:SYNTHETIC_PROFILE_VERSION};return {evaluationId:digest(body),candidateId:e.candidateId,asOf:asOf.toISOString(),policyVersion:ASSET_ELIGIBILITY_VERSION,profileVersion:SYNTHETIC_PROFILE_VERSION,status,checks,fingerprint:digest(body)};}
